/* Общий каталог Quaternius + пользовательская мебель (партия 01). */
(function(g){'use strict';var names=["Anvil","Anvil_Log","Axe_Bronze","Bag","Banner_1","Banner_1_Cloth","Banner_2","Banner_2_Cloth","Barrel","Barrel_Apples","Barrel_Holder","Bed_Twin1","Bed_Twin2","Bench","Book_5","Book_7","Book_Simplified_Single","Book_Stack_1","Book_Stack_2","Bookcase_2","BookGroup_Medium_1","BookGroup_Medium_2","BookGroup_Medium_3","BookGroup_Small_1","BookGroup_Small_2","BookGroup_Small_3","BookStand","Bottle_1","Bucket_Metal","Bucket_Wooden_1","Cabinet","Cage_Small","Candle_1","Candle_2","CandleStick","CandleStick_Stand","CandleStick_Triple","Carrot","Cauldron","Chain_Coil","Chair_1","Chalice","Chandelier","Chest_Wood","Coin","Coin_Pile","Coin_Pile_2","Crate_Metal","Crate_Wooden","Dummy","FarmCrate_Apple","FarmCrate_Carrot","FarmCrate_Empty","Key_Gold","Key_Metal","Lantern_Wall","Mug","Nightstand_Shelf","Peg_Rack","Pickaxe_Bronze","Pot_1","Pot_1_Lid","Potion_1","Potion_2","Potion_4","Pouch_Large","Rope_1","Rope_2","Rope_3","Scroll_1","Scroll_2","Shelf_Arch","Shelf_Simple","Shelf_Small_Bottles","Shield_Wooden","SmallBottle","SmallBottles_1","Stall_Cart_Empty","Stall_Empty","Stool","Sword_Bronze","Table_Fork","Table_Knife","Table_Large","Table_Plate","Table_Spoon","Torch_Metal","Vase_2","Vase_4","Vase_Rubble_Medium","WeaponStand","Whetstone","Workbench","Workbench_Drawers"];var cat={};names.forEach(function(n){cat[n]={id:n,name:n,path:'./app/assets/3d/quaternius/models/'+n+'.gltf',scale:1};});
cat["UserFurniture_table"]={id:"UserFurniture_table",name:"Стол",nameRus:"Стол",category:'furniture',pack:'Пользовательская мебель',path:'./app/assets/3d/user_furniture/table.glb',scale:1};names.push("UserFurniture_table");
cat["UserFurniture_chair"]={id:"UserFurniture_chair",name:"Стул",nameRus:"Стул",category:'furniture',pack:'Пользовательская мебель',path:'./app/assets/3d/user_furniture/chair.glb',scale:1};names.push("UserFurniture_chair");
cat["UserFurniture_bed"]={id:"UserFurniture_bed",name:"Кровать",nameRus:"Кровать",category:'furniture',pack:'Пользовательская мебель',path:'./app/assets/3d/user_furniture/bed.glb',scale:1};names.push("UserFurniture_bed");
cat["UserFurniture_closet"]={id:"UserFurniture_closet",name:"Шкаф",nameRus:"Шкаф",category:'furniture',pack:'Пользовательская мебель',path:'./app/assets/3d/user_furniture/closet.glb',scale:1};names.push("UserFurniture_closet");
cat["UserFurniture_commode"]={id:"UserFurniture_commode",name:"Комод",nameRus:"Комод",category:'furniture',pack:'Пользовательская мебель',path:'./app/assets/3d/user_furniture/commode.glb',scale:1};names.push("UserFurniture_commode");
cat["UserFurniture_bookshelf"]={id:"UserFurniture_bookshelf",name:"Книжный шкаф",nameRus:"Книжный шкаф",category:'furniture',pack:'Пользовательская мебель',path:'./app/assets/3d/user_furniture/bookshelf.glb',scale:1};names.push("UserFurniture_bookshelf");
g.DND3DAssetCatalog=cat;g.DND3DAssetNames=names;})(window);
