/* 3D-система персонажей: тело, морфы, пресеты, экипировка и подготовка к skeleton/animation.
 * Работает поверх существующего 3D-движка и не создаёт отдельный рендерер.
 * Главный API: DNDCharacter3D.createCharacter(), registerRace(), registerEquipment(),
 * applyMorphTargets(), resolveEquipment(), getRenderDescriptor(), serialize().
 */
(function(g){'use strict';
var VERSION=1;
var AXES={height:{min:-1,max:1,default:0},width:{min:-1,max:1,default:0},muscle:{min:-1,max:1,default:0},fat:{min:-1,max:1,default:0},shoulders:{min:-1,max:1,default:0},chest:{min:-1,max:1,default:0},waist:{min:-1,max:1,default:0},hips:{min:-1,max:1,default:0},arms:{min:-1,max:1,default:0},legs:{min:-1,max:1,default:0},head:{min:-1,max:1,default:0}};
var races=Object.create(null),presets=Object.create(null),equipment=Object.create(null);
function clone(v){return JSON.parse(JSON.stringify(v));}
function num(v,d){v=Number(v);return isFinite(v)?v:d;}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function normalizeAxes(input,defs){input=input&&typeof input==='object'?input:{};defs=defs||AXES;var out={};Object.keys(defs).forEach(function(k){var d=defs[k]||AXES[k]||{min:-1,max:1,default:0};out[k]=clamp(num(input[k],d.default==null?0:d.default),d.min==null?-1:d.min,d.max==null?1:d.max);});return out;}
function registerRace(def){if(!def||!def.id)throw Error('Race id required');var r=clone(def);r.id=String(r.id);r.name=String(r.name||r.id);r.baseModel=String(r.baseModel||'');r.skeleton=String(r.skeleton||'');r.morphs=r.morphs&&typeof r.morphs==='object'?r.morphs:{};var defs={};Object.keys(AXES).forEach(function(k){defs[k]=Object.assign({},AXES[k],r.morphs[k]||{});});r.morphs=defs;r.presets=Array.isArray(r.presets)?r.presets.slice():[];races[r.id]=r;return clone(r);}
function registerPreset(def){if(!def||!def.id)throw Error('Preset id required');var p=clone(def);p.id=String(p.id);p.name=String(p.name||p.id);p.body=normalizeAxes(p.body);presets[p.id]=p;return clone(p);}
function registerEquipment(def){if(!def||!def.id)throw Error('Equipment id required');var e=clone(def);e.id=String(e.id);e.name=String(e.name||e.id);e.assetId=String(e.assetId||e.model||'');e.slot=String(e.slot||'body');e.fit=e.fit&&typeof e.fit==='object'?e.fit:{};e.morphChannels=e.morphChannels&&typeof e.morphChannels==='object'?e.morphChannels:{};equipment[e.id]=e;return clone(e);}
function getRace(id){return races[String(id)]||null;}
function createCharacter(o){o=o&&typeof o==='object'?o:{};var raceId=String(o.raceId||'human'),race=getRace(raceId)||getRace('human'),body=normalizeAxes(o.body,race&&race.morphs||AXES),c={schemaVersion:1,id:String(o.id||('char3d_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8))),raceId:raceId,gender:String(o.gender||'neutral'),body:body,presetId:String(o.presetId||''),equipment:{},pose:{animationId:'idle',time:0,weight:1}};if(o.presetId&&presets[o.presetId])c.body=normalizeAxes(Object.assign({},c.body,presets[o.presetId].body),race&&race.morphs||AXES);if(o.equipment&&typeof o.equipment==='object')Object.keys(o.equipment).forEach(function(slot){c.equipment[slot]=String(o.equipment[slot]);});return c;}
function applyPreset(c,id){if(!presets[id])throw Error('Unknown body preset: '+id);c.body=normalizeAxes(Object.assign({},c.body,presets[id].body),getRace(c.raceId).morphs);c.presetId=id;return c;}
function getBodyState(c){var r=getRace(c.raceId),body=normalizeAxes(c.body,r&&r.morphs||AXES);return{raceId:c.raceId,gender:c.gender,baseModel:r&&r.baseModel||'',skeleton:r&&r.skeleton||'',body:body};}
function resolveMorphChannels(body,channels){var out={};Object.keys(channels||{}).forEach(function(target){var rule=channels[target],src=typeof rule==='string'?rule:rule&&rule.source,scale=typeof rule==='object'&&rule.scale!=null?num(rule.scale,1):1,offset=typeof rule==='object'&&rule.offset!=null?num(rule.offset,0):0;out[target]=clamp(num(body[src],0)*scale+offset,-1,1);});return out;}
function resolveEquipment(c,item){var e=typeof item==='string'?equipment[item]:item;if(!e)throw Error('Unknown equipment: '+item);var b=getBodyState(c).body,fit=e.fit||{},sx=1+num(fit.width,0)*b.width+num(fit.muscleWidth,0)*b.muscle+num(fit.shoulderWidth,0)*b.shoulders+num(fit.chestWidth,0)*b.chest+num(fit.hipWidth,0)*b.hips,sy=1+num(fit.height,0)*b.height+num(fit.legHeight,0)*b.legs,sz=1+num(fit.depth,0)*b.width+num(fit.fatDepth,0)*b.fat+num(fit.chestDepth,0)*b.chest;return{equipmentId:e.id,assetId:e.assetId,slot:e.slot,scale:[clamp(sx,.5,1.8),clamp(sy,.5,1.8),clamp(sz,.5,1.8)],morphs:resolveMorphChannels(b,e.morphChannels),fit:clone(fit),raceId:c.raceId};}
function equip(c,id){var e=equipment[id];if(!e)throw Error('Unknown equipment: '+id);c.equipment[e.slot]=e.id;return c;}
function unequip(c,slot){delete c.equipment[slot];return c;}
function applyMorphTargets(base,targets,weights){if(!base)return new Float32Array();var out=new Float32Array(base.length);out.set(base);targets=targets||[];weights=weights||{};for(var i=0;i<targets.length;i++){var t=targets[i];if(!t||!t.delta)continue;var w=typeof t.weight==='number'?t.weight:num(weights[t.name],0);if(!w)continue;var d=t.delta;for(var j=0;j<out.length&&j<d.length;j++)out[j]+=d[j]*w;}return out;}
function getRenderDescriptor(c){var r=getBodyState(c),items=[];Object.keys(c.equipment||{}).forEach(function(slot){var e=equipment[c.equipment[slot]];if(e)items.push(resolveEquipment(c,e));});return{version:VERSION,characterId:c.id,raceId:c.raceId,gender:c.gender,body:r.body,baseModel:r.baseModel,skeleton:r.skeleton,equipment:items,pose:clone(c.pose||{})};}
function serialize(c){return JSON.stringify(clone(c));}
function deserialize(v){var c=typeof v==='string'?JSON.parse(v):clone(v);return createCharacter(c);}
registerRace({id:'human',name:'Человек',baseModel:'https://appassets.androidplatform.net/vtt-apk/human-base-rigged.glb',skeleton:'humanoid',presets:['human_average']});
registerPreset({id:'human_average',name:'Среднее телосложение',body:{}});
g.DNDCharacter3D={VERSION:VERSION,AXES:clone(AXES),registerRace:registerRace,registerPreset:registerPreset,registerEquipment:registerEquipment,getRace:getRace,createCharacter:createCharacter,applyPreset:applyPreset,getBodyState:getBodyState,resolveEquipment:resolveEquipment,equip:equip,unequip:unequip,applyMorphTargets:applyMorphTargets,getRenderDescriptor:getRenderDescriptor,serialize:serialize,deserialize:deserialize,listRaces:function(){return Object.keys(races).map(function(k){return clone(races[k]);});},listPresets:function(){return Object.keys(presets).map(function(k){return clone(presets[k]);});},listEquipment:function(){return Object.keys(equipment).map(function(k){return clone(equipment[k]);});}};
})(window);
