/* GLTF character pipeline: CPU skinning, morph targets and animation metadata. */
(function(g){'use strict';
function C(t){return({SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16})[t]||1;}function T(t){return({5120:Int8Array,5121:Uint8Array,5122:Int16Array,5123:Uint16Array,5125:Uint32Array,5126:Float32Array})[t]||Float32Array;}
function accessor(g,b,i){var a=g.accessors[i],v=g.bufferViews[a.bufferView],raw=b[v.buffer||0],K=T(a.componentType),n=C(a.type),off=(v.byteOffset||0)+(a.byteOffset||0),stride=v.byteStride||K.BYTES_PER_ELEMENT*n,out;if(stride===K.BYTES_PER_ELEMENT*n)return new K(raw,off,a.count*n);out=new K(a.count*n);for(var q=0;q<a.count;q++)for(var j=0;j<n;j++)out[q*n+j]=new K(raw,off+q*stride+j*K.BYTES_PER_ELEMENT,1)[0];return out;}
function ident(){return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];}function mul(a,b){var o=new Array(16);for(var c=0;c<4;c++)for(var r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
function inv(a){var m=a.slice(),o=ident(),i,j,k,p,t;for(i=0;i<4;i++){p=i;for(j=i+1;j<4;j++)if(Math.abs(m[j*4+i])>Math.abs(m[p*4+i]))p=j;if(Math.abs(m[p*4+i])<1e-10)return ident();for(k=0;k<4;k++){t=m[i*4+k];m[i*4+k]=m[p*4+k];m[p*4+k]=t;t=o[i*4+k];o[i*4+k]=o[p*4+k];o[p*4+k]=t;}t=m[i*4+i];for(k=0;k<4;k++){m[i*4+k]/=t;o[i*4+k]/=t;}for(j=0;j<4;j++)if(j!==i){t=m[j*4+i];for(k=0;k<4;k++){m[j*4+k]-=t*m[i*4+k];o[j*4+k]-=t*o[i*4+k];}}}return o;}
function nodeMat(n){if(n.matrix)return n.matrix.slice();var t=n.translation||[0,0,0],s=n.scale||[1,1,1],q=n.rotation||[0,0,0,1],x=q[0],y=q[1],z=q[2],w=q[3];return[(1-2*y*y-2*z*z)*s[0],(2*x*y+2*w*z)*s[0],(2*x*z-2*w*y)*s[0],0,(2*x*y-2*w*z)*s[1],(1-2*x*x-2*z*z)*s[1],(2*y*z+2*w*x)*s[1],0,(2*x*z+2*w*y)*s[2],(2*y*z-2*w*x)*s[2],(1-2*x*x-2*y*y)*s[2],0,t[0],t[1],t[2],1];}
function worldMatrices(g){var nodes=g.nodes||[],out=nodes.map(function(){return null;}),seen={};function walk(i,parent){if(seen[i])return;seen[i]=1;var n=nodes[i]||{},m=mul(parent,nodeMat(n));out[i]=m;(n.children||[]).forEach(function(c){walk(c,m);});}var sc=g.scenes&&g.scenes[g.scene||0],roots=sc&&sc.nodes||[];roots.forEach(function(i){walk(i,ident());});nodes.forEach(function(n,i){if(!seen[i])walk(i,ident());});return out;}
function loadSkin(g,b,i){var s=(g.skins||[])[i];if(!s)return null;var joints=(s.joints||[]).slice(),raw=s.inverseBindMatrices!=null?accessor(g,b,s.inverseBindMatrices):null,ib=[];if(raw){for(var j=0;j<joints.length;j++){var m=[];for(var k=0;k<16;k++)m.push(Number(raw[j*16+k]));ib.push(m);}}else{ib=joints.map(function(){return ident();});}return{joints:joints,skeleton:s.skeleton==null?null:s.skeleton,inverseBindMatrices:ib,name:s.name||('skin_'+i)};}
function buildAnimations(g,b){return(g.animations||[]).map(function(a,ai){var sam=(a.samplers||[]).map(function(s){return{times:accessor(g,b,s.input),values:accessor(g,b,s.output),components:C((g.accessors[s.output]||{}).type),interpolation:s.interpolation||'LINEAR'};}),channels=(a.channels||[]).map(function(ch){var s=sam[ch.sampler]||{},path=ch.target&&ch.target.path;return{times:s.times,values:s.values,components:s.components,interpolation:s.interpolation,path:path,node:ch.target&&ch.target.node};}),duration=channels.reduce(function(d,c){return c.times&&c.times.length?Math.max(d,c.times[c.times.length-1]):d;},0);return{name:a.name||('animation_'+ai),duration:duration,channels:channels};});}
function prepare(url,asset){var g=asset.gltf,b=asset.buffers,skins=(g.skins||[]).map(function(_,i){return loadSkin(g,b,i);});return{url:url,skins:skins,animations:buildAnimations(g,b),worldMatrices:worldMatrices(g),morphChannels:(g.extras&&g.extras.dndMorphChannels)||{}};}
function transform(m,p){return[m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13],m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14]];}
/* Registry rules bind an axis to named positive/negative targets. Direct names
 * remain usable for imported GLBs. Always start from the immutable local base. */
function finite(v,d){v=Number(v);return isFinite(v)?v:d;}
function resolveMorphWeights(part,body,channels){
var names=part.morphNames||[],targets=part.morphTargets||[],weights=targets.map(function(_,i){return finite((part.meshWeights||[])[i],0);}),handled={};body=body||{};
Object.keys(channels||{}).forEach(function(axis){var rule=channels[axis]||{},pi=names.indexOf(rule.positive),ni=names.indexOf(rule.negative);if(pi<0||ni<0||!targets[pi]||!targets[ni]||!targets[pi].POSITION||!targets[ni].POSITION||targets[pi].POSITION.length!==(part.basePositions||part.positions||[]).length||targets[ni].POSITION.length!==(part.basePositions||part.positions||[]).length)return;var v=Math.max(-1,Math.min(1,finite(body[axis],0))),scale=Math.max(0,finite(rule.scale,1));weights[pi]=Math.max(0,v)*scale;weights[ni]=Math.max(0,-v)*scale;handled[axis]=true;});
names.forEach(function(name,i){if(targets[i]&&targets[i].POSITION&&targets[i].POSITION.length===(part.basePositions||part.positions||[]).length&&Object.prototype.hasOwnProperty.call(body,name)&&!handled[name]){weights[i]=Math.max(-1,Math.min(1,finite(body[name],0)));handled[name]=true;}});
return{weights:weights,handled:handled};}
function morphPositions(part,weights){var base=part.basePositions||part.positions,out=new Float32Array(base||[]);(part.morphTargets||[]).forEach(function(t,i){var d=t.POSITION,w=weights[i];if(!w||!d||d.length!==out.length)return;for(var j=0;j<out.length;j++)out[j]+=d[j]*w;});return out;}
function deformPart(part,skin,world,base){
if(!part.joints||!part.weights||!skin){var out=new Float32Array(base.length),m=world[part.node]||ident();for(var i=0;i<base.length;i+=3){var q=transform(m,[base[i],base[i+1],base[i+2]]);out[i]=q[0];out[i+1]=q[1];out[i+2]=q[2];}return out;}
var out=new Float32Array(base.length),ib=skin.inverseBindMatrices||[],j=part.joints,w=part.weights,palette=skin.joints.map(function(bone,i){return mul(world[bone]||ident(),ib[i]||ident());});
for(var i=0;i<base.length;i+=3){var x=base[i],y=base[i+1],z=base[i+2],ox=0,oy=0,oz=0,total=0;for(var k=0;k<4;k++){var ji=j[(i/3)*4+k],wt=w[(i/3)*4+k],m=palette[ji];if(!wt||!m)continue;ox+=(m[0]*x+m[4]*y+m[8]*z+m[12])*wt;oy+=(m[1]*x+m[5]*y+m[9]*z+m[13])*wt;oz+=(m[2]*x+m[6]*y+m[10]*z+m[14])*wt;total+=wt;}out[i]=total>0?ox:x;out[i+1]=total>0?oy:y;out[i+2]=total>0?oz:z;}return out;}
function deformAsset(asset,body,channels){if(!asset)return asset;if(!asset.character)asset.character=prepare(asset.url||'',asset);var c=asset.character,world=c.worldMatrices||worldMatrices(asset.gltf||{});c.worldMatrices=world;channels=channels||c.morphChannels||{};
asset.parts.forEach(function(p){var resolved=resolveMorphWeights(p,body,channels),base=morphPositions(p,resolved.weights);p.morphHandledAxes=resolved.handled;p.deformedPositions=deformPart(p,(c.skins||[])[p.skin],world,base);});return asset;}
function sampleSampler(sampler,time){var times=sampler.times||[],vals=sampler.values||[],n=sampler.components||1;if(!times.length)return null;if(time<=times[0])return Array.prototype.slice.call(vals,0,n);var last=times.length-1;if(time>=times[last])return Array.prototype.slice.call(vals,last*n,(last+1)*n);var i=0;while(i<last&&time>times[i+1])i++;var t=(time-times[i])/(times[i+1]-times[i]),a=Array.prototype.slice.call(vals,i*n,(i+1)*n),b=Array.prototype.slice.call(vals,(i+1)*n,(i+2)*n);return a.map(function(v,k){return v+(b[k]-v)*t;});}
function install(){if(!g.DNDGLTF||g.DNDGLTF.__characterPipeline)return;var old=g.DNDGLTF.load;g.DNDGLTF.load=function(url){return old(url).then(function(asset){if(!asset.character)asset.character=prepare(url,asset);return asset;});};g.DNDGLTF.__characterPipeline=true;}
g.DNDGLTFCharacterPipeline={install:install,prepare:prepare,sampleSampler:sampleSampler,buildAnimations:buildAnimations,loadSkin:loadSkin,deformAsset:deformAsset,resolveMorphWeights:resolveMorphWeights};})(window);
