/* GLTF 2.0 character pipeline: skins, joints, animations and morph targets.
 * This module extends the existing DNDGLTF loader without creating a second renderer.
 */
(function(g){'use strict';
function C(t){return({SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16})[t]||1;}
function T(t){return({5120:Int8Array,5121:Uint8Array,5122:Int16Array,5123:Uint16Array,5125:Uint32Array,5126:Float32Array})[t]||Float32Array;}
function accessor(g,b,i){var a=g.accessors[i],v=g.bufferViews[a.bufferView],raw=b[v.buffer||0],K=T(a.componentType),n=C(a.type),off=(v.byteOffset||0)+(a.byteOffset||0),stride=v.byteStride||K.BYTES_PER_ELEMENT*n,out;if(stride===K.BYTES_PER_ELEMENT*n)return new K(raw,off,a.count*n);out=new K(a.count*n);for(var q=0;q<a.count;q++)for(var j=0;j<n;j++)out[q*n+j]=new K(raw,off+q*stride+j*K.BYTES_PER_ELEMENT,1)[0];return out;}
function ident(){return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];}
function mul(a,b){var o=new Array(16);for(var c=0;c<4;c++)for(var r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
function inv(a){var b=a.slice(),i,j,k,t,aug=[];for(i=0;i<4;i++){aug[i]=[b[i],b[4+i],b[8+i],b[12+i],i===0?1:0,i===1?1:0,i===2?1:0,i===3?1:0];}
for(i=0;i<4;i++){var p=i;for(j=i+1;j<4;j++)if(Math.abs(aug[j][i])>Math.abs(aug[p][i]))p=j;if(Math.abs(aug[p][i])<1e-10)return ident();t=aug[i];aug[i]=aug[p];aug[p]=t;t=aug[i][i];for(k=0;k<8;k++)aug[i][k]/=t;for(j=0;j<4;j++)if(j!==i){t=aug[j][i];for(k=0;k<8;k++)aug[j][k]-=t*aug[i][k];}}
var o=[];for(j=0;j<4;j++)for(i=0;i<4;i++)o[j*4+i]=aug[i][j+4];return o;}
function quatSlerp(a,b,t){var ax=a[0],ay=a[1],az=a[2],aw=a[3],bx=b[0],by=b[1],bz=b[2],bw=b[3],dot=ax*bx+ay*by+az*bz+aw*bw;if(dot<0){dot=-dot;bx=-bx;by=-by;bz=-bz;bw=-bw;}if(dot>.9995){var q=[ax+(bx-ax)*t,ay+(by-ay)*t,az+(bz-az)*t,aw+(bw-aw)*t],l=Math.hypot.apply(Math,q)||1;return q.map(function(v){return v/l;});}var th=Math.acos(Math.max(-1,Math.min(1,dot))),s=Math.sin(th);var a0=Math.sin((1-t)*th)/s,a1=Math.sin(t*th)/s;return[ax*a0+bx*a1,ay*a0+by*a1,az*a0+bz*a1,aw*a0+bw*a1];}
function lerp(a,b,t){var o=[];for(var i=0;i<a.length;i++)o[i]=a[i]+(b[i]-a[i])*t;return o;}
function sampleSampler(sampler,time){var times=sampler.times,vals=sampler.values,n=sampler.components||1;if(!times.length)return null;if(time<=times[0])return Array.prototype.slice.call(vals,0,n);var last=times.length-1;if(time>=times[last])return Array.prototype.slice.call(vals,last*n,(last+1)*n);var i=0;while(i<last&&time>times[i+1])i++;var a=times[i],b=times[i+1],t=(time-a)/(b-a),v0=Array.prototype.slice.call(vals,i*n,(i+1)*n),v1=Array.prototype.slice.call(vals,(i+1)*n,(i+2)*n);return sampler.path==='rotation'?quatSlerp(v0,v1,t):lerp(v0,v1,t);}
function nodeMatrix(n){if(n.matrix)return n.matrix.slice();var t=n.translation||[0,0,0],s=n.scale||[1,1,1],q=n.rotation||[0,0,0,1],x=q[0],y=q[1],z=q[2],w=q[3];return[(1-2*y*y-2*z*z)*s[0],(2*x*y+2*w*z)*s[0],(2*x*z-2*w*y)*s[0],0,(2*x*y-2*w*z)*s[1],(1-2*x*x-2*z*z)*s[1],(2*y*z+2*w*x)*s[1],0,(2*x*z+2*w*y)*s[2],(2*y*z-2*w*x)*s[2],(1-2*x*x-2*y*y)*s[2],0,t[0],t[1],t[2],1];}
function loadSkin(g,b,skinIndex){var s=(g.skins||[])[skinIndex];if(!s)return null;var joints=s.joints||[],ib=s.inverseBindMatrices!=null?accessor(g,b,s.inverseBindMatrices):null;return{joints:joints.slice(),skeleton:s.skeleton==null?null:s.skeleton,inverseBindMatrices:ib||joints.map(function(){return ident();}),name:s.name||('skin_'+skinIndex)};}
function buildAnimations(g,b){return(g.animations||[]).map(function(a,ai){var channels=[],duration=0;(a.samplers||[]).forEach(function(s,si){var input=accessor(g,b,s.input),output=accessor(g,b,s.output),n=C((g.accessors[s.output]||{}).type);for(var i=0;i<input.length;i++)duration=Math.max(duration,input[i]);channels.push({times:input,values:output,components:n,interpolation:s.interpolation||'LINEAR',path:null});});(a.channels||[]).forEach(function(ch){var s=channels[ch.sampler];if(s){s.node=ch.target&&ch.target.node;s.path=ch.target&&ch.target.path;}});return{name:a.name||('animation_'+ai),duration:duration,channels:channels};});}
function prepare(url,asset){var g=asset.gltf,b=asset.buffers,skins=(g.skins||[]).map(function(_,i){return loadSkin(g,b,i);}),animations=buildAnimations(g,b),morphs=[];(g.meshes||[]).forEach(function(mesh,mi){(mesh.primitives||[]).forEach(function(p,pi){var weights=p.weights||mesh.weights||[],targets=p.targets||[];if(targets.length)morphs.push({mesh:mi,primitive:pi,weights:weights.slice(),targets:targets.map(function(t){var out={};Object.keys(t).forEach(function(k){out[k]=accessor(g,b,t[k]);});return out;})});});});return{url:url,skins:skins,animations:animations,morphs:morphs};}
function install(){if(!g.DNDGLTF||g.DNDGLTF.__characterPipeline)return;var old=g.DNDGLTF.load;g.DNDGLTF.load=function(url){return old(url).then(function(asset){if(!asset.character)asset.character=prepare(url,asset);return asset;});};g.DNDGLTF.__characterPipeline=true;}
g.DNDGLTFCharacterPipeline={install:install,prepare:prepare,sampleSampler:sampleSampler,buildAnimations:buildAnimations,loadSkin:loadSkin};
})(window);
