/* 2D-рендер новой карты: реальные floor/wall-текстуры + локальное освещение. */
(function(g){'use strict';
var IMG={},FLOOR={
floor_ceramic_tile_dark:'floor_ceramic_tile_dark.png',floor_ceramic_tile_light:'floor_ceramic_tile_light.png',
floor_checker_tile:'floor_checker_tile.png',floor_cobblestone:'floor_cobblestone.png',floor_earth:'floor_earth.png',
floor_grass:'floor_grass.png',floor_hex_tile:'floor_hex_tile.png',floor_marble_dark:'floor_marble_dark.png',
floor_marble_light:'floor_marble_light.png',floor_parquet_herringbone:'floor_parquet_herringbone.png',
floor_rug_blue:'floor_rug_blue.png',floor_rug_green:'floor_rug_green.png',floor_rug_red:'floor_rug_red.png',
floor_stone_tile_dark:'floor_stone_tile_dark.png',floor_stone_tile_light:'floor_stone_tile_light.png',
floor_tatami:'floor_tatami.png',floor_wood_dark:'floor_wood_dark.png',floor_wood_light:'floor_wood_light.png'
},WALL={
wall_brick_red:'wall_brick_red.png',wall_concrete:'wall_concrete.png',wall_half_timber:'wall_half_timber.png',
wall_marble_dark:'wall_marble_dark.png',wall_marble_light:'wall_marble_light.png',wall_moss_stone:'wall_moss_stone.png',
wall_old_plaster:'wall_old_plaster.png',wall_plaster_dark:'wall_plaster_dark.png',wall_plaster_light:'wall_plaster_light.png',
wall_plaster_panel:'wall_plaster_panel.png',wall_slate:'wall_slate.png',wall_stone_dark:'wall_stone_dark.png',
wall_stone_light:'wall_stone_light.png',wall_stone_masonry:'wall_stone_masonry.png',wall_wallpaper:'wall_wallpaper.png',
wall_white_plaster:'wall_white_plaster.png',wall_wood_dark:'wall_wood_dark.png',wall_wood_light:'wall_wood_light.png'
};
function image(name){if(!name)return null;if(IMG[name])return IMG[name];var im=new Image();im.src=(FLOOR[name]||WALL[name]||name);IMG[name]=im;return im;}
function pattern(ctx,name){var im=image(name);if(im&&im.complete&&im.naturalWidth){try{return ctx.createPattern(im,'repeat');}catch(e){}}return null;}
function draw(c,m){var ctx=c.getContext('2d'),f=g.DNDMapModel.current(m),s=Math.max(.25,Math.min(1.5,(c.parentElement.clientWidth-24)/(m.width*m.cell)));c.width=Math.max(240,Math.floor(m.width*m.cell*s));c.height=Math.max(240,Math.floor(m.height*m.cell*s));ctx.clearRect(0,0,c.width,c.height);
for(var y=0;y<m.height;y++)for(var x=0;x<m.width;x++){var t=f.tiles[x+','+y],name=t||null,X=x*m.cell*s,Y=y*m.cell*s,S=m.cell*s,pat=pattern(ctx,name);ctx.fillStyle=pat||({floor_ceramic_tile_dark:'#555',floor_ceramic_tile_light:'#888',floor_wood_dark:'#4a3424',floor_wood_light:'#765437',floor_grass:'#4b7044',floor_earth:'#634d35',floor_cobblestone:'#555',floor_marble_dark:'#454545',floor_marble_light:'#aaa',floor_stone_tile_dark:'#555',floor_stone_tile_light:'#888',floor_water:'#315f7c'}[name]||'#101010');ctx.fillRect(X,Y,S,S);ctx.strokeStyle='#303030';ctx.lineWidth=1;ctx.strokeRect(X,Y,S,S);}
var objs=f.objects||[];for(var oi=0;oi<objs.length;oi++){var o=objs[oi];if(o.type==='light'){var lx=(o.x+.5)*m.cell*s,ly=(o.y+.5)*m.cell*s;ctx.save();ctx.globalAlpha=.2;ctx.fillStyle='#ffd76a';ctx.beginPath();ctx.arc(lx,ly,Math.max(6,(o.radius||4)*m.cell*s),0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#ffe27a';ctx.beginPath();ctx.arc(lx,ly,Math.max(5,8*s),0,Math.PI*2);ctx.fill();ctx.restore();}else{var ox=o.x*m.cell*s,oy=o.y*m.cell*s,ow=Math.max(1,o.w)*m.cell*s,oh=Math.max(1,o.d)*m.cell*s;ctx.fillStyle=o.id===m.selectedObjectId?'#f0b94b':'#8a5a2b';ctx.fillRect(ox,oy,ow,oh);ctx.strokeStyle='#222';ctx.strokeRect(ox,oy,ow,oh);}}
/* Освещение накладывается на игровую сцену, но не на зоны/выделение. */
var dark=Math.max(0,Math.min(1,Number((m.lighting||{}).darkness)||0));if(dark>0){ctx.save();ctx.fillStyle='rgba(0,0,0,'+dark+')';ctx.fillRect(0,0,c.width,c.height);ctx.globalCompositeOperation='destination-out';for(var li=0;li<objs.length;li++){var l=objs[li];if(l.type!=='light')continue;var Lx=(l.x+.5)*m.cell*s,Ly=(l.y+.5)*m.cell*s,R=Math.max(1,(l.radius||4)*m.cell*s),g1=ctx.createRadialGradient(Lx,Ly,0,Lx,Ly,R);g1.addColorStop(0,'rgba(255,255,255,'+Math.min(1,(l.intensity||1))+')');g1.addColorStop(.7,'rgba(255,255,255,'+Math.min(1,(l.intensity||1)*.65)+')');g1.addColorStop(1,'0');ctx.fillStyle=g1;ctx.beginPath();ctx.arc(Lx,Ly,R,0,Math.PI*2);ctx.fill();}ctx.restore();}
var zs=f.zones||[];for(var zi=0;zi<zs.length;zi++){var z=zs[zi],ZX=z.x*m.cell*s,ZY=z.y*m.cell*s,ZW=z.w*m.cell*s,ZH=z.h*m.cell*s;ctx.fillStyle='rgba(240,200,90,.16)';ctx.fillRect(ZX,ZY,ZW,ZH);ctx.strokeStyle=z.id===m.selectedZoneId?'#fff':'#b58a30';ctx.lineWidth=z.id===m.selectedZoneId?3:2;ctx.strokeRect(ZX+1,ZY+1,ZW-2,ZH-2);ctx.fillStyle='#eee';ctx.font=Math.max(10,12*s)+'px Arial';ctx.fillText(z.name,ZX+5,ZY+15);}
ctx.strokeStyle='#ddd';ctx.lineWidth=5;for(var k in f.walls){var a=k.split(','),wx=+a[0],wy=+a[1],w=f.walls[k],X=wx*m.cell*s,Y=wy*m.cell*s,S=m.cell*s;function side(ok,tx,x1,y1,x2,y2){if(!ok)return;var pat=pattern(ctx,tx);ctx.strokeStyle=pat||'#ddd';ctx.lineWidth=Math.max(4,Math.min(12,S*.08));ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();}side(w.n,w.nTexture,X,Y,X+S,Y);side(w.e,w.eTexture,X+S,Y,X+S,Y+S);side(w.s,w.sTexture,X,Y+S,X+S,Y+S);side(w.w,w.wTexture,X,Y,X,Y+S);}
if(m.zonePreview){var p=m.zonePreview,PX=Math.min(p.x1,p.x2)*m.cell*s,PY=Math.min(p.y1,p.y2)*m.cell*s,PW=(Math.abs(p.x2-p.x1)+1)*m.cell*s,PH=(Math.abs(p.y2-p.y1)+1)*m.cell*s;ctx.fillStyle='rgba(255,255,255,.12)';ctx.fillRect(PX,PY,PW,PH);ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.setLineDash([6,4]);ctx.strokeRect(PX+1,PY+1,PW-2,PH-2);ctx.setLineDash([]);}return{s:s};}
function hitTest(m,s,px,py){var a=g.DNDMapModel.current(m).objects||[];for(var i=a.length-1;i>=0;i--){var o=a[i],x=o.x*m.cell*s,y=o.y*m.cell*s,w=Math.max(1,o.w)*m.cell*s,h=Math.max(1,o.d)*m.cell*s;if(px>=x&&px<=x+w&&py>=y&&py<=y+h)return o.id;}return null;}
function hitZone(m,s,px,py){var a=g.DNDMapModel.current(m).zones||[];for(var i=a.length-1;i>=0;i--){var z=a[i],x=z.x*m.cell*s,y=z.y*m.cell*s,w=z.w*m.cell*s,h=z.h*m.cell*s;if(px>=x&&px<=x+w&&py>=y&&py<=y+h)return z.id;}return null;}
g.DNDMapRenderer2D={draw:draw,hitTest:hitTest,hitZone:hitZone,FLOOR:FLOOR,WALL:WALL};})(window);