/* Настоящий перспективный WebGL-рендер карты. */
(function(g){'use strict';
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function sub(a,b){return[a[0]-b[0],a[1]-b[1],a[2]-b[2]];}
function norm(a){var l=Math.hypot(a[0],a[1],a[2])||1;return[a[0]/l,a[1]/l,a[2]/l];}
function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];}
function lookAt(eye,center,up){var z=norm(sub(eye,center)),x=norm(cross(up,z)),y=cross(z,x);return[x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-(x[0]*eye[0]+x[1]*eye[1]+x[2]*eye[2]),-(y[0]*eye[0]+y[1]*eye[1]+y[2]*eye[2]),-(z[0]*eye[0]+z[1]*eye[1]+z[2]*eye[2]),1];}
function perspective(fov,aspect,near,far){var f=1/Math.tan(fov/2),nf=1/(near-far);return[f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,(2*far*near)*nf,0];}
function mul(a,b){var o=new Array(16);for(var c=0;c<4;c++)for(var r=0;r<4;r++)o[c*4+r]=a[r]*b[c*4]+a[4+r]*b[c*4+1]+a[8+r]*b[c*4+2]+a[12+r]*b[c*4+3];return o;}
function floorBase(m,i){var y=0;for(var q=0;q<i;q++)y+=Number(m.floors[q].height)||3;return y;}
function cameraState(m,cam){var yaw=Number(cam.yaw)||0,pitch=clamp(Number(cam.pitch)||0,-1.35,1.35),pos=cam.position||[m.width/2,2,m.height/2],target=cam.target||[pos[0],pos[1],pos[2]-1];return{pos:pos,target:target,yaw:yaw,pitch:pitch};}
function project(m,cam,x,y,z){var c=cameraState(m,cam),dx=x-c.pos[0],dy=y-c.pos[1],dz=z-c.pos[2],cy=Math.cos(-c.yaw),sy=Math.sin(-c.yaw),cx=Math.cos(-c.pitch),sx=Math.sin(-c.pitch),rx=dx*cy-dz*sy,rz=dx*sy+dz*cy,ry=dy*cx-rz*sx,rz2=dy*sx+rz*cx;if(rz2>=-.05)return[999,999];var f=1/Math.tan((cam.fov||70)*Math.PI/360);return[(rx/-rz2)*f,(ry/-rz2)*f];}
function draw(c,m,cam){var gl=c.getContext('webgl',{antialias:true,alpha:false,depth:true});if(!gl)return false;var vs='attribute vec3 p;attribute vec4 col;attribute vec2 uv;uniform mat4 vp;uniform mat4 model;uniform sampler2D tex;uniform float useTex;varying vec4 v;varying vec2 vu;void main(){gl_Position=vp*model*vec4(p,1.0);v=col;vu=uv;}',fs='precision mediump float;varying vec4 v;varying vec2 vu;uniform sampler2D tex;uniform float useTex;void main(){vec4 t=texture2D(tex,vu);gl_FragColor=mix(v,t,useTex);}';function sh(t,s){var q=gl.createShader(t);gl.shaderSource(q,s);gl.compileShader(q);return q;}var prog=gl.createProgram();gl.attachShader(prog,sh(gl.VERTEX_SHADER,vs));gl.attachShader(prog,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);gl.useProgram(prog);
var modelLoc=gl.getUniformLocation(prog,'model'),texLoc=gl.getUniformLocation(prog,'tex'),useTexLoc=gl.getUniformLocation(prog,'useTex'),uvLoc=gl.getAttribLocation(prog,'uv');
var identity=[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
var f=g.DNDMapModel.current(m),verts=[],cols=[],objs=f.objects||[],dark=clamp(Number((m.lighting||{}).darkness)||0,0,1),by=floorBase(m,m.currentFloor),fh=Number(f.height)||3;
function illum(x,z){if(dark<=0)return 1;var best=0;for(var i=0;i<objs.length;i++){var l=objs[i];if(l.type!=='light')continue;var dist=Math.hypot((l.x+.5)-x,(l.y+.5)-z),rad=Math.max(.1,Number(l.radius)||4),power=clamp(Number(l.intensity==null?1:l.intensity),0,1);if(dist<rad)best=Math.max(best,(1-dist/rad)*power);}return clamp(1-dark*(1-best),.02,1);}
function baseColor(t){return t==='wood'?[.36,.23,.13]:t==='grass'?[.20,.38,.20]:t==='water'?[.12,.30,.42]:[.48,.50,.54];}
function tileCol(t,x,z){var b=baseColor(t),q=illum(x,z);return[b[0]*q,b[1]*q,b[2]*q,1];}
function quad(a,b,d,e,col){verts.push(a[0],a[1],a[2],b[0],b[1],b[2],d[0],d[1],d[2],a[0],a[1],a[2],d[0],d[1],d[2],e[0],e[1],e[2]);for(var i=0;i<6;i++)cols.push(col[0],col[1],col[2],col[3]);}
for(var y=0;y<m.height;y++)for(var x=0;x<m.width;x++){var t=f.tiles[x+','+y];if(t)quad([x,by,y],[x+1,by,y],[x,by,y+1],[x+1,by,y+1],tileCol(t,x+.5,y+.5));}
var walls=f.walls||{};Object.keys(walls).forEach(function(k){var p=k.split(','),x=+p[0],z=+p[1],w=walls[k]||{};if(w.n)quad([x,by,z],[x+1,by,z],[x,by+fh,z],[x+1,by+fh,z],[.38,.38,.42,1]);if(w.s)quad([x,by,z+1],[x+1,by,z+1],[x,by+fh,z+1],[x+1,by+fh,z+1],[.34,.34,.38,1]);if(w.w)quad([x,by,z],[x,by,z+1],[x,by+fh,z],[x,by+fh,z+1],[.36,.36,.40,1]);if(w.e)quad([x+1,by,z],[x+1,by,z+1],[x+1,by+fh,z],[x+1,by+fh,z+1],[.32,.32,.36,1]);});
for(var oi=0;oi<objs.length;oi++){var o=objs[oi],ox=o.x||0,oz=o.y||0,oy=by+(o.z||0),ow=Math.max(.25,o.w||1),od=Math.max(.25,o.d||1),oh=Math.max(.15,o.h||1),cc=o.id===m.selectedObjectId?[.95,.65,.15,1]:o.type==='light'?[1,.78,.25,1]:[.72,.48,.22,1];if(o.type==='light'){var s=.18;quad([ox+.5-s,oy+.1,oz+.5-s],[ox+.5+s,oy+.1,oz+.5-s],[ox+.5-s,oy+.5,oz+.5-s],[ox+.5+s,oy+.5,oz+.5-s],cc);}else{quad([ox,oy,oz],[ox+ow,oy,oz],[ox,oy+oh,oz],[ox+ow,oy+oh,oz],cc);quad([ox,oy,oz+od],[ox+ow,oy,oz+od],[ox,oy+oh,oz+od],[ox+ow,oy+oh,oz+od],cc);quad([ox,oy,oz],[ox,oy,oz+od],[ox,oy+oh,oz],[ox,oy+oh,oz+od],cc);quad([ox+ow,oy,oz],[ox+ow,oy,oz+od],[ox+ow,oy+oh,oz],[ox+ow,oy+oh,oz+od],cc);quad([ox,oy+oh,oz],[ox+ow,oy+oh,oz],[ox,oy+oh,oz+od],[ox+ow,oy+oh,oz+od],cc);}}
var vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);var pl=gl.getAttribLocation(prog,'p');gl.enableVertexAttribArray(pl);gl.vertexAttribPointer(pl,3,gl.FLOAT,false,0,0);var cb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,cb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(cols),gl.STATIC_DRAW);var cl=gl.getAttribLocation(prog,'col');gl.enableVertexAttribArray(cl);gl.vertexAttribPointer(cl,4,gl.FLOAT,false,0,0);
gl.uniformMatrix4fv(modelLoc,false,new Float32Array(identity));
var modelObjects=[];for(var mi=0;mi<objs.length;mi++)if(objs[mi].model)modelObjects.push(objs[mi]);gl.uniform1i(texLoc,0);gl.enable(gl.DEPTH_TEST);
var cs=cameraState(m,cam),vp=mul(perspective((cam.fov||70)*Math.PI/180,c.width/Math.max(1,c.height),.05,Math.max(200,m.width+m.height+50)),lookAt(cs.pos,cs.target,[0,1,0]));gl.uniformMatrix4fv(gl.getUniformLocation(prog,'vp'),false,new Float32Array(vp));
function modelMatrix(o){var sx=Number(o.scale)||1,sy=Number(o.scaleY)||sx,sz=Number(o.scaleZ)||sx,ox=(o.x||0)+.5,oz=(o.y||0)+.5,oy=by+(o.z||0);return[sx,0,0,0,0,sy,0,0,0,0,sz,0,ox,oy,oz,1];}
var texCache=g.__DND3DTextures||(g.__DND3DTextures={});function getTex(url){if(!url)return null;if(texCache[url])return texCache[url];var t=gl.createTexture();t._ready=false;var im=new Image();im.onload=function(){gl.bindTexture(gl.TEXTURE_2D,t);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,im);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.REPEAT);gl.generateMipmap(gl.TEXTURE_2D);t._ready=true;draw(c,m,cam);};im.onerror=function(){if(window.console)console.warn('Texture:',url);};im.src=url;texCache[url]=t;return t;}function matColor(asset,part){var m=(asset.materials||[])[part.material||0],f=m&&m.baseColorFactor;if(f)return[f[0],f[1],f[2],f[3]==null?1:f[3]];return[.72,.48,.22,1];}
function drawLoadedModel(o,asset){for(var pi=0;pi<asset.parts.length;pi++){var part=asset.parts[pi],key='__gpu_'+pi,buf=part[key];if(!buf||buf.ctx!==gl){buf={ctx:gl,pos:gl.createBuffer(),idx:part.indices?gl.createBuffer():null,count:part.indices?part.indices.length:part.positions.length/3,indexType:part.indices?(part.indices.constructor===Uint32Array?gl.UNSIGNED_INT:part.indices.constructor===Uint16Array?gl.UNSIGNED_SHORT:gl.UNSIGNED_BYTE):null};gl.bindBuffer(gl.ARRAY_BUFFER,buf.pos);gl.bufferData(gl.ARRAY_BUFFER,part.positions,gl.STATIC_DRAW);if(buf.idx){gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,buf.idx);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,part.indices,gl.STATIC_DRAW);}part[key]=buf;}gl.bindBuffer(gl.ARRAY_BUFFER,buf.pos);gl.vertexAttribPointer(pl,3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(pl);gl.uniformMatrix4fv(modelLoc,false,new Float32Array(modelMatrix(o)));var ccol=matColor(asset,part);gl.disableVertexAttribArray(cl);gl.vertexAttrib4f(cl,ccol[0],ccol[1],ccol[2],ccol[3]);var mm=asset.materials&&asset.materials[part.material||0],tt=mm&&mm.baseColorTexture?getTex(mm.baseColorTexture):null;gl.uniform1f(useTexLoc,tt&&tt._ready?1:0);if(tt&&tt._ready){gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,tt);}if(part.uv){var ub=part.__uv_gpu; if(!ub||ub.ctx!==gl){ub={ctx:gl,buf:gl.createBuffer()};gl.bindBuffer(gl.ARRAY_BUFFER,ub.buf);gl.bufferData(gl.ARRAY_BUFFER,part.uv,gl.STATIC_DRAW);part.__uv_gpu=ub;}gl.bindBuffer(gl.ARRAY_BUFFER,ub.buf);gl.vertexAttribPointer(uvLoc,2,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(uvLoc);}else{gl.disableVertexAttribArray(uvLoc);gl.vertexAttrib2f(uvLoc,0,0);}if(buf.idx){gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,buf.idx);gl.drawElements(part.mode,buf.count,buf.indexType,0);}else gl.drawArrays(part.mode,0,buf.count);}}
for(var li=0;li<modelObjects.length;li++){(function(o){if(!g.DNDGLTF)return;g.DNDGLTF.load(o.model).then(function(asset){drawLoadedModel(o,asset);}).catch(function(err){if(window.console)console.warn('glTF:',o.model,err);});})(modelObjects[li]);}
gl.uniformMatrix4fv(modelLoc,false,new Float32Array(identity));gl.enableVertexAttribArray(cl);gl.clearColor(.025*(1-dark),.025*(1-dark),.03*(1-dark),1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,verts.length/3);return true;}
function hitTest(c,m,cam,clientX,clientY){var r=c.getBoundingClientRect(),mx=(clientX-r.left)/r.width*2-1,my=1-(clientY-r.top)/r.height*2,objs=g.DNDMapModel.current(m).objects||[],best=null,bd=999;for(var i=0;i<objs.length;i++){var o=objs[i],p=project(m,cam,(o.x||0)+.5,floorBase(m,m.currentFloor)+(o.z||0)+.8,(o.y||0)+.5),d=Math.hypot(mx-p[0],my-p[1]);if(d<.12&&d<bd){bd=d;best=o.id;}}return best;}
g.DNDMapRenderer3D={draw:draw,hitTest:hitTest,projectPoint:function(m,cam,x,y,z){return project(m,cam,x,floorBase(m,m.currentFloor)+z,y);}};})(window);