/* Map world extension: geometry, visibility and transactional character interactions. */
(function(g){'use strict';const M=g.DNDMapModel,eps=1e-6;
function baseHeight(m,i){let h=0;for(let j=0;j<i;j++)h+=+m.floors[j].height||3;return h;}
function wallSegments(m,i){const f=m.floors[i],out=[],seen=new Set();if(!f)return out;Object.entries(f.walls||{}).forEach(([k,w])=>{const [x,y]=k.split(',').map(Number),ends={n:[[x,y],[x+1,y]],e:[[x+1,y],[x+1,y+1]],s:[[x,y+1],[x+1,y+1]],w:[[x,y],[x,y+1]],slash:[[x,y+1],[x+1,y]],backslash:[[x,y],[x+1,y+1]]};Object.keys(ends).forEach(side=>{if(!w[side])return;const [a,b]=ends[side],id=[a.join(','),b.join(',')].sort().join('|');if(seen.has(id))return;seen.add(id);out.push({id,a,b,x,y,side,w,kind:w[side+'Kind']||'wall',open:!!w[side+'Open'],locked:!!w[side+'Locked'],secret:!!w[side+'Secret'],revealed:!!w[side+'Revealed'],front:w[side+'FrontTexture']||w[side+'Texture']||m.selectedWallTexture,back:w[side+'BackTexture']||w[side+'Texture']||m.selectedWallTexture});});});return out;}
function crosses(a,b,c,d){const cross=(u,v)=>u[0]*v[1]-u[1]*v[0],sub=(u,v)=>[u[0]-v[0],u[1]-v[1]],r=sub(b,a),s=sub(d,c),den=cross(r,s);if(Math.abs(den)<eps)return false;const t=cross(sub(c,a),s)/den,u=cross(sub(c,a),r)/den;return t>eps&&t<1-eps&&u>=-eps&&u<=1+eps;}
function blocked(m,a,b,i,movement,segments){return (segments||wallSegments(m,i)).some(s=>!(s.open&&!s.secret||s.open&&s.revealed)&&!(s.kind==='window'&&!movement)&&crosses(a,b,s.a,s.b));}
function editWall(m,x,y,side,values){const f=M.current(m),k=M.key(x,y);f.walls[k]=f.walls[k]||{};const w=f.walls[k];w[side]=true;Object.entries(values).forEach(([key,v])=>w[side+key]=v);return w;}
function ceilings(m,i){const upper=m.floors[i+1];if(!upper)return [];return Object.entries(upper.tiles).map(([k,t])=>({key:k,texture:(upper.ceilings||{})[k]||upper.ceilingTexture||t,height:baseHeight(m,i+1)-.04}));}
function illuminationAt(m,x,y,i){const f=m.floors[i];let q=1-Math.max(0,Math.min(1,+m.lighting.darkness||0));(f.objects||[]).forEach(l=>{if((l.type!=='light'&&!l.emitsLight)||l.enabled===false)return;const d=Math.hypot(l.x+.5-x,l.y+.5-y),r=+l.lightRadius||+l.radius||4;if(d<r&&!blocked(m,[x,y],[l.x+.5,l.y+.5],i,false))q=Math.max(q,1-(+m.lighting.darkness||0)+(1-d/r)*(l.lightIntensity??l.intensity??1));});return Math.max(.08,Math.min(1,q));}
function visibility(m,t){const f=m.floors[t.floor],visible={},radius=+t.visionRadius||8;t.explored=t.explored||{};const explored=t.explored[f.id]=t.explored[f.id]||{};const segments=wallSegments(m,t.floor);for(let y=Math.max(0,Math.floor(t.y-radius));y<Math.min(m.height,t.y+radius+1);y++)for(let x=Math.max(0,Math.floor(t.x-radius));x<Math.min(m.width,t.x+radius+1);x++){if(Math.hypot(x-t.x,y-t.y)<=radius&&!blocked(m,[t.x+.5,t.y+.5],[x+.5,y+.5],t.floor,false,segments)){visible[M.key(x,y)]=true;explored[M.key(x,y)]=true;}}return{visible,explored};}
function actor(t){const a=g.currentCharacter||g.currentChar;if(!a||String(a.id)!==String(t.actorId))throw Error('Привяжите выбранного персонажа');return a;}
function commit(a,fn){const snapshot=M.clone(a);try{fn(a);if(typeof g.saveAllCharacters!=='function'||g.saveAllCharacters()===false)throw Error('Не удалось сохранить персонажа');}catch(e){Object.keys(a).forEach(k=>delete a[k]);Object.assign(a,snapshot);throw e;}}
function reachable(m,t,o){return t.floor===m.currentFloor&&Math.hypot(o.x-t.x,o.y-t.y)<=1.75&&!blocked(m,[t.x+.5,t.y+.5],[o.x+.5,o.y+.5],t.floor,false);}
function lootRows(m,t,o){const a=actor(t);m.worldId=m.worldId||'world-'+Date.now().toString(36);const claim=(a.mapWorldClaims||{})[m.worldId+':'+m.floors[t.floor].id+':'+o.id]||{},taken=o.lootTaken||{};if(o.lootClaimed||claim===true)return[];return(o.loot||[]).map((v,i)=>{const row=typeof v==='string'?{name:v}:v,id=row.lootId||'entry-'+i,count=Math.min(999,Math.max(1,+row.count||1))-Math.max(+taken[id]||0,+((claim.items||{})[id])||0);return Object.assign({},row,{lootId:id,count,category:row.category||'junk'});}).filter(v=>v.count>0);}
function takeLoot(m,t,id,entry){const o=M.getObject(m,id);if(!o||!reachable(m,t,o))throw Error('Контейнер вне досягаемости');if(o.locked)throw Error('Заперто');const a=actor(t),rows=lootRows(m,t,o).filter(r=>!entry||r.lootId===entry);if(!rows.length)return[];M.save(m);const key=m.worldId+':'+m.floors[t.floor].id+':'+o.id;commit(a,a=>{a.inventory=a.inventory||{};a.mapWorldClaims=a.mapWorldClaims||{};const receipt=a.mapWorldClaims[key]=a.mapWorldClaims[key]||{items:{}};rows.forEach(r=>{const cat=['weapons','armor','consumables','materials','junk'].includes(r.category)?r.category:'junk',items=a.inventory[cat]=a.inventory[cat]||[],existing=items.find(v=>v.name===r.name&&!v.equipped);if(existing)existing.count=(+existing.count||1)+r.count;else items.push({name:r.name,count:r.count,equipped:false});receipt.items[r.lootId]=(+receipt.items[r.lootId]||0)+r.count;});});o.lootTaken=o.lootTaken||{};rows.forEach(r=>o.lootTaken[r.lootId]=(+o.lootTaken[r.lootId]||0)+r.count);try{M.save(m);}catch(e){console.warn('Map save failed; actor receipt preserves loot',e);}return rows;}
function useObject(m,t,id){const o=M.getObject(m,id);if(!o||!reachable(m,t,o))throw Error('Объект вне досягаемости');if(o.locked)throw Error('Заперто');if(o.action==='toggleLight'||o.type==='light'){o.enabled=o.enabled===false;return'Свет переключён';}if(o.action==='stairs'||o.action==='hatch'){const i=m.floors.findIndex(f=>String(f.id)===String(o.targetFloorId));if(i<0||!M.canWalk(m,+o.targetX,+o.targetY,i))throw Error('Нет безопасного выхода');t.floor=m.currentFloor=i;t.x=+o.targetX;t.y=+o.targetY;return'Переход на этаж';}if(o.action==='lever'){wallSegments(m,t.floor).filter(s=>s.id===o.targetWallId).forEach(s=>s.w[s.side+'Open']=!s.open);return'Рычаг переключён';}return o.loot?'Обыск: смотрите на контейнер':'Использовано: '+o.name;}
function togglePortal(m,t,id){const s=wallSegments(m,t.floor).find(s=>s.id===id);if(!s||s.kind==='wall'||s.secret&&!s.revealed)throw Error('Проход не найден');const center=[(s.a[0]+s.b[0])/2,(s.a[1]+s.b[1])/2];if(Math.hypot(center[0]-t.x-.5,center[1]-t.y-.5)>1.75)throw Error('Слишком далеко');if(s.locked)throw Error('Заперто');s.w[s.side+'Open']=!s.open;return s.w[s.side+'Open'];}
function check(m,t,target,kind){const a=actor(t);if(!g.DNDRules)throw Error('Правила D&D недоступны');const stat=kind==='unlock'?'dex':'wis',skill=kind==='unlock'?'sleightOfHand':'perception',roll=g.DNDRules.rollD20(g.DNDRules.resolveRollMode(a,'normal')),bonus=g.DNDRules.getSkillBonus(a,skill,stat),dc=+target.lockDC||+target.dc||15,total=roll.result+bonus,success=total>=dc;if(success){if(target.w){target.w[target.side+(kind==='unlock'?'Locked':'Revealed')]=kind!=='unlock';}else if(kind==='unlock')target.locked=false;else target.revealed=true;}return{roll:roll.result,bonus,total,dc,success};}
function trap(m,t,config){const a=actor(t);if(!g.DNDCombat)throw Error('Боевая система недоступна');let result;commit(a,a=>{a.hp=Number(a.hpCurrent??a.hp??10);a.maxHp=Number(a.hpMax??a.maxHp??a.hp);a.tempHp=Number(a.hpTemp??a.tempHp??0);const save=g.DNDCombat.savingThrow(a,config.saveStat||'dex',+config.dc||12,'normal'),damage=g.DNDCombat.rollDice(config.damage||'1d6').total;result={save,damage:g.DNDCombat.applyDamage(a,save.success?Math.floor(damage/2):damage,config.damageType||'колющий',{source:'map-trap'})};a.hpCurrent=a.hp;a.hpTemp=a.tempHp;});['hpCurrent','hpTemp'].forEach(k=>{const el=g.document&&g.document.getElementById(k);if(el)el.value=a[k];});return result;}
function enterEvents(m,t){const f=m.floors[t.floor],messages=[];for(const zone of f.zones||[]){if(t.x<zone.x||t.x>=zone.x+zone.w||t.y<zone.y||t.y>=zone.y+zone.h)continue;zone.triggered=zone.triggered||{};if(zone.once!==false&&zone.triggered[t.id])continue;const event=zone.event||{};if(event.type==='trap')trap(m,t,event);else if(event.type==='check')check(m,t,event,'search');messages.push(event.message||zone.name);zone.triggered[t.id]=true;}return messages;}
Object.assign(M,{check,trap,enterEvents,baseHeight,wallSegments,editWall,ceilings,illuminationAt,visibility,worldActor:actor,lootRows,takeLoot,useObject,togglePortal,reachable,sightBlocked:(m,a,b,i)=>blocked(m,a,b,i,false),blocksMovement:(m,a,b,i)=>blocked(m,a,b,i,true)});
})(window);
