/* Карта v2: единая модель, этажи, стены, объекты и перемещение. */
(function(g){'use strict';
const KEY='dnd_vtt_3dmap_v2',DEFAULT={version:2,schemaVersion:1,name:'Новая карта',width:12,height:12,cell:64,currentFloor:0,view:'2d',selectedTool:'floor',selectedTexture:'floor_stone_tile_dark',selectedWallTexture:'wall_stone_dark',lighting:{darkness:.65},library:{mapId:'',author:'',description:'',tags:[],preview:'',requiredAssets:[],license:'',createdAt:'',updatedAt:''},floors:[{id:0,name:'Этаж 0',height:3,tiles:{},walls:{},objects:[],zones:[]}],tokens:[]};
function clone(v){return JSON.parse(JSON.stringify(v));} function floor(id){return{id:id,name:'Этаж '+id,height:3,tiles:{},walls:{},objects:[],zones:[]};}
function normalize(m){m=m&&typeof m==='object'?m:clone(DEFAULT);m.version=2;m.schemaVersion=1;m.library=m.library&&typeof m.library==='object'?m.library:{};m.library.mapId=String(m.library.mapId||'');m.library.author=String(m.library.author||'');m.library.description=String(m.library.description||'');m.library.tags=Array.isArray(m.library.tags)?m.library.tags.filter(Boolean).map(String):[];m.library.preview=String(m.library.preview||'');m.library.requiredAssets=Array.isArray(m.library.requiredAssets)?m.library.requiredAssets.filter(Boolean).map(String):[];m.library.license=String(m.library.license||'');m.library.createdAt=String(m.library.createdAt||'');m.library.updatedAt=String(m.library.updatedAt||'');m.lighting=m.lighting||{};m.lighting.darkness=(m.lighting.darkness==null?0.65:Math.max(0,Math.min(1,Number(m.lighting.darkness)||0)));m.selectedTexture=m.selectedTexture||'floor_stone_tile_dark';m.selectedWallTexture=m.selectedWallTexture||'wall_stone_dark';m.width=Math.max(1,Math.min(200,Number(m.width)||12));m.height=Math.max(1,Math.min(200,Number(m.height)||12));m.cell=Number(m.cell)||64;m.floors=Array.isArray(m.floors)&&m.floors.length?m.floors:[floor(0)];m.floors.forEach(function(f,i){f.id=Number.isFinite(f.id)?f.id:i;f.name=f.name||('Этаж '+f.id);f.height=Math.max(1,Number(f.height)||3);f.tiles=f.tiles||{};f.walls=f.walls||{};f.objects=Array.isArray(f.objects)?f.objects:[];f.zones=Array.isArray(f.zones)?f.zones:[];});m.tokens=Array.isArray(m.tokens)?m.tokens:[];m.currentFloor=Math.max(0,Math.min(m.floors.length-1,Number(m.currentFloor)||0));return m;}
function key(x,y){return x+','+y;} function current(m){return m.floors[m.currentFloor];}
function load(){try{return normalize(JSON.parse(localStorage.getItem(KEY)||'null'));}catch(e){return clone(DEFAULT);}} function save(m){m=normalize(m);localStorage.setItem(KEY,JSON.stringify(m));return m;} function reset(){localStorage.removeItem(KEY);return load();}
function resize(m,dir,delta){delta=Math.trunc(Number(delta)||0);if(dir==='n'||dir==='s')m.height=Math.max(1,Math.min(200,m.height+delta));if(dir==='e'||dir==='w')m.width=Math.max(1,Math.min(200,m.width+delta));return m;}
function addZone(m,x1,y1,x2,y2,name){var f=current(m),minX=Math.max(0,Math.min(m.width-1,Math.min(x1,x2))),maxX=Math.max(0,Math.min(m.width-1,Math.max(x1,x2))),minY=Math.max(0,Math.min(m.height-1,Math.min(y1,y2))),maxY=Math.max(0,Math.min(m.height-1,Math.max(y1,y2)));var z={id:'z'+Date.now()+Math.random().toString(36).slice(2),x:minX,y:minY,w:maxX-minX+1,h:maxY-minY+1,name:name||'Зона'};f.zones.push(z);m.selectedZoneId=z.id;return z;}function getZone(m,id){var a=current(m).zones||[];for(var i=0;i<a.length;i++)if(a[i].id===id)return a[i];return null;}function removeZone(m,id){var a=current(m).zones||[];for(var i=a.length-1;i>=0;i--)if(a[i].id===id)a.splice(i,1);if(m.selectedZoneId===id)m.selectedZoneId=null;}function setTile(m,x,y,type){if(x<0||y<0||x>=m.width||y>=m.height)return;var f=current(m),k=key(x,y);if(type==='void')delete f.tiles[k];else f.tiles[k]=type;}
function wall(m,x,y,side,texture){var f=current(m),k=key(x,y);f.walls[k]=f.walls[k]||{};if(f.walls[k][side]){f.walls[k][side]=false;return;}f.walls[k][side]=true;f.walls[k][side+'Texture']=texture||m.selectedWallTexture||'wall_stone_dark';}
function addFloor(m,dir){var ids=m.floors.map(function(f){return f.id;}),id=dir==='up'?Math.max.apply(null,ids)+1:Math.min.apply(null,ids)-1;if(dir==='up')m.floors.push(floor(id));else{m.floors.unshift(floor(id));m.currentFloor++;}return m;}
function removeFloor(m){if(m.floors.length>1){m.floors.splice(m.currentFloor,1);m.currentFloor=Math.max(0,Math.min(m.currentFloor,m.floors.length-1));}return m;}
function addObject(m,o){var obj=Object.assign({id:'o'+Date.now()+Math.random().toString(36).slice(2),x:0,y:0,z:0,w:1,d:1,h:1,type:'box',name:'Объект',radius:4,intensity:1},o||{});current(m).objects.push(obj);m.selectedObjectId=obj.id;return obj;} function getObject(m,id){var a=current(m).objects;for(var i=0;i<a.length;i++)if(a[i].id===id)return a[i];return null;} function removeObject(m,id){var a=current(m).objects;for(var i=a.length-1;i>=0;i--)if(a[i].id===id)a.splice(i,1);if(m.selectedObjectId===id)m.selectedObjectId=null;}
function getLibraryManifest(m){m=normalize(clone(m));var totalObjects=0,totalZones=0;for(var i=0;i<m.floors.length;i++){totalObjects+=(m.floors[i].objects||[]).length;totalZones+=(m.floors[i].zones||[]).length;}return{schemaVersion:1,mapId:m.library.mapId||'',name:m.name||'Без названия',author:m.library.author||'',description:m.library.description||'',tags:m.library.tags||[],preview:m.library.preview||'',requiredAssets:m.library.requiredAssets||[],license:m.library.license||'',size:{width:m.width,height:m.height,floors:m.floors.length},content:{objects:totalObjects,zones:totalZones},updatedAt:m.library.updatedAt||''};}function prepareForLibrary(m){m=normalize(clone(m));if(!m.library.mapId)m.library.mapId='map_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);if(!m.library.createdAt)m.library.createdAt=new Date().toISOString();m.library.updatedAt=new Date().toISOString();return m;}
function illuminationAt(m,x,y,i){var dark=Math.max(0,Math.min(1,Number((m.lighting||{}).darkness)||0));if(dark<=0)return 1;var f=m.floors[i],lights=f&&f.objects||[],best=0;for(var q=0;q<lights.length;q++){var l=lights[q];if(l.type!=='light')continue;var dx=(l.x+.5)-x,dy=(l.y+.5)-y,dist=Math.sqrt(dx*dx+dy*dy),rad=Math.max(.1,Number(l.radius)||4),power=Math.max(0,Math.min(1,Number(l.intensity)||1));if(dist<rad)best=Math.max(best,(1-dist/rad)*power);}return Math.max(0,Math.min(1,1-dark*(1-best)));}function isSolid(m,x,y,i){var f=m.floors[i];return !!(f&&f.tiles[key(x,y)]);} function canWalk(m,x,y,i){return x>=0&&y>=0&&x<m.width&&y<m.height&&isSolid(m,x,y,i);}
function resolveFall(m,x,y,start){var f=start;while(f>0&&!isSolid(m,x,y,f))f--;return{floor:f,x:x,y:y,fallen:f!==start};}
g.DNDMapModel={KEY:KEY,DEFAULT:DEFAULT,clone:clone,normalize:normalize,load:load,save:save,prepareForLibrary:prepareForLibrary,getLibraryManifest:getLibraryManifest,current:current,key:key,resize:resize,setTile:setTile,wall:wall,addFloor:addFloor,removeFloor:removeFloor,addObject:addObject,getObject:getObject,removeObject:removeObject,addZone:addZone,getZone:getZone,removeZone:removeZone,isSolid:isSolid,canWalk:canWalk,resolveFall:resolveFall,illuminationAt:illuminationAt};
})(window);