/* Автономный WebGL 3D-рендер карты. Без Three.js и внешних импортов. */
(function(g){'use strict';
function project(m,cam,x,y,z){var S=2/Math.max(m.width,m.height),X=x/m.width*2-1,Y=1-y/m.height*2,Z=z*S*.9,cx=Math.cos(cam.yaw),sx=Math.sin(cam.yaw),cp=Math.cos(cam.pitch),sp=Math.sin(cam.pitch),a=X*cx-Z*sx,b=X*sx+Z*cx;return[x=(a*cam.zoom),y=(Y*cam.zoom*cp-b*sp)];}
function draw(c,m,cam){var gl=c.getContext('webgl',{antialias:true,alpha:false});if(!gl)return false;var vs='attribute vec3 p;uniform mat4 m;void main(){gl_Position=m*vec4(p,1.0);}',fs='precision mediump float;uniform vec4 c;void main(){gl_FragColor=c;}';function sh(t,s){var q=gl.createShader(t);gl.shaderSource(q,s);gl.compileShader(q);return q;}var p=gl.createProgram();gl.attachShader(p,sh(gl.VERTEX_SHADER,vs));gl.attachShader(p,sh(gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);gl.useProgram(p);var f=g.DNDMapModel.current(m),S=2/Math.max(m.width,m.height),v=[],colors=[],yaw=cam.yaw,pitch=cam.pitch,zoom=cam.zoom,cx=Math.cos(yaw),sx=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);
function P(x,y,z){var a=x*cx-z*sx,b=x*sx+z*cx;return[a*zoom,(y*zoom*cp-b*sp)];}
function tileColor(t){return t==='wood'?[.36,.23,.13]:t==='grass'?[.20,.38,.20]:t==='water'?[.12,.30,.42]:[.48,.50,.54];}
function tri(a,b,d,e,col){v.push(a[0],a[1],0,b[0],b[1],0,e[0],e[1],0,a[0],a[1],0,e[0],e[1],0,d[0],d[1],0);for(var q=0;q<6;q++)colors.push(col[0],col[1],col[2],1);}
for(var y=0;y<m.height;y++)for(var x=0;x<m.width;x++){var t=f.tiles[x+','+y];if(t){var X=x/m.width*2-1,Y=1-y/m.height*2,Z=f.id*.18,a=P(X,Y,Z),b=P(X+S,Y,Z),d=P(X,Y-S,Z),e=P(X+S,Y-S,Z);tri(a,b,d,e,tileColor(t));}}
var objs=f.objects||[];for(var oi=0;oi<objs.length;oi++){var o=objs[oi],ox=o.x/m.width*2-1,oy=1-o.y/m.height*2,oz=f.id*.18+(o.z||0)*.12,ow=Math.max(.25,o.w)/m.width*2,od=Math.max(.25,o.d)/m.height*2,oh=Math.max(.15,o.h)*.08;var a=P(ox,oy,oz),b=P(ox+ow,oy,oz),d=P(ox,oy-od,oz),e=P(ox+ow,oy-od,oz);var top=[a[0],a[1]-oh*zoom],bt=[b[0],b[1]-oh*zoom],dt=[d[0],d[1]-oh*zoom],et=[e[0],e[1]-oh*zoom],col=o.id===m.selectedObjectId?[.95,.65,.15]:[.72,.48,.22];tri(a,b,d,e,col);tri(top,bt,dt,et,col);}
var buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(v),gl.STATIC_DRAW);var loc=gl.getAttribLocation(p,'p');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0);gl.uniformMatrix4fv(gl.getUniformLocation(p,'m'),false,new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]));var colorLoc=gl.getUniformLocation(p,'c');gl.uniform4f(colorLoc,.48,.5,.54,1);gl.viewport(0,0,c.width,c.height);gl.clearColor(.025,.025,.03,1);gl.clear(gl.COLOR_BUFFER_BIT);for(var i=0,off=0;i<colors.length;i+=24,off+=6){gl.uniform4f(colorLoc,colors[i],colors[i+1],colors[i+2],1);gl.drawArrays(gl.TRIANGLES,off,6);}return true;}
function hitTest(c,m,cam,clientX,clientY){var r=c.getBoundingClientRect(),px=(clientX-r.left)/Math.max(1,c.width)*2-1,py=1-(clientY-r.top)/Math.max(1,c.height)*2,objs=g.DNDMapModel.current(m).objects||[];for(var i=objs.length-1;i>=0;i--){var o=objs[i],p=project(m,cam,o.x,o.y,o.z||0),p2=project(m,cam,o.x+Math.max(.25,o.w),o.y+Math.max(.25,o.d),o.z||0),w=Math.max(18,Math.abs(p2[0]-p[0])*c.width/2),h=Math.max(18,Math.abs(p2[1]-p[1])*c.height/2);if(Math.abs(px-p[0])<=w*2/c.width&&Math.abs(py-p[1])<=h*2/c.height)return o.id;}return null;}
g.DNDMapRenderer3D={draw:draw,hitTest:hitTest};})(window);