const fs=require('fs'),vm=require('vm'),assert=require('assert');
let randomValue=0.99,randomSequence=null,rollResult=19;
const math=Object.create(Math);math.random=()=>randomSequence&&randomSequence.length?randomSequence.shift():randomValue;
const ctx={console,Math:math,Date,JSON,Set,Number,String,Array,Object,RegExp,parseInt,parseFloat,
  document:{getElementById:()=>null,querySelectorAll:()=>[],addEventListener:()=>{}},
  addEventListener:()=>{},setTimeout:()=>{},clearTimeout:()=>{},prompt:()=>null,alert:()=>{},window:null};
ctx.window=ctx;ctx.globalThis=ctx;
ctx.DNDRules={
  parseDice(expr){const m=String(expr).match(/(\d+)d(\d+)(?:([+-])(\d+))?/i);return m?{groups:[{count:Number(m[1]),sides:Number(m[2])}],constant:m[3]?(m[3]==='-'?-1:1)*Number(m[4]):0}:{groups:[{count:1,sides:6}],constant:0};},
  rollD20(){return {result:rollResult,critical:rollResult===20,fumble:rollResult===1};},getSaveBonus(){return 0;}
};
ctx.DNDContent={packs:[],registerClass(p){this.packs.push(p);},listClasses(){return this.packs.map(p=>({name:p.displayName||p.name}));},getClass(n){return this.packs.find(p=>p.displayName===n||p.name===n||p.id===n)||null;}};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(__dirname+'/../app/expansion_classes_pack.js','utf8'),ctx);
vm.runInContext(fs.readFileSync(__dirname+'/../app/class_features_engine.js','utf8'),ctx);
vm.runInContext(fs.readFileSync(__dirname+'/../app/combat_engine.js','utf8'),ctx);
const pack=ctx.DNDContent.getClass('Пугилист');
assert.ok(pack&&pack.hooks,'Pugilist pack and hooks register');
function hero(level,subclass,extra={}){return Object.assign({id:'pugilist-'+level,classes:[{name:'Пугилист',level,subclass}],stats:{str:16,con:14,dex:10,wis:10,cha:12,int:10},abilityScores:{strength:16,constitution:14,dexterity:10,wisdom:10,charisma:12,intelligence:10},proficiencyBonus:3,hp:30,maxHp:30,tempHp:0,resources:{},classFeaturesState:{}},extra);}
function target(id,ac=1){return{id,hp:30,maxHp:30,ac,tempHp:0,conditions:{},activeConditions:{},resistances:[],immunities:[],vulnerabilities:[],classFeaturesState:{}};}
const boxer=hero(17,'Благородное искусство');pack.hooks.sync(boxer);
const modifiers=ctx.DNDClassFeatures.attackModifiers(boxer,{target:target('crit'),unarmedAttack:true});
assert.equal(modifiers.criticalRange,19,'Saved subclass name resolves to Sweet Science in the actual class-feature engine');
assert.equal(modifiers.unarmedDie,'1d12','Level 17 Fisticuffs die reaches the combat resolver');
const critTarget=target('crit');
const crit=ctx.DNDCombat.attack(boxer,critTarget,{bonus:0,damage:'1d4',damageType:'дробящий',unarmedAttack:true,useRules:false});
assert.equal(crit.critical,true,'Natural 19 is critical through the real combat pipeline');
assert.equal(crit.damage.expression,'1d12','Fisticuffs replaces the supplied unarmed damage die');
assert.equal(crit.damage.rolls.length,2,'Critical Fisticuffs attack rolls two d12');
assert.equal(critTarget.hp,30-crit.damage.total,'Resolved Fisticuffs damage is applied to target HP');
const haymaker=hero(5,'Арена Рояль');pack.hooks.sync(haymaker);
assert.equal(pack.hooks.useFeature(haymaker,'haymaker',{}).ok,true,'Haymaker activates at level 5');
randomValue=0.1;
const hayTarget=target('haymaker-target');
const hay=ctx.DNDCombat.attack(haymaker,hayTarget,{bonus:0,damage:'1d6',damageType:'рубящий',useRules:false});
assert.equal(hay.hit,true,'Haymaker fixture hits');
assert.equal(hay.damage.total,6,'Haymaker maximizes actual damage die');
assert.equal(hay.damage.maximized,true,'Combat result marks damage dice as maximized');
assert.equal(hayTarget.hp,24,'Maximized damage is actually applied to target HP');
const arena=hero(17,'Арена Рояль');pack.hooks.sync(arena);
const sigTarget=target('signature-target');
assert.equal(pack.hooks.useFeature(arena,'signatureMove',{target:sigTarget}).ok,true,'Signature Move can be prepared against a selected target');
const wrong=target('wrong-target');
ctx.DNDCombat.attack(arena,wrong,{bonus:0,damage:'1d6',damageType:'дробящий',useRules:false});
assert.equal(arena.classFeaturesState.pugilistSignatureMovePending,true,'Signature Move does not consume itself on a different target');
assert.equal(wrong.conditions['Оглушён'],undefined,'Signature Move does not stun the wrong target');
const sig=ctx.DNDCombat.attack(arena,sigTarget,{bonus:0,damage:'1d6',damageType:'дробящий',useRules:false});
assert.equal(sig.critical,true,'Signature Move forces a critical hit on its chosen target');
assert.equal(!!sigTarget.conditions['Оглушён'],true,'Signature Move applies stun to its chosen target');
assert.equal(arena.classFeaturesState.pugilistSignatureMovePending,false,'Signature Move clears after its chosen target is hit');
const missArena=hero(17,'Арена Рояль');pack.hooks.sync(missArena);
const missTarget=target('miss-target',99);
const resourceBefore=missArena.resources.pugilistSignatureMove.current;
pack.hooks.useFeature(missArena,'signatureMove',{target:missTarget});
rollResult=1;ctx.DNDCombat.attack(missArena,missTarget,{bonus:-100,damage:'1d6',damageType:'дробящий',useRules:false});rollResult=19;
assert.equal(missArena.classFeaturesState.pugilistSignatureMovePending,false,'Signature Move clears after a miss');
assert.equal(missArena.resources.pugilistSignatureMove.current,resourceBefore,'Signature Move charge is restored after a miss');
const defender=target('dig-deep-defender');
defender.classFeaturesState.pugilistDigDeepActive={roundsRemaining:10,damageTypes:['bludgeoning','piercing','slashing']};
const resisted=ctx.DNDCombat.applyDamage(defender,11,'рубящий',{attackerId:'enemy'});
assert.equal(resisted.amount,5,'Dig Deep halves physical damage');
assert.equal(defender.hp,25,'Dig Deep changes actual HP');
assert.equal(ctx.DNDCombat.effectiveDamage(defender,11,'огонь',{}).amount,11,'Dig Deep does not resist fire');
const expired=target('expired-dig-deep');expired.classFeaturesState.pugilistDigDeepActive={roundsRemaining:0};
assert.equal(ctx.DNDCombat.effectiveDamage(expired,11,'рубящий',{}).amount,11,'Expired Dig Deep no longer resists damage');
const hpShape=hero(18,'Арена Рояль',{hpCurrent:0,hpMax:40});delete hpShape.hp;delete hpShape.maxHp;
pack.hooks.sync(hpShape);
assert.equal(pack.hooks.useFeature(hpShape,'fightingSpirit',{}).ok,true,'Fighting Spirit supports the app hpCurrent/hpMax shape');
assert.equal(hpShape.hpCurrent,20,'Fighting Spirit restores half max HP in the app data shape');
assert.equal(hpShape.classFeaturesState.pugilistExhaustion,1,'Fighting Spirit adds one exhaustion level');
const ironChinTarget=hero(1,'Арена Рояль');ironChinTarget.ac=10;ironChinTarget.abilityScores.constitution=16;ironChinTarget.stats.con=16;
const ironChinAttack=ctx.DNDCombat.attack(hero(1,'Арена Рояль'),ironChinTarget,{bonus:0,damage:'1d4',damageType:'рубящий',useRules:false});
assert.equal(ironChinAttack.ac,15,'Iron Chin computes AC as 12 + Constitution modifier without armor/shield');
const schoolHero=hero(10,'Арена Рояль');pack.hooks.sync(schoolHero);
const schoolDamageTarget=target('school-of-hard-knocks');schoolDamageTarget.classes=[{name:'Пугилист',level:10}];
assert.equal(ctx.DNDCombat.effectiveDamage(schoolDamageTarget,11,'психический',{}).amount,5,'School of Hard Knocks resists psychic damage');
const schoolSave=ctx.DNDCombat.savingThrow(schoolHero,'con',10,'normal',{saveType:'stunned'});
assert.ok(schoolSave.classFeatureNotes.includes('Школа суровой жизни'),'School of Hard Knocks grants advantage against stun/unconsciousness saves');
const counterHero=hero(3,'Благородное искусство');pack.hooks.sync(counterHero);
const counter=pack.hooks.useFeature(counterHero,'crossCounter',{attacker:{id:'enemy-attacker'},incomingDamage:10});
assert.equal(counter.ok,true,'Cross Counter prepares a damage reduction reaction');
const counterDamage=ctx.DNDCombat.applyDamage(counterHero,10,'рубящий',{attackerId:'enemy-attacker'});
assert.equal(counterDamage.amount,counter.effect.damageAfter,'Cross Counter reduction reaches the actual damage resolver');
assert.equal(counterHero.hp,30-counter.effect.damageAfter,'Cross Counter reduces actual HP loss');
assert.equal(counterHero.classFeaturesState.pugilistCounterCounter,undefined,'Cross Counter state is consumed after the matching attack');
const magicFistHero=hero(6,'Арена Рояль');pack.hooks.sync(magicFistHero);
const resistantTarget=target('nonmagical-resistance');resistantTarget.resistances=['nonmagical дробящий'];
const magicHit=ctx.DNDCombat.attack(magicFistHero,resistantTarget,{bonus:0,damage:'1d4',damageType:'дробящий',unarmedAttack:true,useRules:false});
assert.equal(magicHit.damageResult.amount,magicHit.damage.total,'Level 6 magical fists bypass resistance explicitly limited to nonmagical bludgeoning damage');
const conditionHero=hero(7,'Арена Рояль');conditionHero.conditions={Очарован:true,Испуган:true};conditionHero.activeConditions={charmed:true,frightened:true};pack.hooks.sync(conditionHero);
assert.equal(pack.hooks.useFeature(conditionHero,'shakeItOff',{}).ok,true,'Shake It Off resolves');
assert.equal(conditionHero.conditions['Очарован'],undefined,'Shake It Off removes charmed condition');
assert.equal(conditionHero.activeConditions.frightened,undefined,'Shake It Off removes frightened condition');
const dirtyHero=hero(6,'Ярость и дерзость');pack.hooks.sync(dirtyHero);
const dirtyTarget=target('dirty-target');rollResult=1;
const dirty=pack.hooks.useFeature(dirtyHero,'pocketSand',{target:dirtyTarget});rollResult=19;
assert.equal(dirty.ok,true,'Pocket Sand resolves a real Constitution save');
assert.equal(dirtyTarget.conditions['Ослеплён'],true,'Pocket Sand applies blindness on a failed save');
assert.equal(dirty.effect.moxieRestored,1,'A failed dirty-trick save restores one Moxie');
const saltyHero=hero(3,'Ярость и дерзость');pack.hooks.sync(saltyHero);const saltyTarget=target('salty-target');rollResult=1;
const salty=pack.hooks.useFeature(saltyHero,'saltySalute',{target:saltyTarget});rollResult=19;
assert.equal(salty.ok,true,'Salty Salute resolves a real Wisdom save');
assert.ok(saltyTarget.classFeaturesState.pugilistSaltySalute,'Failed Salty Salute save records its attack penalty');
const saltyMods=ctx.DNDClassFeatures.attackModifiers(saltyTarget,{target:target('someone-else')});
assert.equal(saltyMods.disadvantage,true,'Salty Salute imposes disadvantage on attacks away from its source');
const crowdHero=hero(6,'Арена Рояль');pack.hooks.sync(crowdHero);const crowdTarget=target('crowd-target');rollResult=1;
const crowd=pack.hooks.useFeature(crowdHero,'workCrowd',{target:crowdTarget,condition:'frightened'});rollResult=19;
assert.equal(crowd.ok,true,'Work Crowd resolves selected targets');
assert.equal(crowdTarget.conditions['Испуган'],true,'Work Crowd applies frightened on a failed Wisdom save');
assert.ok(crowdTarget.classFeaturesState.pugilistCrowdControl,'Work Crowd tracks its repeat-save condition');
ctx.DNDCombat.applyDamage(crowdTarget,1,'рубящий',{attackerId:'test-attacker'});
assert.equal(crowdTarget.classFeaturesState.pugilistCrowdControl,undefined,'Damage can trigger Work Crowd repeat save and clear the condition on success');
const dreadHero=hero(17,'Рука Ужаса');pack.hooks.sync(dreadHero);const visceraTarget=target('viscera-target');rollResult=1;
const viscera=pack.hooks.useFeature(dreadHero,'fountainViscera',{target:visceraTarget});rollResult=19;
assert.equal(viscera.ok,true,'Fountain of Viscera resolves its Dexterity and fear saves');
assert.equal(visceraTarget.hp,0,'Fountain of Viscera applies its actual damage to HP');
assert.equal(visceraTarget.conditions['Испуган'],true,'Fountain of Viscera applies fear after a failed Wisdom save');
assert.equal(dreadHero.resources.pugilistMoxie.current,4,'Fountain of Viscera spends six Moxie');
const bbuHero=hero(3,'Арена Рояль',{hp:20,maxHp:30,turnResources:{reaction:1}});pack.hooks.sync(bbuHero);bbuHero.resources.pugilistMoxie.current=0;
const bbuDamage=ctx.DNDCombat.applyDamage(bbuHero,6,'рубящий',{attackerId:'threshold-enemy'});
assert.equal(bbuHero.hp,14,'Damage crosses the half-HP threshold');
assert.equal(bbuHero.tempHp,5,'Bloodied but Unbowed automatically grants temporary HP');
assert.equal(bbuHero.resources.pugilistMoxie.current,bbuHero.resources.pugilistMoxie.max,'Bloodied but Unbowed automatically restores Moxie');
assert.equal(bbuHero.turnResources.reaction,0,'Bloodied but Unbowed consumes the reaction');
assert.ok(bbuDamage.note.includes('Израненный, но не сломленный'),'Combat result reports the automatic reaction');
const spiritAuto=hero(18,'Арена Рояль',{hp:5,maxHp:40});pack.hooks.sync(spiritAuto);
const fatalHit=ctx.DNDCombat.applyDamage(spiritAuto,10,'рубящий',{attackerId:'fatal-enemy'});
assert.equal(spiritAuto.hp,20,'Fighting Spirit automatically restores half maximum HP when reduced to zero');
assert.equal(spiritAuto.classFeaturesState.pugilistExhaustion,1,'Automatic Fighting Spirit adds exhaustion');
assert.equal(spiritAuto.resources.pugilistFightingSpirit.current,0,'Automatic Fighting Spirit consumes its long-rest use');
const unbreakableHero=hero(14,'Арена Рояль');pack.hooks.sync(unbreakableHero);const beforeMoxie=unbreakableHero.resources.pugilistMoxie.current;
const unbreakable=pack.hooks.useFeature(unbreakableHero,'unbreakable',{failedSave:true,stat:'str',dc:15});
assert.equal(unbreakable.ok,true,'Unbreakable performs a real rerolled saving throw');
assert.equal(unbreakable.effect.success,true,'The deterministic reroll can succeed');
assert.equal(unbreakableHero.resources.pugilistMoxie.current,beforeMoxie-1,'Unbreakable spends exactly one Moxie');
const dreadHandHero=hero(17,'Рука Ужаса');pack.hooks.sync(dreadHandHero);pack.hooks.useFeature(dreadHandHero,'dreadHand',{});
const dreadTarget=target('dread-hand-target');randomSequence=[0,0.99];
const dreadAttack=ctx.DNDCombat.attack(dreadHandHero,dreadTarget,{bonus:0,damage:'1d6',damageType:'дробящий',unarmedAttack:true,useRules:false});randomSequence=null;
assert.equal(dreadAttack.damage.total,12,'Level 17 Hand of Dread rerolls a d12 damage die that rolled a 1');
assert.ok(dreadAttack.classFeatureNotes.includes('Рука Ужаса: одна кость урона переброшена.'),'Combat log reports the damage-die reroll');
const flyer=hero(11,'Арена Рояль',{speed:30});pack.hooks.sync(flyer);ctx.DNDClassFeatures.resetTurn(flyer);
assert.equal(flyer.turnResources.movement,40,'High Flyer adds 10 feet of movement automatically');
assert.equal(flyer.classFeaturesState.pugilistJumpMultiplier,2,'High Flyer doubles jump distance');
const growth=hero(17,'Рука Ужаса');pack.hooks.sync(growth);pack.hooks.useFeature(growth,'dreadHand',{});
assert.equal(pack.hooks.useFeature(growth,'grotesqueGrowth',{}).ok,true,'Grotesque Growth activates only after Hand of Dread');
const growthTarget=target('growth-target');
const growthAttack=ctx.DNDCombat.attack(growth,growthTarget,{bonus:0,damage:'1d6',damageType:'дробящий',unarmedAttack:true,useRules:false});
assert.ok(growthAttack.damage.extraDice.some(d=>d.expression==='1d4'),'Grotesque Growth adds its d4 to actual attack damage');
for(let i=0;i<10;i++)ctx.DNDClassFeatures.onTurnEnd(growth);
assert.equal(growth.classFeaturesState.pugilistGrotesqueGrowthActive,null,'Grotesque Growth expires after 10 turns');
assert.equal(growth.classFeaturesState.pugilistExhaustion,1,'Grotesque Growth applies exhaustion once on expiry');
const floorHero=hero(17,'Благородное искусство');pack.hooks.sync(floorHero);const floorTarget=target('floor-target');
assert.equal(pack.hooks.useFeature(floorHero,'oneTwoThreeFloor',{target:floorTarget}).ok,true,'One-Two-Three Floor prepares a selected target');
const floorAttack=ctx.DNDCombat.attack(floorHero,floorTarget,{bonus:0,damage:'1d6',damageType:'дробящий',unarmedAttack:true,useRules:false});
assert.equal(floorAttack.damage.total,0,'One-Two-Three Floor deals no damage');
assert.equal(floorTarget.conditions['Сбит с ног'],true,'One-Two-Three Floor knocks the target prone on a hit');
assert.equal(floorTarget.hp,30,'One-Two-Three Floor does not reduce HP');
console.log('Pugilist combat integration tests: PASS (real class hooks, subclass mapping, Fisticuffs die, Haymaker, target-bound Signature Move hit/miss, Dig Deep resistance, Fighting Spirit HP shape)');
