const fs=require('fs'),vm=require('vm'),assert=require('assert');
const ctx={console,Math,Date,JSON,Set,Number,String,Array,Object,RegExp,parseInt,parseFloat,
  document:{getElementById:()=>null,querySelectorAll:()=>[]},addEventListener:()=>{},setTimeout:()=>{},clearTimeout:()=>{},window:null};
ctx.window=ctx;ctx.globalThis=ctx;
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(__dirname+'/../app/expansion_classes_pack.js','utf8'),ctx);
ctx.DNDClassFeatures={attackModifiers:function(hero){if(hero&&hero.classFeaturesState&&hero.classFeaturesState.pugilistHaymakerActive)return{disadvantage:true,maximizeDamageDice:true,notes:['Сокрушительный удар'],pendingOnHit:{}};if(hero&&hero.classFeaturesState&&hero.classFeaturesState.pugilistSweetScience)return{criticalRange:19,notes:['Благородное искусство'],pendingOnHit:{}};return{bonusDamage:0,extraDice:[],notes:[],pendingOnHit:{}};},onAttackResult:function(){}};
vm.runInContext(fs.readFileSync(__dirname+'/../app/combat_engine.js','utf8'),ctx);
assert.ok(ctx.DNDCombat,'Combat engine registers');
const oldRandom=Math.random;Math.random=()=>0.5;
const haymakerAttacker={id:'pugilist-attacker',classFeaturesState:{pugilistHaymakerActive:true}};
const haymakerTarget={id:'haymaker-target',hp:20,maxHp:20,ac:1,tempHp:0,resistances:[],immunities:[],vulnerabilities:[],classFeaturesState:{}};
const haymakerResult=ctx.DNDCombat.attack(haymakerAttacker,haymakerTarget,{bonus:0,damage:'1d6',damageType:'рубящий',target:true,useRules:false});
Math.random=oldRandom;
assert.equal(haymakerResult.hit,true,'Haymaker attack hits in the deterministic fixture');
assert.equal(haymakerResult.damage.total,6,'Haymaker maximizes the actual damage die');
assert.equal(haymakerTarget.hp,14,'Maximized Haymaker damage is applied to target HP');
Math.random=()=>0.9;
const boxer={id:'sweet-science-pugilist',classFeaturesState:{pugilistSweetScience:true}};
const boxerTarget={id:'boxer-target',hp:20,maxHp:20,ac:1,tempHp:0,resistances:[],immunities:[],vulnerabilities:[],classFeaturesState:{}};
const criticalResult=ctx.DNDCombat.attack(boxer,boxerTarget,{bonus:0,damage:'1d6',damageType:'дробящий',target:true,useRules:false});
Math.random=oldRandom;
assert.equal(criticalResult.d20,19,'Deterministic d20 is 19');
assert.equal(criticalResult.critical,true,'Sweet Science turns a natural 19 into a critical hit');
assert.equal(criticalResult.damage.total,12,'Critical hit doubles and rolls both d6 damage dice');
assert.equal(boxerTarget.hp,8,'Sweet Science critical damage is applied to HP');
const target={id:'pugilist-defender',hp:20,maxHp:20,tempHp:0,resistances:[],immunities:[],vulnerabilities:[],
  classFeaturesState:{pugilistDigDeepActive:{roundsRemaining:10,damageTypes:['bludgeoning','piercing','slashing']}}};
const resolved=ctx.DNDCombat.effectiveDamage(target,11,'рубящий',{});
assert.equal(resolved.amount,5,'Dig Deep halves slashing damage');
assert.ok(resolved.note.includes('Соберись с силами'),'combat log identifies Dig Deep resistance');
const applied=ctx.DNDCombat.applyDamage(target,10,'дробящий',{});
assert.equal(applied.amount,5,'actual damage application uses Dig Deep resistance');
assert.equal(target.hp,15,'target HP changes by the reduced damage');
assert.equal(ctx.DNDCombat.effectiveDamage(target,11,'огонь',{}).amount,11,'Dig Deep does not resist non-physical damage');
const expired={hp:20,maxHp:20,resistances:[],immunities:[],vulnerabilities:[],classFeaturesState:{pugilistDigDeepActive:{roundsRemaining:0}}};
assert.equal(ctx.DNDCombat.effectiveDamage(expired,11,'рубящий',{}).amount,11,'expired Dig Deep state does not reduce damage');
console.log('Pugilist combat integration tests: PASS (physical resistance, actual HP damage, non-physical damage, expiry)');
