const fs=require('fs'),vm=require('vm'),assert=require('assert');
const registered=[];
const math=Object.create(Math);math.random=()=>0;
const ctx={console,Math:math,Date,JSON,Set,Number,String,Array,Object,RegExp,parseInt,parseFloat,
  DNDContent:{registerClass:p=>registered.push(p)},document:{getElementById:()=>null},addEventListener:()=>{},window:null};
ctx.window=ctx;ctx.globalThis=ctx;
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(__dirname+'/../app/expansion_classes_pack.js','utf8'),ctx);
const pugilist=registered.find(p=>p.id==='sv-pugilist');
assert.ok(pugilist,'Pugilist class registered');
const hooks=pugilist.hooks;
function hero(level,extra={}){return Object.assign({id:'pugilist-test',classes:[{name:'Пугилист',level}],abilities:{str:16,con:14,cha:12},proficiencyBonus:3,hp:30,maxHp:30,tempHp:0,resources:{},classFeaturesState:{}},extra);}
let h=hero(1);
hooks.sync(h);
let r=hooks.useFeature(h,'braceUp',{});
assert.equal(r.ok,false,'level-2 feature rejected at level 1');
assert.equal(h.resources.pugilistMoxie.current,2,'level gate does not spend Moxie');
h=hero(2);hooks.sync(h);
r=hooks.useFeature(h,'braceUp',{});
assert.equal(r.ok,true,'Brace Up succeeds at level 2');
assert.equal(h.tempHp,5,'Brace Up writes temporary HP to character');
const dig=hooks.useFeature(h,'digDeep',{activate:true});
assert.equal(dig.ok,true,'Dig Deep can be activated with confirmation');
assert.equal(h.resources.pugilistDigDeep.current,0,'Dig Deep use is spent');
assert.equal(hooks.useFeature(h,'digDeep',{activate:true}).ok,false,'Dig Deep cannot be reused before rest');
h=hero(5);hooks.sync(h);
assert.equal(hooks.useFeature(h,'haymaker',{}).ok,true,'Haymaker activates at level 5');
const atk=hooks.attackModifiers(h,{});
assert.equal(atk.disadvantage,true,'Haymaker sets attack disadvantage');
assert.equal(atk.maximizeDamageDice,true,'Haymaker exposes maximized damage dice');
h=hero(17);h.classFeaturesState.pugilistFightClub='sweetScience';hooks.sync(h);
const before=h.resources.pugilistMoxie.current;
assert.equal(hooks.useFeature(h,'knockOut',{moxie:2}).ok,false,'Knock Out requires a target');
assert.equal(h.resources.pugilistMoxie.current,before,'Missing target does not spend Moxie');
assert.equal(hooks.attackModifiers(h,{}).criticalRange,19,'Sweet Science critical range is 19–20');
h=hero(17);h.classFeaturesState.pugilistFightClub='sweetScience';hooks.sync(h);const koTarget={id:'ko-target',hp:20,maxHp:20,conditions:{}};assert.equal(hooks.useFeature(h,'knockOut',{target:koTarget,moxie:1}).ok,true,'Knock Out can be prepared');const koMod=hooks.attackModifiers(h,{target:koTarget,unarmedAttack:true});assert.equal(koMod.noDamage,true,'Knock Out replaces attack damage');hooks.onAttackResult(h,{hit:true,target:koTarget,targetId:'ko-target'});assert.equal(koTarget.hp,0,'Knock Out reduces target to 0 HP on a successful check');assert.equal(koTarget.conditions['Бессознателен'],true,'Knock Out applies unconscious condition');
h=hero(6);h.classFeaturesState.pugilistFightClub='sweetScience';hooks.sync(h);const floorTarget={id:'floor-target',hp:30,maxHp:30,conditions:{}};assert.equal(hooks.useFeature(h,'oldOneTwo',{target:floorTarget}).ok,true,'Old One-Two starts tracked sequence');hooks.onAttackResult(h,{hit:true,target:floorTarget,targetId:'floor-target'});hooks.onAttackResult(h,{hit:true,target:floorTarget,targetId:'floor-target'});assert.equal(h.classFeaturesState.pugilistOldOneTwoActive.ready,true,'Both Old One-Two attacks are recorded as hits');assert.equal(hooks.useFeature(h,'oneTwoThreeFloor',{target:floorTarget}).ok,true,'One Two Three Floor requires and consumes two successful Old One-Two hits');const floorMod=hooks.attackModifiers(h,{target:floorTarget,unarmedAttack:true});assert.equal(floorMod.noDamage,undefined,'One Two Three Floor still deals normal unarmed damage');
h=hero(18,{hp:0,maxHp:40});hooks.sync(h);
r=hooks.useFeature(h,'fightingSpirit',{});
assert.equal(r.ok,true,'Fighting Spirit activates at 0 HP');
assert.equal(h.hp,20,'Fighting Spirit restores HP directly');
assert.equal(h.classFeaturesState.pugilistExhaustion,1,'Fighting Spirit applies one exhaustion level');
assert.equal(h.resources.pugilistFightingSpirit.current,0,'Fighting Spirit is expended');
assert.equal(hooks.useFeature(h,'fightingSpirit',{}).ok,false,'Fighting Spirit cannot be reused before long rest');
h=hero(20);h.classFeaturesState.pugilistExhaustion=3;hooks.sync(h);
ctx.pugilistRuntime.rest(h,'long');
assert.equal(h.classFeaturesState.pugilistExhaustion,1,'Peak Physical Condition removes two exhaustion levels on long rest');
console.log('Pugilist runtime regression tests: PASS (registration, level gates, Moxie, temporary HP, Dig Deep limit, Haymaker modifiers, target-before-spend, Sweet Science crit range, Fighting Spirit, level-20 rest recovery)');
