const assert = require('assert');
const {runtime, hero} = require('./helpers/class_runtime_harness');
const g = runtime(), D = g.DNDContent, C = g.DNDClassFeatures;
const bh = D.getClass('Кровавый охотник');
const hunter = hero('Кровавый охотник', 10, 'Орден ликантропов');
const unknown = bh.hooks.useFeature(hunter, 'missingActive', {}, {action:'action'});
assert.strictEqual(unknown.ok, false);
assert.strictEqual(unknown.unsupported, true);
// The live ID is stalkersProwess, not the historical typo stalkerProwess.
assert.strictEqual(C.useFeature(hunter, 'stalkerProwess', {}).ok, false);
const stalker = C.useFeature(hunter, 'stalkersProwess', {});
assert.strictEqual(stalker.ok, true);
assert.strictEqual(stalker.effect.speedBonusFt, 10);
const psion = D.getClass('Psion');
assert.strictEqual(psion, D.getClass('Псионик'));
assert.strictEqual(psion.id, 'kibbles-psion');
const ph = hero('Psion', 5, 'Пробуждённый разум');
const pu = psion.hooks.useFeature(ph, 'missingActive', {}, {action:'action'});
assert.strictEqual(pu.ok, false);
assert.strictEqual(pu.unsupported, true);
const passive = C.useFeature(ph, 'openMind', {});
assert.strictEqual(passive.ok, true);
assert.strictEqual(passive.passive, true);
assert(ph.classFeaturesState.psionDisciplines.includes('telepathy'));
console.log('External feature refusal, live IDs and Psion alias regression: PASS');
