const assert=require('assert');
const {runtime,hero}=require('./helpers/class_runtime_harness');
const g=runtime(),C=g.DNDClassFeatures,D=g.DNDContent,B=g.DNDCombat;
let h=hero('Мученик',10,'Бремя милосердия'),target=hero('Enemy');
assert.equal(D.getClass('Мученик'),D.getClass('Martyr'));
assert.equal(g.getAvailableSubclasses('Мученик').length,14);
assert(g.getAvailableSubclasses('Мученик').every(s=>s.pickLevel===3));
C.buildFeatureSet(h);assert.equal(h.classFeaturesState.martyr.spellSaveDC,14);
assert.equal(h.resources.martyrDivineRespite.max,1);
h.resources.hitDice={current:3,max:10};h.hpCurrent=5;
assert.equal(C.useFeature(h,'miraculousHealing',{dice:2}).healing.amount,6);
assert.equal(h.hpCurrent,11);assert.equal(h.hp.current,11);assert.equal(h.resources.hitDice.current,1);
const before=JSON.stringify(h);assert.equal(C.useFeature(h,'miraculousHealing',{dice:1.5}).ok,false);assert.equal(JSON.stringify(h),before);
assert.equal(C.useFeature(h,'divineRespite',{}).hitDiceRestored,3);assert.equal(h.resources.hitDice.current,4);
assert.equal(C.useFeature(h,'divineRespite',{}).ok,false);C.restore(h,'short');assert.equal(h.resources.martyrDivineRespite.current,0);
h.hpCurrent=30;h.hpTemp=8;h.immunities=['radiant'];h.resistances=['radiant'];h.concentration={active:true,spellName:'Bless'};
const uses=h.resources.martyrSpellUses.current;
let result=g.martyrRuntime.cast(h,1,'Bane');assert.equal(result.reserved,true);assert.equal(h.hpCurrent,25);assert.equal(h.hpTemp,8);assert(h.concentration.active);
assert.equal(h.resources.martyrSpellUses.current,uses-1);C.buildFeatureSet(h);assert.equal(h.classFeaturesState.martyr.spellUses,uses-1);
result=g.martyrRuntime.cast(h,1,'Cure Wounds');assert.equal(result.hpCost,0);assert.equal(h.hpCurrent,25);
const spent=h.resources.martyrSpellUses.current;assert.equal(g.martyrRuntime.cast(h,2.5,'Bane').ok,false);assert.equal(h.resources.martyrSpellUses.current,spent);
h.hpCurrent=5;assert.equal(g.martyrRuntime.cast(h,1,'Bane').ok,false);assert.equal(h.hpCurrent,5);assert.equal(h.resources.martyrSpellUses.current,spent);
h.hpCurrent=30;target=hero('Enemy');target.immunities=['radiant'];target.resistances=['radiant'];
result=C.useFeature(h,'sacrifice',{target});assert.equal(result.ok,true);assert.equal(target.hpCurrent,20);assert.equal(h.hpCurrent,25);
target.hpCurrent=3;result=C.useFeature(h,'sacrifice',{target});assert.equal(result.selfDamage,0);assert.equal(target.hpCurrent,0);assert.equal(h.hpCurrent,25);
target=hero('Enemy');const enemyHP=target.hpCurrent;
assert(C.reactionOptions(h,{source:'attack',attackKind:'weapon',returnTarget:target,amount:9}).options.some(x=>x.id==='reprisal'));
result=B.applyDamage(h,9,'slashing',{source:'attack',attackKind:'weapon',attacker:target,reactionChoice:'reprisal'});
assert.equal(result.amount,5);assert.equal(h.hpTemp,3);assert.equal(h.hpCurrent,25);assert.equal(target.hpCurrent,enemyHP-2);
assert.equal(C.resolveReaction(h,'reprisal',{source:'attack',attackKind:'weapon',returnTarget:target,amount:9}).ok,false);
C.resetTurn(h);assert.equal(C.useFeature(h,'reprisal',{source:'attack',attackKind:'rangedWeapon',returnTarget:target,amount:9}).ok,false);
h.hpCurrent=0;h.hpTemp=0;assert.equal(C.useFeature(h,'undying',{}).hitPointsAfter,1);assert.equal(h.hp.current,1);h.hpCurrent=0;
assert.equal(C.useFeature(h,'undying',{}).ok,false);C.restore(h,'long');assert.equal(h.resources.martyrUndying.current,1);assert.equal(h.resources.martyrSpellUses.current,h.resources.martyrSpellUses.max);
h=hero('Мученик',2);h.level=20;C.buildFeatureSet(h);assert.equal(C.useFeature(h,'sacrifice',{target:hero('Enemy')}).ok,false);assert.equal(C.useFeature(h,'martyr-chooseBurden',{burden:'Бремя истины'}).ok,false);
h=hero('Martyr',3);assert.equal(C.useFeature(h,'martyr-chooseBurden',{burden:'truth'}).ok,true);assert.equal(h.classes[0].subclass,'Бремя истины');
assert.equal(g.martyrRuntime.cast(h,1,'Identify').reserved,true,'Burden class-level keys are resolved to spell-level entries');
for(let level=1;level<=20;level++){
 h=hero('Мученик',level,'Бремя милосердия');assert(C.buildFeatureSet(h).includes('armorOfFaith'));
 g.applyClassProgression(h,'Мученик',level);C.resetTurn(h);C.onTurnEnd(h);C.restore(h,'short');C.restore(h,'long');
 C.buildFeatureSet(JSON.parse(JSON.stringify(h)));assert.equal(C.attackModifiers(h,{}).extraAttacks,level>=5?2:1);
}
assert.equal(D.getClass('Аккурсд'),D.getClass('Accursed'));assert.equal(g.getAvailableSubclasses('Аккурсд').length,5);
h=hero('Accursed',10,'Проклятое оружие');C.buildFeatureSet(h);assert.equal(h.classFeaturesState.accursed.saveDC,14);
assert.equal(C.useFeature(h,'chooseCurseAbility',{ability:'intelligence'}).ok,true);assert.equal(h.classFeaturesState.accursed.saveDC,15);
assert.equal(C.useFeature(h,'chooseMetamorphosis',{names:['Смертоносное проклятие']}).ok,false);
assert.equal(C.useFeature(h,'chooseMetamorphosis',{names:['Враждебное проклятие','Смертоносное проклятие']}).ok,true);
assert.equal(C.useFeature(h,'chooseMetamorphosis',{names:['Теневое проклятие']}).ok,false);
assert.equal(C.useFeature(h,'chooseMetamorphosis',{names:['Враждебное проклятие']}).ok,true);
const slotsBefore=h.resources.accursedSpellSlots.current;
assert.equal(C.spendExtendedResource(h,'accursedSpellSlots',1,{}).ok,false);
assert.equal(C.spendExtendedResource(h,'accursedSpellSlots',1,{spellLevel:1}).ok,true);
C.buildFeatureSet(h);assert.equal(h.resources.accursedSpellSlots.current,slotsBefore-1);assert.equal(h.classFeaturesState.accursed.slotCurrent[0],3);
C.restore(h,'short');assert.equal(h.resources.accursedSpellSlots.current,slotsBefore-1);C.restore(h,'long');assert.equal(h.resources.accursedSpellSlots.current,slotsBefore);
h.id='caster';target=hero('Enemy');target.id='jinx-target';g.Math.random=()=>0;
assert.equal(C.useFeature(h,'jinx',{target,chosenCreatureId:'chosen',distanceFt:100}).ok,false);
assert.equal(C.useFeature(h,'jinx',{target,chosenCreatureId:'chosen'}).applied,true);
assert.equal(C.useFeature(h,'jinx',{target,jinx:'abilityCheck'}).unsupported,true);
let rolls=[0.8,0.1];g.Math.random=()=>rolls.shift()??0;let chosen=hero('Enemy');chosen.id='chosen';
result=B.attack(target,chosen,{bonus:0});assert.equal(result.d20,3,'next attack against the selected creature uses disadvantage');assert(!target.classFeaturesState.accursedJinx);
g.Math.random=()=>0.5;target=hero('Enemy');target.id='other';
result=B.attack(h,target,{bonus:15,damage:'1d6+2',damageType:'piercing',weaponAttack:true});
assert.equal(result.damage.total,9);assert.equal(target.hpCurrent,21);assert(h.classFeaturesState.accursed.hostileUsed);
result=B.attack(h,target,{bonus:15,damage:'1d6+2',damageType:'piercing',weaponAttack:true});assert.equal(result.damage.total,6);
C.resetTurn(h);assert.equal(C.attackModifiers(h,{weaponAttack:true}).typedExtraDice.length,1);
for(let level=1;level<=20;level++){
 h=hero('Аккурсд',level,'Проклятое оружие');assert(C.buildFeatureSet(h).includes('jinx'));g.applyClassProgression(h,'Аккурсд',level);
 C.resetTurn(h);C.onTurnEnd(h);C.restore(h,'short');C.restore(h,'long');C.buildFeatureSet(JSON.parse(JSON.stringify(h)));
 assert.equal(C.attackModifiers(h,{}).extraAttacks,level>=5?2:1);
}
h=hero('Аккурсд',1);h.level=20;assert.equal(C.useFeature(h,'chooseMetamorphosis',{names:['Враждебное проклятие']}).ok,false);
assert.equal(C.useFeature(h,'chooseCurse',{curse:'Ликантропия'}).ok,true);assert.equal(h.classes[0].subclass,'Ликантропия');
assert.equal(C.useFeature(h,'chooseCurse',{curse:'Вампиризм'}).ok,false);
assert.equal(D.getClass('Рунный хранитель'),D.getClass('RuneKeeper'));assert.equal(D.getClass('Runekeeper'),D.getClass('RuneKeeper'));
assert.equal(g.getAvailableSubclasses('Рунный хранитель').length,6);
h=hero('Рунный хранитель',2,'Диалект Детек');h.languages=['Детек'];C.buildFeatureSet(h);
assert.equal(h.classFeaturesState.runekeeper.dialect,'Детек');assert.equal(h.classFeaturesState.runekeeper.runicDC,13);assert.equal(h.resources.runicCharges.max,0);
assert.equal(C.useFeature(h,'runicLore',{names:['Arausamman','Astim','Dur','Findar']}).ok,true);
assert.equal(C.useFeature(h,'inscribeRune',{rune:'Unknown',objectId:'obj1'}).ok,false);
assert.equal(C.useFeature(h,'inscribeRune',{rune:'Arausamman'}).ok,false);
assert.equal(C.useFeature(h,'inscribeRune',{rune:'Arausamman',objectId:'obj1'}).ok,true);
assert.equal(C.useFeature(h,'inscribeRune',{rune:'Astim',objectId:'obj2'}).ok,true);
assert.equal(C.useFeature(h,'inscribeRune',{rune:'Dur',objectId:'obj3'}).ok,false);
assert.equal(C.useFeature(h,'inscribeRune',{rune:'Dur',objectId:'obj1'}).ok,false);
assert.equal(C.useFeature(h,'invokeRune',{objectId:'obj1'}).reserved,true);assert.equal(C.useFeature(h,'invokeRune',{objectId:'obj1'}).ok,false);
assert.equal(C.useFeature(h,'causalInvocation',{objectId:'obj1'}).ok,false);
h.classes[0].level=9;C.buildFeatureSet(h);assert.equal(h.resources.runicCharges.max,4);C.restore(h,'long');C.useFeature(h,'invokeRune',{objectId:'obj1'});
assert.equal(C.useFeature(h,'causalInvocation',{objectId:'unknown'}).ok,false);assert.equal(h.resources.runicCharges.current,4);
assert.equal(C.spendExtendedResource(h,'runicCharges',1,{objectId:'obj1'}).ok,true);assert.equal(h.resources.runicCharges.current,3);
const runesBefore=JSON.stringify(h.classFeaturesState.runekeeper.runes);
assert.equal(C.useFeature(h,'runeChant',{objectIds:['obj1','missing']}).ok,false);assert.equal(JSON.stringify(h.classFeaturesState.runekeeper.runes),runesBefore);
assert.equal(C.useFeature(h,'runeChant',{objectIds:['obj1','obj1']}).ok,false);
assert.equal(C.useFeature(h,'runeChant',{objectIds:['obj1','obj2']}).reserved,true);
C.restore(h,'short');assert.equal(h.resources.runicCharges.current,3);assert.equal(h.classFeaturesState.runekeeper.runes.obj1.active,false);
C.restore(h,'long');assert.equal(h.resources.runicCharges.current,4);assert.equal(h.classFeaturesState.runekeeper.runes.obj1.active,true);
assert.equal(C.useFeature(h,'runeStance',{stance:'разрушение'}).ok,true);g.Math.random=()=>0.5;target=hero('Enemy');target.id='rune-foe';
assert.equal(B.attack(h,target,{bonus:15,damage:'1d6+2',damageType:'piercing'}).damage.total,7);
assert.equal(B.attack(h,target,{bonus:15,damage:'1d6+2',damageType:'piercing'}).damage.total,6);
C.resetTurn(h);assert.equal(B.attack(h,target,{bonus:15,damage:'1d6+2',damageType:'piercing'}).damage.total,7);
C.useFeature(h,'runeStance',{stance:'защита'});h.resistances=['slashing'];h.initiativeTracker={round:1,activeIndex:0,combatants:[{},{}]};g.currentChar=h;
assert.equal(B.applyDamage(h,8,'slashing').amount,3,'rune reduction follows resistance');assert.equal(B.applyDamage(h,8,'slashing').amount,4);
h.initiativeTracker.activeIndex=1;assert.equal(B.applyDamage(h,8,'slashing').amount,3);
h=JSON.parse(JSON.stringify(h));g.currentChar=h;assert.equal(B.applyDamage(h,8,'slashing').amount,4,'same turn after JSON does not repeat reduction');
h.initiativeTracker.round=2;assert.equal(B.applyDamage(h,8,'slashing').amount,3);
for(let level=1;level<=20;level++){
 h=hero('Рунный хранитель',level,'Диалект Детек');assert(C.buildFeatureSet(h).includes('inscribeRune'));g.applyClassProgression(h,'Рунный хранитель',level);
 C.resetTurn(h);C.onTurnEnd(h);C.restore(h,'short');C.restore(h,'long');C.buildFeatureSet(JSON.parse(JSON.stringify(h)));
 assert.equal(h.resources.runicCharges.max,level>=5?Math.floor(level/2):0);
}
assert.equal(D.getClass('Савант'),D.getClass('Savant'));assert.equal(g.getAvailableSubclasses('Савант').length,6);
h=hero('Savant',11,'Наставник');h.id='savant';h.initiativeTracker={round:1,activeIndex:0,combatants:[{},{}]};g.currentChar=h;C.buildFeatureSet(h);
assert.equal(h.classFeaturesState.savant.saveDC,15);assert.equal(h.ac,15);assert.equal(h.resources.savantReactions.current,3);assert.equal(h.resources.savantReactions.recharge,'round');
target=hero('Enemy');target.id='focus';
assert.equal(C.useFeature(h,'adroitAnalysis',{target,distanceFt:61}).ok,false);
assert.equal(C.useFeature(h,'adroitAnalysis',{target,distanceFt:60}).ok,true);assert.equal(h.concentration.spellId,'savant-focus');
rolls=[0.8,0.1];g.Math.random=()=>rolls.shift()??0;
assert.equal(B.attack(target,h,{bonus:0}).d20,3,'Focus attacks against Savant have disadvantage');
g.Math.random=()=>0.5;
result=C.useFeature(h,'savant-studiedStrike',{target,damageDice:'1d6'});assert.equal(result.attack.bonus,7);assert.equal(result.attack.damage.total,12);assert.equal(target.hpCurrent,18);
assert.equal(C.useFeature(h,'savant-studiedStrike',{target,damageDice:'1d6'}).attack.damage.total,7);
C.resetTurn(h);assert.equal(C.attackModifiers(h,{weaponAttack:true,target}).extraDice[0],'1d8');
let supportedSave={total:10,dc:14,success:false};
assert.equal(C.useFeature(h,'potentObservation',{kind:'save',saveResult:supportedSave,eligible:true,triggerId:'save1'}).bonus,5);
assert.equal(supportedSave.total,15);assert.equal(supportedSave.success,true);assert.equal(h.resources.savantReactions.current,2);
assert.equal(C.useFeature(h,'potentObservation',{kind:'save',saveResult:supportedSave,eligible:true,triggerId:'save1'}).ok,false);assert.equal(h.resources.savantReactions.current,2);
assert.equal(C.spendExtendedResource(h,'savantReactions',1,{}).ok,true);C.buildFeatureSet(h);assert.equal(h.resources.savantReactions.current,1);
C.restore(h,'short');assert.equal(h.resources.savantReactions.current,1);assert.equal(h.classFeaturesState.savant.focuses.length,0);
h.initiativeTracker.round=2;C.resetTurn(h);assert.equal(h.resources.savantReactions.current,3);
C.spendExtendedResource(h,'savantReactions',1,{});C.resetTurn(h);assert.equal(h.resources.savantReactions.current,2,'another actor/duplicate start in same round does not refill reactions');
target=hero('Enemy');target.id='attacker';const savantHP=h.hpCurrent;
result=B.attack(target,h,{bonus:5,damage:'1d6+2',damageType:'piercing',defenderReaction:'calculatedFlourish',triggerId:'incoming1'});
assert.equal(result.savantFlourish.acBonus,5);assert.equal(result.ac,20);assert.equal(result.hit,false);assert.equal(h.hpCurrent,savantHP);assert.equal(h.resources.savantReactions.current,1);
assert.equal(C.useFeature(h,'calculatedFlourish',{}).ok,false);assert.equal(h.resources.savantReactions.current,1);
h.stats.intelligence=18;C.buildFeatureSet(h);assert.equal(h.ac,16);h.shieldEquipped=true;C.buildFeatureSet(h);assert.equal(h.ac,10);delete h.shieldEquipped;C.buildFeatureSet(h);assert.equal(h.ac,16);
C.useFeature(h,'adroitAnalysis',{target});h=JSON.parse(JSON.stringify(h));g.currentChar=h;C.buildFeatureSet(h);assert(h.classFeaturesState.savant.focuses.includes('attacker'));
B.toggleCondition(h,'Оглушён',true);assert.equal(h.classFeaturesState.savant.focuses.length,0);assert.equal(h.concentration.active,false);B.toggleCondition(h,'Оглушён',false);
C.useFeature(h,'adroitAnalysis',{target});h.classFeaturesState.savant.focusExpiresAt=Date.now()-1;C.buildFeatureSet(h);assert.equal(h.classFeaturesState.savant.focuses.length,0);
C.restore(h,'long');assert.equal(h.resources.savantReactions.current,3);
for(let level=1;level<=20;level++){
 h=hero('Савант',level,'Тактик');g.currentChar=h;assert(C.buildFeatureSet(h).includes('adroitAnalysis'));g.applyClassProgression(h,'Савант',level);
 C.resetTurn(h);C.onTurnEnd(h);C.restore(h,'short');C.restore(h,'long');C.buildFeatureSet(JSON.parse(JSON.stringify(h)));
 assert.equal(h.resources.savantReactions.max,level>=17?4:level>=11?3:level>=5?2:1);
 assert.equal(C.attackModifiers(h,{}).extraAttacks,level>=7?2:1);
}
h=hero('Савант',2);h.level=20;assert.equal(C.useFeature(h,'calculatedFlourish',{}).ok,false);assert.equal(C.useFeature(h,'savant-chooseDiscipline',{discipline:'physician'}).ok,false);
h=hero('Savant',3);assert.equal(C.useFeature(h,'savant-chooseDiscipline',{discipline:'physician'}).ok,true);assert.equal(h.classes[0].subclass,'Врач');
D.setEnabled('ll-savant',false);assert.equal(C.useFeature(h,'adroitAnalysis',{target}).ok,false);assert.equal(g.savantRuntime.incomingAttackModifiers(h,{attacker:target}).disadvantage,false);D.setEnabled('ll-savant',true);
console.log('Class audit stage 3: four classes, real HP/roll/combat effects, canonical resources, guards and lifecycle PASS');
