const fs=require('fs'),vm=require('vm');
const ctx={console,setTimeout,setInterval,clearTimeout,clearInterval,Date,Math,JSON};
ctx.window=ctx;ctx.global=ctx;
if(!ctx.document)ctx.document={readyState:'complete',getElementById:function(){return null;},addEventListener:function(){},createElement:function(){return {style:{},appendChild:function(){}};},body:{appendChild:function(){}}};
if(!ctx.localStorage){var __ls={};ctx.localStorage={getItem:function(k){return __ls[k]||null;},setItem:function(k,v){__ls[k]=v;}};}
if(!ctx.DNDCombatEventBusV69)ctx.DNDCombatEventBusV69={record:function(){}};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync('vtt_debug_lab_v703.js','utf8'),ctx,{filename:'vtt_debug_lab_v703.js'});
const __TEST_SRC__="(function(global){'use strict';\n  var assert=global.__TEST_ASSERT__||function(c,m){if(!c)throw new Error(m);};\n  var old=global.currentCharacter;\n  global.currentCharacter={id:'qa703',name:'Lab Hero',hpCurrent:30,hpMax:30,ac:18,speed:'30',initiative:5,inventory:[]};\n  global.currentChar=global.currentCharacter;\n  global.autoSaveCurrentCharacter=function(){};\n  global.updateCharacterUI=function(){};\n  global.renderCharacterSheet=function(){};\n  global.renderConditions=function(){};\n  global.renderSpellSlots=function(){};\n  global.renderCombatAbilities=function(){};\n  global.DNDCombatEventBusV69={record:function(){}};\n  var api=global.DNDDebugLabV703;assert(api&&api.version==='70.3.0','V70.3 API missing');\n  global.document={getElementById:function(id){\n    var vals={v703CombatAmount:'10',v703DiceMode:'nat20',v703DiceValue:'20',v703Latency:'250',v703Loss:'10'};\n    return {value:vals[id]||'',checked:id==='v703Offline'?false:id==='v703Duplicate'?true:id==='v703OutOfOrder'?true:false};\n  },createElement:function(){return {style:{},appendChild:function(){}};},body:{appendChild:function(){}},readyState:'complete'};\n  api.backup();\n  api.combat('damage');assert(global.currentCharacter.hpCurrent===20,'damage failed');\n  api.combat('heal');assert(global.currentCharacter.hpCurrent===30,'heal failed');\n  api.forceDice();assert(api.getState().forcedDice.value===20,'dice failed');\n  api.network();assert(api.getState().network.latency===250 && api.getState().network.loss===10,'network failed');\n  api.chaos();assert(global.currentCharacter.hpCurrent===0 && api.getState().network.loss===25,'chaos failed');\n  api.rollback();assert(global.currentCharacter.hpCurrent===30,'rollback failed');\n  global.currentCharacter=old;global.currentChar=old;global.__TEST_RESULT__='V70_3_QA_LABS_TEST_OK';\n})(window);\n";
vm.runInContext(__TEST_SRC__,ctx,{filename:'test_v703.js'});
