const assert=require('assert');
const {runtime,hero}=require('./helpers/class_runtime_harness');
const g=runtime(),D=g.DNDContent,C=g.DNDClassFeatures,B=g.DNDCombat,R=g.WARDEN_MHP_2024;
assert.equal(D.getClass('Страж'),D.getClass('Warden'));
assert.equal(g.getAvailableSubclasses('Warden').length,13);
assert(g.getAvailableSubclasses('Страж').every(x=>x.pickLevel===3));
assert.equal(g.DND_CLASSES_LIST.filter(x=>x.name==='Warden').length,0);
assert.equal(g.CLASSES_REFERENCE.Warden.savingThrows[1],'constitution');
let h=hero('Страж',13,'Диаболист');C.buildFeatureSet(h);
h.conditions={stunned:true,'Испуган':true};h.activeConditions={'Оглушён':true};
assert.equal(C.useFeature(h,'warden-fontOfLife',{condition:'stunned'}).ok,false);
assert.equal(h.resources.wardenFontOfLife.current,2);
assert.equal(C.useFeature(h,'warden-fontOfLife',{condition:'stunned',atStartOfTurn:true}).ok,true);
assert(!h.conditions.stunned);assert(!h.activeConditions['Оглушён']);assert(h.conditions['Испуган']);
assert.equal(h.resources.wardenFontOfLife.current,1);
assert.equal(C.useFeature(h,'warden-fontOfLife',{condition:'stunned',atStartOfTurn:true}).ok,false);
assert.equal(h.resources.wardenFontOfLife.current,1);
h.hpCurrent=0;h.hitPoints=0;h.conditions['Бессознателен']=true;h.activeConditions['Бессознателен']=true;h.deathSaves={successes:1,failures:2};
assert.equal(C.useFeature(h,'warden-survive',{}).hitPointsAfter,27);
assert.equal(h.hp.current,27);assert.equal(h.hitPoints,27);assert.equal(h.deathSaves.failures,0);assert(!h.activeConditions['Бессознателен']);
h.hpCurrent=0;assert.equal(C.useFeature(h,'warden-survive',{}).ok,false);C.restore(h,'short');assert.equal(h.resources.wardenSurvive.current,0);
C.restore(h,'long');assert.equal(h.resources.wardenSurvive.current,1);assert.equal(h.classFeaturesState.wardenSurviveReady,true);
assert.equal(C.useFeature(h,'warden-survive',{instantDeath:true}).ok,false);assert.equal(h.resources.wardenSurvive.current,1);
h=hero('Warden',9);h.hpCurrent=3;h.hpTemp=0;
let result=B.applyDamage(h,5,'force',{zeroHpReaction:'warden-survive'});
assert.equal(result.wardenSurvive.ok,true);assert.equal(result.hp,19);assert.equal(h.defeated,false);
h=hero('Страж',9);h.hpCurrent=3;h.hpMax=10;
assert.equal(B.applyDamage(h,20,'force',{zeroHpReaction:'warden-survive'}).wardenSurvive.ok,false);assert.equal(h.resources.wardenSurvive.current,1);
h=hero('Страж',1);h.level=20;
assert.equal(R.useFeature(h,'sentinelSoul',{choice:'fortified'}).ok,false);
assert.equal(C.useFeature(h,'warden-stoneheartDefender-10',{}).ok,false);
assert.equal(R.useFeature(h,'survive',{}).ok,false);
assert.equal(R.useFeature(hero('Enemy'),'fontOfLife',{}).ok,false);
h=hero('Страж',3);assert.equal(C.useFeature(h,'warden-chooseCall',{call:'rimekeeper'}).ok,true);assert.equal(h.classes[0].subclass,'Хранитель изморози');
assert.equal(C.useFeature(h,'warden-chooseCall',{call:'diabolist'}).ok,false);
assert.equal(B.effectiveDamage(h,9,'cold').amount,4);h.hpCurrent=20;
assert.equal(B.effectiveDamage(h,9,'slashing').amount,4);h.hpCurrent=21;assert.equal(B.effectiveDamage(h,9,'slashing').amount,9);
h=hero('Страж',15);h.hpCurrent=20;h.resistances=['fire'];assert.equal(B.effectiveDamage(h,9,'fire').amount,4);
assert.equal(B.effectiveDamage(h,9,'psychic').amount,9);assert.equal(B.effectiveDamage(h,9,'fire',{ignoreResistance:true}).amount,9);
h=hero('Страж',18);C.useFeature(h,'warden-sentinelSoul',{choice:'fortified'});h.turnResources.reaction=0;
let target=h,attacker=hero('Enemy');let rolls=[0.1,0.8];g.Math.random=()=>rolls.shift()??0;
assert.equal(B.attack(attacker,target,{mode:'advantage',bonus:0}).d20,3,'fortified removes advantage even after a reaction');
B.toggleCondition(h,'Оглушён',true);rolls=[0.1,0.8];assert.equal(B.attack(attacker,target,{mode:'advantage',bonus:0}).d20,17);B.toggleCondition(h,'Оглушён',false);
h=hero('Страж',10,'Каменносердечный защитник');h.resistances=['slashing'];C.buildFeatureSet(h);g.Math.random=()=>0;
result=B.applyDamage(h,12,'slashing',{defenderReaction:'warden-stoneShield'});
assert.equal(result.amount,3);assert.equal(h.hpCurrent,27);assert.equal(h.turnResources.reaction,0);assert.equal(h.resources.wardenStoneShield.current,0);
assert.equal(B.applyDamage(h,12,'slashing',{defenderReaction:'warden-stoneShield'}).amount,6);
C.restore(h,'short');C.resetTurn(h);h.immunities=['slashing'];B.applyDamage(h,12,'slashing',{defenderReaction:'warden-stoneShield'});assert.equal(h.resources.wardenStoneShield.current,1);
h=hero('Страж',6,'Охотник на ведьм');C.buildFeatureSet(h);
B.applyDamage(h,10,'force',{source:'attack',defenderReaction:'warden-breakSpell'});assert.equal(h.resources.wardenBreakSpell.current,1);
assert.equal(B.applyDamage(h,10,'force',{source:'spell',defenderReaction:'warden-breakSpell'}).amount,6);
h=hero('Страж',5);C.buildFeatureSet(h);attacker=hero('Enemy');
result=B.attack(attacker,h,{bonus:50,damage:'1d6',defenderReaction:'wardenInterrupt',distanceFt:5,multiAttackAction:true});
assert.equal(result.interrupted,true);assert.equal(h.hpCurrent,30);assert.equal(h.resources.wardenInterrupt.current,2);assert.equal(h.turnResources.reaction,0);
C.resetTurn(h);assert.equal(B.attack(attacker,h,{bonus:50,defenderReaction:'wardenInterrupt',distanceFt:5,multiAttackAction:false}).interrupted,undefined);assert.equal(h.resources.wardenInterrupt.current,2);
h=hero('Страж',20);g.Math.random=()=>0;
result=B.savingThrow(h,'wis',99,'normal',{defenderReaction:'wardenLegendaryResistance'});assert.equal(result.success,true);assert.equal(h.resources.wardenLegendaryResistance.current,2);
assert.equal(C.useFeature(h,'warden-legendaryResistance',{saveResult:result}).ok,false);
g.Math.random=()=>0.5;h=hero('Страж',7);assert.equal(B.savingThrow(h,'con',10,'normal',{halfDamageEffect:true}).mettle,true);assert.equal(B.savingThrow(h,'dex',10,'normal',{halfDamageEffect:true}).mettle,false);
h=hero('Страж',3,'Диаболист');target=hero('Enemy');target.id='marked';
assert.equal(C.useFeature(h,'warden-diabolist-3',{target,distanceFt:31}).ok,false);
assert.equal(C.useFeature(h,'warden-diabolist-3',{target,distanceFt:30}).ok,true);
assert.equal(B.attack(h,target,{bonus:15,damage:'1d6',damageType:'slashing',weaponAttack:true}).damage.typedExtraDice[0].type,'fire');
assert.equal(B.attack(h,target,{bonus:15,damage:'1d6',weaponAttack:true}).damage.typedExtraDice,undefined);
C.resetTurn(h);assert.equal(C.attackModifiers(h,{target,weaponAttack:true}).typedExtraDice.length,1);
h=JSON.parse(JSON.stringify(h));C.buildFeatureSet(h);h.classFeaturesState.wardenMarkedExpiresAt=Date.now()-1;assert.equal(C.attackModifiers(h,{target,weaponAttack:true}).typedExtraDice.length,0);
h=hero('Страж',3,'Хранитель изморози');h.classFeaturesState.wardenMarkedTargetId=target.id;h.classFeaturesState.wardenMarkedExpiresAt=Date.now()+60000;
assert.equal(C.attackModifiers(h,{target,weaponAttack:true}).typedExtraDice.length,0,'old other-Call state cannot grant its effects');
assert.equal(C.useFeature(h,'warden-rimekeeper-17',{}).ok,false);
for(const call of R.subclasses){h=hero('Страж',20,call.name);const ids=C.buildFeatureSet(h);assert(ids.includes('warden-'+call.id+'-17'));assert.equal(R.useFeature(h,'guardianBlock',{target}).ok,false,'unimplemented descriptor is not success');}
for(let level=1;level<=20;level++){
 h=hero(level%2?'Warden':'Страж',level,'Серый страж');C.buildFeatureSet(h);g.applyClassProgression(h,h.classes[0].name,level);
 C.resetTurn(h);C.onTurnEnd(h);C.restore(h,'short');C.restore(h,'long');C.buildFeatureSet(JSON.parse(JSON.stringify(h)));
 assert.equal(C.attackModifiers(h,{}).extraAttacks,level>=5?2:1);assert.equal(h.resources.wardenSurvive.max,level>=9?1:0);
 assert.equal(h.classFeaturesState.wardenWeaponMasteries.length,0,'no sparse fake mastery entries');
}
h=hero('Страж',9);h.classFeaturesState.wardenSurviveReady=false;C.buildFeatureSet(h);assert.equal(h.resources.wardenSurvive.current,0);
console.log('PASS class audit stage4: Warden integration, actual HP/conditions/defense, levels, aliases, rest and JSON');
const W=g.WARLORD_LASERLLAMA_V330;
assert.equal(D.getClass('Военачальник'),D.getClass('Warlord'));assert.equal(g.getAvailableSubclasses('Warlord').length,12);
assert(g.getAvailableSubclasses('Военачальник').every(x=>x.pickLevel===3));assert.equal(g.CLASSES_REFERENCE.Warlord.hitDie,8);
assert.equal(g.DND_CLASSES_LIST.filter(x=>x.name==='Warlord').length,0);
h=hero('Военачальник',5);C.buildFeatureSet(h);assert.equal(h.resources.warlordExploitDice.max,3);assert.equal(h.resources.warlordExploitDice.die,'d6');assert.equal(h.resources.warlordRally.max,0);
assert.equal(C.useFeature(h,'leadershipStyle',{style:'strategist'}).ok,true);assert.equal(h.classFeaturesState.warlordSaveDC,14);
h.stats.intelligence=18;C.buildFeatureSet(h);assert.equal(h.classFeaturesState.warlordSaveDC,15);
target=hero('Воин',3);target.id='ally';target.hpCurrent=5;g.Math.random=()=>0;
const iw=h.resources.warlordInspiringWord.current;
assert.equal(C.useFeature(h,'inspiringWord',{target,distanceFt:31}).ok,false);assert.equal(h.resources.warlordInspiringWord.current,iw);
assert.equal(C.useFeature(h,'inspiringWord',{target,distanceFt:30,hitDie:'d12'}).ok,false);assert.equal(h.resources.warlordInspiringWord.current,iw);
result=C.useFeature(h,'inspiringWord',{target,distanceFt:30});assert.equal(result.healing.amount,5);assert.equal(target.hpCurrent,10);assert.equal(target.hp.current,10);assert.equal(h.turnResources.bonusAction,0);
assert.equal(C.useFeature(h,'inspiringWord',{target,distanceFt:30}).ok,false);assert.equal(h.resources.warlordInspiringWord.current,iw-1);
assert.equal(C.useFeature(h,'warlord-chooseExploits',{names:['parry','parry']}).ok,false);
assert.equal(C.useFeature(h,'warlord-chooseExploits',{names:['parry','heroicWill','attackOrder','finalStrike']}).ok,false);
assert.equal(C.useFeature(h,'warlord-chooseExploits',{names:['parry','heroicWill','attackOrder']}).ok,true);
C.resetTurn(h);let check={total:8};result=C.useFeature(h,'tacticalSkill',{checkResult:check,proficient:true,triggerId:'check1'});assert.equal(check.total,9);assert.equal(h.resources.warlordExploitDice.current,2);
assert.equal(C.useFeature(h,'tacticalSkill',{checkResult:check,proficient:true,triggerId:'check1'}).ok,false);assert.equal(h.resources.warlordExploitDice.current,2);
let save={total:9,dc:10,stat:'wis',success:false};assert.equal(C.useFeature(h,'heroicWill',{saveResult:save,triggerId:'wis1'}).ok,true);assert(save.success);assert.equal(h.turnResources.reaction,0);
C.restore(h,'short');C.resetTurn(h);g.Math.random=()=>0.5;h.ac=15;
attacker=hero('Enemy');result=B.attack(attacker,h,{bonus:5,damage:'1d6+2',defenderReaction:'warlordParry',triggerId:'parry1'});
assert.equal(result.warlordParry.acBonus,4);assert.equal(result.hit,false);assert.equal(h.hpCurrent,30);assert.equal(h.turnResources.reaction,0);assert.equal(h.resources.warlordExploitDice.current,2);
assert.equal(C.useFeature(h,'parry',{pendingAttack:true,attackResult:{total:16,ac:15,hit:true},triggerId:'parry2'}).ok,false);
C.resetTurn(h);target=hero('Воин',3);target.id='order-ally';attacker=hero('Enemy');attacker.id='order-foe';
const weapon={name:'Sword',damageDice:'1d6+3',damageType:'slashing',rangeFt:5,stat:'str'};
const orderCtx={target,enemy:attacker,weapon,distanceFt:30,enemyDistanceFt:5,inAttackAction:true,attackReplaced:true,triggerId:'order1'};
assert.equal(C.useFeature(h,'attackOrder',{...orderCtx,enemyDistanceFt:10}).ok,false);assert.equal(h.resources.warlordExploitDice.current,2);
result=C.useFeature(h,'attackOrder',orderCtx);assert.equal(result.attack.hit,true);assert.equal(attacker.hpCurrent,23);assert.equal(target.turnResources.reaction,0);assert.equal(h.resources.warlordExploitDice.current,1);
assert.equal(C.useFeature(h,'maneuveringOrder',{target,distanceFt:30}).ok,false);assert.equal(h.resources.warlordExploitDice.current,1,'unknown/nonexecuted order cannot consume a die');
h=hero('Военачальник',9);target=hero('Воин',3);target.id='save-ally';g.Math.random=()=>0.5;save={stat:'wis',total:5,dc:15,success:false};
result=C.useFeature(h,'rallyingCry',{target,distanceFt:30,saveResult:save});assert.equal(result.ok,true);assert.equal(save.total,16);assert.equal(save.success,true);assert.equal(h.resources.warlordRally.current,0);assert.equal(h.turnResources.reaction,0);
C.resetTurn(h);assert.equal(C.useFeature(h,'rallyingCry',{target,distanceFt:30,saveResult:{stat:'wis',total:5,dc:15,success:false}}).ok,false);
h=hero('Warlord',20);C.buildFeatureSet(h);target.hpCurrent=1;assert.equal(C.useFeature(h,'inspiringWord',{target,distanceFt:60}).healing.amount,13);
h.resources.warlordRally.current=0;save={stat:'wis',total:5,dc:15,success:false};assert.equal(C.useFeature(h,'rallyingCry',{target,distanceFt:60,saveResult:save}).ok,true);assert.equal(h.resources.warlordRally.current,0);
h=hero('Военачальник',11);C.buildFeatureSet(h);h.resources.warlordInspiringWord.current=0;h.resources.warlordRally.current=0;
assert.equal(W.initiative(h,{initiativeRoll:true,encounterId:'combat1'}).ok,true);assert.equal(h.resources.warlordInspiringWord.current,1);assert.equal(h.resources.warlordRally.current,1);
assert.equal(W.initiative(h,{initiativeRoll:true,encounterId:'combat1'}).ok,false);C.resetTurn(h);assert.equal(h.resources.warlordInspiringWord.current,1);
h=JSON.parse(JSON.stringify(h));C.buildFeatureSet(h);assert.equal(h.resources.warlordInspiringWord.current,1);assert.equal(W.initiative(h,{initiativeRoll:true,encounterId:'combat1'}).ok,false);
for(const academy of W.academies){h=hero('Военачальник',20,academy.name);const ids=C.buildFeatureSet(h);for(const f of D.getClass('Военачальник').subclasses.find(x=>x.id===academy.id).features)assert(ids.includes(f.id));assert.equal(C.useFeature(h,'monstrousMinion',{}).ok,false,'no fictitious summoned minion');}
h=hero('Военачальник',2);h.level=20;assert.equal(W.useFeature(h,'rallyingCry',{target,distanceFt:30,saveResult:save}).ok,false);assert.equal(C.useFeature(h,'warlord-chooseAcademy',{academy:'tactics'}).ok,false);
h=hero('Warlord',3);assert.equal(C.useFeature(h,'warlord-chooseAcademy',{academy:'tactics'}).ok,true);assert.equal(h.classes[0].subclass,'Тактика');assert.equal(h.resources.warlordExploitDice.max,3);assert.equal(h.classFeaturesState.warlordExploitKnown,4);
assert.equal(C.useFeature(h,'warlord-chooseAcademy',{academy:'dread'}).ok,false);
for(let level=1;level<=20;level++){
 h=hero(level%2?'Warlord':'Военачальник',level,'Рыцарство');C.buildFeatureSet(h);g.applyClassProgression(h,h.classes[0].name,level);C.resetTurn(h);C.onTurnEnd(h);C.restore(h,'short');C.restore(h,'long');C.buildFeatureSet(JSON.parse(JSON.stringify(h)));
 assert.equal(h.resources.warlordExploitDice.max,[0,0,2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,5,5,5,5,5][level]);
 assert.equal(C.attackModifiers(h,{}).extraAttacks,level>=5?2:1);
}
console.log('PASS class audit stage4: Warlord aliases, 12 academies, real healing/rolls/parry/ally attacks, resources and guards');
const S=g.SPELLBLADE_RUNTIME;
assert.equal(D.getClass('Заклинатель клинка'),D.getClass('Spellblade'));
assert.equal(g.getAvailableSubclasses('Заклинатель клинка').length,6);assert(g.getAvailableSubclasses('Spellblade').every(x=>x.pickLevel===3));
h=hero('Spellblade',5,'Aether Blade');C.buildFeatureSet(h);assert.equal(h.classes[0].subclass,'Эфирный клинок');assert.equal(h.classFeaturesState.spellblade.legacyTechnique,'Aether Blade');
assert.equal(g.DNDRules.spellSlotTable(h).casterLevel,3);assert.equal(h.spellSlotsData[1].max,4);assert.equal(h.spellSlotsData[2].max,2);
assert.equal(g.DNDMagic.getSpellInfo(h,{castingClass:'Spellblade'}).dc,14);assert.equal(h.classFeaturesState.spellblade.saveDC,14);
h.classes.push({name:'Волшебник',level:1});assert.equal(g.DNDRules.spellSlotTable(h).casterLevel,3,'half contribution is rounded down for multiclass Spellblade');h.classes.pop();
const knownSpell={name:'Audit Flame',level:1,castingClass:'Spellblade',castingStat:'int',castingTime:'1 действие',damage:'3d6',damageType:'fire',attackType:'spell'};
h.spellsData=[knownSpell,{...knownSpell,name:'Other class',castingClass:'Волшебник'}];
assert.equal(C.useFeature(h,'spellstrike',{spellName:'Other class'}).ok,false);assert.equal(h.spellSlotsData[1].used,0);
assert.equal(C.useFeature(h,'spellstrike',{spellName:'Audit Flame',slotLevel:2}).ok,false);assert.equal(h.resources.arcaneSurges.current,3);
assert.equal(C.useFeature(h,'spellstrike',{spellName:'Audit Flame'}).reserved,true);assert.equal(h.spellSlotsData[1].used,1);assert.equal(h.resources.arcaneSurges.current,2);assert.equal(h.turnResources.bonusAction,0);
assert.equal(C.useFeature(h,'spellstrike',{spellName:'Audit Flame'}).ok,false);assert.equal(h.spellSlotsData[1].used,1);
h=JSON.parse(JSON.stringify(h));C.buildFeatureSet(h);assert.equal(h.spellSlotsData[1].used,1);assert.equal(h.classFeaturesState.spellblade.prepared.spellName,'Audit Flame');
target=hero('Enemy');target.resistances=['fire'];g.Math.random=()=>0.5;
result=B.attack(h,target,{weapon:{name:'Sword',damageDice:'1d6+3',damageType:'slashing',rangeFt:5},damageType:'slashing',distanceFt:5});
assert.equal(result.spellstrike.executed,true);assert.equal(result.spellstrike.damageRoll.total,12);assert.equal(result.damage.total,19);assert.equal(target.hpCurrent,17,'physical 7 + fire 12/2 resolves once as mixed damage');
assert.equal(result.damageResult.damageParts.length,2);assert.equal(h.classFeaturesState.spellblade.prepared,undefined);
result=B.attack(h,hero('Enemy'),{weapon,damage:'1d6+3',distanceFt:5});assert.equal(result.spellstrike,undefined);assert.equal(result.damage.total,7,'no fixed 2d6 on subsequent attack');
C.restore(h,'short');assert.equal(h.resources.arcaneSurges.current,3);assert.equal(h.spellSlotsData[1].used,1);
C.resetTurn(h);C.useFeature(h,'spellstrike',{spellName:'Audit Flame'});target=hero('Enemy');g.Math.random=()=>0;
result=B.attack(h,target,{weapon,damage:'1d6+3',distanceFt:5});assert.equal(result.hit,false);assert.equal(result.spellstrike.missed,true);assert.equal(target.hpCurrent,30);assert.equal(h.classFeaturesState.spellblade.prepared,undefined);assert.equal(h.spellSlotsData[1].used,2);
C.resetTurn(h);C.useFeature(h,'spellstrike',{spellName:'Audit Flame'});target=hero('Enemy');g.Math.random=()=>0.5;
result=B.attack(h,target,{weapon,damage:'1d6+3',distanceFt:5,deferDamage:true});assert.equal(target.hpCurrent,30);assert.equal(result.spellstrike.reservationRetained,true);assert(h.classFeaturesState.spellblade.prepared);C.onTurnEnd(h);assert.equal(h.classFeaturesState.spellblade.prepared,undefined);
C.restore(h,'long');assert.equal(h.spellSlotsData[1].used,0);
C.resetTurn(h);assert.equal(C.useFeature(h,'arcaneGuard',{}).tempHP.tempHp,10);assert.equal(h.hpTemp,10);assert.equal(h.tempHp,10);assert.equal(h.hp.temp,10);assert.equal(h.hpCurrent,30);
C.resetTurn(h);h.hpTemp=15;h.tempHp=15;assert.equal(C.useFeature(h,'arcaneGuard',{}).tempHP.tempHp,15,'temporary HP are replaced by higher value, not summed');
C.resetTurn(h);g.Math.random=()=>0.5;h.ac=15;attacker=hero('Enemy');
result=B.attack(attacker,h,{bonus:5,damage:'1d6+2',defenderReaction:'spellbladeDeflection'});assert.equal(result.hit,false);assert.equal(result.ac,20);assert.equal(h.spellSlotsData[1].used,1);assert.equal(h.turnResources.reaction,0);
assert.equal(B.attack(attacker,h,{bonus:5,damage:'1d6+2'}).ac,20);C.resetTurn(h);assert.equal(B.attack(attacker,h,{bonus:5}).ac,15);assert.equal(h.spellSlotsData[1].used,1);
C.resetTurn(h);assert.equal(C.useFeature(h,'arcaneSurge',{mode:'teleport'}).ok,false);const surge=h.resources.arcaneSurges.current;
assert.equal(C.useFeature(h,'arcaneSurge',{mode:'attack'}).ok,true);assert.equal(h.resources.arcaneSurges.current,surge-1);let attackRolls=[0.1,0.8];g.Math.random=()=>attackRolls.shift()??0.5;
assert.equal(B.attack(h,target,{bonus:0}).d20,17);assert.equal(h.classFeaturesState.spellblade.surgeAttack,undefined);
h=hero('Заклинатель клинка',5);h.spellsData=[{...knownSpell,castingClass:'Заклинатель клинка',savingThrow:'con',attackType:null,halfOnSave:true}];C.buildFeatureSet(h);C.useFeature(h,'spellstrike',{spellName:'Audit Flame'});target=hero('Страж',7);target.stats.constitution=18;g.Math.random=()=>0.5;
result=B.attack(h,target,{weapon,damage:'1d6+3',distanceFt:5});assert.equal(result.spellstrike.save.mettle,true);assert.equal(target.hpCurrent,23);assert.equal(result.spellstrike.amount,0);
h=hero('Заклинатель клинка',4);h.spellsData=[{...knownSpell,level:0,name:'Cantrip',castingClass:'Заклинатель клинка'}];C.buildFeatureSet(h);assert.equal(C.useFeature(h,'spellstrike',{spellName:'Cantrip'}).ok,false);
h.classes[0].level=5;C.buildFeatureSet(h);assert.equal(C.useFeature(h,'spellstrike',{spellName:'Cantrip'}).reserved,true);
h=hero('Заклинатель клинка',1);h.level=20;assert.equal(S.useFeature(h,'spellstrike',{spellName:'Audit Flame'}).ok,false);C.buildFeatureSet(h);assert.equal(h.spellSlotsData[1].max,0);
for(const technique of S.techniques){h=hero('Заклинатель клинка',20,technique.name);C.buildFeatureSet(h);const sc=D.getClass('Заклинатель клинка').subclasses.find(x=>x.id===technique.id);assert(sc.features.every(f=>[3,7,15,20].includes(f.level)));assert.equal(S.useFeature(h,sc.features[0].id,{}).ok,false,'catalog is not a fictitious technique effect');}
for(let level=1;level<=20;level++){
 h=hero(level%2?'Spellblade':'Заклинатель клинка',level,'Боевой маг');C.buildFeatureSet(h);g.applyClassProgression(h,h.classes[0].name,level);C.resetTurn(h);C.onTurnEnd(h);C.restore(h,'short');C.restore(h,'long');C.buildFeatureSet(JSON.parse(JSON.stringify(h)));
 assert.equal(h.spellSlotsData[1].max,level===1?0:level===2?2:level<=4?3:4);assert.equal(g.DNDRules.spellSlotTable(h).casterLevel,level===1?0:Math.ceil(level/2));
}

h=hero('Заклинатель клинка',5);h.spellsData=[{...knownSpell,castingClass:'Заклинатель клинка',damageType:'bludgeoning'}];C.buildFeatureSet(h);C.useFeature(h,'spellstrike',{spellName:'Audit Flame'});target=hero('Enemy');target.resistances=['nonmagical bludgeoning'];target.hpTemp=8;target.concentration={active:true,spellName:'Test'};g.Math.random=()=>0.5;
result=B.attack(h,target,{weapon,damage:'1d6+3',damageType:'slashing',distanceFt:5});assert.equal(result.damageResult.amount,19);assert.equal(target.hpCurrent,19);assert.equal(target.hpTemp,0);assert.equal(result.damageResult.hpDamage,11);assert.equal(result.damageResult.concentration.dc,10);
console.log('PASS class audit stage4: Spellblade spells/slots, actual mixed Spellstrike damage, temp HP, Shield/Surge, six techniques and guards');

assert.equal(g.getExpandedClassDefinition('Warden').id,D.getClass('Страж').id);
assert.equal(g.getExpandedClassDefinition('Страж').savingThrows[1],'constitution');
assert.equal(g.getExpandedClassDefinition('Warden').source,D.getClass('Страж').source);
assert.equal(g.getExpandedClassDefinition('Warlord').hitDie,8);
assert.equal(g.getExpandedClassDefinition('Военачальник').savingThrows[0],'wisdom');
assert.equal(g.getExpandedClassDefinition('Warlord').source,D.getClass('Военачальник').source);
assert.equal(g.getExpandedClassDefinition('Spellblade').id,g.getExpandedClassDefinition('Заклинатель клинка').id);
console.log('PASS stage4 public class definitions follow live canonical packs');
