const assert=require('assert');
const {runtime,hero}=require('./helpers/class_runtime_harness');
const g=runtime(),D=g.DNDContent,C=g.DNDClassFeatures;
assert.equal(D.getClass('Некромант').id,'mh-necromancer');
assert.equal(D.getClass('Necromancer'),D.getClass('Некромант'));
assert.equal(D.listClasses().filter(x=>x.id==='mh-necromancer').length,1);
assert.equal(g.getAvailableSubclasses('Некромант').length,14);
assert(g.getAvailableSubclasses('Некромант').every(s=>s.pickLevel===3));
let h=hero('Некромант',2);h.level=20;C.buildFeatureSet(h);
assert.equal(h.resources.charnelTouch.max,10);
assert.equal(C.useFeature(h,'darkArcana',{spellLevel:1}).ok,false);
assert.equal(C.useFeature(h,'necromancer-reaper-20',{}).ok,false);
h=hero('Некромант',5,'Рыцарь смерти');C.buildFeatureSet(h);
assert.equal(h.spellSaveDC,14);assert.equal(h.spellAttackBonus,6);
assert(C.buildFeatureSet(h).includes('necromancer-deathKnight-3'));
assert(!C.buildFeatureSet(h).includes('necromancer-reaper-3'));
assert.equal(C.useFeature(h,'necromancer-reaper-3',{}).ok,false);
assert.equal(C.useFeature(h,'necromancer-deathKnight-3',{}).unsupported,true);
let target=hero('Enemy');target.id='necro-enemy';
const pool=h.resources.charnelTouch.current;
g.Math.random=()=>0;let result=C.useFeature(h,'charnelTouch',{points:5,target});
assert.equal(result.ok,true);assert.equal(result.attack.hit,false);
assert.equal(h.resources.charnelTouch.current,pool);assert.equal(target.hpCurrent,30);
g.Math.random=()=>0.5;result=C.useFeature(h,'charnelTouch',{points:5,target});
assert.equal(result.attack.hit,true);assert.equal(result.attack.critical,false);
assert.equal(target.hpCurrent,25);assert.equal(h.resources.charnelTouch.current,pool-5);
g.Math.random=()=>0.95;result=C.useFeature(h,'charnelTouch',{points:5,target});
assert.equal(result.attack.critical,true);assert.equal(target.hpCurrent,15);
assert.equal(h.resources.charnelTouch.current,pool-10);
for(const points of [-5,1.5,NaN,100])assert.equal(C.useFeature(h,'charnelTouch',{points,target}).ok,false);
const before=h.resources.charnelTouch.current;
assert.equal(C.useFeature(h,'charnelTouch',{points:5,target,distanceFt:30}).ok,false);
assert.equal(h.resources.charnelTouch.current,before);
g.Math.random=()=>0;const used=h.spellSlotsData[1].used;
assert.equal(C.useFeature(h,'darkArcana',{spellLevel:1}).restored,4);
assert.equal(h.spellSlotsData[1].used,used+1);
C.buildFeatureSet(h);assert.equal(h.resources.charnelTouch.current,before+4);
C.restore(h,'short');assert.equal(h.resources.charnelTouch.current,before+4);
C.restore(h,'long');assert.equal(h.resources.charnelTouch.current,pool);
h=hero('Некромант',20);g.currentChar=h;
h.initiativeTracker={round:1,activeIndex:0,combatants:[],battlefield:{cols:10,rows:10,tokens:{},entities:{}}};
const corpse={id:'corpse-1',hpCurrent:0};
const block={name:'Скелет',cr:0.25,hp:13,maxHp:13,ac:13,speed:30,actions:[{name:'Меч',damage:'1d6',attackBonus:4}]};
result=C.useFeature(h,'thralls',{corpse,statBlock:block});assert.equal(result.ok,true);
const eid=result.entity.id;assert.equal(g.DNDSecondaryEntities.get(eid).ownerId,h.id);
assert(h.initiativeTracker.battlefield.tokens['bt_'+eid]);assert(h.initiativeTracker.combatants.some(c=>c.entityId===eid));
assert.equal(C.useFeature(h,'thralls',{corpse,statBlock:block}).ok,false);
g.DNDSecondaryEntities.update(eid,{hp:4});
assert.equal(C.useFeature(h,'charnelTouch',{mode:'heal',points:5,target:{id:eid}}).ok,true);
assert.equal(g.DNDSecondaryEntities.get(eid).hp,9);
assert.equal(C.useFeature(h,'deadSpace',{entityId:eid}).ok,true);
assert(!g.DNDSecondaryEntities.get(eid));assert(!h.initiativeTracker.battlefield.tokens['bt_'+eid]);
assert(!h.initiativeTracker.combatants.some(c=>c.entityId===eid));
h=JSON.parse(JSON.stringify(h));g.currentChar=h;C.buildFeatureSet(h);
assert.equal(C.useFeature(h,'deadSpace',{mode:'release',entityId:eid}).ok,true);
assert.equal(g.DNDSecondaryEntities.get(eid).hp,9);assert.equal(h.classFeaturesState.necromancer.deadSpace.length,0);
assert.equal(C.useFeature(h,'deadSpace',{mode:'release',entityId:eid}).ok,false);
const foreign=g.DNDSummoning.create({...block,ownerId:'other'});
assert.equal(C.useFeature(h,'deadSpace',{entityId:foreign.id}).ok,false);
g.DNDSecondaryEntities.update(eid,{hp:0,defeated:true});
assert.equal(C.useFeature(h,'undyingServitude',{entityId:eid}).ok,true);
assert.equal(g.DNDSecondaryEntities.get(eid).hp,1);assert.equal(h.resources.undyingServitude.current,0);
assert.equal(C.useFeature(h,'undyingServitude',{entityId:eid}).ok,false);
for(let level=1;level<=20;level++){
 h=hero('Некромант',level,'Жнец');assert(C.buildFeatureSet(h).includes('charnelTouch'));
 g.applyClassProgression(h,'Некромант',level);C.resetTurn(h);C.onTurnEnd(h);C.restore(h,'short');C.restore(h,'long');C.buildFeatureSet(JSON.parse(JSON.stringify(h)));
 assert.equal(C.attackModifiers(h,{spellAttack:true}).criticalRange,level>=14?18:level>=5?19:20);
}
h=hero('Некромант',6,'Рыцарь смерти');assert.equal(C.attackModifiers(h,{}).extraAttacks,2);
assert.equal(C.useFeature(h,'necromancer-chooseAmbition',{subclass:'Жнец'}).ok,true);assert.equal(h.classes[0].subclass,'reaper');
assert.equal(C.attackModifiers(h,{}).extraAttacks,1);
assert.equal(D.getClass('Сосуд'),D.getClass('Vessel'));
assert.equal(g.getAvailableSubclasses('Сосуд').length,6);
h=hero('Сосуд',1);h.level=20;C.buildFeatureSet(h);
assert.equal(h.resources.vesselMagicSlots.max,0);assert.equal(h.resources.vesselArchonUses.max,0);
assert.equal(C.useFeature(h,'archonForm',{}).ok,false);
assert.equal(C.useFeature(h,'unsealedAspects',{aspect:'Эфирные крылья'}).ok,false);
assert.equal(C.useFeature(h,'unsealedAspects',{aspect:'Эфирный усик'}).ok,true);
assert.equal(C.useFeature(h,'unsealedAspects',{aspect:'Сверхъестественная сила'}).ok,false,'aspect count enforced');
h=hero('Сосуд',14,'fallen');C.buildFeatureSet(h);
assert.equal(C.useFeature(h,'unsealedAspects',{aspect:'Изначальная жажда'}).ok,false,'required aspect enforced');
assert.equal(C.useFeature(h,'unsealedAspects',{aspect:'Иная пасть'}).ok,true);
assert.equal(C.useFeature(h,'unsealedAspects',{aspect:'Изначальная жажда'}).ok,true);
h=hero('Сосуд',3,'Падший');C.buildFeatureSet(h);assert.equal(h.classFeaturesState.vessel.spirit,'Падший');
assert.equal(h.classFeaturesState.vessel.spellSaveDC,13);
assert.equal(C.useFeature(h,'spiritMantle',{}).ok,true);assert.equal(h.ac,15);
const vesselHP=h.hpCurrent,attributes=JSON.stringify(h.stats);
result=C.useFeature(h,'archonForm',{});assert.equal(result.free,true);assert.equal(h.hpTemp,6);assert.equal(h.ac,17);
assert.equal(h.hpCurrent,vesselHP);assert.equal(JSON.stringify(h.stats),attributes);
assert.equal(g.DNDCombat.effectiveDamage(h,10,'necrotic').amount,5);
const slots=h.resources.vesselMagicSlots.current;C.buildFeatureSet(h);assert.equal(h.resources.vesselArchonUses.current,0);
assert.equal(C.useFeature(h,'archonForm',{}).ok,false);assert.equal(h.resources.vesselMagicSlots.current,slots);
h.resistances.push('acid');h=JSON.parse(JSON.stringify(h));C.buildFeatureSet(h);
assert.equal(C.useFeature(h,'vessel-endArchon',{}).ok,true);assert.equal(h.ac,15);
assert(h.resistances.includes('acid'));assert(!h.resistances.includes('necrotic'));
assert.equal(C.useFeature(h,'archonForm',{}).ok,false);
assert.equal(C.useFeature(h,'archonForm',{forceSlot:true}).ok,true);assert.equal(h.resources.vesselMagicSlots.current,slots-1);
assert.equal(h.classFeaturesState.vessel.vesselSlots,slots-1);
C.restore(h,'short');assert.equal(h.resources.vesselMagicSlots.current,slots);assert.equal(h.classFeaturesState.vessel.vesselSlots,slots);
assert.equal(h.resources.vesselArchonUses.current,1);assert.equal(h.classFeaturesState.vessel.archonActive,false);
assert.equal(C.useFeature(h,'vessel-chooseSpirit',{spirit:'Катаклизм'}).ok,false);
assert.equal(C.useFeature(h,'vessel-chooseSpirit',{spirit:'Катаклизм',affinity:'Огонь'}).ok,true);
assert.equal(h.classes[0].subclass,'Катаклизм');assert.equal(C.useFeature(h,'archonForm',{}).ok,true);
h.hpTemp=0;h.tempHp=0;g.DNDCombat.applyDamage(h,h.hpCurrent,'force');assert.equal(h.classFeaturesState.vessel.archonActive,false,'damage event ends Archon immediately at zero HP');
for(let level=1;level<=20;level++){
 h=hero('Сосуд',level,'Вознесённый');assert(C.buildFeatureSet(h).includes('spiritMantle'));g.applyClassProgression(h,'Сосуд',level);
 C.resetTurn(h);C.onTurnEnd(h);C.restore(h,'short');C.restore(h,'long');C.buildFeatureSet(JSON.parse(JSON.stringify(h)));
 assert.equal(C.attackModifiers(h,{}).extraAttacks,level>=5?2:1);
}
h=hero('Vessel',5,'Вознесённый');C.useFeature(h,'spiritMantle',{});target=hero('Enemy');g.Math.random=()=>0.5;
const strikeHP=target.hpCurrent;result=C.useFeature(h,'iridescentStrike',{target});assert.equal(result.attack.hit,true);assert(target.hpCurrent<strikeHP);
assert.equal(D.getClass('Шифтер'),D.getClass('Shifter'));assert.equal(g.getAvailableSubclasses('Шифтер').length,7);
assert(g.getAvailableSubclasses('Шифтер').every(s=>s.pickLevel===1));
h=hero('Шифтер',5);h.level=20;C.buildFeatureSet(h);assert.equal(h.resources.shifterAdrenaline.max,0);
assert.equal(C.useFeature(h,'adrenalineSurge',{damage:5}).ok,false);
assert.equal(C.useFeature(h,'shifter-chooseBloodline',{bloodline:'Carnivore'}).ok,true);assert.equal(h.classes[0].subclass,'Хищная');
const wolf={name:'Wolf',creatureType:'beast',cr:0.25,hp:13,ac:13,speed:40,size:1,stats:{strength:12,dexterity:15,constitution:20},actions:[{name:'Укус',attackBonus:4,damage:'1d6+2',damageType:'piercing'}]};
h=hero('Шифтер',11,'Хищная');C.buildFeatureSet(h);
assert.equal(C.useFeature(h,'learnShape',{target:{...wolf,team:'enemy'},statBlock:wolf}).ok,false);
assert.equal(C.useFeature(h,'learnShape',{target:wolf,statBlock:wolf}).ok,true);
const normal=JSON.stringify(h.stats),hpBeforeShift=h.hpCurrent;
assert.equal(C.useFeature(h,'shift',{shape:'Unknown'}).ok,false);
assert.equal(C.useFeature(h,'shift',{shape:'Wolf'}).ok,true);
assert.equal(h.stats.constitution,20);assert.equal(h.speed,40);assert.equal(h.hpCurrent,hpBeforeShift);assert.equal(h.hpMax,40);
assert.equal(h.resources.shifterAdrenaline.max,2,'resource uses normal Constitution, not beast Constitution');
assert.equal(h.classFeaturesState.shifter.saveDC,14);
const expiration=h.classFeaturesState.shifter.shapeExpiresAt;
assert.equal(C.useFeature(h,'shift',{shape:'Wolf'}).ok,true);assert.equal(h.classFeaturesState.shifter.shapeExpiresAt,expiration,'direct shift does not restart the one-hour limit');
assert.equal(C.useFeature(h,'primevalForm',{}).ok,true);assert.equal(h.size,2);assert.equal(h.resources.shifterPrimevalForm.current,2);
assert.equal(C.useFeature(h,'primevalForm',{}).ok,false);assert.equal(C.saveModifiers(h,{saveType:'str'}).advantage,true);
assert.equal(g.DNDCombat.effectiveDamage(h,8,'slashing').amount,4);
assert.equal(g.DNDCombat.effectiveDamage(h,8,'slashing',{magicalAttack:true}).amount,8);
assert.equal(g.DNDCombat.effectiveDamage({resistances:['slashing','nonmagical slashing']},8,'slashing',{magicalAttack:true}).amount,4,'a separate unconditional resistance remains effective');
const incoming=g.DNDCombat.attack(hero('Enemy'),h,{bonus:20,damage:'1d6+4',damageType:'slashing'});
assert.equal(incoming.damageResult.amount,4,'actual nonmagical attack applies Primeval resistance');
target=hero('Enemy');target.resistances=['nonmagical piercing'];
const naturalAttack=C.useFeature(h,'shifter-formAttack',{target});
assert.equal(naturalAttack.attack.hit,true);assert.equal(naturalAttack.attack.extraAttacks,2);
assert.equal(naturalAttack.attack.damageResult.amount,naturalAttack.attack.damage.total,'Mystic Empowerment bypasses only nonmagical resistance');
assert.equal(C.useFeature(h,'adrenalineSurge',{damage:-5}).ok,false);
assert.equal(C.useFeature(h,'adrenalineSurge',{damage:5}).tempHP,5);assert.equal(h.hpTemp,5);
const adr=h.resources.shifterAdrenaline.current;C.buildFeatureSet(h);assert.equal(h.resources.shifterAdrenaline.current,adr);
let save={success:false,total:12,dc:14};assert.equal(C.useFeature(h,'primalResilience',{saveResult:save}).ok,true);assert.equal(save.total,14);assert.equal(save.success,true);
assert.equal(h.resources.shifterAdrenaline.current,0);
h.resistances.push('acid');h=JSON.parse(JSON.stringify(h));C.buildFeatureSet(h);
assert.equal(C.useFeature(h,'shifter-revert',{}).ok,true);assert.equal(JSON.stringify(h.stats),normal);assert.equal(h.speed,30);assert(h.resistances.includes('acid'));assert(!h.resistances.includes('nonmagical slashing'));
h.resources.shifterPrimevalForm.current=0;C.restore(h,'short');assert.equal(h.resources.shifterPrimevalForm.current,1,'short rest restores exactly one use');assert.equal(h.classFeaturesState.shifter.primevalForm,1);
C.restore(h,'long');assert.equal(h.resources.shifterPrimevalForm.current,3);
assert.equal(C.useFeature(h,'shift',{shape:'Wolf'}).ok,true);g.DNDCombat.toggleCondition(h,'Оглушён',true);assert(!h.classFeaturesState.shifter.activeShape);assert.equal(h.stats.constitution,14);
g.DNDCombat.toggleCondition(h,'Оглушён',false);
const tiny={...wolf,name:'Mouse',cr:0,diminutive:true,sizeCategory:'Tiny',stats:{strength:2,dexterity:14,constitution:8}};
assert.equal(C.useFeature(h,'learnShape',{target:tiny,statBlock:tiny}).ok,true);
assert.equal(C.useFeature(h,'shift',{shape:'Mouse'}).ok,true);g.DNDCombat.applyDamage(h,1,'fire');assert(!h.classFeaturesState.shifter.activeShape);
assert.equal(C.useFeature(h,'shift',{shape:'Mouse'}).ok,true);g.Math.random=()=>0;g.DNDCombat.savingThrow(h,'wis',25);assert(!h.classFeaturesState.shifter.activeShape);
h=hero('Shifter',20,'Водная');C.buildFeatureSet(h);h.resources.shifterAdrenaline.current=0;C.resetTurn(h);assert.equal(h.resources.shifterAdrenaline.current,1);
for(let level=1;level<=20;level++){
 h=hero('Шифтер',level,'Хищная');assert(C.buildFeatureSet(h).includes('shift'));g.applyClassProgression(h,'Шифтер',level);
 C.resetTurn(h);C.onTurnEnd(h);C.restore(h,'short');C.restore(h,'long');C.buildFeatureSet(JSON.parse(JSON.stringify(h)));
 assert.equal(h.resources.shifterAdrenaline.max,level>=6?2:0);
}
for(const name of ['Necromancer','Vessel','Shifter']){const canonical=D.getClass(name).name;assert.equal(g.getClassData(name).progression,g.getClassData(canonical).progression);}
h=hero('Шифтер',15,'Хищная');C.buildFeatureSet(h);
const mythic={...wolf,name:'Dire Tiger',cr:5};
assert.equal(C.useFeature(h,'shifter-bloodlineShape',{shape:'Dire Tiger',statBlock:mythic}).ok,true);
assert.equal(C.useFeature(h,'shift',{shape:'Dire Tiger'}).ok,true);C.useFeature(h,'shifter-revert',{});
assert.equal(C.useFeature(h,'shift',{shape:'Dire Tiger'}).ok,false);C.restore(h,'short');
assert.equal(C.useFeature(h,'shift',{shape:'Dire Tiger'}).ok,true);
h.classFeaturesState.shifter.shapeExpiresAt=Date.now()-1;C.buildFeatureSet(h);assert(!h.classFeaturesState.shifter.activeShape);assert.equal(h.stats.constitution,14);
console.log('Class audit stage 2: three classes, real effects, ownership/resources, forms, events, aliases and lifecycle PASS');
