const fs=require('fs'),vm=require('vm'),assert=require('assert');
const sandbox={console,Math,Date,setTimeout,clearTimeout};sandbox.window=sandbox;sandbox.global=sandbox;sandbox.addEventListener=()=>{};
sandbox.DNDRules={profBonus:()=>3,rollD20:()=>({result:15,critical:false,fumble:false}),parseDice:e=>{const m=String(e).match(/(\d+)d(\d+)(?:\+(\d+))?/);return {groups:[{count:+m[1],sides:+m[2]}],constant:+(m[3]||0)};},getSaveBonus:()=>0};
sandbox.currentChar={id:'h',name:'Герой',classes:[{name:'Плут',level:5}],stats:{dex:16},spellSlotsData:{},resources:{},classFeaturesState:{}};
vm.runInNewContext(fs.readFileSync('class_features_engine.js','utf8'),sandbox,{filename:'class_features_engine.js'});
vm.runInNewContext(fs.readFileSync('combat_engine.js','utf8'),sandbox,{filename:'combat_engine.js'});
const cf=sandbox.DNDClassFeatures, cb=sandbox.DNDCombat;
let rogue={id:'r',name:'Плут',classes:[{name:'Плут',level:5}],stats:{dex:16},turnResources:{action:true,bonusAction:true,reaction:true},classFeaturesState:{}};
let opts=cf.reactionOptions(rogue,{amount:11,damageType:'рубящий',source:'attack',attackKind:'weapon',visible:true});assert(opts&&opts.options.some(x=>x.id==='uncannyDodge'),'uncanny dodge reaction window missing');
let rr=cf.resolveReaction(rogue,'uncannyDodge',{amount:11,damageType:'рубящий',source:'attack',attackKind:'weapon',visible:true});assert(rr.ok&&rr.remainingAmount===6);assert.strictEqual(rogue.turnResources.reaction,false);
let monk={id:'m',name:'Монах',classes:[{name:'Монах',level:5}],stats:{dex:16,wis:16},turnResources:{action:true,bonusAction:true,reaction:true},classFeaturesState:{}};
opts=cf.reactionOptions(monk,{amount:9,damageType:'колющий',source:'attack',attackKind:'rangedWeapon',projectile:true,visible:true});assert(opts&&opts.options.some(x=>x.id==='deflectMissiles'));
let mr=cf.resolveReaction(monk,'deflectMissiles',{amount:9,damageType:'колющий',source:'attack',attackKind:'rangedWeapon',projectile:true,visible:true});assert(mr.ok&&mr.remainingAmount<9);
let barbarian={id:'b',name:'Варвар',classes:[{name:'Варвар',level:11}],stats:{con:16},hp:5,hitPoints:5,maxHp:20,turnResources:{action:true,bonusAction:true,reaction:true},classFeaturesState:{raging:true}};
opts=cf.reactionOptions(barbarian,{amount:10,damageType:'рубящий',source:'attack',attackKind:'weapon',visible:true});assert(opts&&opts.options.some(x=>x.id==='relentlessRage'));
let br=cf.resolveReaction(barbarian,'relentlessRage',{amount:10,damageType:'рубящий',source:'attack',attackKind:'weapon',visible:true});assert(br.ok&&br.dc===10&&br.keptAtOne);
let target={id:'t',hp:20,maxHp:20,ac:10,classes:[],stats:{},turnResources:{reaction:true},conditions:{}};
let atk={id:'a',classes:[],stats:{str:16},turnResources:{action:true,bonusAction:true,reaction:true}};
const old=Math.random;Math.random=()=>0.9;let a=cb.attack(atk,target,{bonus:20,damage:'1d6',damageType:'рубящий',target:target,attackKind:'weapon',useRules:false});Math.random=old;assert(a.hit);assert.equal(target.hp,14,'attack damage must be applied exactly once');
let fall={id:'f',name:'Монах',classes:[{name:'Монах',level:4}],stats:{dex:14},hp:20,maxHp:20,turnResources:{action:true,bonusAction:true,reaction:true},classFeaturesState:{}};
let ro=cf.reactionOptions(fall,{amount:12,damageType:'дробящий',source:'fall',fall:true});assert(ro&&ro.options.some(x=>x.id==='slowFall'));
console.log('V70.21 reaction + single-damage tests: PASS');
