const assert=require('assert');
const {runtime,hero}=require('./helpers/class_runtime_harness');
const g=runtime(),C=g.DNDClassFeatures,B=g.DNDCombat,H=g.DNDBloodHunter,R=g.DNDRules;
let id=0;
function hunter(order,level=20){const a=hero('Кровавый охотник',level,order);a.id='order-'+(++id);a.weapons=[{id:'sword',name:'Меч',damageDice:'1d6',rangeFt:5}];C.buildFeatureSet(a);return a;}
function enemy(){const t=hero('Enemy',1);t.id='target-'+(++id);t.hpCurrent=100;t.hpMax=100;return t;}
g.Math.random=()=>0;R.rollD20=()=>({result:11,critical:false,fumble:false});
// Mutagens are chosen, prepared once after a rest, consumed from real stock,
// projected into real stats/attacks/saves/speed, and removed without stat drift.
let a=hunter('mutant',18);const raw=JSON.stringify(a.stats);
assert.equal(C.useFeature(a,'chooseMutagenFormulas',{formulas:['celerity','potency','sagacity','embers','mobility','rapidity','precision','reconstruction']}).ok,true);
assert.equal(C.useFeature(a,'mutagencraft',{mutagen:'celerity'}).ok,false);
assert.equal(C.useFeature(a,'prepareMutagens',{mutagens:['celerity','embers','rapidity']}).ok,true);
assert.equal(C.useFeature(a,'prepareMutagens',{mutagens:['potency']}).ok,false);
assert.equal(C.useFeature(a,'mutagencraft',{mutagen:'celerity'}).ok,true);assert.equal(R.getStats(a).dex,19);assert.equal(JSON.stringify(a.stats),raw);assert.equal(C.saveModifiers(a,{stat:'wis'}).disadvantage,true);
C.resetTurn(a);assert.equal(C.useFeature(a,'mutagencraft',{mutagen:'embers'}).ok,true);assert.equal(B.effectiveDamage(a,10,'fire').amount,5);assert.equal(B.effectiveDamage(a,10,'cold').amount,20);assert.equal(B.effectiveDamage(a,10,'poison').amount,0);assert.equal(B.toggleCondition(a,'Отравлен',true),false);
C.resetTurn(a);assert.equal(C.useFeature(a,'strangeMetabolism',{mutagen:'embers'}).ok,true);assert.equal(B.effectiveDamage(a,10,'cold').amount,10);assert.equal(B.effectiveDamage(a,10,'fire').amount,5);for(let i=0;i<10;i++)C.onTurnEnd(a);assert.equal(B.effectiveDamage(a,10,'cold').amount,20);
C.resetTurn(a);assert.equal(C.useFeature(a,'mutagencraft',{mutagen:'rapidity'}).ok,true);assert.equal(a.speed,50);C.buildFeatureSet(a);assert.equal(a.speed,50);C.resetTurn(a);assert.equal(C.useFeature(a,'exaltedMutation',{replaceMutagen:'celerity',mutagen:'potency'}).ok,true);assert.equal(R.getStats(a).dex,14);assert.equal(R.getStats(a).str,21);assert.equal(a.resources.exaltedMutation.current,2);
C.resetTurn(a);assert.equal(C.useFeature(a,'flushMutagens',{}).ok,true);assert.equal(a.speed,35);assert.equal(R.getStats(a).str,16);assert.equal(JSON.stringify(a.stats),raw);C.restore(a,'short');assert.equal(a.resources.mutagenConcoctions.current,0);assert.equal(C.useFeature(a,'prepareMutagens',{mutagens:['mobility','reconstruction']}).ok,true);assert.equal(C.useFeature(a,'mutagencraft',{mutagen:'mobility'}).ok,true);assert.equal(B.toggleCondition(a,'Захвачен',true),false);assert.equal(B.toggleCondition(a,'Парализован',true),false);
const restored=JSON.parse(JSON.stringify(a));C.buildFeatureSet(restored);assert.equal(B.toggleCondition(restored,'Захвачен',true),false);C.restore(restored,'long');assert.equal(B.toggleCondition(restored,'Захвачен',true),true);
// Real weapon attacks normalize stats. Temporary mutagen boosts must not be
// copied into the base scores, and ASI modifies the permanent score only.
let normalized=hunter('mutant',18);C.useFeature(normalized,'chooseMutagenFormulas',{formulas:['potency']});C.useFeature(normalized,'prepareMutagens',{mutagens:['potency']});C.useFeature(normalized,'mutagencraft',{mutagen:'potency'});R.weaponAttack(normalized,{stat:'str'});assert.equal(normalized.stats.str,16);assert.equal(R.getStats(normalized).str,21);assert.equal(R.applyASI(normalized,{str:2}).str.after,18);assert.equal(R.getStats(normalized).str,23);C.restore(normalized,'short');assert.equal(R.getStats(normalized).str,18);

// Lycan form has actual AC/resistance, silver exception, bonus action economy,
// permanent speed, bounded regeneration and a persisted bloodlust save.
a=hunter('lycan',11);assert.equal(a.speed,45);assert.equal(C.useFeature(a,'hybridTransformation',{}).ok,true);assert.equal(H.incomingAC(a),1);assert.equal(B.effectiveDamage(a,10,'slashing',{magicalAttack:false}).amount,5);assert.equal(B.effectiveDamage(a,10,'slashing',{magicalAttack:false,silvered:true}).amount,10);assert.equal(B.effectiveDamage(a,10,'slashing',{magicalAttack:true}).amount,10);
assert.equal(C.useFeature(a,'hybridTransformation',{}).ok,false);a.hpCurrent=18;C.resetTurn(a);assert.equal(a.hpCurrent,21);assert(!a.classFeaturesState.bhBloodlust);a.hpCurrent=5;B.beginConcentration(a,{name:'Тест',concentration:true});C.resetTurn(a);assert.equal(a.hpCurrent,8);assert.equal(a.classFeaturesState.bhBloodlust.requiresNearestAttack,true);assert.equal(a.classFeaturesState.bhBloodlust.save.autoFailed,true);
a=hunter('lycan',18);for(let i=0;i<4;i++){C.resetTurn(a);assert.equal(C.useFeature(a,'hybridTransformation',{}).ok,true);}assert.equal(a.resources.hybridTransformation.max,2,'unlimited state is separate from the finite JSON resource');
// Dawn is granted by the order, but activation still pays HP on a real weapon.
a=hunter('ghostslayer',18);let t=enemy();t.creatureType='undead';assert.equal(C.useFeature(a,'riteOfTheDawn',{weaponId:'sword'}).ok,true);assert.equal(B.effectiveDamage(a,10,'necrotic').amount,5);const mods=C.attackModifiers(a,{weapon:a.weapons[0],weaponAttack:true,target:t});assert.equal(mods.typedExtraDice[0].dice,'2d10');assert.equal(mods.typedExtraDice[0].type,'radiant');a.hpCurrent=1;let r=B.applyDamage(a,2,'fire',{zeroHpReaction:'blood-rite-revival'});assert.equal(r.bloodRiteRevival.ok,true);assert.equal(a.hpCurrent,1);assert.equal(B.effectiveDamage(a,10,'necrotic').amount,10);
a=hunter('ghostslayer',18);C.useFeature(a,'riteOfTheDawn',{weaponId:'sword'});a.hpCurrent=1;r=B.applyDamage(a,41,'fire',{zeroHpReaction:'blood-rite-revival'});assert.equal(r.bloodRiteRevival.ok,false);assert.equal(a.hpCurrent,0);
a=hunter('ghostslayer',7);assert.equal(C.useFeature(a,'aetherWalk',{}).ok,false);assert.equal(C.useFeature(a,'aetherWalk',{atStartOfTurn:true}).ok,true);a.insideObject=true;const hp=a.hpCurrent;C.onTurnEnd(a);assert.equal(a.hpCurrent,hp-1);
// Pact slots are a single shared counter. Native Blood Hunter progression and
// Warlock multiclass progression differ at level 7; sync never grants free slots.
for(let l=3;l<=20;l++){a=hunter('profaneSoul',l);const table=H.spellTable(l);assert.equal(a.pactMagicData.max,table.slots);assert.equal(a.pactMagicData.slotLevel,table.slotLevel);assert(!a.resources.profaneSoulSlots);a.pactMagicData.used=1;C.buildFeatureSet(a);assert.equal(a.pactMagicData.used,1);C.restore(a,'short');assert.equal(a.pactMagicData.used,0);}
a=hunter('profaneSoul',7);a.classes.push({name:'Колдун',level:1});C.buildFeatureSet(a);assert.equal(a.pactMagicData.slotLevel,2);assert.equal(R.spellSlotTable(a).pact.count,2);assert.equal(C.useFeature(a,'setHemocraftAbility',{ability:'wisdom'}).ok,true);assert.equal(g.DNDMagic.getSpellInfo(a,{castingClass:'Кровавый охотник'}).ability,'wis');
a=hunter('profaneSoul',18);a.pactMagicData.used=1;t=enemy();t.hpCurrent=0;assert.equal(C.useFeature(a,'soulEater',{target:t,distanceFt:10,justDroppedToZero:true,amplify:true}).ok,true);assert.equal(a.pactMagicData.used,0);assert.equal(B.effectiveDamage(a,10,'fire').amount,5);assert.equal(C.attackModifiers(a,{}).advantage,true);C.onTurnEnd(a);assert.equal(C.attackModifiers(a,{}).advantage,true);C.onTurnEnd(a);assert.equal(C.attackModifiers(a,{}).advantage,false);C.resetTurn(a);a.pactMagicData.used=1;assert.equal(C.useFeature(a,'soulEater',{target:t,distanceFt:10,justDroppedToZero:true,amplify:true}).ok,false);
// Howl has real multi-target saves and fear/stun, immunity for a successful save.
a=hunter('lycan',18);t=enemy();R.rollD20=()=>({result:1,critical:false,fumble:true});assert.equal(C.useFeature(a,'bloodMaledict',{curse:'howl',targets:[{target:t,distanceFt:10,canHear:true}]}).ok,true);assert.equal(t.conditions['Испуган'],true);assert.equal(t.conditions['Оглушён'],true);R.rollD20=()=>({result:20,critical:true,fumble:false});C.onTurnEnd(t);assert.equal(t.conditions['Испуган'],false);assert.equal(t.conditions['Оглушён'],false);
// Fallen Puppet performs one actual attack; missing/drop/range/move validation
// happens before resource or HP mutations.
a=hunter('ghostslayer');t=enemy();t.hpCurrent=0;t.weapons=[{id:'club',damageDice:'1d6',rangeFt:5}];const victim=enemy();C.useFeature(a,'chooseBloodCurses',{curses:['fallenPuppet']});const charges=a.resources.bloodMaledict.current;assert.equal(C.useFeature(a,'bloodMaledict',{curse:'fallenPuppet',target:t,distanceFt:10,justDroppedToZero:true,moveFt:10,amplify:true}).ok,false);assert.equal(a.resources.bloodMaledict.current,charges);g.Math.random=()=>0.5;const puppet=C.useFeature(a,'bloodMaledict',{curse:'fallenPuppet',target:t,distanceFt:10,justDroppedToZero:true,weapon:{id:'club',damageDice:'1d6',rangeFt:5},attackTarget:victim,attackDistanceFt:5});assert.equal(puppet.ok,true);assert(puppet.attack.damageResult);assert(victim.hpCurrent<100);
// UI invokes a scoped real action and cancel never changes the character.
a=hunter('mutant',3);g.currentChar=a;let prompts=['1,2,3,4'];g.prompt=()=>prompts.shift()??null;g.useBloodHunterFeature('chooseMutagenFormulas');assert.equal(a.classFeaturesState.mutagenFormulasKnown.length,4);const snapshot=JSON.stringify(a);g.useBloodHunterFeature('prepareMutagens');assert.equal(JSON.stringify(a),snapshot);assert(H.renderControls(a).includes('useBloodHunterFeature'));
console.log('Blood Hunter orders: PASS (real mutagens, lycan/dawn, pact slots, special curses and scoped UI)');
