const fs=require('fs'),vm=require('vm'),assert=require('assert');
function sandbox(){
 const store={}; const ctx={console,Date,Math,JSON,URL:{createObjectURL:()=>'',revokeObjectURL:()=>{}},Blob:function(){},FileReader:function(){},prompt:()=>'',alert:()=>{},document:{addEventListener(){},getElementById(){return null},querySelectorAll(){return []},createElement(){return {style:{},click(){}}}},localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>{store[k]=String(v)},removeItem:k=>delete store[k]},addEventListener(){},setTimeout};ctx.window=ctx;vm.createContext(ctx);return ctx;}
// Campaign migration + safe save
let c=sandbox();vm.runInContext(fs.readFileSync('campaign_manager.js','utf8'),c);c.localStorage.setItem('dnd_campaigns_v1',JSON.stringify([{id:'old',name:'Old',sessions:[{title:'S'}],npcs:[{name:'N'}]}]));let st=c.DNDCampaign.load();assert.equal(st.schemaVersion,2);assert.equal(st.campaigns[0].sessions[0].id.startsWith('ses_'),true);assert.equal(c.DNDCampaign.save(),true);assert.equal(JSON.parse(c.localStorage.getItem('dnd_campaigns_v1')).schemaVersion,2);
// Checkpoint migration
c=sandbox();c.currentCharacter={id:'h',initiativeTracker:{round:3,activeIndex:4,combatants:[{id:'a'}]}};c.DNDGameplayV58={snapshot:()=>({round:3}),restoreSnapshot:p=>{c.restoredGameplay=p}};c.DNDEncounterMapV59={snapshot:()=>({activeEncounterId:'e'}),restoreSnapshot:p=>{c.restoredEncounter=p}};c.DNDBattleBoard={getView:()=>({x:1}),setView:p=>{c.restoredBoard=p}};vm.runInContext(fs.readFileSync('vtt_encounter_checkpoint_v68.js','utf8'),c);let p=c.DNDEncounterCheckpointV68.build();assert.equal(p.schemaVersion,2);assert.equal(p.version,'68.1.0');assert.equal(c.DNDEncounterCheckpointV68.importText(JSON.stringify({version:'68.0.0',initiativeTracker:{round:2,activeIndex:0,combatants:[{id:'z'}]}}),'x').ok,true);assert.equal(c.DNDEncounterCheckpointV68.restore('x').ok,true);
// Mobile session must restore gameplay and board, not only character
c=sandbox();c.currentCharacter={id:'h',name:'Hero',initiativeTracker:{round:2,activeIndex:0,combatants:[]}};c.DNDGameplayV57={snapshot:()=>({round:2,active:'Hero'}),restoreSnapshot:p=>{c.gp=p}};c.DNDBattleBoard={getView:()=>({cellPx:50}),setView:p=>{c.board=p}};c.DNDCombatLogV66={events:()=>[],clear(){},record(){}};vm.runInContext(fs.readFileSync('vtt_mobile_session_v67.js','utf8'),c);assert.equal(c.DNDMobileSessionV67.save('q').ok,true);c.currentCharacter.name='Mutated';assert.equal(c.DNDMobileSessionV67.restore('q').ok,true);assert.equal(c.currentCharacter.name,'Hero');assert.equal(c.gp.round,2);assert.equal(c.board.cellPx,50);
console.log('V70.17 save/campaign/checkpoint/session tests PASS');
