const fs=require('fs'), vm=require('vm'), assert=require('assert');
const app=fs.readFileSync('app.js','utf8');
assert(app.includes('CHARACTER_SAVE_SCHEMA_VERSION = 3'),'save schema version missing');
assert(app.includes('function normalizeCharacterSave(c)'),'character migration helper missing');
assert(app.includes('Array.isArray(parsed.characters)'),'wrapped backup/legacy character format supported');
assert(app.includes("if (typeof alert === 'function') alert('Не удалось сохранить данные персонажей."),'storage quota handling missing');
assert(app.includes("imported = normalizeCharacterSave(imported);"),'character import must migrate');
const settings=fs.readFileSync('Settings.js','utf8');
assert(settings.includes("if (!backupData || typeof backupData !== 'object' || Array.isArray(backupData))"),'backup root validation missing');
assert(settings.includes('const oldData = {};'),'backup restore guard missing');
assert(settings.includes('for (const key in oldData) localStorage.setItem(key, oldData[key]);'),'backup rollback missing');
const sandbox={console,Math,Date,JSON,window:null,document:{addEventListener(){},getElementById(){return null},querySelector(){return null}},localStorage:{_:{},getItem(k){return this._[k]??null},setItem(k,v){this._[k]=String(v)}}};
sandbox.window=sandbox; vm.runInNewContext(app,sandbox,{filename:'app.js'});
sandbox.localStorage.setItem('dnd_multi_characters_v2',JSON.stringify([{id:'old',name:'Old',stats:{str:18},spellSlotsData:{1:{max:2,used:9}}}]));
sandbox.loadAllCharacters();
assert.strictEqual(sandbox.allCharacters.length,1);
const c=sandbox.allCharacters[0];
assert.strictEqual(c.schemaVersion,3); assert.strictEqual(c.stats.dex,10); assert.strictEqual(c.spellSlotsData[1].used,2);
sandbox.saveAllCharacters();
const stored=JSON.parse(sandbox.localStorage.getItem('dnd_multi_characters_v2'));
assert.strictEqual(stored[0].schemaVersion,3);
console.log('V70.16 SAVE_MIGRATION TEST OK');
