const assert = require('assert');
const {runtime, hero} = require('./helpers/class_runtime_harness');
const g = runtime(), D = g.DNDContent;
const low = hero('Кровавый охотник', 1, 'Орден ликантропов');
assert.strictEqual(D.invoke('Кровавый охотник', low, 'brandOfCastigation', {}).unavailable, true);
const wrong = hero('Кровавый охотник', 10, 'Орден мутантов');
assert.strictEqual(D.invoke('Кровавый охотник', wrong, 'hybridTransformation', {}).unavailable, true);
const h = hero('Кровавый охотник', 10, 'Орден ликантропов');
h.hpCurrent = 2;
g.Math.random = () => 0.999; // Deterministic d6 cost of 6 exceeds current HP.
g.DNDBloodHunter.sync(h);
const before = JSON.stringify({hp:h.hpCurrent, resources:h.resources});
const badR = D.invoke('Кровавый охотник', h, 'crimsonRite', {riteType:'fire'});
assert.strictEqual(badR.ok, false);
assert.strictEqual(JSON.stringify({hp:h.hpCurrent, resources:h.resources}), before);
assert(!h.classFeaturesState.crimsonRite, 'failed activation never enables a rite');
// Crimson Rite pays HP; there is no synthetic crimsonRite resource pool.
const beforeCurse = h.resources.bloodMaledict.current;
assert.strictEqual(D.invoke('Кровавый охотник', h, 'bloodMaledict', {}).ok, false);
assert.strictEqual(h.resources.bloodMaledict.current, beforeCurse);
const amplified = D.invoke('Кровавый охотник', h, 'bloodMaledict', {target:hero('Enemy'), amplify:true});
assert.strictEqual(amplified.ok, false);
assert.strictEqual(h.resources.bloodMaledict.current, beforeCurse);
assert.strictEqual(h.hpCurrent, 2);
h.hpCurrent = 30;
assert.strictEqual(D.invoke('Кровавый охотник', h, 'hybridTransformation', {}).ok, true);
const spent = h.resources.hybridTransformation.current;
assert.strictEqual(D.invoke('Кровавый охотник', h, 'hybridTransformation', {}).ok, true);
assert.strictEqual(h.resources.hybridTransformation.current, spent);
assert.strictEqual(h.classFeaturesState.hybridForm, false);
console.log('Blood Hunter availability and canonical HP/resource transactions: PASS');
