const fs=require('fs'),vm=require('vm');
const ctx={console,setTimeout,setInterval,clearTimeout,clearInterval,Date,Math,JSON};
ctx.window=ctx;ctx.global=ctx;
if(!ctx.document)ctx.document={readyState:'complete',getElementById:function(){return null;},addEventListener:function(){},createElement:function(){return {style:{},appendChild:function(){}};}};
if(!ctx.localStorage){var __ls={};ctx.localStorage={getItem:function(k){return __ls[k]||null;},setItem:function(k,v){__ls[k]=v;}};}
if(!ctx.DNDCombatEventBusV69)ctx.DNDCombatEventBusV69={record:function(){}};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync('vtt_debug_scenarios_v704.js','utf8'),ctx,{filename:'vtt_debug_scenarios_v704.js'});
const __TEST_SRC__="(function(global){'use strict';var assert=global.__TEST_ASSERT__||function(c,m){if(!c)throw new Error(m);};var old=global.currentCharacter;global.currentCharacter={id:'qa704',name:'Scenario Hero',hpCurrent:30,hpMax:30,ac:18,level:5,classes:[{name:'Воин',level:5}],inventory:[]};global.currentChar=global.currentCharacter;global.autoSaveCurrentCharacter=function(){};global.updateCharacterUI=function(){};global.renderCharacterSheet=function(){};global.renderConditions=function(){};global.renderSpellSlots=function(){};global.renderCombatAbilities=function(){};global.DNDCombatEventBusV69={record:function(){}};var storage={};global.localStorage={getItem:function(k){return storage[k]||null;},setItem:function(k,v){storage[k]=v;}};global.document={readyState:'complete',getElementById:function(){return null;},addEventListener:function(){}};var api=global.DNDDebugScenarioManagerV704;assert(api&&api.version==='70.4.0','V70.4 API missing');var list=api.list();assert(list.length>=6,'defaults missing');var r=api.run('multiclass');assert(global.currentCharacter.level===20,'level scenario failed');assert(global.currentCharacter.classes.length===2,'multiclass scenario failed');api.rollback();assert(global.currentCharacter.level===5 && global.currentCharacter.classes.length===1,'rollback failed');api.run('broken-state');assert(global.currentCharacter.hpCurrent===-50 && global.currentCharacter.ac===-10,'broken state failed');api.rollback();assert(global.currentCharacter.hpCurrent===30,'second rollback failed');global.currentCharacter=old;global.__TEST_RESULT__='V70_4_SCENARIO_MANAGER_TEST_OK';})(window);\n";
vm.runInContext(__TEST_SRC__,ctx,{filename:'test_v704.js'});
