const assert=require('assert'),vm=require('vm'),fs=require('fs');
function ctx(){const c={console,Math,Date,JSON,setTimeout,clearTimeout,alert:()=>{},prompt:()=>null};c.window=c;c.globalThis=c;c.addEventListener=()=>{};c.DNDRules={parseDice:(x)=>{const m=String(x).match(/(\d+)d(\d+)([+-]\d+)?/i);return {groups:[{count:+m[1],sides:+m[2]}],constant:m[3]?+m[3]:0};},getSaveBonus:()=>0,rollD20:()=>({result:10,critical:false,fumble:false})};c.DNDClassFeatures={activeRage:()=>false,reactionOptions:()=>null};return c;}
// Mixed damage: radiant resistance must not halve the physical component.
{const c=ctx();vm.runInNewContext(fs.readFileSync('combat_engine.js','utf8'),c,{filename:'combat_engine.js'});const t={hp:20,maxHp:20,tempHp:0,resistances:['излучение'],vulnerabilities:[],immunities:[]};const r=c.DNDCombat.applyDamage(t,20,'рубящий',{damageParts:[{amount:10,damageType:'рубящий'},{amount:10,damageType:'излучение'}]});assert.strictEqual(r.hpDamage,15);assert.strictEqual(t.hp,5);assert.strictEqual(r.damageParts[0].amount,10);assert.strictEqual(r.damageParts[1].amount,5);}
// Immunity applies only to its component; other damage still lands.
{const c=ctx();vm.runInNewContext(fs.readFileSync('combat_engine.js','utf8'),c,{filename:'combat_engine.js'});const t={hp:20,maxHp:20,tempHp:0,resistances:[],vulnerabilities:[],immunities:['яд']};const r=c.DNDCombat.applyDamage(t,12,'яд',{damageParts:[{amount:7,damageType:'яд'},{amount:5,damageType:'рубящий'}]});assert.strictEqual(r.hpDamage,5);assert.strictEqual(t.hp,15);}
// Critical damage against a 0-HP hero produces two death-save failures.
{const c=ctx();vm.runInNewContext(fs.readFileSync('combat_engine.js','utf8'),c,{filename:'combat_engine.js'});const t={hp:0,maxHp:20,tempHp:0,type:'hero',deathSaves:{successes:0,failures:0},resistances:[],vulnerabilities:[],immunities:[]};const r=c.DNDCombat.applyDamage(t,3,'рубящий',{critical:true});assert.strictEqual(r.deathSaveFailures,2);assert.strictEqual(t.deathSaves.failures,2);}
// Resistance + vulnerability cancel instead of stacking.
{const c=ctx();vm.runInNewContext(fs.readFileSync('combat_engine.js','utf8'),c,{filename:'combat_engine.js'});const t={hp:20,maxHp:20,tempHp:0,resistances:['огонь'],vulnerabilities:['огонь'],immunities:[]};const r=c.DNDCombat.applyDamage(t,9,'огонь');assert.strictEqual(r.hpDamage,9);}
console.log('V70.25.41 damage pipeline regression: PASS');
