const fs=require('fs'),vm=require('vm');
const ctx={console,setTimeout,setInterval,clearTimeout,clearInterval,Date,Math,JSON};
ctx.window=ctx;ctx.global=ctx;
if(!ctx.document)ctx.document={readyState:'complete',getElementById:function(){return null;},addEventListener:function(){},createElement:function(){return {style:{},appendChild:function(){}};}};
if(!ctx.localStorage){var __ls={};ctx.localStorage={getItem:function(k){return __ls[k]||null;},setItem:function(k,v){__ls[k]=v;}};}
if(!ctx.DNDCombatEventBusV69)ctx.DNDCombatEventBusV69={record:function(){}};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync('vtt_debug_sandbox_v701.js','utf8'),ctx,{filename:'vtt_debug_sandbox_v701.js'});
const __TEST_SRC__="(function(global){'use strict';\n  var assert=global.__TEST_ASSERT__||function(c,m){if(!c)throw new Error(m);};\n  var oldChar=global.currentCharacter, oldChar2=global.currentChar;\n  global.currentCharacter={id:'qa1',name:'QA Hero',level:3,hpCurrent:20,hpMax:30,ac:15,speed:'30',activeConditions:{},combatAbilities:[{name:'Action Surge',usedCount:1,maxUses:1}],spellSlotsData:{'1':{used:1,total:4}},initiativeTracker:{combatants:[{initiative:10}]}};\n  global.currentChar=global.currentCharacter;\n  var saveCount=0;global.autoSaveCurrentCharacter=function(){saveCount++;};\n  var api=global.DNDDebugSandboxV701;assert(api&&api.version==='70.1.0','V70.1 API missing');\n  api.set('hpCurrent',1);assert(global.currentCharacter.hpCurrent===1,'set hp failed');\n  api.set('abilities.str',20);assert(global.currentCharacter.abilities.str===20,'nested set failed');\n  api.damage(1);assert(global.currentCharacter.hpCurrent===0,'damage failed');\n  api.heal(10);assert(global.currentCharacter.hpCurrent===10,'heal failed');\n  api.addCondition('Poisoned');assert(global.currentCharacter.activeConditions.Poisoned===true,'condition failed');\n  api.setSpell(1,0,9);assert(global.currentCharacter.spellSlotsData['1'].total===9,'spell slot failed');\n  api.setResource(0,99,99);assert(global.currentCharacter.combatAbilities[0].usedCount===99,'resource failed');\n  api.backup();api.set('ac',1);api.rollback();assert(global.currentCharacter.ac===15,'rollback failed');\n  assert(saveCount>0,'autosave not called');\n  global.currentCharacter=oldChar;global.currentChar=oldChar2;\n  global.__TEST_RESULT__='V70_1_DEBUG_SANDBOX_TEST_OK';\n})(window);\n";
vm.runInContext(__TEST_SRC__,ctx,{filename:'test_v701.js'});
