const fs=require('fs'),vm=require('vm');
const ctx={console,setTimeout,setInterval,clearTimeout,clearInterval,Date,Math,JSON};
ctx.window=ctx;ctx.global=ctx;
if(!ctx.document)ctx.document={readyState:'complete',getElementById:function(){return null;},addEventListener:function(){},createElement:function(){return {style:{},appendChild:function(){}};}};
if(!ctx.localStorage){var __ls={};ctx.localStorage={getItem:function(k){return __ls[k]||null;},setItem:function(k,v){__ls[k]=v;}};}
if(!ctx.DNDCombatEventBusV69)ctx.DNDCombatEventBusV69={record:function(){}};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync('vtt_debug_scenario_editor_v705.js','utf8'),ctx,{filename:'vtt_debug_scenario_editor_v705.js'});
const __TEST_SRC__="(function(global){'use strict';var assert=global.__TEST_ASSERT__||function(c,m){if(!c)throw new Error(m);};var old=global.currentCharacter;var oldChar=global.currentChar;var storage={};global.localStorage={getItem:function(k){return storage[k]||null;},setItem:function(k,v){storage[k]=v;}};global.document={readyState:'complete',getElementById:function(){return null;},addEventListener:function(){}};global.currentCharacter={id:'qa705',name:'Chain Hero',hpCurrent:30,hpMax:30,ac:18,level:5,classes:[{name:'Воин',level:5}],inventory:[]};global.currentChar=global.currentCharacter;global.autoSaveCurrentCharacter=function(){};global.updateCharacterUI=function(){};global.renderCharacterSheet=function(){};global.renderConditions=function(){};global.renderSpellSlots=function(){};global.renderCombatAbilities=function(){};var events=[];global.DNDCombatEventBusV69={record:function(e){events.push(e);}};var api=global.DNDDebugScenarioEditorV705;assert(api&&api.version==='70.5.0','V70.5 API missing');var list=api.list();assert(list.length>=3,'defaults missing');var r=api.run('chain-smoke');assert(r.ok,'chain smoke failed');assert(global.currentCharacter.level===10,'level mutation failed');assert(global.currentCharacter.classes[1].name==='Волшебник','class chain failed');assert(events.length>0,'event missing');assert(api.rollback(),'rollback failed');assert(global.currentCharacter.level===5 && global.currentCharacter.classes.length===1,'state not restored');var custom={id:'imported',name:'Imported QA',description:'test',steps:[{action:'set',path:'hpCurrent',value:1},{action:'assert',path:'hpCurrent',equals:1}]};assert(api.importJSON(custom)===1,'import failed');var out=JSON.parse(api.exportJSON('imported'));assert(out.id==='imported'&&out.steps.length===2,'export failed');global.currentCharacter=old;global.currentChar=oldChar;global.__TEST_RESULT__='V70_5_SCENARIO_EDITOR_TEST_OK';})(window);\n";
vm.runInContext(__TEST_SRC__,ctx,{filename:'test_v705.js'});
