/**
 * Alchemy 2.0 Gameplay v30: завершает алхимию поверх alchemy_engine_v29.js.
 * Как работает: добавляет эффекты свойств, создание результата в инвентаре, эксперименты,
 * расход ингредиентов, риск провала, катализаторы и полноценную лабораторную панель.
 * Основные переменные: DNDAlchemy, currentCharacter/currentChar, alchemyState, profile/effects/product.
 */
(function(global){'use strict';
const A=global.DNDAlchemy;if(!A)return;
const EXTRA_TRIGGER={Vitality:'Invisibility',Volatility:'Hallucination',Recovery:'Necrotic',Stability:'Recovery',Hallucination:'Radiant',Hemorrhage:'Perception',Magic:'Radiant',Necrotic:'Magic',Fear:'Venom',Fire:'Acid',Antidote:'Stability',Perception:'Speed',Strength:'Mind',Radiant:'Fire',Acid:'Invisibility'};
const EFFECTS={
 Recovery:{label:'Восстановление',kind:'heal',formula:'1d4 + Potency/20'},Vitality:{label:'Жизненность',kind:'tempHP',formula:'временные HP = Potency/5'},Regeneration:{label:'Регенерация',kind:'regen',formula:'1d4 HP/ход'},
 Speed:{label:'Скорость',kind:'speed',formula:'+10 футов'},Dexterity:{label:'Ловкость',kind:'ability',formula:'преимущество на проверки Ловкости'},Strength:{label:'Сила',kind:'ability',formula:'преимущество на проверки Силы'},Constitution:{label:'Телосложение',kind:'ability',formula:'преимущество на проверки Телосложения'},Mind:{label:'Разум',kind:'ability',formula:'преимущество на проверки Интеллекта'},Perception:{label:'Восприятие',kind:'ability',formula:'преимущество на проверки Мудрости'},
 Venom:{label:'Яд',kind:'damage',damageType:'poison',formula:'1d6 + Potency/15'},Hemorrhage:{label:'Кровотечение',kind:'damage',damageType:'bleed',formula:'1d4/ход'},Weakness:{label:'Слабость',kind:'debuff',formula:'штраф к силовым атакам/проверкам'},Nausea:{label:'Тошнота',kind:'condition',condition:'poisoned',formula:'Poisoned'},Blindness:{label:'Слепота',kind:'condition',condition:'blinded',formula:'Blinded'},Fear:{label:'Страх',kind:'condition',condition:'frightened',formula:'Frightened'},Hallucination:{label:'Галлюцинация',kind:'condition',condition:'confused',formula:'дезориентация'},Sleep:{label:'Сон',kind:'condition',condition:'unconscious',formula:'Unconscious'},
 Acid:{label:'Кислота',kind:'damage',damageType:'acid',formula:'2d4 + Potency/10'},Fire:{label:'Огонь',kind:'damage',damageType:'fire',formula:'2d4 + Potency/10'},Cold:{label:'Холод',kind:'damage',damageType:'cold',formula:'2d4 + Potency/10'},Necrotic:{label:'Некротика',kind:'damage',damageType:'necrotic',formula:'2d4 + Potency/10'},Radiant:{label:'Сияние',kind:'damage',damageType:'radiant',formula:'2d4 + Potency/10'},
 Invisibility:{label:'Невидимость',kind:'condition',condition:'invisible',formula:'10 минут'},Breathing:{label:'Дыхание',kind:'utility',formula:'1 час'},Antidote:{label:'Антидот',kind:'cleanse',formula:'снимает яд'},Stability:{label:'Стабильность',kind:'stability',formula:'снижает риск'},Volatility:{label:'Нестабильность',kind:'volatile',formula:'ускоряет реакцию и риск'},Magic:{label:'Магия',kind:'amplify',formula:'+25% к силе'},Earth:{label:'Земля',kind:'resistance',formula:'устойчивость к сбиванию'},Petrification:{label:'Окаменение',kind:'condition',condition:'petrified',formula:'тяжёлое состояние'}
};
const hero=()=>global.currentChar||global.currentCharacter||null;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function state(){const h=hero();if(!h)return null;h.alchemyState=h.alchemyState||{discovered:{},experiments:0,discoveries:0,mastery:0,history:[],knownReactions:{}};return h.alchemyState;}
function save(){try{if(typeof autoSaveCurrentCharacter==='function')autoSaveCurrentCharacter();else if(typeof saveCharacter==='function')saveCharacter();}catch(e){}}
function prof(){const h=hero();if(!h)return false;const vals=[h.toolProficiencies,h.proficiencies,h.proficienciesTools,h.skills,h.tools];const t=vals.flatMap(x=>Array.isArray(x)?x:(x&&typeof x==='object'?Object.values(x):[])).join(' ').toLowerCase();return /alchemist|алхим|herbal|трав|chemist|poisoner|ядовит/.test(t);}
function discover(id,count=1){const s=state(),ing=A.ingredients.find(x=>x.id===id);if(!s||!ing)return[];s.discovered[id]=s.discovered[id]||[];const hidden=ing.properties.filter(x=>!s.discovered[id].includes(x));let got=hidden.slice(0,Math.max(1,count));if(!got.length&&ing.extra&&!s.discovered[id].includes(ing.extra))got=[ing.extra];s.discovered[id].push(...got);s.discoveries+=got.length;save();return got;}
function inspect(id){const s=state(),ing=A.ingredients.find(x=>x.id===id);if(!ing)return null;const known=s?.discovered[id]||[];return {id:ing.id,name:ing.name,properties:ing.properties.map(x=>known.includes(x)?x:'???'),extra:ing.extra?(known.includes(ing.extra)?ing.extra:'???'):null};}
function profile(ings,catalystId){const all=ings.flatMap(x=>x.properties),counts={};all.forEach(x=>counts[x]=(counts[x]||0)+1);const shared=Object.keys(counts).filter(x=>counts[x]>=2),synergies=[],conflicts=[];const key=(a,b)=>[a,b].sort().join('|');for(let i=0;i<all.length;i++)for(let j=i+1;j<all.length;j++){const k=key(all[i],all[j]);if(A.synergy.some(p=>key(p[0],p[1])===k)&&!synergies.includes(k))synergies.push(k);if(A.conflict.some(p=>key(p[0],p[1])===k)&&!conflicts.includes(k))conflicts.push(k);}const extras=[];ings.forEach(x=>{if(x.extra&&EXTRA_TRIGGER[x.extra]&&(shared.includes(EXTRA_TRIGGER[x.extra])||all.includes(EXTRA_TRIGGER[x.extra]))&&!extras.includes(x.extra))extras.push(x.extra);});let potency=Math.round(ings.reduce((n,x)=>n+x.potency,0)/ings.length),stability=Math.round(ings.reduce((n,x)=>n+x.stability,0)/ings.length),volatility=Math.round(ings.reduce((n,x)=>n+x.volatility,0)/ings.length),purity=Math.round(ings.reduce((n,x)=>n+x.purity,0)/ings.length);const c=A.catalysts.find(x=>x.id===catalystId);if(c){potency+=c.potency;stability+=c.stability;volatility+=c.volatility;purity+=c.purity;}potency=clamp(potency+synergies.length*8,1,100);stability=clamp(stability,1,100);volatility=clamp(volatility,1,100);purity=clamp(purity,1,100);const risk=clamp(Math.round((volatility+(100-stability)+conflicts.length*18-purity)/2),0,100);const active=[...new Set([...shared,...synergies.flatMap(x=>x.split('|')),...extras])];return {sharedProperties:shared,synergies,conflicts,extras,potency,stability,volatility,purity,risk,unstable:risk>=60,activeProperties:active,catalystId:catalystId||null};}
function effects(p){const mult=p.activeProperties.includes('Magic')?1.25:1;return p.activeProperties.map(x=>EFFECTS[x]?Object.assign({property:x},EFFECTS[x],{strength:Math.round(p.potency*mult)}):null).filter(Boolean);}
function kind(p){const a=p.activeProperties;if(a.some(x=>['Venom','Hemorrhage','Weakness','Nausea'].includes(x)))return'poison';if(a.some(x=>['Fire','Acid','Cold','Necrotic','Radiant'].includes(x)))return'bomb';if(a.some(x=>['Recovery','Vitality','Regeneration','Antidote'].includes(x)))return'potion';if(a.some(x=>['Invisibility','Speed','Breathing','Mind','Perception'].includes(x)))return'elixir';return'reagent';}
function name(p){const labels=effects(p).slice(0,2).map(x=>x.label).join(' + ');return(kind(p)==='poison'?'Алхимический яд':kind(p)==='bomb'?'Алхимическая бомба':kind(p)==='potion'?'Зелье':kind(p)==='elixir'?'Эликсир':'Алхимический реагент')+(labels?' — '+labels:'');}
function consume(ings){const h=hero();if(!h?.inventory)return true;const refs=[];for(const ing of ings){let found=null;for(const cat of ['materials','consumables','junk']){const arr=h.inventory[cat]||[];const idx=arr.findIndex(x=>x.alchemyId===ing.id||x.name===ing.name);if(idx>=0){found={cat,idx};break;}}if(!found)return false;refs.push(found);}refs.sort((a,b)=>b.idx-a.idx).forEach(r=>{const arr=h.inventory[r.cat];arr[r.idx].count=(arr[r.idx].count||1)-1;if(arr[r.idx].count<=0)arr.splice(r.idx,1);});return true;}
function addProduct(p){const h=hero();if(!h)return null;h.inventory=h.inventory||{weapons:[],armor:[],consumables:[],materials:[],junk:[]};h.inventory.consumables=h.inventory.consumables||[];const item={name:name(p),count:1,crafted:true,alchemyId:'alchemy_'+Date.now(),kind:kind(p),properties:p.activeProperties,effects:effects(p),potency:p.potency,stability:p.stability,volatility:p.volatility,purity:p.purity,risk:p.risk,unstable:p.unstable,catalyst:p.catalystId,description:'Динамический результат Alchemy 2.0. Эффект определяется свойствами смеси.'};const old=h.inventory.consumables.find(x=>x.name===item.name&&x.potency===item.potency&&x.risk===item.risk);if(old)old.count=(old.count||1)+1;else h.inventory.consumables.push(item);save();if(typeof renderInventory==='function')renderInventory();return item;}
function mix(ids,catalystId=null,opts={}){const s=state(),ings=ids.map(id=>A.ingredients.find(x=>x.id===id)).filter(Boolean);if(ings.length<2||ings.length>5)return{ok:false,error:'Нужно от 2 до 5 ингредиентов.'};if(!prof()&&!opts.ignoreProficiency)return{ok:false,error:'Нужно владение алхимическими инструментами, травничеством или отравительством.'};const p=profile(ings,catalystId);if(opts.consume!==false&&!consume(ings))return{ok:false,error:'В инвентаре не хватает выбранных ингредиентов.'};if(s)s.experiments++;const professionBonus=Math.max(0,Number(opts.professionBonus)||0);const chance=clamp(Math.round(p.risk*.55-p.purity*.12-p.stability*.08-professionBonus*3),0,65),roll=Math.floor(Math.random()*100)+1;if(!opts.safe&&roll<=chance){if(s)s.history.push({time:Date.now(),type:'failure',ingredients:ings.map(x=>x.id),risk:p.risk});save();return{ok:false,failure:true,error:'Реакция сорвалась: '+(p.conflicts.length?'конфликт свойств':'нестабильность смеси')+'.',risk:p.risk,roll,failChance:chance,sideEffects:p.conflicts};}p.effects=effects(p);p.kind=kind(p);p.name=name(p);const product=addProduct(p);if(s){s.mastery=(s.mastery||0)+1;s.knownReactions[ids.slice().sort().join('|')]=p.activeProperties;s.history.push({time:Date.now(),type:'success',name:p.name,ingredients:ids,risk:p.risk});}save();return Object.assign({ok:true,product,roll,failChance:chance},p);}
function experiment(ids){const s=state(),ings=ids.map(id=>A.ingredients.find(x=>x.id===id)).filter(Boolean);if(!s||!ings.length||ings.length>3)return{ok:false,error:'Для исследования выбери 1–3 ингредиента.'};if(!prof())return{ok:false,error:'Нужны алхимические инструменты или профильное владение.'};const target=ings[Math.floor(Math.random()*ings.length)],got=discover(target.id,1);if(got.length)return{ok:true,discovered:got,ingredient:target.name,message:'Новое свойство раскрыто.'};const p=profile(ings,null);if(Math.random()<.45){s.mastery=(s.mastery||0)+1;save();return{ok:true,discovered:[],ingredient:target.name,message:'Эксперимент дал сведения о совместимости свойств.',profile:p};}save();return{ok:false,failure:true,error:'Эксперимент не удался: образец испорчен.',ingredient:target.name};}
function useProduct(item){
 const h=hero();if(!h||!item||!item.effects)return{ok:false,error:'Это не алхимический предмет.'};
 let healed=0;h.alchemyBuffs=h.alchemyBuffs||{};
 for(const e of item.effects){const power=Math.max(1,Math.round(Number(item.potency||20)/20));
  if(e.kind==='heal'){const max=Number(h.hpMax??h.maxHitPoints??h.maxHp??h.hp?.max??0);const cur=Number(h.hpCurrent??h.hitPoints??h.hp?.current??0);healed=Math.max(0,Math.min(power+(Number(item.potency)||20)/20,max?max-cur:power));if('hpCurrent' in h)h.hpCurrent=cur+healed;else if('hitPoints' in h)h.hitPoints=cur+healed;else{h.hp=h.hp||{};h.hp.current=cur+healed;}}
  else if(e.kind==='tempHP'){h.hpTemp=Math.max(Number(h.hpTemp)||0,Math.round(Number(item.potency||20)/5));}
  else if(e.kind==='speed'){h.alchemyBuffs.speed=(h.alchemyBuffs.speed||0)+10;}
  else if(e.kind==='ability'){h.alchemyBuffs[e.property]=(h.alchemyBuffs[e.property]||0)+1;}
  else if(e.kind==='cleanse'){h.conditions=h.conditions||{};delete h.conditions.poisoned;delete h.conditions.Poisoned;}
  else if(e.kind==='condition'){h.conditions=h.conditions||{};h.conditions[e.condition]=true;}
  else if(e.kind==='resistance'){h.alchemyBuffs.earthResistance=true;}
 }
 if(item.count>1)item.count--;else{const arr=h.inventory?.consumables||[];const i=arr.indexOf(item);if(i>=0)arr.splice(i,1);}
 save();if(typeof renderInventory==='function')renderInventory();return{ok:true,healed,item};
}
function resultHTML(r){if(!r.ok)return `<div style="padding:8px;background:#321b1b;border:1px solid #7f3b3b;border-radius:6px;color:#ffb0aa"><b>${r.failure?'⚠️ Реакция сорвалась':'Ошибка'}</b><br>${r.error||''}${r.sideEffects?.length?'<br>Конфликты: '+r.sideEffects.join(', '):''}</div>`;const es=(r.effects||[]).map(x=>`${x.label} <small>(${x.formula})</small>`).join(', ');return `<div style="padding:8px;background:#20251f;border:1px solid #456;border-radius:6px"><b>🧪 ${r.name}</b><br>Общие: ${(r.sharedProperties||[]).join(', ')||'нет'}<br>Синергии: ${(r.synergies||[]).join(', ')||'нет'}<br>Конфликты: <span style="color:#ff8a80">${(r.conflicts||[]).join(', ')||'нет'}</span><br>Extra: ${(r.extras||[]).join(', ')||'нет'}<br>Эффекты: ${es||'нейтральный реагент'}<br><b>Potency ${r.potency} · Stability ${r.stability} · Volatility ${r.volatility} · Purity ${r.purity} · Риск ${r.risk}</b>${r.unstable?' ⚠️':''}</div>`;}
function render(){const c=document.getElementById('alchemyPanel'),s=state();if(!c||!s)return;c.innerHTML=`<div style="padding:10px;background:#171717;border:1px solid #4b3a20;border-radius:8px;margin-top:10px"><h3 style="margin:0 0 5px;color:#ffb74d">⚗️ Алхимическая лаборатория 2.0</h3><div style="font-size:.78em;color:#aaa;margin-bottom:7px">Исследуй → открывай свойства → смешивай 2–5 компонентов. Катализаторы меняют реакцию. Результаты создаются прямо в инвентаре.</div><div style="font-size:.78em;color:#d6c6a0;margin-bottom:7px">Открыто: ${s.discoveries||0} · Экспериментов: ${s.experiments||0} · Мастерство: ${s.mastery||0}</div><div id="alchemyIngredients" style="display:grid;grid-template-columns:1fr 1fr;gap:5px;max-height:320px;overflow:auto"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:7px"><select id="alchemyCat"><option value="">Без катализатора</option>${A.catalysts.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select><button class="btn-action" style="background:#6a1b9a" onclick="DNDAlchemy.uiMix()">⚗️ Сварить</button></div><button class="btn-action" style="width:100%;margin-top:6px;background:#455a64" onclick="DNDAlchemy.uiExperiment()">🔬 Исследовать выбранные</button><div id="alchemyResult" style="margin-top:8px"></div></div>`;const list=document.getElementById('alchemyIngredients');A.ingredients.forEach(x=>{const known=s.discovered[x.id]||[],b=document.createElement('label');b.style.cssText='display:block;padding:6px;background:#26221a;border:1px solid #4a3d28;border-radius:5px;font-size:.74em';b.innerHTML=`<input type="checkbox" value="${x.id}"> <b>${x.name}</b> <span style="color:#888">(${x.rarity})</span><br><small style="color:#aaa">${x.properties.map(p=>known.includes(p)?(A.properties[p]?.name||p):'???').join(' · ')}${x.extra?' · ✦ '+(known.includes(x.extra)?(A.properties[x.extra]?.name||x.extra):'???'):''}</small>`;b.querySelector('input').onchange=()=>{if(b.querySelector('input').checked&&known.length<4)discover(x.id,1);};b.ondblclick=()=>{discover(x.id,1);render();};list.appendChild(b);});}
function uiMix(){const ids=[...document.querySelectorAll('#alchemyIngredients input:checked')].map(x=>x.value),r=mix(ids,document.getElementById('alchemyCat')?.value||null);const e=document.getElementById('alchemyResult');if(e)e.innerHTML=resultHTML(r);if(r.ok)setTimeout(render,120);}
function uiExperiment(){const ids=[...document.querySelectorAll('#alchemyIngredients input:checked')].map(x=>x.value),r=experiment(ids),e=document.getElementById('alchemyResult');if(e)e.innerHTML=r.ok?`<div style="padding:8px;background:#1d2a1f;border:1px solid #4b7052;border-radius:6px">🔬 ${r.message}<br>${r.discovered?.length?'Открыто: '+r.discovered.join(', '):''}</div>`:resultHTML(r);if(r.ok)setTimeout(render,120);}
A.discover=discover;A.inspect=inspect;A.mix=mix;A.experiment=experiment;A.reactionProfile=profile;A.effectList=effects;A.render=render;A.uiMix=uiMix;A.uiExperiment=uiExperiment;A.effects=EFFECTS;A.useProduct=useProduct;global.dndUseAlchemyProduct=useProduct;global.dndRenderAlchemy=render;
document.addEventListener('DOMContentLoaded',()=>setTimeout(render,150));
})(window);
