window.defaultArmors = [
  // --- 🪖 ГОЛОВНЫЕ УБОРЫ И ШЛЕМЫ (Helms & Headwear) ---
  {
    id: 'h_leather_cap',
    name: 'Кожаный подшлемник',
    category: 'Шлем',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Без бонуса к КД',
    weight: '2 фунта',
    cost: '2 зм',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🪖 Простой стеганый чепец, смягчающий удары по голове.'
  },
  {
    id: 'h_great_helm',
    name: 'Тяжелый закрытый шлем',
    category: 'Шлем',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Защита от критов в голову (опционально)',
    weight: '6 фунтов',
    cost: '15 зм',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🪖 Полное стальное забрало. Дает защиту, но немного сужает обзор.'
  },
  {
    id: 'h_cap_of_waterbreathing',
    name: 'Шапка подводного дыхания',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Дыхание под водой',
    weight: '2 фунта',
    cost: 'Необычное',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🪖 Позволяет комфортно дышать под водой. Идеально для абордажей затонувших судов.'
  },
  {
    id: 'h_helm_of_telepathy',
    name: 'Шлем телепатии',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Заклинание Общение с разумом',
    weight: '3 фунта',
    cost: 'Редкое',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 1, wis: 0, cha: 0 },
    description: '🪖 Позволяет читать мысли окружающих и транслировать им свои приказы.'
  },
  {
    id: 'h_helm_of_brilliance',
    name: 'Шлем блеска',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Свечение, сопротивление огню, огненные заклинания',
    weight: '3 фунта',
    cost: 'Очень редкое',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🪖 Украшенный драгоценными камнями шлем, испускающий яркий свет и метающий сферы огня.'
  },
  {
    id: 'h_helm_of_comprehending_languages',
    name: 'Шлем понимания языков',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Понимание языков',
    weight: '3 фунта',
    cost: 'Необычное',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🪖 Позволяет понимать любые устные и письменные языки.'
  },

  // --- 👕 ЛЕГКИЕ ДОСПЕХИ (Armor - Body) ---
  {
    id: 'a_padded',
    name: 'Стёганый доспех',
    category: 'Лёгкий доспех',
    acBase: 11,
    minStr: 0,
    proficiencyType: 'light',
    acFormula: '11 + мод. Ловкости (Треб. навык легких доспехов)',
    weight: '8 фунтов',
    cost: '5 зм',
    stealthDisadvantage: true,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Состоит из слоев простеганной ткани. Создает помеху при проверках Скрытности.'
  },
  {
    id: 'a_leather',
    name: 'Кожаный доспех',
    category: 'Лёгкий доспех',
    acBase: 11,
    minStr: 0,
    proficiencyType: 'light',
    acFormula: '11 + мод. Ловкости (Треб. навык легких доспехов)',
    weight: '10 фунтов',
    cost: '10 зм',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Легкий и гибкий доспех из выдубленной кожи, не сковывающий движений.'
  },
  {
    id: 'a_studded_leather',
    name: 'Клепаный кожаный доспех',
    category: 'Лёгкий доспех',
    acBase: 12,
    minStr: 0,
    proficiencyType: 'light',
    acFormula: '12 + мод. Ловкости (Треб. навык легких доспехов)',
    weight: '13 фунтов',
    cost: '45 зм',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Усилен рядами металлических заклёпок и блях.'
  },
  {
    id: 'a_buccaneer_vest',
    name: 'Жилет головореза',
    category: 'Лёгкий доспех (Хоумбрю)',
    acBase: 12,
    minStr: 0,
    proficiencyType: 'light',
    acFormula: '12 + мод. Ловкости (Треб. навык легких доспехов)',
    weight: '8 фунтов',
    cost: '35 зм',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 1, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Легкий жилет для абордажных вылазок, дающий свободу маневра и ловкость.'
  },

  // --- 👕 СРЕДНИЕ ДОСПЕХИ (Armor - Body) ---
  {
    id: 'a_hide',
    name: 'Шкурный доспех',
    category: 'Средний доспех',
    acBase: 12,
    minStr: 0,
    proficiencyType: 'medium',
    acFormula: '12 + мод. Ловкости (макс. +2, треб. навык средних)',
    weight: '12 фунтов',
    cost: '10 зм',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Грубый доспех из толстых шкур диких зверей.'
  },
  {
    id: 'a_chain_shirt',
    name: 'Кольчужная рубаха',
    category: 'Средний доспех',
    acBase: 13,
    minStr: 0,
    proficiencyType: 'medium',
    acFormula: '13 + мод. Ловкости (макс. +2, треб. навык средних)',
    weight: '20 фунтов',
    cost: '50 зм',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Сплетенные из металлических колец ряды поверх одежды.'
  },
  {
    id: 'a_scale_mail',
    name: 'Чешуйчатый доспех',
    category: 'Средний доспех',
    acBase: 14,
    minStr: 0,
    proficiencyType: 'medium',
    acFormula: '14 + мод. Ловкости (макс. +2, треб. навык средних)',
    weight: '45 фунтов',
    cost: '50 зм',
    stealthDisadvantage: true,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Кожаная куртка, покрытая чешуйчатыми металлическими пластинками.'
  },
  {
    id: 'a_breastplate',
    name: 'Кираса',
    category: 'Средний доспех',
    acBase: 14,
    minStr: 0,
    proficiencyType: 'medium',
    acFormula: '14 + мод. Ловкости (макс. +2, треб. навык средних)',
    weight: '20 фунтов',
    cost: '400 зм',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Жесткая нагрудная пластина из металла с гибкими элементами.'
  },
  {
    id: 'a_half_plate',
    name: 'Полулаты',
    category: 'Средний доспех',
    acBase: 15,
    minStr: 0,
    proficiencyType: 'medium',
    acFormula: '15 + мод. Ловкости (макс. +2, треб. навык средних)',
    weight: '40 фунтов',
    cost: '750 зм',
    stealthDisadvantage: true,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Почти полноценные латы, оставляющие суставы свободными.'
  },
  {
    id: 'a_spiked_armor',
    name: 'Шипастый доспех',
    category: 'Средний доспех (SCAG)',
    acBase: 14,
    minStr: 0,
    proficiencyType: 'medium',
    acFormula: '14 + мод. Ловкости (макс. +2, треб. навык средних)',
    weight: '45 фунтов',
    cost: '75 зм',
    stealthDisadvantage: true,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Модифицированный чешуйчатый доспех с металлическими шипами.'
  },
  {
    id: 'a_captain_coat',
    name: 'Капитанский камзол из кожи кракена',
    category: 'Средний доспех (Хоумбрю)',
    acBase: 14,
    minStr: 0,
    proficiencyType: 'medium',
    acFormula: '14 + мод. Ловкости (макс. +2, треб. навык средних)',
    weight: '15 фунтов',
    cost: '600 зм',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 1, con: 0, int: 0, wis: 0, cha: 2 },
    description: '👕 Роскошный кожаный сюртук морского волка, повышающий харизму.'
  },

  // --- 👕 ТЯЖЕЛЫЕ ДОСПЕХИ (Armor - Body) ---
  {
    id: 'a_ring_mail',
    name: 'Колечный доспех',
    category: 'Тяжелый доспех',
    acBase: 14,
    minStr: 0,
    proficiencyType: 'heavy',
    acFormula: 'Фиксированный КД 14 (Треб. навык тяжелых доспехов)',
    weight: '40 фунтов',
    cost: '30 зм',
    stealthDisadvantage: true,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Кожаная основа с нашитыми тяжелыми кольцами.'
  },
  {
    id: 'a_chain_mail',
    name: 'Кольчуга',
    category: 'Тяжелый доспех',
    acBase: 16,
    minStr: 13,
    proficiencyType: 'heavy',
    acFormula: 'Фиксированный КД 16 (Треб. Сила 13 + навык тяжелых)',
    weight: '55 фунтов',
    cost: '75 зм',
    stealthDisadvantage: true,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Полноценная сеть из металлических колец. Требует Силу 13 и навык тяжелых доспехов (иначе штрафы и скорость -10 фт).'
  },
  {
    id: 'a_splint',
    name: 'Латы из полос (Шинный доспех)',
    category: 'Тяжелый доспех',
    acBase: 17,
    minStr: 15,
    proficiencyType: 'heavy',
    acFormula: 'Фиксированный КД 17 (Треб. Сила 15 + навык тяжелых)',
    weight: '60 фунтов',
    cost: '200 зм',
    stealthDisadvantage: true,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Вертикальные полосы металла. Требует Силу 15 и навык тяжелых доспехов (иначе штрафы и скорость -10 фт).'
  },
  {
    id: 'a_plate',
    name: 'Полные латы',
    category: 'Тяжелый доспех',
    acBase: 18,
    minStr: 15,
    proficiencyType: 'heavy',
    acFormula: 'Фиксированный КД 18 (Треб. Сила 15 + навык тяжелых)',
    weight: '65 фунтов',
    cost: '1500 зм',
    stealthDisadvantage: true,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Вершина кузнечного искусства. Требует Силу 15 и навык тяжелых доспехов (иначе штрафы и скорость -10 фт).'
  },
  {
    id: 'a_mithral_plate',
    name: 'Мифриловые латы',
    category: 'Магический доспех (DMG)',
    acBase: 18,
    minStr: 0,
    proficiencyType: 'heavy',
    acFormula: 'Фиксированный КД 18 (Треб. навык тяжелых доспехов)',
    weight: '32.5 фунта',
    cost: 'Очень редкое',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Невесомые пластины из мифрила. Снимают требования по Силе и штраф скрытности, но требуют навык тяжелых доспехов.'
  },
  {
    id: 'a_adamantine_plate',
    name: 'Адамантитовые латы',
    category: 'Магический доспех (DMG)',
    acBase: 18,
    minStr: 15,
    proficiencyType: 'heavy',
    acFormula: 'Фиксированный КД 18 (Защита от критов, треб. Сила 15 + навык)',
    weight: '65 фунтов',
    cost: 'Очень редкое',
    stealthDisadvantage: true,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👕 Сверхпрочный сплав нивелирует критический урон. Требуется Сила 15 и навык тяжелых доспехов.'
  },

  // --- 🛡️ ЩИТЫ (Shields - Off-Hand) ---
  {
    id: 'a_shield',
    name: 'Щит',
    category: 'Щит',
    acBase: 2,
    minStr: 0,
    proficiencyType: 'shield',
    acFormula: '+2 к КД (Требуется владение щитами)',
    weight: '6 фунтов',
    cost: '10 зм',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🛡️ Стандартный деревянный или металлический щит. Без навыка вы не получаете бонус к КД.'
  },
  {
    id: 'a_sentinel_shield',
    name: 'Дозорный щит',
    category: 'Магический щит (DMG)',
    acBase: 2,
    minStr: 0,
    proficiencyType: 'shield',
    acFormula: '+2 к КД (Бонус к Инициативе/Восприятию, треб. навык щитов)',
    weight: '6 фунтов',
    cost: 'Необычное',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 1, cha: 0 },
    description: '🛡️ Наделяет владельца бдительностью (требует навык владения щитами).'
  },
  {
    id: 'a_boarding_buckler',
    name: 'Абордажная баклер-тарча',
    category: 'Щит (Хоумбрю)',
    acBase: 1,
    minStr: 0,
    proficiencyType: 'shield',
    acFormula: '+1 к КД (Требуется владение щитами)',
    weight: '3 фунта',
    cost: '20 зм',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🛡️ Маленький стальной кулачный щит для тесных трюмов.'
  },
  {
    id: 'a_spellguard_shield',
    name: 'Щит стража заклинаний',
    category: 'Магический щит (DMG)',
    acBase: 2,
    minStr: 0,
    proficiencyType: 'shield',
    acFormula: '+2 к КД (Преимущество против заклинаний, треб. навык щитов)',
    weight: '6 фунтов',
    cost: 'Очень редкое',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🛡️ Защита от магии. Без навыка владения щитами бонус к КД не применяется.'
  },

  // --- 🧤 ПЕРЧАТКИ И РУКАВИЦЫ (Gloves & Gauntlets) ---
  {
    id: 'g_gloves_of_thievery',
    name: 'Перчатки воровства',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Преимущество на Ловкость рук и взлом',
    weight: '0 фунтов',
    cost: 'Редкое',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 1, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🧤 Невидимые шелковые перчатки для взлома замков и карманных краж.'
  },
  {
    id: 'g_gauntlets_of_ogre_power',
    name: 'Рукавицы силы огра',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Значение Силы становится равным 19',
    weight: '2 фунта',
    cost: 'Необычное',
    stealthDisadvantage: false,
    bonuses: { str: 4, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🧤 Наделяют владельца титанической силой (Сила устанавливается на 19).'
  },
  {
    id: 'g_gloves_of_swimming_and_climbing',
    name: 'Перчатки плавания и лазания',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Скорость плавания/лазания равна обычной',
    weight: '2 фунта',
    cost: 'Необычное',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🧤 Облегчают карабканье по вантам и плавание в бушующем море.'
  },
  {
    id: 'g_bracers_of_defense',
    name: 'Наручи защиты',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: '+2 к Классу Защиты (если нет доспехов и щита)',
    weight: '1 фунт',
    cost: 'Редкое',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🧤 Зачарованные наручи, создающие силовое поле вокруг незащищенного бойца.'
  },

  // --- 🥾 ОБУВЬ И САПОГИ (Boots & Footwear) ---
  {
    id: 'b_boots_of_elvenkind',
    name: 'Эльфийские сапоги',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Бесшумная ходьба (Преимущество на Скрытность)',
    weight: '0 фунтов',
    cost: 'Необычное',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🥾 Шаги владельца становятся абсолютно беззвучными.'
  },
  {
    id: 'b_boots_of_striding_and_springing',
    name: 'Сапоги прыжков и ходьбы',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Увеличение прыжка втрое, скорость не падает от веса',
    weight: '2 фунта',
    cost: 'Необычное',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🥾 Позволяют легко преодолевать преграды и прыгать на огромные расстояния.'
  },
  {
    id: 'b_winged_boots',
    name: 'Окрыленные сапоги',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Скорость полета равна наземной',
    weight: '0 фунтов',
    cost: 'Редкое',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🥾 Позволяют взмывать в воздух и парить над палубой корабля.'
  },
  {
    id: 'b_boots_of_levitation',
    name: 'Сапоги левитации',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Заклинание Левитация по воле',
    weight: '2 фунта',
    cost: 'Редкое',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🥾 Позволяют вертикально подниматься и опускаться в воздухе.'
  },

  // --- 👖 ШТАНЫ И ПОЯСА (Pants & Belts) ---
  {
    id: 'pt_sailor_trousers',
    name: 'Прочные парусиновые штаны',
    category: 'Одежда (Обиход)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Защита от ожогов и соли',
    weight: '3 фунта',
    cost: '1 зм',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👖 Плотные матросские штаны с усиленными коленями для лазания по мачтам.'
  },
  {
    id: 'pt_belt_of_hill_giant_strength',
    name: 'Пояс холмового великана',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Значение Силы становится равным 21',
    weight: '2 фунта',
    cost: 'Редкое',
    stealthDisadvantage: false,
    bonuses: { str: 5, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👖 Широкий ремень из шкуры гиганта, придающий невероятную мощь (Сила устанавливается на 21).'
  },
  {
    id: 'pt_belt_of_fire_giant_strength',
    name: 'Пояс огненного великана',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Значение Силы становится равным 25',
    weight: '2 фунта',
    cost: 'Очень редкое',
    stealthDisadvantage: false,
    bonuses: { str: 9, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '👖 Легендарный пояс правителей пламени, поднимающий силу до 25.'
  },

  // --- 💍 ЮВЕЛИРНЫЕ ИЗДЕЛИЯ: КОЛЬЦА И АМУЛЕТЫ (Jewelry - Rings & Amulets) ---
  {
    id: 'j_ring_of_protection',
    name: 'Кольцо защиты',
    category: 'Кольцо (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: '+1 к Классу Защиты и спасброскам',
    weight: '0 фунтов',
    cost: 'Редкое',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '💍 Изящное серебряное кольцо, добавляющее +1 к КД и ко всем спасброскам владельца.'
  },
  {
    id: 'j_ring_of_evasion',
    name: 'Кольцо уклонения',
    category: 'Кольцо (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Игнорирование урона от заклинаний по Ловкости',
    weight: '0 фунтов',
    cost: 'Редкое',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '💍 Позволяет силой воли избежать взрывной волны или дыхания дракона.'
  },
  {
    id: 'j_ring_of_free_action',
    name: 'Кольцо свободных действий',
    category: 'Кольцо (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Иммунитет к опутыванию и параличу',
    weight: '0 фунтов',
    cost: 'Редкое',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '💍 Скорость передвижения не падает в трудных условиях и под водой, игнорирует паралич.'
  },
  {
    id: 'j_amulet_of_health',
    name: 'Амулет здоровья',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Значение Выносливости становится равным 19',
    weight: '1 фунт',
    cost: 'Редкое',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 4, int: 0, wis: 0, cha: 0 },
    description: '📿 Массивный талисман на толстой цепи, устанавливающий Выносливость в 19.'
  },
  {
    id: 'j_cloak_of_protection',
    name: 'Плащ защиты',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: '+1 к Классу Защиты и спасброскам',
    weight: '3 фунта',
    cost: 'Необычное',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '🧥 Зачарованная накидка, добавляющая +1 к КД и ко всем спасброскам.'
  },
  {
    id: 'j_brooch_of_shielding',
    name: 'Брошь защиты',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Иммунитет к урону силой (Magic Missile)',
    weight: '0 фунтов',
    cost: 'Необычное',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '📿 Поглощает любые магические стрелы, полностью защищая от этого типа урона.'
  },
  {
    id: 'j_periapt_of_wound_closure',
    name: 'Амулет заживления ран',
    category: 'Чудесный предмет (DMG)',
    acBase: 0,
    minStr: 0,
    proficiencyType: 'none',
    acFormula: 'Стабильность при смерти, удвоение хитов от костей исцеления',
    weight: '0 фунтов',
    cost: 'Необычное',
    stealthDisadvantage: false,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: '📿 Автоматически стабилизирует персонажа при смерти и ускоряет регенерацию на отдыхе.'
  }
];

window.defaultArmors = defaultArmors;
