/**
 * bestiary_catalog_v56_2.js
 * ------------------------------------------------------------------
 * WHAT THIS FILE IS:
 * V56.2 is the large Monsters of the Multiverse catalogue layer. It
 * adds a broad set of creature profiles using public creature names
 * and original app-native mechanics; it does NOT reproduce published
 * statblocks or text. The file is an extension of Bestiary 2.0, not a
 * second monster engine.
 *
 * HOW IT WORKS:
 * - sourcePack=motm marks the catalogue family for future DLC toggles;
 * - profiles are generated deterministically from creature archetype;
 * - combat uses the existing monster engine through ordinary actions;
 * - harvest creates stable material IDs and registers them in the
 *   existing crafting material catalog;
 * - existing creatures are skipped, so V56/V56.1 entries are preserved.
 * IMPORTANT APIS: DND_BESTIARY_V56_2, getCreature(), listBySource(),
 * listByFamily(), summary(), register().
 * ------------------------------------------------------------------
 */
(function(global){'use strict';
var base=global.DNDExpandedBestiary, monsters=global.DNDMonsters, loot=global.DNDMonsterLoot;
var craft=global.DND_CRAFTING_V31;
if(!base||!monsters)return;
function clone(v){return JSON.parse(JSON.stringify(v));}
function mod(n){return Math.floor((n-10)/2);}
var NAMES = [
'Abishai','Black Abishai','Blue Abishai','Green Abishai','Red Abishai','White Abishai','Alhoon','Alkilith','Allip','Amnizu','Annis Hag','Archdruid','Archer','Armanite','Astral Dreadnought',
'Babau','Bael','Balhannoth','Banderhobb','Baphomet','Bard','Barghest','Berbalang','Bheur Hag','Blackguard','Bodak','Boggle','Boneclaw','Bulezau',
'Cadaver Collector','Canoloth','Catoblepas','Aurochs','Deep Rothe','Ox','Stench Kow','Cave Fisher','Champion','Chitine','Choker','Choldrith','Clockwork Bronze Scout','Clockwork Iron Cobra','Clockwork Oaken Bolter','Clockwork Stone Defender','Cloud Giant Smiling One','Corpse Flower','Cranium Rat','Swarm of Cranium Rats',
'Darkling','Darkling Elder','Death Kiss','Deathlock','Deathlock Mastermind','Deathlock Wight','Deep Scion','Demogorgon','Derro','Derro Savant','Devourer','Dhergoloth','Brontosaurus','Deinonychus','Dimetrodon','Hadrosaurus','Quetzalcoatlus','Stegosaurus','Velociraptor','Dolphin','Dolphin Delighter','Draegloth','Drow Arachnomancer','Drow Favored Consort','Drow House Captain','Drow Inquisitor','Drow Matron Mother','Drow Shadowblade','Duergar Despot','Duergar Kavalrachni','Duergar Mind Master','Duergar Soulblade','Duergar Stone Guard','Duergar Warlord','Duergar Xarrorn','Duergar Hammerer','Duergar Screamer','Dybbuk',
'Eidolon','Autumn Eladrin','Spring Eladrin','Summer Eladrin','Winter Eladrin','Elder Brain','Elder Tempest','Air Elemental Myrmidon','Earth Elemental Myrmidon','Fire Elemental Myrmidon','Water Elemental Myrmidon',
'Fire Giant Dreadnought','Firenewt Warlock of Imix','Firenewt Warrior','Flail Snail','Flind','Fraz-Urb’luu','Froghemoth','Frost Giant Everlasting One','Frost Salamander',
'Gauth','Gazer','Geryon','Giant Strider','Giff','Girallon','Githyanki Gish','Githyanki Kith’rak','Githyanki Supreme Commander','Githzerai Anarch','Githzerai Enlightened','Gnoll Flesh Gnawer','Gnoll Hunter','Gnoll Witherling','Gray Render','Graz’zt','Grung','Grung Elite Warrior','Grung Wildling','Guard Drake',
'Hellfire Engine','Hobgoblin Devastator','Hobgoblin Iron Shadow','Howler','Hutijin','Hydroloth','Juiblex','Ki-rin','Kobold Dragonshield','Kobold Inventor','Kobold Scale Sorcerer','Korred','Kraken Priest','Young Kruthik','Adult Kruthik','Kruthik Hive Lord',
'Leucrotta','Leviathan','Martial Arts Adept','Marut','Master Thief','Maurezhi','Maw Demon','Meazel','Meenlock','Merregon','Merrenoloth','Mindwitness','Moloch','Molydeus','Morkoth','Mouth of Grolantor',
'Nabassu','Nagpa','Narzugon','Neogi Hatchling','Neogi Adult','Neogi Master','Neothelid','Nightwalker','Nilbog','Nupperibo','Oblex Spawn','Adult Oblex','Elder Oblex','Ogre Battering Ram','Ogre Bolt Launcher','Ogre Chain Brute','Ogre Howdah','Oinoloth','Orcus','Orthon',
'Phoenix','Quickling','Redcap','Retriever','Rutterkin','Sea Spawn','Shadar-Kai Gloom Weaver','Shadar-Kai Shadow Dancer','Shadar-Kai Soul Monger','Shadow Mastiff','Shadow Mastiff Alpha','Shoosuva','Sibriex','Skulk','Skull Lord','Slithering Tracker','Angry Sorrowsworn','Hungry Sorrowsworn','Lonely Sorrowsworn','Lost Sorrowsworn','Wretched Sorrowsworn','Spawn of Kyuss','Star Spawn Grue','Star Spawn Hulk','Star Spawn Larva Mage','Star Spawn Mangler','Star Spawn Seer','Female Steeder','Male Steeder','Steel Predator','Stone Cursed','Stone Giant Dreamwalker','Storm Giant Quintessent','Swarm of Rot Grubs','Swashbuckler','Sword Wraith Commander','Sword Wraith Warrior',
'Tanarukk','Titivilus','Tlincalli','Tortle Druid','Trapper','Dire Troll','Rot Troll','Spirit Troll','Venom Troll','Ulitharid','Vampiric Mist','Vargouille','Vegepygmy','Vegepygmy Chief','Thorny Vegepygmy','War Priest','Warlock of the Archfey','Warlock of the Fiend','Warlock of the Great Old One','Warlord','Wastrilith','Apprentice Wizard','Abjurer Wizard','Conjurer Wizard','Diviner Wizard','Enchanter Wizard','Evoker Wizard','Illusionist Wizard','Necromancer Wizard','Transmuter Wizard','Wood Woad','Xvart','Xvart Warlock of Raxivort','Yagnoloth','Yeenoghu','Yeth Hound','Yuan-ti Anathema','Yuan-ti Broodguard','Yuan-ti Mind Whisperer','Yuan-ti Nightmare Speaker','Yuan-ti Pit Master','Zaratan','Zariel','Zuggtmoy'
];
var FAMILY_NAMES={aberration:'Аберрации',humanoid:'Гуманоиды',monstrosity:'Чудовища',fey:'Феи',magical_beast:'Магические звери',construct:'Конструкты',fiend:'Исчадия',elemental:'Элементали',dragon:'Драконы',undead:'Нежить',plant:'Растения',celestial:'Небожители'};
var SOURCE='motm';
function family(name){var s=name.toLowerCase(); if(/zombie|death|bone|wraith|undead|corpse|skull|vampir|spawn of kyuss|allip|bodak|nightwalker|vargouille|mist|dybbuk|sorrowsworn|eidolon|deathlock|skeleton/.test(s))return'undead'; if(/demon|devil|fiend|abishai|bael|baphomet|demogorgon|graz|juiblex|orcus|zariel|yeeno|zuggtmoy|narzugon|hellfire|merregon|nupperibo|orthon|moloch|titivilus|bulezau|babau|armanite|rutterkin|maurezhi|sibriex|yagnoloth/.test(s))return'fiend'; if(/wizard|warlock|archdruid|archer|bard|blackguard|champion|master thief|warlord|priest|adept|giff|gith|drow|duergar|derro|grung|kobold|hobgoblin|gnoll|tortle|xvart|yuan-ti|shadar-kai|darkling|firenewt|neogi|meazel|skulk|swashbuckler|troll|ogre/.test(s))return'humanoid'; if(/elemental|myrmidon|mephit|tempest|leviathan|wastrilith|hydroloth/.test(s))return'elemental'; if(/golem|clockwork|construct|marut|steel predator|hellfire engine|cadaver collector|retriever/.test(s))return'construct'; if(/plant|vegepygmy|wood woad|corpse flower/.test(s))return'plant'; if(/eladrin|fey|quickling|redcap|korred|boggle|hag|meenlock|barghest|yeth hound/.test(s))return'fey'; if(/ki-rin|zariel/.test(s))return'celestial'; if(/dragon|drake|abishai/.test(s))return'dragon'; if(/phoenix|gith|beholder|mindwitness|neothelid|ulitharid|brain|alkilith|allip|gazer|death kiss|sphinx|astral dreadnought|star spawn|oblex|balhannoth|banderhobb|choker|chitine|choldrith|cave fisher|froghemoth|kruthik|morkoth|sibriex/.test(s))return'aberration'; return'monstrosity';}
function role(name){var s=name.toLowerCase(); if(/wizard|warlock|archdruid|priest|sorcerer|brain|beholder|gazer|sphinx|hag|caster|se er|seer|controller/.test(s))return'controller'; if(/archer|ranged|launcher|gish|mind master|shadowblade|swashbuckler/.test(s))return'ranged'; if(/thief|quickling|scion|shadow|skulk|steeder|boggle|assassin|tracker|vampiric mist/.test(s))return'skirmisher'; if(/giant|troll|ogre|brute|dreadnought|render|golem|marut|predator|warlord|champion|guard|despot|wight|boneclaw/.test(s))return'bruiser'; if(/priest|captain|guardian|defender|sentinel|wraith/.test(s))return'guardian'; if(/druid|archdruid|plant|wood woad|vegepygmy/.test(s))return'controller'; if(/dragon|demon|devil|phoenix|leviathan|kraken|hydra|remorhaz/.test(s))return'bruiser'; return'hunter';}
function crFor(i,name){var s=name.toLowerCase(); if(/astral dreadnought|demogorgon|baphomet|fraz|geryon|grazz|juiblex|orcus|zariel|zuggtmoy|zaratan|yeeno|molydeus/.test(s))return 20; if(/elder brain|marut|nightwalker|sibriex|steel predator|morkoth|phoenix|leviathan|amni|amnis/.test(s))return 16; if(/dreadnought|archon|warlord|troll|giant|dragon|golem|retriever|oblex|hydroloth|neothelid/.test(s))return 10+(i%8); return 1+(i%12);}
function habitat(name){var s=name.toLowerCase(); if(/underdark|drow|duergar|derro|choker|neothelid|mindwitness|meazel|meenlock|skulk|oblex|kruthik|gith/.test(s))return['underdark','caves']; if(/desert|sphinx|tlincalli|nagpa|baphomet/.test(s))return['desert','ruins']; if(/ocean|sea|kraken|leviathan|dolphin|wastrilith|hydroloth|scion/.test(s))return['coast','underwater']; if(/forest|wood|fey|redcap|korred|vegepygmy|hag|satyr/.test(s))return['forest','feywild']; if(/grave|death|wraith|vampir|undead|corpse|bone|nightwalker/.test(s))return['graveyard','ruins']; if(/giant|mountain|gith|eagle|tempest|elemental/.test(s))return['mountains','hills']; return['ruins','wilderness'];}
function material(name,fam){var s=name.toLowerCase(); var tag=fam==='construct'?'metal':fam==='plant'?'fiber':fam==='undead'?'bone':fam==='elemental'?'essence':fam==='fiend'?'essence':fam==='dragon'?'scale':/giant|troll|ogre|beast|hybrid/.test(s)?'hide':'trophy'; var clean=name.toLowerCase().replace(/[^a-z0-9]+/g,'_'); return {name:name+' harvest',category:'materials',count:[1,3],guaranteed:true,tags:[tag,fam],skill:fam==='construct'?'arcana':'survival',dc:10,craftMaterialId:'v56_2_'+clean,tool:fam==='construct'?'p_tool_smith':fam==='plant'?'p_tool_alchemist':fam==='elemental'||fam==='fiend'?'p_tool_alchemist':'p_tool_leatherworker'};}
function profile(name,i){var fam=family(name),r=role(name),cr=crFor(i,name),xp=Math.max(25,cr*cr*50),ac=11+Math.min(8,Math.floor(cr/2)),hp=10+cr*10+(i%7)*3,spd=r==='skirmisher'?40:r==='bruiser'?30:30,dex=r==='skirmisher'||r==='ranged'?16:12,str=r==='bruiser'?18:14,con=14+Math.min(5,Math.floor(cr/5)),int=r==='controller'?16:8,wis=12,cha=10; var atkBonus=3+Math.floor(cr/2),damage=cr>=10?'3d8+6':cr>=5?'2d8+4':cr>=2?'2d6+3':'1d8+2'; var acts=[{name:'Signature Attack',kind:'attack',bonus:atkBonus,damage:damage,damageType:fam==='elemental'?'energy':fam==='undead'?'necrotic':'physical'}]; if(r==='controller')acts.push({name:'Control Pulse',kind:'utility',description:'Original app-native control action: imposes a short movement or targeting complication.'}); if(r==='ranged')acts.push({name:'Ranged Volley',kind:'attack',bonus:atkBonus,damage:'1d8+'+(2+Math.floor(cr/3)),damageType:'physical'}); if(r==='skirmisher')acts.push({name:'Disengage Step',kind:'utility',description:'Original mobility action; favors repositioning before the next attack.'}); if(r==='bruiser')acts.push({name:'Heavy Assault',kind:'attack',bonus:atkBonus,damage:damage,damageType:'physical'}); var h=material(name,fam); return {name:name,familyId:fam,cr:String(cr),xp:xp,ac:ac,hp:hp,maxHp:hp,initiative:mod(dex),speed:spd,abilities:{str:str,dex:dex,con:con,int:int,wis:wis,cha:cha},actions:acts,role:r,habitats:habitat(name),sourceType:'official-name-catalog / authorial-mechanics',sourcePack:SOURCE,sourceLabel:'Mordenkainen Presents: Monsters of the Multiverse',bestiaryVersion:'2.0.2',loot:{pockets:{rolls:0,table:[]},harvest:[h]},ecology:{habitats:habitat(name),social:/swarm|pack|gnoll|gith|drow|duergar|hobgoblin|orc|derro/.test(name.toLowerCase())?'group':'variable',activity:/undead|night|dark|shadow/.test(name.toLowerCase())?'nocturnal':'diurnal',diet:fam==='plant'?'photosynthetic':'variable',role:r}};}
var CATALOG={}; NAMES.forEach(function(n,i){if(!base.catalog[n])CATALOG[n]=profile(n,i);});
function register(){Object.keys(CATALOG).forEach(function(n){var c=CATALOG[n];base.families[c.familyId]=base.families[c.familyId]||{id:c.familyId,name:FAMILY_NAMES[c.familyId]||c.familyId,category:c.familyId,habitats:c.habitats,variantHooks:['source','regional']};c.family=FAMILY_NAMES[c.familyId]||c.familyId;base.catalog[n]=clone(c);if(base.familyByCreature)base.familyByCreature[n]=c.familyId;monsters.catalog[n]=clone(c);if(loot&&loot.catalog)loot.catalog[n]=clone(c.loot);var h=c.loot.harvest[0];if(craft&&h&&h.craftMaterialId&&Array.isArray(craft.MATERIALS)&&!craft.MATERIALS.some(function(m){return m.id===h.craftMaterialId;}))craft.MATERIALS.push({id:h.craftMaterialId,name:h.name,cat:'monster_harvest',rarity:'uncommon',price:8,weight:.1,roles:['harvest','crafting'],tags:h.tags,source:'bestiary_v56_2'});});}
function getCreature(n){return CATALOG[n]?clone(CATALOG[n]):(base.catalog[n]?clone(base.catalog[n]):null);} function listBySource(s){return Object.keys(CATALOG).filter(function(n){return CATALOG[n].sourcePack===s;}).map(getCreature);} function listByFamily(f){return Object.keys(CATALOG).filter(function(n){return CATALOG[n].familyId===f;}).map(getCreature);} function summary(){var byFamily={};Object.keys(CATALOG).forEach(function(n){var f=CATALOG[n].familyId;byFamily[f]=(byFamily[f]||0)+1;});return {version:'56.2.0',source:'motm',added:Object.keys(CATALOG).length,total:Object.keys(base.catalog).length,families:byFamily};}
register(); global.DND_BESTIARY_V56_2={VERSION:'56.2.0',catalog:CATALOG,sourcePack:SOURCE,getCreature:getCreature,listBySource:listBySource,listByFamily:listByFamily,summary:summary,register:register};
})(window);
