/**
 * bestiary_catalog_v56_4.js
 * ------------------------------------------------------------------
 * WHAT THIS FILE IS:
 * V56.4 is the Volo/Xanathar legacy catalogue layer. It
 * adds a Volo/Xanathar-era creature profiles using public creature names
 * and original app-native mechanics; it does NOT reproduce published
 * statblocks or text. The file is an extension of Bestiary 2.0, not a
 * second monster engine.
 *
 * HOW IT WORKS:
 * - sourcePack=legacy_official marks the catalogue family for future DLC toggles;
 * - profiles are generated deterministically from creature archetype;
 * - combat uses the existing monster engine through ordinary actions;
 * - harvest creates stable material IDs and registers them in the
 *   existing crafting material catalog;
 * - existing creatures are skipped, so V56/V56.1 entries are preserved.
 * IMPORTANT APIS: DND_BESTIARY_V56_4, getCreature(), listBySource(),
 * listByFamily(), summary(), register().
 * ------------------------------------------------------------------
 */
(function(global){'use strict';
var base=global.DNDExpandedBestiary, monsters=global.DNDMonsters, loot=global.DNDMonsterLoot;
var craft=global.DND_CRAFTING_V31;
if(!base||!monsters)return;
function clone(v){return JSON.parse(JSON.stringify(v));}
function mod(n){return Math.floor((n-10)/2);}
var NAMES = ['Abjurer','Alhoon','Annis Hag','Apprentice Wizard','Archdruid','Archer','Aurochs','Babau','Banderhobb','Bard','Barghest','Bheur Hag','Blackguard','Bodak','Boggle','Brontosaurus','Catoblepas','Cave Fisher','Champion','Chitine','Choldrith','Cloud Giant Smiling One','Conjurer','Cow','Cranium Rat','Darkling','Darkling Elder','Death Kiss','Deep Scion','Deinonychus','Devourer','Dimetrodon','Diviner','Dolphin','Draegloth','Elder Brain','Enchanter','Evoker','Fire Giant Dreadnought','Firenewt','Firenewt Warlock of Imix','Flail Snail','Flind','Froghemoth','Frost Giant Everlasting One','Gauth','Gazer','Giant Strider','Girallon','Gnoll Flesh Gnawer','Gnoll Hunter','Gnoll Witherling','Grung','Grung Elite Warrior','Grung Wildling','Guard Drake','Hadrosaurus','Hobgoblin Devastator','Hobgoblin Iron Shadow','Illusionist','Ki-Rin','Kobold Dragonshield','Kobold Inventor','Kobold Scale Sorcerer','Korred','Kraken Priest','Leucrotta','Martial Arts Adept','Master Thief','Maw Demon','Meenlock','Mind Flayer Lich','Mindwitness','Morkoth','Mouth of Grolantor','Necromancer','Neogi','Neogi Hatchling','Neogi Master','Neothelid','Nilbog','Orc Blade of Ilneval','Orc Claw of Luthic','Orc Hand of Yurtrus','Orc Nurtured One of Yurtrus','Orc Red Fang of Shargaas','Ox (Cow)','Quetzalcoatlus','Quickling','Redcap','Roth\u00e9 (Cow)','Sea Spawn','Shadow Mastiff','Shoosuva','Slithering Tracker','Spawn of Kyuss','Stegosaurus','Stench Kow (Cow)','Stone Giant Dreamwalker','Storm Giant Quintessent','Swarm of Cranium Rats','Swarm of Rot Grubs','Swashbuckler','Tanarukk','Thorny','Tlincalli','Transmuter','Trapper','Ulitharid','Vargouille','Vegepygmy','Vegepygmy Chief','Velociraptor','War Priest','Warlock of the Archfey','Warlock of the Fiend','Warlock of the Great Old One','Warlord','Wood Woad','Xvart','Xvart Warlock of Raxivort','Yeth Hound','Yuan-Ti Anathema','Yuan-Ti Broodguard','Yuan-Ti Mind Whisperer','Yuan-Ti Nightmare Speaker','Yuan-Ti Pit Master','Tiny Servant']
var FAMILY_NAMES={aberration:'Аберрации',humanoid:'Гуманоиды',monstrosity:'Чудовища',fey:'Феи',magical_beast:'Магические звери',construct:'Конструкты',fiend:'Исчадия',elemental:'Элементали',dragon:'Драконы',undead:'Нежить',plant:'Растения',celestial:'Небожители'};
var SOURCE='volo_xanathar_legacy';
function family(name){var s=name.toLowerCase(); if(/zombie|death|bone|wraith|undead|corpse|skull|vampir|spawn of kyuss|allip|bodak|nightwalker|vargouille|mist|dybbuk|sorrowsworn|eidolon|deathlock|skeleton/.test(s))return'undead'; if(/demon|devil|fiend|abishai|bael|baphomet|demogorgon|graz|juiblex|orcus|zariel|yeeno|zuggtmoy|narzugon|hellfire|merregon|nupperibo|orthon|moloch|titivilus|bulezau|babau|armanite|rutterkin|maurezhi|sibriex|yagnoloth/.test(s))return'fiend'; if(/wizard|warlock|archdruid|archer|bard|blackguard|champion|master thief|warlord|priest|adept|giff|gith|drow|duergar|derro|grung|kobold|hobgoblin|gnoll|tortle|xvart|yuan-ti|shadar-kai|darkling|firenewt|neogi|meazel|skulk|swashbuckler|troll|ogre/.test(s))return'humanoid'; if(/elemental|myrmidon|mephit|tempest|leviathan|wastrilith|hydroloth/.test(s))return'elemental'; if(/golem|clockwork|construct|marut|steel predator|hellfire engine|cadaver collector|retriever/.test(s))return'construct'; if(/plant|vegepygmy|wood woad|corpse flower/.test(s))return'plant'; if(/eladrin|fey|quickling|redcap|korred|boggle|hag|meenlock|barghest|yeth hound/.test(s))return'fey'; if(/ki-rin|zariel/.test(s))return'celestial'; if(/dragon|drake|abishai/.test(s))return'dragon'; if(/phoenix|gith|beholder|mindwitness|neothelid|ulitharid|brain|alkilith|allip|gazer|death kiss|sphinx|astral dreadnought|star spawn|oblex|balhannoth|banderhobb|choker|chitine|choldrith|cave fisher|froghemoth|kruthik|morkoth|sibriex/.test(s))return'aberration'; return'monstrosity';}
function role(name){var s=name.toLowerCase(); if(/wizard|warlock|archdruid|priest|sorcerer|brain|beholder|gazer|sphinx|hag|caster|se er|seer|controller/.test(s))return'controller'; if(/archer|ranged|launcher|gish|mind master|shadowblade|swashbuckler/.test(s))return'ranged'; if(/thief|quickling|scion|shadow|skulk|steeder|boggle|assassin|tracker|vampiric mist/.test(s))return'skirmisher'; if(/giant|troll|ogre|brute|dreadnought|render|golem|marut|predator|warlord|champion|guard|despot|wight|boneclaw/.test(s))return'bruiser'; if(/priest|captain|guardian|defender|sentinel|wraith/.test(s))return'guardian'; if(/druid|archdruid|plant|wood woad|vegepygmy/.test(s))return'controller'; if(/dragon|demon|devil|phoenix|leviathan|kraken|hydra|remorhaz/.test(s))return'bruiser'; return'hunter';}
function crFor(i,name){var s=name.toLowerCase(); if(/astral dreadnought|demogorgon|baphomet|fraz|geryon|grazz|juiblex|orcus|zariel|zuggtmoy|zaratan|yeeno|molydeus/.test(s))return 20; if(/elder brain|marut|nightwalker|sibriex|steel predator|morkoth|phoenix|leviathan|amni|amnis/.test(s))return 16; if(/dreadnought|archon|warlord|troll|giant|dragon|golem|retriever|oblex|hydroloth|neothelid/.test(s))return 10+(i%8); return 1+(i%12);}
function habitat(name){var s=name.toLowerCase(); if(/underdark|drow|duergar|derro|choker|neothelid|mindwitness|meazel|meenlock|skulk|oblex|kruthik|gith/.test(s))return['underdark','caves']; if(/desert|sphinx|tlincalli|nagpa|baphomet/.test(s))return['desert','ruins']; if(/ocean|sea|kraken|leviathan|dolphin|wastrilith|hydroloth|scion/.test(s))return['coast','underwater']; if(/forest|wood|fey|redcap|korred|vegepygmy|hag|satyr/.test(s))return['forest','feywild']; if(/grave|death|wraith|vampir|undead|corpse|bone|nightwalker/.test(s))return['graveyard','ruins']; if(/giant|mountain|gith|eagle|tempest|elemental/.test(s))return['mountains','hills']; return['ruins','wilderness'];}
function material(name,fam){var s=name.toLowerCase(); var tag=fam==='construct'?'metal':fam==='plant'?'fiber':fam==='undead'?'bone':fam==='elemental'?'essence':fam==='fiend'?'essence':fam==='dragon'?'scale':/giant|troll|ogre|beast|hybrid/.test(s)?'hide':'trophy'; var clean=name.toLowerCase().replace(/[^a-z0-9]+/g,'_'); return {name:name+' harvest',category:'materials',count:[1,3],guaranteed:true,tags:[tag,fam],skill:fam==='construct'?'arcana':'survival',dc:10,craftMaterialId:'v56_4_'+clean,tool:fam==='construct'?'p_tool_smith':fam==='plant'?'p_tool_alchemist':fam==='elemental'||fam==='fiend'?'p_tool_alchemist':'p_tool_leatherworker'};}
function profile(name,i){var fam=family(name),r=role(name),cr=crFor(i,name),xp=Math.max(25,cr*cr*50),ac=11+Math.min(8,Math.floor(cr/2)),hp=10+cr*10+(i%7)*3,spd=r==='skirmisher'?40:r==='bruiser'?30:30,dex=r==='skirmisher'||r==='ranged'?16:12,str=r==='bruiser'?18:14,con=14+Math.min(5,Math.floor(cr/5)),int=r==='controller'?16:8,wis=12,cha=10; var atkBonus=3+Math.floor(cr/2),damage=cr>=10?'3d8+6':cr>=5?'2d8+4':cr>=2?'2d6+3':'1d8+2'; var acts=[{name:'Signature Attack',kind:'attack',bonus:atkBonus,damage:damage,damageType:fam==='elemental'?'energy':fam==='undead'?'necrotic':'physical'}]; if(r==='controller')acts.push({name:'Control Pulse',kind:'utility',description:'Original app-native control action: imposes a short movement or targeting complication.'}); if(r==='ranged')acts.push({name:'Ranged Volley',kind:'attack',bonus:atkBonus,damage:'1d8+'+(2+Math.floor(cr/3)),damageType:'physical'}); if(r==='skirmisher')acts.push({name:'Disengage Step',kind:'utility',description:'Original mobility action; favors repositioning before the next attack.'}); if(r==='bruiser')acts.push({name:'Heavy Assault',kind:'attack',bonus:atkBonus,damage:damage,damageType:'physical'}); var h=material(name,fam); return {name:name,familyId:fam,cr:String(cr),xp:xp,ac:ac,hp:hp,maxHp:hp,initiative:mod(dex),speed:spd,abilities:{str:str,dex:dex,con:con,int:int,wis:wis,cha:cha},actions:acts,role:r,habitats:habitat(name),sourceType:'official-name-catalog / authorial-mechanics',sourcePack:SOURCE,sourceLabel:'Volo / Xanathar Legacy Sources',bestiaryVersion:'2.0.3',loot:{pockets:{rolls:0,table:[]},harvest:[h]},ecology:{habitats:habitat(name),social:/swarm|pack|gnoll|gith|drow|duergar|hobgoblin|orc|derro/.test(name.toLowerCase())?'group':'variable',activity:/undead|night|dark|shadow/.test(name.toLowerCase())?'nocturnal':'diurnal',diet:fam==='plant'?'photosynthetic':'variable',role:r}};}
var CATALOG={}; NAMES.forEach(function(n,i){if(!base.catalog[n])CATALOG[n]=profile(n,i);});
function register(){Object.keys(CATALOG).forEach(function(n){var c=CATALOG[n];base.families[c.familyId]=base.families[c.familyId]||{id:c.familyId,name:FAMILY_NAMES[c.familyId]||c.familyId,category:c.familyId,habitats:c.habitats,variantHooks:['source','regional']};c.family=FAMILY_NAMES[c.familyId]||c.familyId;base.catalog[n]=clone(c);if(base.familyByCreature)base.familyByCreature[n]=c.familyId;monsters.catalog[n]=clone(c);if(loot&&loot.catalog)loot.catalog[n]=clone(c.loot);var h=c.loot.harvest[0];if(craft&&h&&h.craftMaterialId&&Array.isArray(craft.MATERIALS)&&!craft.MATERIALS.some(function(m){return m.id===h.craftMaterialId;}))craft.MATERIALS.push({id:h.craftMaterialId,name:h.name,cat:'monster_harvest',rarity:'uncommon',price:8,weight:.1,roles:['harvest','crafting'],tags:h.tags,source:'bestiary_v56_4'});});}
function getCreature(n){return CATALOG[n]?clone(CATALOG[n]):(base.catalog[n]?clone(base.catalog[n]):null);} function listBySource(s){return Object.keys(CATALOG).filter(function(n){return CATALOG[n].sourcePack===s;}).map(getCreature);} function listByFamily(f){return Object.keys(CATALOG).filter(function(n){return CATALOG[n].familyId===f;}).map(getCreature);} function summary(){var byFamily={};Object.keys(CATALOG).forEach(function(n){var f=CATALOG[n].familyId;byFamily[f]=(byFamily[f]||0)+1;});return {version:'56.4.0',source:'legacy_official',added:Object.keys(CATALOG).length,total:Object.keys(base.catalog).length,families:byFamily};}
register(); global.DND_BESTIARY_V56_4={VERSION:'56.4.0',catalog:CATALOG,sourcePack:SOURCE,getCreature:getCreature,listBySource:listBySource,listByFamily:listByFamily,summary:summary,register:register};
})(window);
