(function(g){
'use strict';
function hero(){return g.currentChar||null}
function arr(h){if(!h)return [];h.companions=Array.isArray(h.companions)?h.companions:[];return h.companions}
function uid(){return 'cmp_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7)}
function num(v,d){v=Number(v);return isFinite(v)?v:d}
function prof(l){return 2+Math.floor((Math.max(1,num(l,1))-1)/4)}
function ownerLevel(h){return num(h&&h.level,0)||(h&&h.classes||[]).reduce(function(a,c){return a+num(c.level,0)},0)||1}
function make(o){o=o||{};var h=hero(),l=num(o.level,ownerLevel(h));return{id:uid(),ownerId:h&&h.id||null,name:o.name||'Новый спутник',species:o.species||'Неизвестное существо',type:o.type||'beast',size:o.size||'Medium',role:o.role||'companion',level:l,linkedClass:o.linkedClass||null,scaleWithOwner:!!o.scaleWithOwner,active:true,hp:{current:num(o.hp,10),max:num(o.hp,10),temp:0},ac:num(o.ac,10),speed:num(o.speed,30),proficiencyBonus:prof(l),abilities:{str:num(o.str,10),dex:num(o.dex,10),con:num(o.con,10),int:num(o.int,10),wis:num(o.wis,10),cha:num(o.cha,10)},savingThrows:{},skills:{},senses:{},languages:[],resistances:[],immunities:[],vulnerabilities:[],conditionsImmune:[],traits:[],actions:[],bonusActions:[],reactions:[],resources:{},effects:[],notes:''}}
function norm(c,h){c.id=c.id||uid();c.ownerId=c.ownerId||(h&&h.id)||null;c.level=Math.max(1,num(c.level,1));c.proficiencyBonus=num(c.proficiencyBonus,prof(c.level));c.hp=c.hp||{current:1,max:1,temp:0};c.hp.max=Math.max(1,num(c.hp.max,1));c.hp.current=Math.max(0,Math.min(num(c.hp.current,c.hp.max),c.hp.max));c.abilities=c.abilities||{};['str','dex','con','int','wis','cha'].forEach(function(k){c.abilities[k]=num(c.abilities[k],10)});['traits','actions','bonusActions','reactions','resistances','immunities','vulnerabilities','conditionsImmune','languages','effects'].forEach(function(k){c[k]=Array.isArray(c[k])?c[k]:[]});c.resources=c.resources||{};return c}
function save(){try{if(typeof g.autoSaveCurrentCharacter==='function')g.autoSaveCurrentCharacter()}catch(e){}}
function sync(){var h=hero();if(!h)return;arr(h).forEach(function(c){norm(c,h);if(c.scaleWithOwner){c.level=ownerLevel(h);c.proficiencyBonus=prof(c.level);c.linkedOwnerLevel=c.level}});save();render()}
function get(x){var h=hero();return arr(h).find(function(c){return String(c.id)===String(x)})}
function create(o){var h=hero();if(!h)return null;var c=make(o);arr(h).push(c);save();render();open(c.id);return c}
function remove(x){var h=hero();if(!h)return;h.companions=arr(h).filter(function(c){return String(c.id)!==String(x)});save();render();close()}
function copy(x){var c=get(x);if(!c)return;var d=JSON.parse(JSON.stringify(c));d.id=uid();d.name+=' (копия)';arr(hero()).push(d);save();render();open(d.id)}
function esc(s){return String(s==null?'':s).replace(/[&<>]/g,function(x){return{'&':'&amp;','<':'&lt;','>':'&gt;'}[x]})}
function modal(){if(document.getElementById('companionModal'))return;var e=document.createElement('div');e.id='companionModal';e.style.cssText='display:none;position:fixed;inset:0;z-index:32000;background:rgba(0,0,0,.9);overflow:auto;padding:12px;box-sizing:border-box';e.innerHTML='<div style="max-width:760px;margin:15px auto;background:#1b1b1b;color:#eee;border:1px solid #555;border-radius:12px;padding:14px"><div style="display:flex;justify-content:space-between"><h2 id="cmpHead">Спутник</h2><button class="btn-action" onclick="Companions.close()">✕</button></div><div id="cmpBody"></div></div>';document.body.appendChild(e)}
function open(x){var c=get(x);if(!c)return;modal();norm(c,hero());g.Companions._openId=c.id;document.getElementById('cmpHead').textContent='🦊 '+c.name;var ab=['str','dex','con','int','wis','cha'].map(function(k){return '<label>'+k.toUpperCase()+'<input data-a="'+k+'" type="number" value="'+c.abilities[k]+'"></label>'}).join('');document.getElementById('cmpBody').innerHTML='<div style="display:grid;grid-template-columns:1fr 1fr;gap:7px"><label>Имя<input id="cn" value="'+esc(c.name)+'"></label><label>Вид<input id="cs" value="'+esc(c.species)+'"></label><label>Тип<input id="ct" value="'+esc(c.type)+'"></label><label>Размер<input id="cz" value="'+esc(c.size)+'"></label><label>Уровень<input id="cl" type="number" value="'+c.level+'"></label><label>Роль<input id="cr" value="'+esc(c.role)+'"></label><label>КД<input id="ca" type="number" value="'+c.ac+'"></label><label>Скорость<input id="cv" type="number" value="'+c.speed+'"></label><label>HP<input id="ch" type="number" value="'+c.hp.current+'"></label><label>Макс. HP<input id="cm" type="number" value="'+c.hp.max+'"></label></div><label><input id="cscale" type="checkbox" '+(c.scaleWithOwner?'checked':'')+'> Масштабировать с уровнем владельца</label><h3>Характеристики</h3><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:6px">'+ab+'</div><h3>Свойства</h3><textarea id="ctr" rows="4" style="width:100%;box-sizing:border-box">'+esc(c.traits.join(', '))+'</textarea><h3>Действия</h3><textarea id="cac" rows="5" style="width:100%;box-sizing:border-box">'+esc(c.actions.join(', '))+'</textarea><h3>Бонусные действия / реакции</h3><textarea id="cbr" rows="4" style="width:100%;box-sizing:border-box">'+esc(c.bonusActions.concat(c.reactions).join(', '))+'</textarea><h3>Защита</h3><textarea id="cdf" rows="3" style="width:100%;box-sizing:border-box">'+esc(c.resistances.concat(c.immunities).join(', '))+'</textarea><label>Заметки<textarea id="cno" rows="3" style="width:100%;box-sizing:border-box">'+esc(c.notes)+'</textarea></label><div style="display:flex;gap:7px;margin-top:10px"><button class="btn-action" style="flex:1;background:#4caf50" onclick="Companions.saveSheet()">💾 Сохранить</button><button class="btn-action" onclick="Companions.copy()">📋 Копия</button><button class="btn-action" style="background:#e53935" onclick="Companions.remove()">🗑️ Удалить</button></div>';document.getElementById('companionModal').style.display='block'}
function saveSheet(){var c=get(g.Companions._openId);if(!c)return;function v(x){return document.getElementById(x).value}c.name=v('cn');c.species=v('cs');c.type=v('ct');c.size=v('cz');c.level=num(v('cl'),1);c.role=v('cr');c.ac=num(v('ca'),10);c.speed=num(v('cv'),30);c.hp.current=num(v('ch'),1);c.hp.max=Math.max(1,num(v('cm'),1));c.scaleWithOwner=document.getElementById('cscale').checked;['str','dex','con','int','wis','cha'].forEach(function(k){c.abilities[k]=num(document.querySelector('[data-a="'+k+'"]').value,10)});c.traits=v('ctr').split(',').map(function(s){return s.trim()}).filter(Boolean);c.actions=v('cac').split(',').map(function(s){return s.trim()}).filter(Boolean);c.notes=v('cno');norm(c,hero());save();render();open(c.id)}
function close(){var e=document.getElementById('companionModal');if(e)e.style.display='none'}
function render(){var p=document.getElementById('companionsPanel');if(!p)return;var h=hero(),a=arr(h);p.innerHTML='<div style="display:flex;justify-content:space-between;align-items:center"><b>Спутники</b><button class="btn-action" onclick="Companions.create()">+ Создать</button></div>'+(a.length?a.map(function(c){norm(c,h);return '<div style="display:flex;justify-content:space-between;gap:7px;margin-top:7px;padding:8px;background:#242424;border:1px solid #444;border-radius:8px"><span><b>🦊 '+esc(c.name)+'</b><br><small>'+esc(c.species)+' · Ур. '+c.level+' · HP '+c.hp.current+'/'+c.hp.max+' · КД '+c.ac+'</small></span><button class="btn-action" data-cmp-id="'+c.id+'" onclick="Companions.open(this.dataset.cmpId)">Статблок</button></div>'}).join(''):'<span style="color:#999">Спутников пока нет.</span>')}
function install(){modal();var b=document.querySelector('[onclick="exportCurrentCharacter()"]');if(b&&b.parentElement&&b.parentElement.parentElement&&!document.getElementById('companionsCard')){var c=document.createElement('div');c.id='companionsCard';c.className='card';c.innerHTML='<h3>🦊 Спутники</h3><div id="companionsPanel"></div><small style="color:#888">Отдельный статблок; можно иметь несколько спутников и связывать их с классом или владельцем.</small>';b.parentElement.parentElement.insertAdjacentElement('afterend',c)}render()}
g.Companions={create:create,createFor:create,get:get,remove:function(){remove(g.Companions._openId)},copy:function(){copy(g.Companions._openId)},open:open,close:close,saveSheet:saveSheet,sync:sync,render:render,normalize:norm,attach:function(c,h){h=h||hero();if(!h)return null;norm(c,h);c.ownerId=h.id||null;arr(h).push(c);save();render();return c}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install()
})(window);