/**
 * Crafting Resources v34: единый каталог сырья, компонентов и производственных материалов.
 * Как работает: добавляет сотни материалов с категорией, редкостью, ценой, весом,
 * назначением и списком профессий, где материал используется; расширяет цепочки
 * производства через рецепты переработки и показывает справочник материалов в UI.
 * Основные переменные: DND_CRAFT_RESOURCES_V34, RESOURCES, PROCESSING_RECIPES,
 * PROFESSIONS, MATERIALS, RECIPES, usedBy, roles, sourceTags.
 */
(function(global){'use strict';
const base=global.DND_CRAFTING_V31, professions=global.DND_CRAFT_PROFESSIONS_V33;
if(!base||!professions)return;
const R=[];
function add(id,name,cat,rarity,price,weight,usedBy,roles,tags=[]){R.push({id,name,cat,rarity,price,weight,usedBy,roles,tags});}
const addGroup=(cat,rows)=>rows.forEach((x,i)=>add(x[0],x[1],cat,x[2]||'common',x[3]??1,x[4]??1,x[5],x[6]||['component'],x[7]||[]));
addGroup('metal',[
 ['rawCopper','Медная руда','common',.2,1,['smith','jeweler','tinkerer'],['ore','smelting'],['ore']],['rawIron','Железная руда','common',.3,1,['smith','tinkerer'],['ore','smelting'],['ore']],['tinOre','Оловянная руда','common',.25,1,['smith','jeweler','tinkerer'],['ore','alloy'],['ore']],['leadOre','Свинцовая руда','common',.15,1,['smith','tinkerer','glasswork'],['ore','casting'],['ore']],['zincOre','Цинковая руда','uncommon',.4,1,['smith','tinkerer'],['ore','alloy'],['ore']],['nickelOre','Никелевая руда','uncommon',1,1,['smith','tinkerer'],['ore','alloy'],['ore']],['coldIronOre','Руда холодного железа','rare',12,1,['smith','jeweler'],['ore','supernatural'],['magic']],['mithralOre','Мифриловая руда','very_rare',60,1,['smith','jeweler','tinkerer'],['ore','magicMetal'],['magic']],['adamantineOre','Адамантиновая руда','very_rare',90,1,['smith','tinkerer'],['ore','magicMetal'],['magic']],['meteorIron','Метеоритное железо','rare',20,1,['smith','jeweler','tinkerer'],['ore','magicMetal'],['magic']],['starMetal','Звёздный металл','very_rare',100,1,['smith','jeweler'],['ore','magicMetal'],['magic']],['electrum','Электрум','uncommon',15,1,['smith','jeweler','tinkerer'],['alloy','jewelry'],['metal']],['brass','Латунь','common',3,1,['smith','tinkerer','jeweler'],['alloy','casting'],['metal']],['bronze','Бронза','common',2,1,['smith','tinkerer','jeweler'],['alloy','casting'],['metal']],['steelBillet','Стальная заготовка','common',4,1,['smith','tinkerer'],['billet','component'],['metal']],['silverBillet','Серебряная заготовка','uncommon',12,1,['smith','jeweler'],['billet','jewelry'],['metal']],['goldBillet','Золотая заготовка','rare',40,1,['jeweler','smith'],['billet','jewelry'],['metal']],['platinumBillet','Платиновая заготовка','very_rare',120,1,['jeweler','smith'],['billet','jewelry'],['metal']],['ironWire','Железная проволока','common',1,0.2,['smith','tinkerer','weaver'],['wire','fastener'],['metal']],['copperWire','Медная проволока','common',1.5,0.2,['smith','tinkerer','weaver'],['wire','fastener'],['metal']],['steelWire','Стальная проволока','uncommon',4,0.2,['smith','tinkerer','weaver'],['wire','fastener'],['metal']]
]);
addGroup('wood',[
 ['pine','Сосна','common',.1,1,['woodwork','weaver','tinkerer'],['lumber','fuel'],['wood']],['oak','Дуб','common',.5,1,['woodwork','tinkerer'],['lumber','structural'],['wood']],['ashWood','Ясень','common',.4,1,['woodwork'],['lumber','flexible'],['wood']],['birch','Берёза','common',.25,1,['woodwork','scribe'],['lumber','paperStock'],['wood']],['yew','Тис','uncommon',5,1,['woodwork'],['bowStock','fineLumber'],['wood']],['ebony','Эбен','rare',20,1,['woodwork','jeweler'],['fineLumber','decor'],['wood']],['heartwood','Сердцевина древнего дерева','rare',15,1,['woodwork','jeweler','tinkerer'],['fineLumber','magicComponent'],['magic']],['darkheart','Сердцевина тенедерева','very_rare',80,1,['woodwork','jeweler'],['magicWood','fineLumber'],['magic']],['ironwood','Железное дерево','rare',25,1,['woodwork','smith','tinkerer'],['structural','magicWood'],['magic']],['bark','Кора','common',.05,.2,['alchemy','pottery','weaver'],['reagent','fiber'],['natural']],['birchBark','Берёзовая кора','common',.2,.2,['scribe','alchemy'],['paperStock','reagent'],['natural']],['pineResin','Сосновая смола','common',.5,.2,['alchemy','woodwork','glasswork'],['adhesive','reagent'],['natural']],['dragonwood','Драконье дерево','very_rare',90,1,['woodwork','jeweler'],['magicWood','weaponCore'],['magic']]
]);
addGroup('fiber',[
 ['flax','Лён','common',.2,.2,['weaver','scribe'],['fiber','paperStock'],['plant']],['hemp','Конопляное волокно','common',.25,.2,['weaver','leatherwork'],['fiber','cordage'],['plant']],['cotton','Хлопок','common',.3,.1,['weaver','scribe'],['fiber','cloth'],['plant']],['wool','Овечья шерсть','common',.2,.2,['weaver','leatherwork'],['fiber','padding'],['animal']],['silkwormSilk','Шёлк','uncommon',5,.1,['weaver','jeweler','scribe'],['fineFiber','fineCloth'],['animal']],['giantSpiderSilk','Шёлк гигантского паука','rare',18,.1,['weaver','jeweler','alchemy'],['fineFiber','magicFiber'],['monster']],['dryadThread','Нить дриады','rare',25,.05,['weaver','jeweler'],['magicFiber','enchantmentCarrier'],['magic']],['ghostThread','Призрачная нить','very_rare',80,.05,['weaver','jeweler','scribe'],['magicFiber','binding'],['undead','magic']],['goldThread','Золотая нить','rare',35,.05,['weaver','jeweler'],['embroidery','luxuryFiber'],['metal']],['silverThread','Серебряная нить','uncommon',12,.05,['weaver','jeweler','alchemy'],['warding','embroidery'],['metal']],['horseHair','Конский волос','common',.1,.05,['weaver','tinkerer','scribe'],['brush','string'],['animal']],['sinew','Жильная нить','common',.5,.2,['leatherwork','woodwork','smith'],['cordage','binding'],['animal']],['displacerFiber','Волокно дизлока','rare',20,.1,['weaver','alchemy'],['magicFiber','illusion'],['monster']],['phoenixThread','Нить феникса','legendary',250,.05,['weaver','jeweler','alchemy'],['magicFiber','fireResistant'],['magic']]
]);
addGroup('hide',[
 ['boarHide','Кабанья шкура','common',2,1,['leatherwork','weaver'],['hide','padding'],['animal']],['deerHide','Оленья шкура','common',2,1,['leatherwork','weaver'],['hide','fineLeather'],['animal']],['wolfPelt','Волчья шкура','uncommon',5,1,['leatherwork','weaver','jeweler'],['hide','warmth'],['animal']],['bearHide','Медвежья шкура','uncommon',7,2,['leatherwork','weaver'],['heavyHide','padding'],['animal']],['direWolfPelt','Шкура лютого волка','rare',15,1,['leatherwork','weaver'],['magicHide','coldResistant'],['monster']],['displacerHide','Шкура дизлока','rare',25,1,['leatherwork','weaver','alchemy'],['magicHide','illusion'],['monster']],['bulettePlate','Пластина бурого прыгуна','rare',30,1,['smith','leatherwork'],['plate','armorComponent'],['monster']],['owlbearHide','Шкура совомедведя','rare',22,2,['leatherwork','weaver'],['heavyHide','reinforcement'],['monster']],['trollHide','Шкура тролля','very_rare',70,2,['leatherwork','alchemy'],['regenerative','magicHide'],['monster']],['wyvernHide','Шкура виверны','very_rare',60,1,['leatherwork','weaver','alchemy'],['poisonResistant','magicHide'],['monster']],['dragonScaleRed','Красная драконья чешуя','very_rare',90,.5,['leatherwork','smith','jeweler'],['scale','fireResistant'],['monster']],['dragonScaleBlue','Синяя драконья чешуя','very_rare',90,.5,['leatherwork','smith','jeweler'],['scale','lightningResistant'],['monster']],['dragonScaleWhite','Белая драконья чешуя','very_rare',80,.5,['leatherwork','smith'],['scale','coldResistant'],['monster']],['dragonScaleBlack','Чёрная драконья чешуя','very_rare',90,.5,['leatherwork','smith','alchemy'],['scale','acidResistant'],['monster']],['krakenLeather','Кожа кракена','legendary',180,1,['leatherwork','weaver','alchemy'],['magicHide','waterResistant'],['monster']],['angelHide','Небесная кожа','legendary',250,.5,['leatherwork','weaver','jeweler'],['holyMaterial','warding'],['celestial','magic']]
]);
addGroup('gem',[
 ['quartz','Кварц','common',1,.1,['jeweler','glasswork','tinkerer'],['gem','abrasive'],['mineral']],['amethyst','Аметист','uncommon',20,.1,['jeweler','glasswork','alchemy'],['gem','arcaneFocus'],['gem']],['garnet','Гранат','uncommon',18,.1,['jeweler','smith','alchemy'],['gem','heatFocus'],['gem']],['sapphire','Сапфир','rare',50,.1,['jeweler','glasswork','alchemy'],['gem','coldFocus'],['gem']],['ruby','Рубин','rare',60,.1,['jeweler','glasswork','alchemy'],['gem','fireFocus'],['gem']],['emerald','Изумруд','rare',55,.1,['jeweler','alchemy'],['gem','vitalityFocus'],['gem']],['opal','Опал','rare',45,.1,['jeweler','glasswork','alchemy'],['gem','illusionFocus'],['gem']],['moonstone','Лунный камень','uncommon',25,.1,['jeweler','alchemy'],['gem','divinationFocus'],['gem']],['sunstone','Солнечный камень','rare',60,.1,['jeweler','alchemy'],['gem','radiantFocus'],['gem']],['blackOpal','Чёрный опал','very_rare',120,.1,['jeweler','alchemy'],['gem','shadowFocus'],['gem']],['dragonCrystal','Драконий кристалл','very_rare',150,.2,['jeweler','glasswork','alchemy'],['gem','elementalFocus'],['monster','magic']],['feyCrystal','Фейский кристалл','rare',75,.1,['jeweler','glasswork','weaver'],['gem','illusionFocus'],['fey','magic']],['soulGem','Камень души','legendary',300,.1,['jeweler','alchemy','tinkerer'],['gem','soulContainer'],['magic']],['obsidian','Обсидиан','uncommon',8,.2,['jeweler','smith','glasswork'],['gem','bladeEdge'],['mineral']],['jade','Нефрит','uncommon',15,.1,['jeweler','pottery','alchemy'],['gem','warding'],['gem']]
]);
addGroup('plant',[
 ['lavender','Лаванда','common',1,.1,['alchemy','cook','weaver'],['herb','scent'],['plant']],['sage','Шалфей','common',1,.1,['alchemy','cook','scribe'],['herb','antidote'],['plant']],['mint','Мята','common',.8,.1,['alchemy','cook'],['herb','cooling'],['plant']],['nightshade','Паслён','uncommon',4,.1,['alchemy','cook'],['toxin','reagent'],['plant']],['bloodroot','Кровокорень','uncommon',5,.1,['alchemy','leatherwork'],['hemostatic','dye'],['plant']],['ghostMoss','Призрачный мох','rare',18,.1,['alchemy','scribe','weaver'],['illusion','reagent'],['plant','magic']],['fireLichen','Огненный лишайник','uncommon',7,.1,['alchemy','cook','pottery'],['heat','fuel'],['plant']],['frostLichen','Морозный лишайник','uncommon',7,.1,['alchemy','weaver'],['cooling','reagent'],['plant']],['dreamLotus','Лотос сновидений','rare',30,.1,['alchemy','weaver'],['sleep','scent'],['plant','magic']],['sunleaf','Солнечный лист','rare',22,.1,['alchemy','cook','weaver'],['radiant','vitality'],['plant','magic']],['mooncap','Лунный гриб','rare',25,.1,['alchemy','cook'],['night','mind'],['fungus','magic']],['voidMushroom','Гриб пустоты','very_rare',90,.1,['alchemy','jeweler'],['void','magicReagent'],['fungus','magic']],['emberPetal','Угольный лепесток','rare',18,.05,['alchemy','weaver','jeweler'],['fire','dye'],['plant','magic']],['silverThistle','Серебряный чертополох','rare',20,.1,['alchemy','weaver','jeweler'],['antidote','warding'],['plant','metal']]
]);
addGroup('monster',[
 ['spiderFang','Клык паука','common',2,.1,['alchemy','smith','jeweler'],['venom','component'],['monster']],['scorpionStinger','Жало скорпиона','uncommon',6,.1,['alchemy','smith','jeweler'],['venom','needle'],['monster']],['basiliskEye','Глаз василиска','rare',40,.1,['alchemy','jeweler','glasswork'],['petrification','lens'],['monster']],['medusaHair','Волосы медузы','rare',35,.1,['alchemy','weaver'],['petrification','fiber'],['monster']],['manticoreSpine','Шип мантикоры','rare',25,.2,['smith','leatherwork','alchemy'],['piercing','poison'],['monster']],['displacerTentacle','Щупальце дизлока','rare',30,.5,['leatherwork','weaver','alchemy'],['illusion','flexibleComponent'],['monster']],['beholderEye','Глаз бехолдера','very_rare',150,.2,['jeweler','glasswork','alchemy'],['arcane','lens'],['monster']],['chimeraHorn','Рог химеры','rare',35,.5,['smith','jeweler','alchemy'],['horn','focus'],['monster']],['unicornHair','Волос единорога','legendary',250,.05,['weaver','jeweler','alchemy'],['purity','warding'],['celestial','magic']],['phoenixAsh','Пепел феникса','legendary',300,.1,['alchemy','jeweler','smith'],['rebirth','fire'],['celestial','magic']],['elementalCore','Сердце элементаля','very_rare',120,.5,['smith','jeweler','alchemy','tinkerer'],['elementalCore','powerSource'],['elemental']],['golemCore','Осколок големного ядра','very_rare',100,.5,['tinkerer','smith','jeweler'],['powerSource','construct'],['construct']],['krakenSinew','Жильная связка кракена','very_rare',80,.5,['leatherwork','weaver','woodwork'],['cordage','reinforcement'],['monster']],['giantBone','Кость великана','rare',20,2,['smith','woodwork','jeweler'],['bone','reinforcement'],['monster']],['dragonTooth','Зуб дракона','very_rare',100,.5,['smith','jeweler','alchemy'],['bladeEdge','arcane'],['monster']]
]);
addGroup('mineral',[
 ['limestone','Известняк','common',.05,1,['pottery','smith','glasswork'],['flux','ceramic'],['mineral']],['flint','Кремень','common',.1,.2,['smith','woodwork','tinkerer'],['spark','edge'],['mineral']],['pumice','Пемза','common',.2,.2,['pottery','glasswork','alchemy'],['abrasive','filter'],['mineral']],['graphite','Графит','uncommon',3,.2,['smith','pottery','scribe'],['lubricant','pigment'],['mineral']],['sulfur','Сера','uncommon',2,.2,['alchemy','pottery','smith'],['reagent','fuel'],['mineral']],['saltpeter','Селитра','uncommon',2,.2,['alchemy','tinkerer'],['oxidizer','reagent'],['mineral']],['quicksilver','Ртуть','rare',25,.2,['alchemy','jeweler','tinkerer'],['catalyst','metal'],['mineral']],['dragonstone','Драконий камень','very_rare',100,.2,['jeweler','smith','alchemy'],['arcaneFocus','powerSource'],['magic']],['voidCrystal','Кристалл пустоты','legendary',250,.1,['jeweler','alchemy','tinkerer'],['voidFocus','powerSource'],['magic']],['faeQuartz','Фейский кварц','rare',45,.1,['jeweler','glasswork','weaver'],['illusionFocus','arcaneFocus'],['fey','magic']],['adamantDust','Адамантиновая пыль','very_rare',70,.1,['smith','jeweler','tinkerer'],['abrasive','reinforcement'],['magic']],['mithralDust','Мифриловая пыль','very_rare',50,.1,['smith','jeweler','alchemy'],['catalyst','reinforcement'],['magic']]
]);
addGroup('reagent',[
 ['alum','Квасцы','common',1,.2,['leatherwork','weaver','alchemy'],['tanning','mordant'],['reagent']],['tannin','Танин','common',1,.2,['leatherwork','weaver','alchemy'],['tanning','dye'],['plant']],['potash','Поташ','common',.5,.2,['glasswork','alchemy'],['flux','alkali'],['reagent']],['vinegar','Уксус','common',.5,.2,['alchemy','cook','leatherwork'],['solvent','preservative'],['food']],['ethanol','Спирт','uncommon',4,.2,['alchemy','cook','glasswork'],['solvent','fuel'],['reagent']],['charcoalFine','Тонкий активированный уголь','uncommon',3,.2,['alchemy','pottery','smith'],['filter','purifier'],['reagent']],['animalGlue','Столярный клей','common',1,.2,['woodwork','scribe','leatherwork'],['adhesive','binding'],['animal']],['hideGlue','Кожевенный клей','common',1,.2,['leatherwork','woodwork','scribe'],['adhesive','binding'],['animal']],['beeswaxPure','Чистый пчелиный воск','common',1,.2,['weaver','glasswork','scribe','alchemy'],['sealant','waterproof'],['natural']],['lampOil','Лампадное масло','common',1,.5,['tinkerer','alchemy','cook'],['fuel','lubricant'],['reagent']],['pigmentOchre','Охра','common',.5,.1,['scribe','weaver','pottery'],['pigment','dye'],['mineral']],['pigmentIndigo','Индиго','uncommon',3,.1,['scribe','weaver'],['pigment','dye'],['plant']],['pigmentCarmine','Кармин','rare',12,.05,['scribe','weaver','jeweler'],['pigment','dye'],['animal']],['lampblack','Лампадная сажа','common',.5,.1,['scribe','pottery','smith'],['pigment','inkBase'],['reagent']],['gumArabic','Аравийская камедь','common',1,.1,['scribe','alchemy','weaver'],['binder','inkBase'],['plant']]
]);
addGroup('glass',[
 ['obsidianGlass','Обсидиановое стекло','rare',15,.5,['glasswork','jeweler','smith'],['bladeGlass','decor'],['mineral']],['coloredGlass','Цветное стекло','uncommon',3,.2,['glasswork','jeweler'],['decor','lens'],['glass']],['crystalGlass','Кристаллическое стекло','rare',20,.2,['glasswork','jeweler','alchemy'],['fineGlass','lens'],['glass']],['leadGlass','Свинцовое стекло','uncommon',4,.3,['glasswork','alchemy'],['denseGlass','lens'],['glass']],['frostGlass','Морозное стекло','rare',18,.2,['glasswork','alchemy'],['coldResistant','lens'],['magic']],['dragonGlass','Драконье стекло','very_rare',100,.2,['glasswork','jeweler','alchemy'],['elementalGlass','lens'],['magic']]
]);
addGroup('ceramic',[
 ['fireClay','Огнеупорная глина','uncommon',2,1,['pottery','glasswork','smith'],['refractory','crucible'],['ceramic']],['porcelainClay','Каолин','uncommon',3,1,['pottery','jeweler','scribe'],['fineCeramic','whitePigment'],['mineral']],['boneAsh','Костяная зола','uncommon',2,.5,['pottery','alchemy'],['flux','porcelain'],['mineral']],['glaze','Глазурь','common',1,.2,['pottery','glasswork'],['coating','sealant'],['ceramic']],['magicGlaze','Чародейная глазурь','rare',20,.2,['pottery','jeweler','alchemy'],['magicCoating','warding'],['magic']],['dragonCeramic','Драконья керамика','very_rare',80,.5,['pottery','alchemy','tinkerer'],['refractory','magicContainer'],['magic']]
]);
addGroup('paper',[
 ['ragPulp','Тряпичная масса','common',.2,.5,['scribe','cartographer'],['paperStock','pulp'],['paper']],['woodPulp','Древесная масса','common',.1,.5,['scribe','cartographer'],['paperStock','pulp'],['paper']],['vellum','Выделанный велень','uncommon',5,.1,['scribe','cartographer','leatherwork'],['fineParchment','writingSurface'],['hide']],['cottonPaper','Хлопковая бумага','uncommon',2,.1,['scribe','cartographer'],['finePaper','durablePaper'],['fiber']],['magicPaper','Чародейская бумага','rare',20,.05,['scribe','cartographer','alchemy'],['magicPaper','spellCarrier'],['magic']],['starPaper','Звёздная бумага','very_rare',90,.05,['scribe','cartographer','jeweler'],['magicPaper','divination'],['magic']]
]);
addGroup('food',[
 ['grain','Зерно','common',.05,1,['cook','alchemy'],['food','fermentation'],['food']],['rice','Рис','common',.05,1,['cook','alchemy'],['food','fermentation'],['food']],['driedMeat','Вяленое мясо','common',1,.5,['cook','alchemy'],['food','preservation'],['food']],['honey','Мёд','common',2,.2,['cook','alchemy','weaver'],['sweetener','preservative'],['food']],['spices','Пряности','uncommon',5,.1,['cook','alchemy'],['flavor','reagent'],['food']],['exoticSpice','Экзотические специи','rare',20,.1,['cook','alchemy','jeweler'],['flavor','rareReagent'],['food','magic']],['monsterMeat','Мясо чудовища','uncommon',4,.5,['cook','alchemy'],['food','reagent'],['monster']],['dragonMeat','Мясо дракона','very_rare',60,1,['cook','alchemy'],['food','elementalReagent'],['monster','magic']]
]);
// Дополнительные ресурсы — по 10 тематических материалов на производственную ветку.
const themed=[
 ['smith','Уголь кузнеца','fuel','common',.2,.5,['fuel','smithing']],['smith','Флюс кузнеца','reagent','common',.4,.2,['flux','smithing']],['smith','Закалочная соль','reagent','uncommon',3,.2,['quench','smithing']],['smith','Масло закалки','reagent','common',1,.5,['quench','smithing']],['smith','Кузнечный шлак','mineral','common',.05,1,['recycle','smithing']],
 ['jeweler','Абразивный порошок','mineral','common',.5,.1,['abrasive','gemCutting']],['jeweler','Алмазная паста','gem','rare',25,.05,['abrasive','gemCutting']],['jeweler','Ювелирный воск','reagent','common',1,.1,['casting','jewelry']],['jeweler','Полировальная паста','reagent','common',.5,.1,['polish','jewelry']],['jeweler','Пробирный камень','mineral','uncommon',5,.2,['assay','jewelry']],
 ['weaver','Крашеная нить','fiber','common',.3,.05,['thread','dye']],['weaver','Эластичная нить','fiber','uncommon',2,.05,['thread','stretch']],['weaver','Водостойкая ткань','fiber','uncommon',4,.2,['cloth','waterproof']],['weaver','Огнестойкая ткань','fiber','rare',15,.2,['cloth','fireResistant']],['weaver','Арканная ткань','fiber','rare',25,.2,['cloth','magicCarrier']],
 ['woodwork','Дубовый шпон','wood','common',.5,.2,['veneer','fineWood']],['woodwork','Луковая тетива','fiber','common',1,.05,['bowString','binding']],['woodwork','Столярный штифт','wood','common',.05,.05,['fastener','joinery']],['woodwork','Деревянный клей','reagent','common',.3,.2,['adhesive','joinery']],['woodwork','Деревянная пропитка','reagent','uncommon',2,.2,['preservative','woodTreatment']],
 ['leatherwork','Дублёная кожа','hide','common',2,.5,['leather','armorComponent']],['leatherwork','Мягкая кожа','hide','uncommon',4,.3,['fineLeather','clothing']],['leatherwork','Толстая кожа','hide','common',3,1,['heavyLeather','armor']],['leatherwork','Водостойкая кожа','hide','uncommon',7,.5,['waterproof','armor']],['leatherwork','Арканная кожа','hide','rare',25,.5,['magicHide','enchantmentCarrier']],
 ['pottery','Шамот','ceramic','common',1,1,['refractory','ceramic']],['pottery','Каолиновая паста','ceramic','uncommon',3,1,['fineCeramic','ceramic']],['pottery','Керамический порошок','ceramic','common',.3,.5,['slip','ceramic']],['pottery','Глиняный шликер','ceramic','common',.2,.5,['binder','ceramic']],['pottery','Печная глазурь','ceramic','uncommon',2,.2,['coating','ceramic']],
 ['glasswork','Кварцевый песок','mineral','common',.1,1,['glassBatch','glass']],['glasswork','Сода','mineral','common',.2,1,['flux','glass']],['glasswork','Известковый стабилизатор','mineral','common',.1,1,['stabilizer','glass']],['glasswork','Краситель стекла','reagent','uncommon',2,.1,['glassColor','glass']],['glasswork','Оптический порошок','mineral','rare',10,.1,['lens','optics']],
 ['scribe','Пемзовая пудра','mineral','common',.3,.1,['paperPrep','scribe']],['scribe','Галун','reagent','common',1,.2,['paperPrep','ink']],['scribe','Сухой пигмент','reagent','common',.5,.1,['ink','pigment']],['scribe','Связующее для чернил','reagent','common',.5,.1,['ink','binder']],['scribe','Арканные чернила','reagent','rare',25,.05,['magicInk','spellWriting']],
 ['cartographer','Компасная игла','metal','uncommon',3,.1,['navigation','cartography']],['cartographer','Латунный компасный корпус','metal','uncommon',8,.2,['navigation','cartography']],['cartographer','Масштабная линейка','wood','common',.5,.2,['measurement','cartography']],['cartographer','Картографическая сетка','paper','common',.2,.05,['grid','cartography']],['cartographer','Арканная тушь','reagent','rare',20,.05,['magicMap','cartography']],
 ['alchemy','Дистиллированная вода','reagent','common',.2,.5,['solvent','alchemy']],['alchemy','Кислотный раствор','reagent','uncommon',3,.5,['acid','alchemy']],['alchemy','Щёлочной раствор','reagent','uncommon',3,.5,['base','alchemy']],['alchemy','Стабилизатор эфира','reagent','rare',15,.2,['stability','alchemy']],['alchemy','Катализатор ртути','reagent','rare',20,.2,['catalyst','alchemy']],
 ['cook','Мука','food','common',.05,1,['food','cooking']],['cook','Сушёные фрукты','food','common',.5,.5,['food','preservation']],['cook','Сыр','food','common',.5,.5,['food','cooking']],['cook','Сахар','food','common',.2,.5,['sweetener','cooking']],['cook','Экзотический мёд','food','rare',12,.2,['rareFood','magicCooking']],
 ['tinkerer','Пружинная сталь','metal','uncommon',5,.2,['spring','mechanism']],['tinkerer','Тонкая шестерня','metal','uncommon',3,.1,['gear','mechanism']],['tinkerer','Механическая пружина','metal','uncommon',4,.1,['spring','mechanism']],['tinkerer','Тонкая цепь','metal','common',1,.2,['chain','mechanism']],['tinkerer','Магнитный камень','mineral','uncommon',5,.2,['magnet','mechanism']]
];
themed.forEach((x,i)=>add('trade_'+x[0]+'_'+i,x[1],x[2],x[3],x[4],x[5],[x[0]],x[6],['profession_specific']));
// Объединяем каталог с базовым MATERIALS: существующие id не дублируем.
const known=new Set(base.MATERIALS.map(x=>x.id));R.forEach(x=>{if(!known.has(x.id)){base.MATERIALS.push(x);known.add(x.id);}});
// Производственные цепочки из сырья в компоненты. Они намеренно небольшие и повторно используемые.
const PROCESSING_RECIPES=[];
function proc(id,name,profession,dc,time,materials,outputId,outputName,cat='materials',count=1){const r={id,name,profession,dc,time,materials,output:{cat,name:outputName,materialId:outputId,count,rarity:'common',craftValue:1}};PROCESSING_RECIPES.push(r);professions.RECIPES.push(r);}
proc('res_smelt_copper','Выплавка меди','smith',9,2,{rawCopper:2,charcoal:1},'refinedCopper','Слиток меди');
proc('res_smelt_iron','Выплавка железа','smith',10,2,{rawIron:2,charcoal:1},'ironIngot','Слиток железа');
proc('res_smelt_bronze','Литьё бронзы','smith',11,3,{copper:2,tinOre:1,charcoal:1},'bronzeIngot','Слиток бронзы');
proc('res_smelt_brass','Литьё латуни','smith',11,3,{copper:2,zincOre:1,charcoal:1},'brassIngot','Слиток латуни');
proc('res_wire_copper','Волочение меди','smith',10,2,{refinedCopper:1},'copperWire','Медная проволока', 'materials',3);
proc('res_wire_iron','Волочение железа','smith',10,2,{ironIngot:1},'ironWire','Железная проволока', 'materials',3);
proc('res_cut_quartz','Огранка кварца','jeweler',9,2,{quartz:1,diamondPaste:1},'cutQuartz','Огранённый кварц');
proc('res_cut_gem','Огранка камня','jeweler',12,4,{gem:1,diamondPaste:1},'cutGemV34','Огранённый камень');
proc('res_gold_wire','Волочение золотой нити','jeweler',12,3,{goldBillet:1},'goldWire','Золотая проволока', 'materials',3);
proc('res_spin_flax','Прядение льна','weaver',8,2,{flax:3},'linenThread','Льняная нить','materials',4);
proc('res_spin_hemp','Прядение конопли','weaver',8,2,{hemp:3},'hempCord','Конопляный шнур','materials',4);
proc('res_spin_silk','Прядение шёлка','weaver',11,3,{silkwormSilk:2},'silkThread','Шёлковая нить','materials',3);
proc('res_tan_deer','Выделка оленьей кожи','leatherwork',9,4,{deerHide:1,alum:1,tannin:1},'fineDeerLeather','Выделанная оленья кожа');
proc('res_tan_dragon','Выделка драконьей чешуи','leatherwork',16,8,{dragonScaleRed:2,alum:1,tannin:1},'treatedDragonScale','Обработанная драконья чешуя');
proc('res_lumber_oak','Распил дуба','woodwork',8,2,{oak:2},'oakPlank','Дубовая доска','materials',4);
proc('res_lumber_yew','Обработка тиса','woodwork',12,4,{yew:2},'yewLumber','Тисовая заготовка','materials',2);
proc('res_resin','Очистка смолы','woodwork',8,1,{pineResin:2},'cleanResin','Очищенная смола','materials',2);
proc('res_paper_flax','Изготовление льняной бумаги','scribe',9,3,{flax:4,ragPulp:2},'linenPaper','Льняная бумага','materials',6);
proc('res_paper_cotton','Изготовление хлопковой бумаги','scribe',10,3,{cotton:4,ragPulp:2},'cottonPaperFine','Хлопковая бумага','materials',6);
proc('res_ink','Изготовление чернил','scribe',9,2,{lampblack:1,gumArabic:1,vinegar:1},'scribeInk','Письменные чернила','materials',2);
proc('res_glass_batch','Стекольная шихта','glasswork',9,2,{quartz:2,potash:1,limestone:1},'glassBatch','Стекольная шихта','materials',2);
proc('res_crystal_glass','Кристаллическое стекло','glasswork',13,5,{glassBatch:2,crystal:1},'crystalGlassFine','Кристаллическое стекло');
proc('res_ceramic','Огнеупорная керамика','pottery',11,4,{fireClay:3,glaze:1,charcoal:1},'refractoryCeramic','Огнеупорная керамика');
proc('res_porcelain','Фарфор','pottery',13,6,{porcelainClay:3,boneAsh:1,glaze:1},'porcelain','Фарфор');
proc('res_distill','Дистилляция спирта','alchemy',11,4,{grain:2,ethanol:1,glass:1},'pureEthanol','Очищенный спирт');
proc('res_purify_charcoal','Активация угля','alchemy',10,2,{charcoalFine:2},'activatedCharcoal','Активированный уголь','materials',2);
proc('res_ferment','Ферментация уксуса','alchemy',9,6,{grain:2,vinegar:1},'fermentedAcid','Ферментированный раствор');
proc('res_ration','Сушка пайков','cook',8,4,{grain:2,driedMeat:2,salt:1},'trailRation','Сухой походный паёк','consumables',4);
proc('res_spice_mix','Смесь специй','cook',8,1,{spices:2,honey:1},'spiceBlend','Смесь специй','consumables',3);
proc('res_gear','Изготовление шестерён','tinkerer',11,4,{steelBillet:2},'fineGear','Точные шестерни','materials',2);
proc('res_spring','Изготовление пружины','tinkerer',12,4,{springSteel:1},'mechanicalSpring','Механическая пружина');
proc('res_chain','Изготовление цепи','tinkerer',10,3,{steelWire:3},'fineChain','Тонкая цепь','materials',2);
// Результаты переработки тоже становятся полноценными материалами и могут входить в следующие цепочки.
const knownProcessed=new Set(base.MATERIALS.map(x=>x.id));
PROCESSING_RECIPES.forEach(pr=>{
  const o=pr.output;
  if(o.materialId&&!knownProcessed.has(o.materialId)){
    base.MATERIALS.push({id:o.materialId,name:o.name,cat:'processed',rarity:o.rarity||'common',price:Number(o.craftValue)||1,weight:.2,usedBy:[pr.profession],roles:['processed','component'],tags:['crafting']});
    knownProcessed.add(o.materialId);
  }
});
// UI справочника материалов.
function render(){const host=document.getElementById('craftingResourcesPanel')||document.getElementById('craftingProfessionsPanel');if(!host)return;if(!document.getElementById('craftResourceBook')){const box=document.createElement('div');box.id='craftResourceBook';box.style.cssText='margin-top:10px;padding:10px;background:#151515;border:1px solid #4b3a20;border-radius:8px';box.innerHTML='<h3 style="margin:0;color:#d7b86e">📚 Справочник сырья и материалов</h3><div style="font-size:.76em;color:#aaa;margin:5px 0">У каждого материала указано, в каких ремёслах он используется и какую роль выполняет.</div><input id="craftResourceSearch" placeholder="Поиск материала или профессии..." style="width:100%;box-sizing:border-box;padding:7px;background:#222;color:#fff;border:1px solid #444;border-radius:5px" oninput="DND_CRAFT_RESOURCES_V34.renderList()"><div id="craftResourceList" style="max-height:500px;overflow:auto;margin-top:7px"></div>';host.appendChild(box);}renderList();}
function renderList(){const list=document.getElementById('craftResourceList');if(!list)return;const q=(document.getElementById('craftResourceSearch')?.value||'').toLowerCase();const rows=R.filter(x=>!q||x.name.toLowerCase().includes(q)||x.usedBy.some(p=>(professions.PROFESSIONS[p]?.name||p).toLowerCase().includes(q))||x.roles.some(t=>t.toLowerCase().includes(q)));list.innerHTML=rows.map(x=>`<div style="padding:7px;margin-bottom:4px;background:#211f1b;border:1px solid #39342b;border-radius:6px;font-size:.75em"><b>${x.name}</b> · ${x.rarity} · ${x.price} зм · ${x.weight} ед.<br><span style="color:#c9b98c">Ремёсла:</span> ${x.usedBy.map(p=>professions.PROFESSIONS[p]?.name||p).join(', ')}<br><span style="color:#aaa">Роли:</span> ${x.roles.join(', ')}</div>`).join('')||'<div style="color:#888;padding:8px">Ничего не найдено.</div>';}
function grant(id,count=1){const m=R.find(x=>x.id===id);if(!m)return false;const v=(global.currentCharacter||global.currentChar);if(!v)return false;v.inventory=v.inventory||{weapons:[],armor:[],consumables:[],materials:[],junk:[]};const a=v.inventory.materials||(v.inventory.materials=[]);const same=a.find(x=>x.materialId===id);if(same)same.count=(same.count||0)+count;else a.push({name:m.name,count,materialId:id,craftMaterialId:id,weight:m.weight,cost:m.price,rarity:m.rarity,category:'Материал',usedBy:m.usedBy,roles:m.roles});if(typeof global.autoSaveCurrentCharacter==='function')global.autoSaveCurrentCharacter();if(typeof global.renderInventory==='function')global.renderInventory();return true;}
const API={RESOURCES:R,PROCESSING_RECIPES,render,renderList,grant,get:(id)=>R.find(x=>x.id===id)||null};global.DND_CRAFT_RESOURCES_V34=API;document.addEventListener('DOMContentLoaded',()=>setTimeout(render,600));
})(window);
