/**
 * expanded_bestiary_v39.js
 * ------------------------------------------------------------------
 * ЧТО ЭТО ЗА ФАЙЛ:
 * Расширенный внутриигровой бестиарий и слой creature-dependent loot для D&D 5e 2014.
 * Добавляет новые app-native statblock'и и связывает каждое существо с двумя
 * независимыми источниками добычи: pockets (карманы/снаряжение) и harvest (разделка).
 * Данные намеренно являются собственной игровой реализацией, а не копией текста
 * официальных statblock'ов.
 *
 * КАК РАБОТАЕТ:
 * - DNDExpandedBestiary.catalog содержит расширенные существа;
 * - при загрузке они регистрируются в DNDMonsters.catalog;
 * - lootProfile каждого существа регистрируется в DNDMonsterLoot.catalog;
 * - loot может ссылаться на CR, материалы ремесла, трофеи, еду и алхимические реагенты;
 * - bestiary UI показывает CR, XP, HP и ключевые источники добычи;
 * - getHarvestPreview() позволяет другим системам получить ожидаемые категории добычи.
 *
 * ОСНОВНЫЕ ПЕРЕМЕННЫЕ:
 * CREATURES, DNDExpandedBestiary.catalog, DNDMonsters.catalog,
 * DNDMonsterLoot.catalog, harvest, pockets.
 *
 * НЕ ИЗМЕНЯЕТ Wallpapers.js/Ambiences.js.
 * ------------------------------------------------------------------
 */
(function(global){
  'use strict';
  var CREATURES={
    'Бандит':{name:'Бандит',cr:'1/8',xp:25,ac:12,hp:9,maxHp:9,initiative:1,speed:30,abilities:{str:11,dex:13,con:12,int:10,wis:10,cha:10},actions:[{name:'Короткий меч',kind:'attack',bonus:3,damage:'1d6+1',damageType:'колющий'},{name:'Лёгкий арбалет',kind:'attack',bonus:3,damage:'1d8+1',damageType:'колющий'}],loot:{pockets:{rolls:1,table:[
      {weight:45,item:{name:'Медные и серебряные монеты',category:'currency',count:[4,16]}},{weight:20,item:{name:'Короткий меч',category:'weapons',count:1}},{weight:12,item:{name:'Арбалетный болт',category:'junk',count:[2,6]}},{weight:10,item:{name:'Кусок кожи',category:'materials',count:[1,2]}},{weight:8,item:{name:'Ключ от сундука',category:'junk',count:1}},{weight:5,item:{name:'Сухой паёк',category:'consumables',count:1}}
    ]},harvest:[{name:'Бандитская кожа',category:'materials',count:[1,2],guaranteed:true,tags:['hide','leather'],skill:'survival',tool:'p_tool_leatherworker',dc:10}]}},
    'Кобольд':{name:'Кобольд',cr:'1/8',xp:25,ac:12,hp:6,maxHp:6,initiative:2,speed:30,abilities:{str:7,dex:15,con:9,int:8,wis:7,cha:8},actions:[{name:'Кинжал',kind:'attack',bonus:4,damage:'1d4+2',damageType:'колющий'},{name:'Праща',kind:'attack',bonus:4,damage:'1d4+2',damageType:'дробящий'}],loot:{pockets:{rolls:1,table:[{weight:40,item:{name:'Медные монеты',category:'currency',count:[3,12]}},{weight:20,item:{name:'Каменный наконечник',category:'materials',count:[1,3]}},{weight:15,item:{name:'Праща',category:'weapons',count:1}},{weight:15,item:{name:'Драгоценный камешек',category:'materials',count:1}},{weight:10,item:{name:'Странный ключ',category:'junk',count:1}}]},harvest:[{name:'Кобольдская чешуйчатая кожа',category:'materials',count:[1,2],guaranteed:true,tags:['scale','leather'],skill:'survival',tool:'p_tool_leatherworker',dc:10},{name:'Малый рог',category:'materials',count:[1,2],guaranteed:true,tags:['horn'],skill:'medicine',dc:10}]}},
    'Бугбир':{name:'Бугбир',cr:'1',xp:200,ac:16,hp:27,maxHp:27,initiative:2,speed:30,abilities:{str:15,dex:14,con:13,int:8,wis:11,cha:9},actions:[{name:'Дубинка',kind:'attack',bonus:4,damage:'1d8+2',damageType:'дробящий'},{name:'Удар дубиной',kind:'attack',bonus:4,damage:'2d8+2',damageType:'дробящий'}],loot:{pockets:{rolls:2,table:[{weight:30,item:{name:'Серебряные монеты',category:'currency',count:[5,20]}},{weight:20,item:{name:'Грубая дубина',category:'weapons',count:1}},{weight:15,item:{name:'Кожаные ремни',category:'materials',count:[1,3]}},{weight:15,item:{name:'Железный лом',category:'materials',count:[1,4]}},{weight:10,item:{name:'Талисман банды',category:'junk',count:1}},{weight:10,item:{name:'Сухое мясо',category:'consumables',count:[1,2]}}]},harvest:[{name:'Грубая шкура бугбира',category:'materials',count:[1,2],guaranteed:true,tags:['hide','leather','large'],skill:'survival',tool:'p_tool_leatherworker',dc:12},{name:'Крупный клык',category:'materials',count:[1,3],guaranteed:true,tags:['bone','trophy'],skill:'medicine',dc:12}]}},
    'Гнолл':{name:'Гнолл',cr:'1/2',xp:100,ac:15,hp:22,maxHp:22,initiative:2,speed:30,abilities:{str:14,dex:12,con:13,int:6,wis:10,cha:7},actions:[{name:'Укус',kind:'attack',bonus:4,damage:'1d6+2',damageType:'колющий'},{name:'Копьё',kind:'attack',bonus:4,damage:'1d6+2',damageType:'колющий'}],loot:{pockets:{rolls:1,table:[{weight:35,item:{name:'Медные и серебряные монеты',category:'currency',count:[5,18]}},{weight:20,item:{name:'Копьё',category:'weapons',count:1}},{weight:15,item:{name:'Костяной амулет',category:'junk',count:1}},{weight:15,item:{name:'Кожа',category:'materials',count:[1,2]}},{weight:15,item:{name:'Сырое мясо',category:'consumables',count:[1,3]}}]},harvest:[{name:'Гноллья шкура',category:'materials',count:[1,2],guaranteed:true,tags:['hide','leather'],skill:'survival',tool:'p_tool_leatherworker',dc:12},{name:'Гнолльский зуб',category:'materials',count:[1,4],guaranteed:true,tags:['bone','trophy'],skill:'medicine',dc:12},{name:'Гнолльское мясо',category:'materials',count:[2,5],guaranteed:true,tags:['food','meat'],skill:'medicine',dc:11}]}},
    'Гигантский паук':{name:'Гигантский паук',cr:'1',xp:200,ac:14,hp:26,maxHp:26,initiative:3,speed:30,abilities:{str:14,dex:16,con:12,int:2,wis:11,cha:4},actions:[{name:'Укус',kind:'attack',bonus:5,damage:'1d8+3',damageType:'колющий',save:{stat:'con',dc:11,onFail:'Отравление'}},{name:'Паутина',kind:'utility',description:'Опутывает пространство липкой паутиной.'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Паучий шёлк',category:'materials',count:[2,5],guaranteed:true,tags:['silk','textile','alchemy'],skill:'survival',tool:'p_tool_weaver',dc:12},{name:'Паучий яд',category:'materials',count:[1,2],guaranteed:false,chance:.65,tags:['venom','alchemy'],skill:'medicine',tool:'p_tool_alchemist',dc:13},{name:'Паучий хитин',category:'materials',count:[1,3],guaranteed:true,tags:['chitin'],skill:'survival',dc:12}]}},
    'Лютый волк':{name:'Лютый волк',cr:'1',xp:200,ac:14,hp:30,maxHp:30,initiative:2,speed:50,abilities:{str:17,dex:15,con:15,int:3,wis:12,cha:7},actions:[{name:'Укус',kind:'attack',bonus:5,damage:'2d6+3',damageType:'колющий',save:{stat:'str',dc:13,onFail:'Сбит с ног'}}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Шкура лютого волка',category:'materials',count:[1,2],guaranteed:true,tags:['hide','leather','pristine-hide'],skill:'survival',tool:'p_tool_leatherworker',dc:14,qualityBonus:true},{name:'Клык лютого волка',category:'materials',count:[2,4],guaranteed:true,tags:['bone','trophy'],skill:'medicine',dc:13},{name:'Мясо лютого волка',category:'materials',count:[3,6],guaranteed:true,tags:['food','meat'],skill:'medicine',dc:11}]}},
    'Бурый медведь':{name:'Бурый медведь',cr:'1',xp:200,ac:11,hp:34,maxHp:34,initiative:0,speed:40,abilities:{str:19,dex:10,con:16,int:2,wis:13,cha:7},actions:[{name:'Укус',kind:'attack',bonus:5,damage:'1d8+4',damageType:'колющий'},{name:'Когти',kind:'attack',bonus:5,damage:'2d6+4',damageType:'рубящий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Медвежья шкура',category:'materials',count:[1,2],guaranteed:true,tags:['hide','leather','fur'],skill:'survival',tool:'p_tool_leatherworker',dc:13,qualityBonus:true},{name:'Медвежий жир',category:'materials',count:[1,3],guaranteed:true,tags:['fat','alchemy'],skill:'survival',dc:11},{name:'Медвежье мясо',category:'materials',count:[4,8],guaranteed:true,tags:['food','meat'],skill:'medicine',dc:10}]}},
    'Совомедведь':{name:'Совомедведь',cr:'3',xp:700,ac:13,hp:59,maxHp:59,initiative:1,speed:40,abilities:{str:20,dex:12,con:17,int:3,wis:12,cha:7},actions:[{name:'Клюв',kind:'attack',bonus:7,damage:'1d10+5',damageType:'колющий'},{name:'Когти',kind:'attack',bonus:7,damage:'2d8+5',damageType:'рубящий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Перья совомедведя',category:'materials',count:[4,10],guaranteed:true,tags:['feather','textile','fletching'],skill:'survival',dc:13},{name:'Толстая шкура',category:'materials',count:[1,3],guaranteed:true,tags:['hide','leather','fur'],skill:'survival',tool:'p_tool_leatherworker',dc:15,qualityBonus:true},{name:'Совомедвежий коготь',category:'materials',count:[2,5],guaranteed:true,tags:['bone','trophy'],skill:'medicine',dc:14}]}},
    'Гарпия':{name:'Гарпия',cr:'1',xp:200,ac:11,hp:38,maxHp:38,initiative:1,speed:20,abilities:{str:12,dex:13,con:10,int:7,wis:10,cha:13},actions:[{name:'Когти',kind:'attack',bonus:3,damage:'2d4+1',damageType:'рубящий'},{name:'Леденящая песнь',kind:'utility',description:'Магическая песнь отвлекает и сбивает с толку.'}],loot:{pockets:{rolls:1,table:[{weight:40,item:{name:'Медные монеты',category:'currency',count:[4,15]}},{weight:25,item:{name:'Украшение',category:'accessories',count:1}},{weight:20,item:{name:'Украденный ключ',category:'junk',count:1}},{weight:15,item:{name:'Разноцветная лента',category:'materials',count:[1,3]}}]},harvest:[{name:'Перья гарпии',category:'materials',count:[4,8],guaranteed:true,tags:['feather','textile'],skill:'survival',dc:12},{name:'Голосовая мембрана',category:'materials',count:1,guaranteed:false,chance:.45,tags:['organ','magic'],skill:'medicine',dc:14}]}},
    'Гуль':{name:'Гуль',cr:'1',xp:200,ac:12,hp:22,maxHp:22,initiative:2,speed:30,abilities:{str:13,dex:15,con:10,int:7,wis:10,cha:6},actions:[{name:'Когти',kind:'attack',bonus:4,damage:'2d4+2',damageType:'рубящий',save:{stat:'con',dc:10,onFail:'Паралич'}},{name:'Укус',kind:'attack',bonus:2,damage:'2d6',damageType:'колющий'}],loot:{pockets:{rolls:1,table:[{weight:50,item:{name:'Погребальные монеты',category:'currency',count:[1,10]}},{weight:20,item:{name:'Ржавый кинжал',category:'junk',count:1}},{weight:15,item:{name:'Сгнивший амулет',category:'junk',count:1}},{weight:15,item:{name:'Костяной фрагмент',category:'materials',count:[1,3]}}]},harvest:[{name:'Некротическая ткань',category:'materials',count:[1,2],guaranteed:true,tags:['undead','necrotic','alchemy'],skill:'medicine',dc:13},{name:'Гульский коготь',category:'materials',count:[2,4],guaranteed:true,tags:['bone','trophy'],skill:'medicine',dc:12}]}},
    'Вайт':{name:'Вайт',cr:'3',xp:700,ac:14,hp:45,maxHp:45,initiative:2,speed:30,abilities:{str:15,dex:14,con:16,int:10,wis:13,cha:15},actions:[{name:'Меч',kind:'attack',bonus:4,damage:'1d8+2',damageType:'рубящий'},{name:'Вытягивание жизненной силы',kind:'utility',description:'Удар ослабляет жизненную силу цели.'}],loot:{pockets:{rolls:2,table:[{weight:35,item:{name:'Серебряные монеты',category:'currency',count:[10,30]}},{weight:20,item:{name:'Старый меч',category:'weapons',count:1}},{weight:15,item:{name:'Чёрный камень',category:'materials',count:1}},{weight:15,item:{name:'Ритуальная ткань',category:'materials',count:[1,2]}},{weight:15,item:{name:'Погребальный знак',category:'junk',count:1}}]},harvest:[{name:'Некротическая кость',category:'materials',count:[2,5],guaranteed:true,tags:['bone','undead','necrotic'],skill:'medicine',dc:15},{name:'Тёмная эссенция',category:'materials',count:1,guaranteed:false,chance:.5,tags:['magic','necrotic','alchemy'],skill:'medicine',dc:16}]}},
    'Мимик':{name:'Мимик',cr:'2',xp:450,ac:12,hp:45,maxHp:45,initiative:1,speed:15,abilities:{str:17,dex:12,con:15,int:5,wis:13,cha:8},actions:[{name:'Псевдоподия',kind:'attack',bonus:5,damage:'1d8+3',damageType:'дробящий'},{name:'Клей',kind:'utility',description:'Липкая поверхность удерживает предметы.'}],loot:{pockets:{rolls:2,table:[{weight:40,item:{name:'Случайная монета',category:'currency',count:[5,25]}},{weight:25,item:{name:'Поддельный драгоценный камень',category:'junk',count:1}},{weight:20,item:{name:'Кусок металла',category:'materials',count:[1,3]}},{weight:15,item:{name:'Липкий реагент',category:'materials',count:[1,2]}}]},harvest:[{name:'Мимическая слизь',category:'materials',count:[1,3],guaranteed:true,tags:['slime','acid','alchemy'],skill:'medicine',dc:14},{name:'Мимическая кожа',category:'materials',count:[1,2],guaranteed:true,tags:['hide','elastic'],skill:'survival',tool:'p_tool_leatherworker',dc:15}]}},
    'Базилиск':{name:'Базилиск',cr:'3',xp:700,ac:15,hp:52,maxHp:52,initiative:-1,speed:20,abilities:{str:16,dex:8,con:15,int:2,wis:8,cha:7},actions:[{name:'Укус',kind:'attack',bonus:5,damage:'2d6+3',damageType:'колющий',save:{stat:'con',dc:12,onFail:'Отравление'}},{name:'Окаменяющий взгляд',kind:'utility',description:'Опасный взгляд постепенно минерализует плоть.'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Базилисковая чешуя',category:'materials',count:[3,6],guaranteed:true,tags:['scale','armor','magic'],skill:'survival',tool:'p_tool_leatherworker',dc:15},{name:'Базилисковый глаз',category:'materials',count:1,guaranteed:false,chance:.4,tags:['organ','petrification','magic'],skill:'medicine',dc:17},{name:'Базилисковый желчный камень',category:'materials',count:1,guaranteed:true,tags:['stone','alchemy'],skill:'medicine',dc:15}]}},
    'Мантикора':{name:'Мантикора',cr:'3',xp:700,ac:14,hp:68,maxHp:68,initiative:3,speed:30,abilities:{str:17,dex:16,con:17,int:5,wis:12,cha:8},actions:[{name:'Когти',kind:'attack',bonus:5,damage:'2d4+3',damageType:'рубящий'},{name:'Шип',kind:'attack',bonus:5,damage:'1d8+3',damageType:'колющий'}],loot:{pockets:{rolls:1,table:[{weight:50,item:{name:'Монеты',category:'currency',count:[10,35]}},{weight:20,item:{name:'Старая сбруя',category:'materials',count:[1,2]}},{weight:15,item:{name:'Металлический наконечник',category:'materials',count:[1,3]}},{weight:15,item:{name:'Трофей охотника',category:'junk',count:1}}]},harvest:[{name:'Мантикорьи шипы',category:'materials',count:[4,10],guaranteed:true,tags:['spine','bone','weapon'],skill:'survival',dc:15},{name:'Мантикорья шкура',category:'materials',count:[1,2],guaranteed:true,tags:['hide','leather'],skill:'survival',tool:'p_tool_leatherworker',dc:15},{name:'Мантикорье мясо',category:'materials',count:[3,7],guaranteed:true,tags:['food','meat'],skill:'medicine',dc:12}]}},
    'Тролль':{name:'Тролль',cr:'5',xp:1800,ac:15,hp:84,maxHp:84,initiative:1,speed:30,abilities:{str:18,dex:13,con:20,int:7,wis:9,cha:7},actions:[{name:'Когти',kind:'attack',bonus:7,damage:'2d6+4',damageType:'рубящий'},{name:'Укус',kind:'attack',bonus:7,damage:'1d6+4',damageType:'колющий'}],loot:{pockets:{rolls:2,table:[{weight:40,item:{name:'Большие монеты',category:'currency',count:[15,45]}},{weight:20,item:{name:'Железный лом',category:'materials',count:[2,5]}},{weight:20,item:{name:'Разорванная одежда',category:'materials',count:[1,3]}},{weight:20,item:{name:'Странный хлам',category:'junk',count:[1,2]}}]},harvest:[{name:'Троллья шкура',category:'materials',count:[2,4],guaranteed:true,tags:['hide','leather','regeneration'],skill:'survival',tool:'p_tool_leatherworker',dc:17,qualityBonus:true},{name:'Троллья кровь',category:'materials',count:[1,3],guaranteed:true,tags:['blood','regeneration','alchemy'],skill:'medicine',dc:17},{name:'Тролльский коготь',category:'materials',count:[2,5],guaranteed:true,tags:['bone','trophy'],skill:'medicine',dc:16}]}},
    'Молодой дракон':{name:'Молодой дракон',cr:'6',xp:2300,ac:18,hp:115,maxHp:115,initiative:2,speed:40,abilities:{str:19,dex:10,con:17,int:12,wis:13,cha:15},actions:[{name:'Укус',kind:'attack',bonus:7,damage:'2d10+4',damageType:'колющий'},{name:'Когти',kind:'attack',bonus:7,damage:'2d6+4',damageType:'рубящий'},{name:'Дыхание',kind:'utility',description:'Область элементального дыхания зависит от разновидности дракона.'}],loot:{pockets:{rolls:2,table:[{weight:45,item:{name:'Золотые монеты',category:'currency',count:[20,80]}},{weight:15,item:{name:'Драгоценный камень',category:'materials',count:1}},{weight:15,item:{name:'Старый артефактный лом',category:'materials',count:[1,2]}},{weight:15,item:{name:'Кость оружия',category:'materials',count:1}},{weight:10,item:{name:'Свиток или карта',category:'junk',count:1}}]},harvest:[{name:'Драконья чешуя',category:'materials',count:[8,16],guaranteed:true,tags:['scale','armor','dragon'],skill:'survival',tool:'p_tool_leatherworker',dc:18,qualityBonus:true},{name:'Драконья кровь',category:'materials',count:[2,5],guaranteed:true,tags:['blood','dragon','alchemy'],skill:'medicine',dc:18},{name:'Драконьи кости',category:'materials',count:[2,5],guaranteed:true,tags:['bone','dragon','weapon'],skill:'medicine',dc:19},{name:'Драконье сердце',category:'materials',count:1,guaranteed:false,chance:.2,tags:['organ','dragon','magic'],skill:'medicine',dc:21,rareChance:.25}]}}
  };



  /* v41 CONTENT EXPANSION: creature families for encounters + physically plausible loot. */
  Object.assign(CREATURES, {
    'Олень':{name:'Олень',cr:'0',xp:10,ac:13,hp:4,maxHp:4,initiative:2,speed:50,abilities:{str:11,dex:16,con:11,int:2,wis:14,cha:5},actions:[{name:'Рога',kind:'attack',bonus:2,damage:'1d4',damageType:'колющий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Оленья шкура',category:'materials',count:[1,2],guaranteed:true,tags:['hide','leather'],skill:'survival',tool:'p_tool_leatherworker',dc:9},{name:'Оленье мясо',category:'materials',count:[3,6],guaranteed:true,tags:['food','meat'],skill:'medicine',dc:9},{name:'Оленьи рога',category:'materials',count:[1,2],guaranteed:false,chance:.35,tags:['horn','bone'],skill:'survival',dc:11}]}},
    'Кабан':{name:'Кабан',cr:'1/4',xp:50,ac:11,hp:11,maxHp:11,initiative:0,speed:40,abilities:{str:13,dex:11,con:12,int:2,wis:9,cha:5},actions:[{name:'Клык',kind:'attack',bonus:3,damage:'1d6+1',damageType:'рубящий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Кабанья шкура',category:'materials',count:[1,2],guaranteed:true,tags:['hide','leather'],skill:'survival',tool:'p_tool_leatherworker',dc:10},{name:'Кабанье мясо',category:'materials',count:[3,7],guaranteed:true,tags:['food','meat','fat'],skill:'medicine',dc:9},{name:'Кабаний клык',category:'materials',count:[1,2],guaranteed:true,tags:['tusk','bone','trophy'],skill:'medicine',dc:10}]}},
    'Гигантская крыса':{name:'Гигантская крыса',cr:'1/8',xp:25,ac:12,hp:7,maxHp:7,initiative:2,speed:30,abilities:{str:7,dex:15,con:11,int:2,wis:10,cha:4},actions:[{name:'Укус',kind:'attack',bonus:4,damage:'1d4+2',damageType:'колющий',save:{stat:'con',dc:10,onFail:'Болезнь'}}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Крысиная шкура',category:'materials',count:[1,2],guaranteed:true,tags:['hide','leather'],skill:'survival',tool:'p_tool_leatherworker',dc:9},{name:'Крысиные клыки',category:'materials',count:[1,4],guaranteed:true,tags:['bone','trophy'],skill:'medicine',dc:9},{name:'Крысиное мясо',category:'materials',count:[1,3],guaranteed:false,chance:.6,tags:['food','meat'],skill:'medicine',dc:10}]}},
    'Гигантская лягушка':{name:'Гигантская лягушка',cr:'1/4',xp:50,ac:11,hp:18,maxHp:18,initiative:1,speed:30,abilities:{str:12,dex:13,con:11,int:2,wis:10,cha:3},actions:[{name:'Укус',kind:'attack',bonus:3,damage:'1d6+1',damageType:'колющий'},{name:'Язык',kind:'utility',description:'Длинный язык подтягивает добычу.'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Лягушачья кожа',category:'materials',count:[1,2],guaranteed:true,tags:['hide','elastic'],skill:'survival',tool:'p_tool_leatherworker',dc:10},{name:'Лягушачья железа',category:'materials',count:1,guaranteed:false,chance:.5,tags:['organ','alchemy'],skill:'medicine',dc:12},{name:'Лягушачье мясо',category:'materials',count:[2,4],guaranteed:true,tags:['food','meat'],skill:'medicine',dc:9}]}},
    'Крокодил':{name:'Крокодил',cr:'1/2',xp:100,ac:12,hp:19,maxHp:19,initiative:0,speed:20,abilities:{str:15,dex:10,con:13,int:2,wis:10,cha:5},actions:[{name:'Укус',kind:'attack',bonus:4,damage:'1d10+2',damageType:'колющий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Крокодилья кожа',category:'materials',count:[2,4],guaranteed:true,tags:['hide','leather','scale'],skill:'survival',tool:'p_tool_leatherworker',dc:12},{name:'Крокодильи зубы',category:'materials',count:[4,8],guaranteed:true,tags:['bone','trophy'],skill:'medicine',dc:11},{name:'Крокодилье мясо',category:'materials',count:[3,6],guaranteed:true,tags:['food','meat'],skill:'medicine',dc:10}]}},
    'Гигантская гиена':{name:'Гигантская гиена',cr:'1',xp:200,ac:12,hp:45,maxHp:45,initiative:2,speed:50,abilities:{str:16,dex:14,con:14,int:2,wis:12,cha:5},actions:[{name:'Укус',kind:'attack',bonus:5,damage:'2d6+3',damageType:'колющий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Гиеновая шкура',category:'materials',count:[1,2],guaranteed:true,tags:['hide','leather'],skill:'survival',tool:'p_tool_leatherworker',dc:13},{name:'Гиеновые клыки',category:'materials',count:[2,5],guaranteed:true,tags:['bone','trophy'],skill:'medicine',dc:12},{name:'Гиеновое мясо',category:'materials',count:[3,7],guaranteed:true,tags:['food','meat'],skill:'medicine',dc:10}]}},
    'Гигантский удав':{name:'Гигантский удав',cr:'2',xp:450,ac:12,hp:60,maxHp:60,initiative:2,speed:30,abilities:{str:19,dex:14,con:12,int:1,wis:10,cha:3},actions:[{name:'Укус',kind:'attack',bonus:6,damage:'1d8+4',damageType:'колющий'},{name:'Сдавливание',kind:'attack',bonus:6,damage:'2d8+4',damageType:'дробящий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Змеиная кожа',category:'materials',count:[2,5],guaranteed:true,tags:['hide','leather','scale'],skill:'survival',tool:'p_tool_leatherworker',dc:14},{name:'Змеиный яд',category:'materials',count:[1,2],guaranteed:false,chance:.55,tags:['venom','alchemy'],skill:'medicine',tool:'p_tool_alchemist',dc:15},{name:'Змеиное мясо',category:'materials',count:[3,8],guaranteed:true,tags:['food','meat'],skill:'medicine',dc:11}]}},
    'Гигантский орёл':{name:'Гигантский орёл',cr:'1',xp:200,ac:13,hp:26,maxHp:26,initiative:3,speed:10,abilities:{str:16,dex:17,con:13,int:8,wis:14,cha:10},actions:[{name:'Когти',kind:'attack',bonus:5,damage:'1d6+3',damageType:'рубящий'},{name:'Клюв',kind:'attack',bonus:5,damage:'1d8+3',damageType:'колющий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Перо гигантского орла',category:'materials',count:[4,10],guaranteed:true,tags:['feather','fletching','textile'],skill:'survival',dc:12},{name:'Коготь гигантского орла',category:'materials',count:[2,4],guaranteed:true,tags:['bone','trophy'],skill:'medicine',dc:13},{name:'Мясо гигантского орла',category:'materials',count:[2,5],guaranteed:true,tags:['food','meat'],skill:'medicine',dc:10}]}},
    'Гигантская сова':{name:'Гигантская сова',cr:'1/4',xp:50,ac:12,hp:19,maxHp:19,initiative:2,speed:5,abilities:{str:13,dex:15,con:12,int:8,wis:13,cha:10},actions:[{name:'Когти',kind:'attack',bonus:4,damage:'2d4+2',damageType:'рубящий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Перо гигантской совы',category:'materials',count:[3,8],guaranteed:true,tags:['feather','fletching','textile'],skill:'survival',dc:11},{name:'Совиный глаз',category:'materials',count:2,guaranteed:true,tags:['organ','perception','alchemy'],skill:'medicine',dc:12}]}},
    'Мерцающий пёс':{name:'Мерцающий пёс',cr:'1/2',xp:100,ac:13,hp:22,maxHp:22,initiative:3,speed:40,abilities:{str:12,dex:17,con:13,int:10,wis:13,cha:11},actions:[{name:'Укус',kind:'attack',bonus:5,damage:'1d6+3',damageType:'колющий'},{name:'Мерцание',kind:'utility',description:'Коротко перемещается между точками пространства.'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Мерцающая шерсть',category:'materials',count:[1,2],guaranteed:true,tags:['fur','magic','textile'],skill:'survival',tool:'p_tool_leatherworker',dc:14},{name:'Фазовая железа',category:'materials',count:1,guaranteed:false,chance:.35,tags:['organ','magic','alchemy'],skill:'medicine',dc:16}]}},
    'Дисplacer-зверь':{name:'Дисplacer-зверь',cr:'3',xp:700,ac:13,hp:85,maxHp:85,initiative:2,speed:40,abilities:{str:18,dex:15,con:16,int:6,wis:12,cha:8},actions:[{name:'Щупальце',kind:'attack',bonus:6,damage:'1d6+4',damageType:'рубящий'},{name:'Когти',kind:'attack',bonus:6,damage:'1d6+4',damageType:'рубящий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Дисplacer-шкура',category:'materials',count:[2,4],guaranteed:true,tags:['hide','leather','magic'],skill:'survival',tool:'p_tool_leatherworker',dc:16},{name:'Фазовый усик',category:'materials',count:[1,2],guaranteed:false,chance:.5,tags:['organ','magic'],skill:'medicine',dc:17}]}},
    'Ржавник':{name:'Ржавник',cr:'1/2',xp:100,ac:14,hp:27,maxHp:27,initiative:2,speed:40,abilities:{str:13,dex:12,con:13,int:2,wis:13,cha:6},actions:[{name:'Усики',kind:'utility',description:'Разрушает металлические предметы при контакте.'},{name:'Укус',kind:'attack',bonus:3,damage:'1d8+1',damageType:'колющий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Ржавниковый хитин',category:'materials',count:[2,4],guaranteed:true,tags:['chitin','metal','armor'],skill:'survival',dc:13},{name:'Каталитическая железа',category:'materials',count:1,guaranteed:false,chance:.45,tags:['organ','rust','alchemy'],skill:'medicine',dc:15}]}},
    'Анкег':{name:'Анкег',cr:'2',xp:450,ac:14,hp:39,maxHp:39,initiative:1,speed:30,abilities:{str:17,dex:11,con:13,int:1,wis:13,cha:6},actions:[{name:'Укус',kind:'attack',bonus:5,damage:'2d6+3',damageType:'колющий'},{name:'Кислота',kind:'utility',description:'Извергает кислотную струю.'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Анкеговый панцирь',category:'materials',count:[3,6],guaranteed:true,tags:['chitin','armor','acid'],skill:'survival',tool:'p_tool_leatherworker',dc:15},{name:'Кислотная железа анкега',category:'materials',count:1,guaranteed:false,chance:.7,tags:['organ','acid','alchemy'],skill:'medicine',tool:'p_tool_alchemist',dc:16},{name:'Анкеговое мясо',category:'materials',count:[2,5],guaranteed:true,tags:['food','meat'],skill:'medicine',dc:11}]}},
    'Падальщик-ползун':{name:'Падальщик-ползун',cr:'2',xp:450,ac:13,hp:51,maxHp:51,initiative:1,speed:30,abilities:{str:14,dex:13,con:16,int:1,wis:12,cha:5},actions:[{name:'Щупальца',kind:'attack',bonus:5,damage:'1d4+2',damageType:'яд',save:{stat:'con',dc:13,onFail:'Отравление'}}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Паралитический яд',category:'materials',count:[1,2],guaranteed:false,chance:.7,tags:['venom','paralysis','alchemy'],skill:'medicine',tool:'p_tool_alchemist',dc:15},{name:'Хитиновая пластина',category:'materials',count:[2,4],guaranteed:true,tags:['chitin','armor'],skill:'survival',dc:13}]}},
    'Слизь-кислота':{name:'Слизь-кислота',cr:'1/2',xp:100,ac:8,hp:22,maxHp:22,initiative:-2,speed:10,abilities:{str:10,dex:6,con:16,int:1,wis:6,cha:1},actions:[{name:'Кислотный контакт',kind:'attack',bonus:3,damage:'2d6',damageType:'кислота'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Кислотная слизь',category:'materials',count:[1,3],guaranteed:true,tags:['slime','acid','alchemy'],skill:'medicine',tool:'p_tool_alchemist',dc:13},{name:'Слизистая мембрана',category:'materials',count:[1,2],guaranteed:true,tags:['elastic','alchemy'],skill:'survival',dc:11}]}},
    'Огненный элементаль':{name:'Огненный элементаль',cr:'5',xp:1800,ac:13,hp:102,maxHp:102,initiative:5,speed:50,abilities:{str:10,dex:17,con:16,int:6,wis:10,cha:7},actions:[{name:'Огненный удар',kind:'attack',bonus:6,damage:'2d6+3',damageType:'огонь'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Огненная эссенция',category:'materials',count:[1,3],guaranteed:true,tags:['fire','elemental','alchemy'],skill:'arcana',dc:16},{name:'Элементальная зола',category:'materials',count:[1,3],guaranteed:true,tags:['ash','fire','alchemy'],skill:'arcana',dc:14}]}},
    'Водяной элементаль':{name:'Водяной элементаль',cr:'5',xp:1800,ac:14,hp:114,maxHp:114,initiative:2,speed:30,abilities:{str:18,dex:14,con:18,int:5,wis:10,cha:8},actions:[{name:'Удар волной',kind:'attack',bonus:7,damage:'2d8+4',damageType:'дробящий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Водяная эссенция',category:'materials',count:[1,3],guaranteed:true,tags:['water','elemental','alchemy'],skill:'arcana',dc:16},{name:'Сердце течения',category:'materials',count:1,guaranteed:false,chance:.3,tags:['water','magic'],skill:'arcana',dc:18}]}},
    'Воздушный элементаль':{name:'Воздушный элементаль',cr:'5',xp:1800,ac:15,hp:90,maxHp:90,initiative:5,speed:90,abilities:{str:14,dex:20,con:14,int:6,wis:10,cha:6},actions:[{name:'Вихрь',kind:'attack',bonus:8,damage:'2d8+5',damageType:'дробящий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Воздушная эссенция',category:'materials',count:[1,3],guaranteed:true,tags:['air','elemental','alchemy'],skill:'arcana',dc:16},{name:'Сжатый вихрь',category:'materials',count:1,guaranteed:false,chance:.3,tags:['air','magic'],skill:'arcana',dc:18}]}},
    'Земляной элементаль':{name:'Земляной элементаль',cr:'5',xp:1800,ac:17,hp:126,maxHp:126,initiative:-1,speed:30,abilities:{str:20,dex:8,con:20,int:5,wis:10,cha:5},actions:[{name:'Удар',kind:'attack',bonus:8,damage:'2d8+5',damageType:'дробящий'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Земляная эссенция',category:'materials',count:[1,3],guaranteed:true,tags:['earth','elemental','alchemy'],skill:'arcana',dc:16},{name:'Сердце камня',category:'materials',count:1,guaranteed:false,chance:.3,tags:['stone','magic'],skill:'arcana',dc:18}]}},
    'Тень':{name:'Тень',cr:'1/2',xp:100,ac:12,hp:16,maxHp:16,initiative:2,speed:40,abilities:{str:6,dex:14,con:13,int:6,wis:10,cha:8},actions:[{name:'Высасывание силы',kind:'attack',bonus:4,damage:'1d4+2',damageType:'некротический'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Теневой сгусток',category:'materials',count:[1,2],guaranteed:true,tags:['shadow','necrotic','magic','alchemy'],skill:'arcana',dc:14},{name:'Эктоплазма',category:'materials',count:[1,2],guaranteed:true,tags:['ectoplasm','undead','alchemy'],skill:'arcana',dc:13}]}},
    'Призрак':{name:'Призрак',cr:'1',xp:200,ac:11,hp:22,maxHp:22,initiative:2,speed:40,abilities:{str:7,dex:13,con:10,int:10,wis:12,cha:17},actions:[{name:'Призрачное касание',kind:'attack',bonus:5,damage:'2d6',damageType:'некротический'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Эктоплазма',category:'materials',count:[1,3],guaranteed:true,tags:['ectoplasm','undead','alchemy'],skill:'arcana',dc:15},{name:'Призрачная нить',category:'materials',count:[1,2],guaranteed:false,chance:.45,tags:['textile','ghost','magic'],skill:'arcana',dc:16}]}},
    'Спектр':{name:'Спектр',cr:'1',xp:200,ac:12,hp:22,maxHp:22,initiative:3,speed:50,abilities:{str:1,dex:16,con:10,int:10,wis:10,cha:11},actions:[{name:'Похищение жизни',kind:'attack',bonus:4,damage:'3d6',damageType:'некротический'}],loot:{pockets:{rolls:0,table:[]},harvest:[{name:'Спектральная пыль',category:'materials',count:[1,3],guaranteed:true,tags:['undead','necrotic','alchemy'],skill:'arcana',dc:15},{name:'Эфирный осколок',category:'materials',count:1,guaranteed:false,chance:.35,tags:['magic','crystal'],skill:'arcana',dc:17}]}},
    'Культист':{name:'Культист',cr:'1/8',xp:25,ac:12,hp:9,maxHp:9,initiative:2,speed:30,abilities:{str:11,dex:12,con:10,int:10,wis:10,cha:10},actions:[{name:'Кинжал',kind:'attack',bonus:3,damage:'1d4+1',damageType:'колющий'}],loot:{pockets:{rolls:1,table:[{weight:35,item:{name:'Медные монеты',category:'currency',count:[3,12]}},{weight:25,item:{name:'Кинжал',category:'weapons',count:1}},{weight:20,item:{name:'Ритуальный символ',category:'junk',count:1}},{weight:10,item:{name:'Ладан',category:'materials',count:[1,3]}},{weight:10,item:{name:'Свиток',category:'consumables',count:1}}]},harvest:[{name:'Культовая одежда',category:'materials',count:[1,2],guaranteed:true,tags:['textile','cloth'],skill:'survival',dc:9}]}},
    'Аколит':{name:'Аколит',cr:'1/4',xp:50,ac:10,hp:9,maxHp:9,initiative:0,speed:30,abilities:{str:10,dex:10,con:10,int:10,wis:14,cha:11},actions:[{name:'Священный жезл',kind:'attack',bonus:2,damage:'1d6',damageType:'дробящий'}],loot:{pockets:{rolls:1,table:[{weight:40,item:{name:'Медные монеты',category:'currency',count:[5,15]}},{weight:20,item:{name:'Священный символ',category:'accessories',count:1}},{weight:20,item:{name:'Ладан',category:'materials',count:[1,3]}},{weight:20,item:{name:'Ритуальная книга',category:'junk',count:1}}]},harvest:[{name:'Ритуальная ткань',category:'materials',count:[1,2],guaranteed:true,tags:['textile','cloth'],skill:'survival',dc:9}]}},
    'Ветеран':{name:'Ветеран',cr:'3',xp:700,ac:17,hp:58,maxHp:58,initiative:1,speed:30,abilities:{str:16,dex:13,con:14,int:10,wis:11,cha:10},actions:[{name:'Меч',kind:'attack',bonus:5,damage:'1d8+3',damageType:'рубящий'},{name:'Арбалет',kind:'attack',bonus:3,damage:'1d10+1',damageType:'колющий'}],loot:{pockets:{rolls:2,table:[{weight:35,item:{name:'Серебряные монеты',category:'currency',count:[10,35]}},{weight:20,item:{name:'Ключи',category:'junk',count:1}},{weight:15,item:{name:'Точильный камень',category:'materials',count:1}},{weight:15,item:{name:'Зелье',category:'consumables',count:1}},{weight:15,item:{name:'Стальной жетон',category:'materials',count:1}}]},harvest:[{name:'Кожаная броня ветерана',category:'materials',count:1,guaranteed:true,tags:['leather','armor'],skill:'survival',tool:'p_tool_leatherworker',dc:13}]}},
    'Капитан разбойников':{name:'Капитан разбойников',cr:'2',xp:450,ac:15,hp:45,maxHp:45,initiative:3,speed:30,abilities:{str:15,dex:16,con:14,int:14,wis:11,cha:15},actions:[{name:'Рапира',kind:'attack',bonus:5,damage:'1d8+3',damageType:'колющий'},{name:'Кинжал',kind:'attack',bonus:5,damage:'1d4+3',damageType:'колющий'}],loot:{pockets:{rolls:2,table:[{weight:35,item:{name:'Золотые монеты',category:'currency',count:[5,20]}},{weight:20,item:{name:'Рапира',category:'weapons',count:1}},{weight:15,item:{name:'Отмычки',category:'junk',count:1}},{weight:15,item:{name:'Карта тайника',category:'junk',count:1}},{weight:15,item:{name:'Драгоценный камень',category:'materials',count:1}}]},harvest:[{name:'Капитанская кожаная броня',category:'materials',count:1,guaranteed:true,tags:['leather','armor'],skill:'survival',tool:'p_tool_leatherworker',dc:12}]}}
  });

  /*
   * V42 creature-family layer.
   * WHAT: groups creatures into reusable ecological/biological families without creating
   *       a second bestiary registry. Family data is metadata used by future regional
   *       variants, harvest modifiers, encounter generation and family-based crafting.
   * HOW: FAMILY_BY_CREATURE maps every current creature to exactly one primary family;
   *      FAMILY_DEFS stores the family label, category, habitat hints and future variant hooks.
   * IMPORTANT VARIABLES/APIS: FAMILY_DEFS, FAMILY_BY_CREATURE, getFamily(), listByFamily(),
   *      getFamilyMembers(), familySummary().
   */
  var FAMILY_DEFS={
    humanoid:{id:'humanoid',name:'Гуманоиды',category:'humanoid',habitats:['settlement','camp','ruins'],variantHooks:['culture','equipment','faction']},
    goblinoid:{id:'goblinoid',name:'Гоблиноиды',category:'humanoid',habitats:['caves','ruins','wilderness'],variantHooks:['clan','warband','camp']},
    gnoll:{id:'gnoll',name:'Гноллы',category:'humanoid',habitats:['savanna','wilderness','ruins'],variantHooks:['pack','scavenger','warband']},
    canid:{id:'canid',name:'Псовые',category:'beast',habitats:['forest','hills','wilderness'],variantHooks:['pack','coat','diet']},
    ursine:{id:'ursine',name:'Медвежьи',category:'beast',habitats:['forest','mountains','wilderness'],variantHooks:['season','coat','size']},
    avian:{id:'avian',name:'Птицы',category:'beast',habitats:['forest','mountains','coast'],variantHooks:['plumage','nest','diet']},
    reptile:{id:'reptile',name:'Рептилии',category:'beast',habitats:['swamp','jungle','coast'],variantHooks:['scale','venom','habitat']},
    vermin:{id:'vermin',name:'Вредители и мелкие существа',category:'beast',habitats:['dungeon','settlement','swamp'],variantHooks:['colony','disease','size']},
    amphibian:{id:'amphibian',name:'Земноводные',category:'beast',habitats:['swamp','marsh','forest'],variantHooks:['skin','venom','habitat']},
    ungulate:{id:'ungulate',name:'Копытные',category:'beast',habitats:['forest','plains','hills'],variantHooks:['season','antler','herd']},
    swine:{id:'swine',name:'Кабаньи',category:'beast',habitats:['forest','swamp','hills'],variantHooks:['tusk','season','herd']},
    hyena:{id:'hyena',name:'Гиены',category:'beast',habitats:['savanna','badlands','wilderness'],variantHooks:['pack','disease','diet']},
    insectoid:{id:'insectoid',name:'Членистоногие',category:'beast',habitats:['cave','forest','underdark'],variantHooks:['carapace','venom','colony']},
    monstrosity:{id:'monstrosity',name:'Чудовища',category:'monstrosity',habitats:['wilderness','ruins','underdark'],variantHooks:['mutation','territory','trophy']},
    ooze:{id:'ooze',name:'Слизи',category:'ooze',habitats:['dungeon','cave','ruins'],variantHooks:['acid','color','composition']},
    elemental:{id:'elemental',name:'Элементали',category:'elemental',habitats:['elemental_plane','ruins','wild_magic'],variantHooks:['element','manifestation','density']},
    undead:{id:'undead',name:'Нежить',category:'undead',habitats:['graveyard','ruins','dungeon'],variantHooks:['origin','haunt','essence']},
    dragon:{id:'dragon',name:'Драконы',category:'dragon',habitats:['mountains','caves','ancient_ruins'],variantHooks:['age','element','hoard']},
    magical_beast:{id:'magical_beast',name:'Магические звери',category:'magical_beast',habitats:['forest','wilderness','feywild'],variantHooks:['fey','territory','mutation']}
  };

  var FAMILY_BY_CREATURE={
    'Бандит':'humanoid','Кобольд':'goblinoid','Бугбир':'goblinoid','Гнолл':'gnoll',
    'Гигантский паук':'insectoid','Лютый волк':'canid','Бурый медведь':'ursine','Совомедведь':'monstrosity',
    'Гарпия':'monstrosity','Гуль':'undead','Вайт':'undead','Мимик':'monstrosity','Базилиск':'reptile',
    'Мантикора':'monstrosity','Тролль':'monstrosity','Молодой дракон':'dragon','Олень':'ungulate',
    'Кабан':'swine','Гигантская крыса':'vermin','Гигантская лягушка':'amphibian','Крокодил':'reptile',
    'Гигантская гиена':'hyena','Гигантский удав':'reptile','Гигантский орёл':'avian','Гигантская сова':'avian',
    'Мерцающий пёс':'magical_beast','Дисplacer-зверь':'magical_beast','Ржавник':'insectoid','Анкег':'insectoid',
    'Падальщик-ползун':'insectoid','Слизь-кислота':'ooze','Огненный элементаль':'elemental','Водяной элементаль':'elemental',
    'Воздушный элементаль':'elemental','Земляной элементаль':'elemental','Тень':'undead','Призрак':'undead',
    'Спектр':'undead','Культист':'humanoid','Аколит':'humanoid','Ветеран':'humanoid','Капитан разбойников':'humanoid'
  };

  Object.keys(CREATURES).forEach(function(name){
    var familyId=FAMILY_BY_CREATURE[name]||'monstrosity';
    CREATURES[name].familyId=familyId;
    CREATURES[name].family=FAMILY_DEFS[familyId].name;
    CREATURES[name].familyCategory=FAMILY_DEFS[familyId].category;
  });

  function getFamily(name){
    var c=CREATURES[name];
    if(!c)return null;
    var id=c.familyId||FAMILY_BY_CREATURE[name];
    return id?clone(FAMILY_DEFS[id]):null;
  }
  function getFamilyMembers(familyId){
    return Object.keys(CREATURES).filter(function(name){return CREATURES[name].familyId===familyId;});
  }
  function listByFamily(familyId){
    return getFamilyMembers(familyId).map(function(name){return clone(CREATURES[name]);});
  }
  function familySummary(){
    return Object.keys(FAMILY_DEFS).map(function(id){
      var f=FAMILY_DEFS[id];
      return {id:id,name:f.name,category:f.category,count:getFamilyMembers(id).length,habitats:f.habitats.slice(),members:getFamilyMembers(id)};
    });
  }

  function clone(v){return JSON.parse(JSON.stringify(v));}
  function register(){
    if(global.DNDMonsters&&global.DNDMonsters.catalog){Object.keys(CREATURES).forEach(function(k){global.DNDMonsters.catalog[k]=clone(CREATURES[k]);});}
    if(global.DNDMonsterLoot&&global.DNDMonsterLoot.catalog){Object.keys(CREATURES).forEach(function(k){if(CREATURES[k].loot)global.DNDMonsterLoot.catalog[k]=clone(CREATURES[k].loot);});}
  }
  function getHarvestPreview(name){var c=CREATURES[name];if(!c||!c.loot)return[];return (c.loot.harvest||[]).map(function(x){return {name:x.name,category:x.category,tags:(x.tags||[]).slice(),guaranteed:!!x.guaranteed,dc:x.dc||null,tool:x.tool||null};});}
  function render(){
    var host=document.getElementById('dndCombatV3');if(!host||document.getElementById('dndExpandedBestiaryV41'))return;
    var box=document.createElement('div');box.id='dndExpandedBestiaryV41';box.className='card';
    var familyOpts='<option value="all">Все семейства</option>'+Object.keys(FAMILY_DEFS).filter(function(id){return getFamilyMembers(id).length;}).map(function(id){return '<option value="'+id+'">'+FAMILY_DEFS[id].name+' · '+getFamilyMembers(id).length+'</option>';}).join('');
    var opts=Object.keys(CREATURES).map(function(k){var c=CREATURES[k];return '<option data-family="'+c.familyId+'" value="'+String(k).replace(/"/g,'&quot;')+'">'+k+' · '+c.family+' · CR '+c.cr+' · '+c.hp+' HP</option>';}).join('');
    box.innerHTML='<h3>📚 Расширенный бестиарий 4.1</h3><p style="font-size:12px;color:#aaa">Семейства существ — общая основа для будущих региональных вариантов, генерации встреч и модификаторов добычи.</p><select id="dndExpandedBestiaryFamilyV41" style="width:100%;margin-bottom:6px">'+familyOpts+'</select><select id="dndExpandedBestiarySelectV41" style="width:100%">'+opts+'</select><div id="dndExpandedBestiaryInfoV41" style="margin-top:8px"></div><button class="btn-action" style="width:100%;margin-top:6px" onclick="dndExpandedBestiaryAddV41()">+ Добавить в encounter</button>';
    host.appendChild(box);
    var familySelect=document.getElementById('dndExpandedBestiaryFamilyV41');
    var creatureSelect=document.getElementById('dndExpandedBestiarySelectV41');
    if(familySelect)familySelect.addEventListener('change',function(){
      var id=familySelect.value;
      Array.prototype.forEach.call(creatureSelect.options,function(o){o.hidden=id!=='all'&&o.getAttribute('data-family')!==id;});
      var first=Array.prototype.find.call(creatureSelect.options,function(o){return !o.hidden;});
      if(first)creatureSelect.value=first.value;
      updateInfo();
    });
    if(creatureSelect)creatureSelect.addEventListener('change',updateInfo);
    updateInfo();
  }
  function updateInfo(){var s=document.getElementById('dndExpandedBestiarySelectV41'),el=document.getElementById('dndExpandedBestiaryInfoV41');if(!s||!el)return;var c=CREATURES[s.value];if(!c)return;var f=FAMILY_DEFS[c.familyId];el.innerHTML='<strong>'+c.name+'</strong> · CR '+c.cr+' · XP '+c.xp+' · AC '+c.ac+' · HP '+c.hp+'<br><small>Семейство: '+c.family+' · Среда: '+f.habitats.join(', ')+'</small><br><small>Разделка: '+getHarvestPreview(c.name).map(function(x){return x.name;}).join(', ')+'</small>';}
  global.DNDExpandedBestiary={VERSION:'41.1.0',catalog:CREATURES,families:FAMILY_DEFS,familyByCreature:FAMILY_BY_CREATURE,getHarvestPreview:getHarvestPreview,getFamily:getFamily,getFamilyMembers:getFamilyMembers,listByFamily:listByFamily,familySummary:familySummary,register:register};
  global.dndExpandedBestiaryAddV41=function(){var s=document.getElementById('dndExpandedBestiarySelectV41'),t=global.DNDMonsters&&global.DNDMonsters.catalog[s&&s.value];if(!t||typeof global.dndEncounterV2Add!=='function')return;var old=document.getElementById('dndMonsterV2Preset');if(old){old.value=s.value;global.dndEncounterV2Add();}else{var h=global.currentChar||global.currentCharacter;if(!h)return;h.encounters=h.encounters||[{id:'enc_'+Date.now(),name:'Новый encounter',combatants:[]}];var e=h.encounters[h.encounters.length-1];e.combatants.push(clone(t));if(typeof global.autoSaveCurrentCharacter==='function')global.autoSaveCurrentCharacter();}}
  if(global.addEventListener)global.addEventListener('DOMContentLoaded',function(){register();setTimeout(function(){render();var s=document.getElementById('dndExpandedBestiarySelectV41');if(s)s.addEventListener('change',updateInfo);},180);});
  register();
})(window);
