/**
 * gameplay_core_v57.js — Gameplay Core orchestration layer.
 *
 * V57 does not replace combat/network/loot/campaign engines. It gives them one
 * authoritative local API and one turn-state schema: encounter -> turn -> action
 * -> combat result -> defeat/loot -> campaign event.
 */
(function(global){
  'use strict';
  var VERSION='57.0.0';
  var ACTIONS=['action','bonusAction','reaction'];
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function num(v,d){var n=Number(v);return isFinite(n)?n:(d||0);}
  function hero(){return global.currentChar||global.currentCharacter||null;}
  function save(){if(typeof global.autoSaveCurrentCharacter==='function')global.autoSaveCurrentCharacter();}
  function tracker(){var h=hero();return h&&h.initiativeTracker||null;}
  function ensureTracker(){var h=hero();if(!h)return null;if(!h.initiativeTracker||!Array.isArray(h.initiativeTracker.combatants))h.initiativeTracker={round:1,activeIndex:0,combatants:[]};var t=h.initiativeTracker;t.round=Math.max(1,num(t.round,1));t.activeIndex=Math.max(0,Math.min(num(t.activeIndex),Math.max(0,t.combatants.length-1)));t.turnResources=t.turnResources||{};return t;}
  function resetTurnResources(c){if(!c)return null;c.turnResources={action:true,bonusAction:true,reaction:true,movement:num(c.speed,30)||30,movementUsed:0};c.turnStartedAt=new Date().toISOString();return c.turnResources;}
  function active(){var t=ensureTracker();return t&&t.combatants[t.activeIndex]||null;}
  function activeIndex(){var t=ensureTracker();return t?t.activeIndex:-1;}
  function isDefeated(c){return !!(c&&c.defeated)||num(c&&c.hp,0)<=0;}
  function livingIndexes(t){var out=[];(t&&t.combatants||[]).forEach(function(c,i){if(!isDefeated(c))out.push(i);});return out;}
  function isCurrentHeroCombatant(c,h){if(!c||!h)return false;if(c===h)return true;var ids=[h.id,h.characterId].filter(function(x){return x!=null;});if(ids.indexOf(c.id)>=0||ids.indexOf(c.entityId)>=0||ids.indexOf(c.characterId)>=0)return true;if(c.isHero===true||c.type==='hero')return true;return !!(h.name&&c.name===h.name&&Array.isArray(c.classes)&&c.classes.some(function(x){return x.name==='Алхимик'||x.englishName==='Alchemist';}));}
  function alchemistHook(actor,name){if(!actor||!global.DNDContent||typeof global.DNDContent.getClass!=='function')return;var cls=(actor.classes||[]).some(function(x){return x.name==='Алхимик'||x.englishName==='Alchemist';});if(!cls)return;var pack=global.DNDContent.getClass('Алхимик');if(pack&&pack.hooks&&typeof pack.hooks[name]==='function')pack.hooks[name](actor,{turnResources:actor.turnResources});}
  function expireAlchemistDebuffs(source){
    if(!source)return;var h=hero(),list=(h&&h.initiativeTracker&&h.initiativeTracker.combatants||[]).slice();if(h&&list.indexOf(h)<0)list.push(h);
    list.forEach(function(target){var d=target&&target.classFeaturesState&&target.classFeaturesState.alchemistDebuffs;if(!d)return;
      var id=source.id||source.entityId||source.characterId,match=(d.sourceId!=null&&id!=null&&String(d.sourceId)===String(id))||(d.sourceName&&source.name&&String(d.sourceName)===String(source.name));if(!match)return;var hadSpeedZero=!!d.speedZero;
      (d.conditionsApplied||[]).forEach(function(condition){if(target.conditions)delete target.conditions[condition];if(target.activeConditions)delete target.activeConditions[condition];});
      ['acPenalty','attackPenalty','savePenalty','speedZero','noOpportunityAttacks','verbalComponentsBlocked','revealsInvisible','attacksHaveAdvantage','burning'].forEach(function(key){delete d[key];});
      if(target.turnResources&&hadSpeedZero)target.turnResources.movement=Math.max(0,num(target.speed,30));
      delete d.sourceId;delete d.sourceName;delete d.conditionsApplied;delete d.expires;
      if(!d.oilCoated&&!d.smokeCloud&&!Object.keys(d).length)delete target.classFeaturesState.alchemistDebuffs;
    });
  }
  function startTurn(c){if(!c)return null;resetTurnResources(c);c.turnCount=num(c.turnCount)+1;expireAlchemistDebuffs(c);if(c.preparedAction&&c.preparedAction.expiresRound&&num(c.preparedAction.expiresRound)<num(ensureTracker().round))c.preparedAction=null;var h=hero();if(isCurrentHeroCombatant(c,h)){alchemistHook(h,'startTurn');if(c!==h)alchemistHook(c,'startTurn');}return c;}
  function endTurn(opts){opts=opts||{};var t=ensureTracker();if(!t||!t.combatants.length)return {ok:false,error:'Нет участников боя.'};var prev=t.combatants[t.activeIndex];var currentHero=hero();if(isCurrentHeroCombatant(prev,currentHero)){alchemistHook(currentHero,'onTurnEnd');if(prev!==currentHero)alchemistHook(prev,'onTurnEnd');}if(prev&&global.DNDSummoning&&typeof global.DNDSummoning.endTurn==='function')try{global.DNDSummoning.endTurn(prev);}catch(e){}
    var count=t.combatants.length,next=t.activeIndex,guard=0;do{next=(next+1)%count;if(next===0)t.round=num(t.round,1)+1;guard++;}while(guard<=count&&!opts.includeDefeated&&isDefeated(t.combatants[next]));
    if(guard>count){return {ok:false,error:'Все участники повержены.',battleOver:true,previous:prev};}
    t.activeIndex=next;var now=t.combatants[next];startTurn(now);if(now&&now.entityId&&global.DNDSummoning&&typeof global.DNDSummoning.startTurn==='function')try{global.DNDSummoning.startTurn(now);}catch(e){}
    save();render();commit('COMBAT_CHANGED');return {ok:true,round:t.round,previous:prev,active:now};}
  function spend(c,resource){if(!c)return {ok:false,error:'Участник не найден.'};var r=c.turnResources||resetTurnResources(c);if(resource==='movement')return {ok:true};if(ACTIONS.indexOf(resource)<0)return {ok:false,error:'Неизвестный ресурс: '+resource};if(!r[resource])return {ok:false,error:'Ресурс уже использован: '+resource};r[resource]=false;return {ok:true,resource:resource};}
  function spendMovement(c,feet){if(!c)return {ok:false,error:'Участник не найден.'};var r=c.turnResources||resetTurnResources(c),used=num(r.movementUsed),speed=num(r.movement,num(c.speed,30));feet=Math.max(0,num(feet));if(used+feet>speed)return {ok:false,error:'Недостаточно движения.',remaining:Math.max(0,speed-used)};r.movementUsed=used+feet;return {ok:true,spent:feet,remaining:speed-r.movementUsed};}
  function useAction(resource){var c=active();if(!c)return {ok:false,error:'Нет активного участника.'};var r=spend(c,resource||'action');if(r.ok){save();render();commit('COMBAT_CHANGED');}return r;}
  function validateTurn(actorId){var c=active();if(!c)return {ok:false,error:'Нет активного участника.'};if(actorId!=null&&String(c.id)!==String(actorId))return {ok:false,error:'Сейчас ходит не этот участник.',active:c};if(isDefeated(c))return {ok:false,error:'Активный участник повержен.'};return {ok:true,actor:c};}
  function executeAttack(actor,target,opts){opts=opts||{};var check=validateTurn(actor&&actor.id);if(!check.ok)return check;var resource=spend(actor,opts.resource||'action');if(!resource.ok)return resource;if(!global.DNDCombat||typeof global.DNDCombat.attack!=='function')return {ok:false,error:'DNDCombat недоступен.'};var base={bonus:num(opts.bonus),damage:opts.damage||'1d6',damageType:opts.damageType||'',target:target,weapon:opts.weapon,useRules:opts.useRules!==false};var first=global.DNDCombat.attack(actor,target,base);var count=first&&num(first.extraAttacks,1)||1;count=Math.max(1,Math.min(4,count));var results=[first];if(count>1&&! (target&&isDefeated(target))){var rest=[];for(var ai=1;ai<count;ai++)rest.push(base);if(global.DNDCombat.attackSequence){var seq=global.DNDCombat.attackSequence(actor,target,rest,{stopOnDefeat:true});results=results.concat(seq.attacks||[]);}else{for(var i=0;i<rest.length;i++){if(target&&isDefeated(target))break;results.push(global.DNDCombat.attack(actor,target,base));}}}results.forEach(function(r){if(r&&r.ok===undefined)r.ok=true;});if(target&&isDefeated(target))onDefeat(target);save();render();commit('COMBAT_CHANGED');if(count===1){first.ok=true;first.resource='action';return first;}return {ok:true,resource:'action',attacks:results,attackCount:results.length,hitCount:results.filter(function(r){return r&&r.hit;}).length,targetDefeated:!!(target&&isDefeated(target))};} 
  function onDefeat(target,killer){if(!target||target._v57DefeatHandled)return null;target.defeated=true;target.defeatedAt=new Date().toISOString();target.defeatedBy=killer&&killer.id||null;var loot=null;if(global.DNDMonsterLoot&&typeof global.DNDMonsterLoot.generate==='function'&&(target.name||target.monsterName)){try{loot=global.DNDMonsterLoot.generate(target.name,{monsterId:target.id,cr:target.cr});target.generatedLoot=clone(loot);}catch(e){loot=null;}}target._v57DefeatHandled=true;var event={type:'COMBATANT_DEFEATED',combatantId:target.id,name:target.name,loot:loot,round:num(tracker()&&tracker().round,1),at:new Date().toISOString()};commit('COMBAT_CHANGED');campaignEvent(event);return event;}
  function collectLoot(target,containers){if(!target||!target.generatedLoot)return {ok:false,error:'Для цели нет сгенерированного лута.'};var h=hero();if(!h)return {ok:false,error:'Персонаж не загружен.'};if(!global.DNDMonsterLoot||typeof global.DNDMonsterLoot.collect!=='function')return {ok:false,error:'Loot engine недоступен.'};var loot=global.DNDMonsterLoot.collect(h,target.generatedLoot,containers||['pockets','harvest']);target.lootCollected=true;save();campaignEvent({type:'LOOT_COLLECTED',combatantId:target.id,loot:loot});return {ok:true,loot:loot};}
  function campaignEvent(ev){var c=global.DNDCampaign&&typeof global.DNDCampaign.getCurrent==='function'?global.DNDCampaign.getCurrent():null;if(c){c.gameplayEvents=Array.isArray(c.gameplayEvents)?c.gameplayEvents:[];c.gameplayEvents.push(clone(ev));if(c.gameplayEvents.length>200)c.gameplayEvents.shift();if(global.DNDCampaign.save)global.DNDCampaign.save();}}
  function commit(type){var net=global.dndNetwork,t=tracker();if(net&&net.state&&net.state.role==='host'&&typeof net.commitHostEvent==='function'&&t)try{return net.commitHostEvent(type||'COMBAT_CHANGED',clone(t),'master');}catch(e){}return null;}
  function render(){if(typeof global.renderInitiativeTracker==='function')try{global.renderInitiativeTracker();}catch(e){}if(typeof global.dndNetworkGameplayRender==='function')try{global.dndNetworkGameplayRender();}catch(e){}if(typeof global.dndBattleActionOpen==='function'){} }
  function snapshot(){var t=ensureTracker();return {version:VERSION,round:t?num(t.round,1):0,activeIndex:t?t.activeIndex:-1,active:t?clone(t.combatants[t.activeIndex]):null,combatants:t?clone(t.combatants):[],living:t?livingIndexes(t).length:0};}
  function renderPanel(){var tab=document.getElementById('tabDice');if(!tab||document.getElementById('dndGameplayCoreV57'))return;var box=document.createElement('div');box.className='card';box.id='dndGameplayCoreV57';box.innerHTML='<h3>🎮 Gameplay Core V57</h3><div id="dndGameplayCoreStatus" style="color:#bbb;font-size:.84em;margin-bottom:7px"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px"><button class="btn-action" onclick="DNDGameplayV57.startTurn()">▶ Начать ход</button><button class="btn-action" onclick="DNDGameplayV57.endTurn()">⏭ Следующий ход</button><button class="btn-action" onclick="DNDGameplayV57.spendAction(\'action\')">⚔️ Потратить Action</button><button class="btn-action" onclick="DNDGameplayV57.spendAction(\'bonusAction\')">✨ Потратить Bonus</button></div><div id="dndGameplayCoreResources" style="margin-top:7px"></div><button class="btn-action" style="width:100%;margin-top:7px;background:#455a64" onclick="dndTurnPlannerOpen()">📋 Открыть планировщик хода</button>' ;tab.appendChild(box);renderPanelState();}
  function renderPanelState(){var box=document.getElementById('dndGameplayCoreStatus'),res=document.getElementById('dndGameplayCoreResources'),c=active();if(!box||!res)return;if(!c){box.textContent='Бой не запущен.';res.innerHTML='';return;}var r=c.turnResources||{};box.innerHTML='Раунд <b>'+num(ensureTracker().round,1)+'</b> • активен: <b>'+String(c.name||'—')+'</b>'+(isDefeated(c)?' • 💀':'');res.innerHTML='Action: '+(r.action?'✓':'—')+' • Bonus: '+(r.bonusAction?'✓':'—')+' • Reaction: '+(r.reaction?'✓':'—')+' • Movement: '+Math.max(0,num(r.movement,num(c.speed,30))-num(r.movementUsed))+'/'+num(r.movement,num(c.speed,30))+' фт.';}
  function patchUI(){if(typeof global.renderDndTools!=='function'||global.renderDndTools.__v57){return;}var old=global.renderDndTools;var wrapped=function(){old.apply(this,arguments);setTimeout(function(){renderPanel();},0);};wrapped.__v57=true;global.renderDndTools=wrapped;}
  global.DNDGameplayV57={VERSION:VERSION,ensureTracker:ensureTracker,snapshot:snapshot,active:active,startTurn:function(){var c=active();if(!c)return {ok:false,error:'Нет активного участника.'};startTurn(c);save();render();commit('COMBAT_CHANGED');return {ok:true,active:c,resources:c.turnResources};},endTurn:endTurn,spendAction:useAction,spend:spend,spendMovement:spendMovement,validateTurn:validateTurn,executeAttack:executeAttack,onDefeat:onDefeat,collectLoot:collectLoot,campaignEvent:campaignEvent,resetTurnResources:resetTurnResources};
  global.dndGameplayCoreV57Render=renderPanelState;
  if(global.addEventListener)global.addEventListener('DOMContentLoaded',function(){patchUI();setTimeout(function(){renderPanel();},250);});
})(window);
