/**
 * martyr_mhp_2024_runtime.js
 * Полный runtime Мученика 2024/5.5E.
 * API: window.martyrRuntime / window.martyrProgression.
 * Заклинания используют HP-жертву, а 14 Mortal Burdens подключаются как
 * структурированные подклассы с уровнями 3/6/14/18.
 */
(function(){
"use strict";
const PB=[0,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,6,6,6,6];
const PREP=[0,2,3,4,5,6,6,7,7,8,8,10,10,11,11,12,12,14,14,15,15];
const MAX=[0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5];
const USES=[0,2,2,3,3,6,6,7,7,9,9,10,10,11,11,12,12,14,14,15,15];
const HIT_COST={1:5,2:10,3:20,4:30,5:40};
const spells={
1:["Bane","Bless","Command","Cure Wounds","Detect Evil and Good","Detect Magic","Detect Poison and Disease","Divine Favor","Guiding Bolt","Heroism","Inflict Wounds","Protection from Evil and Good","Purify Food and Drink","Sanctuary"],
2:["Aid","Augury","Calm Emotions","Darkvision","Enhance Ability","Ethereal Jaunt","Hold Person","Lesser Restoration","Magic Weapon","Prayer of Healing","Silence","Spiritual Weapon","Warding Bond"],
3:["Create Food and Water","Daylight","Dispel Magic","Divine Wrath","Magic Circle","Protection from Energy","Remove Curse","Revivify","Speak with Dead","Tongues","Water Walk","Word of Frailty"],
4:["Aura of Life","Banishment","Death Ward","Divination","Freedom of Movement","Locate Creature","Stoneskin"],
5:["Commune","Dispel Evil and Good","Flame Strike","Geas","Greater Restoration","Hallow","Hold Monster","Insect Plague","Mass Cure Wounds","Raise Dead","Word of Control"]
};
const burdens={};
function burden(name,desc,spellsByLevel,features){burdens[name]={name,description:desc,featureLevels:[3,6,14,18],alwaysPrepared:spellsByLevel,features};}
burden("Бремя анонимности","Работа из тени, без славы и признания.",{
3:["Disguise Self","Expeditious Retreat"],5:["Invisibility","Silence"],9:["Sending","Word of Transience"],13:["Arcane Eye","Greater Invisibility"],17:["Modify Memory","Passwall"]
},{3:["Владение Скрытностью и инструментами воров."],6:["Исчезновение: при инициативе можно стать Невидимым до конца следующего хода; часть эффектов позволяет восстановить невидимость через жертву HP."],14:["Ложная смерть: при уроне или спасении от гибели создаётся убедительный двойник, а вы перемещаетесь в известное место; 1/долгий отдых."],18:["Божественный убийца: преимущества против обнаружения; невидимость становится быстрым действием и её HP-цена уменьшается."]});
burden("Бремя вознесения","Выполнение божественных трудов ради посмертного возвышения.",{
3:["Divine Favor","Heroism"],5:["Enhance Ability","Locate Object"],9:["Beacon of Hope","Protection from Energy"],13:["Death Ward","Locate Creature"],17:["Hold Monster","Legend Lore"]
},{3:["Аегис, Оракул и Ксифос — три легендарных предмета, связанные с вашими трудами; каждый получает особую функцию."],6:["Божественные труды: известные вам задания получают преимущество на D20 Test; завершение труда увеличивает максимум HP."],14:["Высшая награда: одно из связанных с предметами чудесных применений усиливается; ресурсы можно возвращать через радиантную жертву."],18:["Вознесение: финальный набор преимуществ для легендарных предметов и выполнения последнего труда."]});
burden("Бремя искупления","Защита невиновных и искупление прошлых ошибок.",{
3:["Cure Wounds","Sanctuary"],5:["Calm Emotions","Lesser Restoration"],9:["Remove Curse","Speak with Dead"],13:["Death Ward","Stoneskin"],17:["Greater Restoration","Mass Cure Wounds"]
},{3:["Перенаправление: реакцией можно принять на себя атаку, предназначенную союзнику в 5 футах."],6:["Искупительная жертва: использование Торжества/Мучения для защиты других можно восстанавливать дополнительной радиантной ценой."],14:["Сила искупления: защитные эффекты распространяются на союзников и помогают снять состояния/последствия."],18:["Последнее искупление: ответная магия и спасение союзника получают усиление, связанное с вашим HP-жертвованием."]});
burden("Бремя бедствия","Вестник чумы, стихийных бедствий и дурных знамений.",{
3:["Contagion","Fog Cloud"],5:["Bestow Curse","Sleet Storm"],9:["Blight","Call Lightning"],13:["Control Water","Insect Plague"],17:["Contagion","Control Winds"]
},{3:["Знамение бедствия: создаёте локальные разрушительные проявления и получаете тематическое преимущество на D20 Tests."],6:["Катастрофический призыв: после получения радиантного урона можно вызвать случайный эффект бедствия в зоне."],14:["Отречение от арканы: враги, полагающиеся на магию, получают помехи/урон от ваших бедствий; эффект можно поддерживать жертвой HP."],18:["Апокалиптический ответ: реакцией на полученный урон применяете бедственный эффект и уменьшаете собственную цену заклинания."]});
burden("Бремя раздора","Распространяет хаос и ломает привычный порядок.",{
3:["Chaos Bolt","Dissonant Whispers"],5:["Mirror Image","Shatter"],9:["Confusion","Haste"],13:["Dimension Door","Polymorph"],17:["Mislead","Passwall"]
},{3:["Хаос!: после попадания оружием раз за отдых/через 5 HP жертвы бросок по таблице хаоса: лечение, огонь, толчок, телепорт, сбивание с ног и другие случайные эффекты."],6:["Монета хаоса: добавляет к D20 Test +4 или +1; после использования переходит GM и затем возвращается."],14:["Раскол реальности: случайные эффекты хаоса становятся сильнее и чаще."],18:["Хаотический триумф: критические/случайные эффекты могут накладывать состояния Charmed, Frightened или Poisoned либо автоматически критовать атаку."]});
burden("Бремя конца","Предотвращение грядущей катастрофы любой ценой.",{
3:["Chromatic Orb","Protection from Evil and Good","Sacred Flame"],5:["Darkness","Shatter"],9:["Counterspell","Lightning Bolt"],13:["Banishment","Blight"],17:["Cone of Cold","Telekinesis"]
},{3:["Мистическая мудрость: владение Arcana с бонусом Wisdom; восстановление части использований после короткого отдыха 1/долгий отдых."],6:["Освящённая аркана: выбранные заклинания Бремени конца требуют меньше радиантной цены."],14:["Жертвенное заклинание: за 10 радиантного урона можно усилить спасбросок против заклинания помехой или ускорить заклинание до бонусного действия с ограничениями."],18:["Мстительное заклинание: реакцией после урона врага можно сотворить атакующее заклинание 1–3 уровня с уменьшенной ценой жертвы."]});
burden("Бремя славы","Божественная знаменитость и сила публичного присутствия.",{
3:["Charm Person","Unseen Servant"],5:["Misty Step","Suggestion"],9:["Hypnotic Pattern","Tongues"],13:["Compulsion","Private Sanctum"],17:["Dominate Person","Teleportation Circle"]
},{3:["Мистическая сценическая речь: владение Performance и бонус Wisdom к проверкам."],6:["Звёздный эффект: Charm Person можно колдовать без радиантной цены; очарованные вами существа воспринимают вас как выдающуюся знаменитость."],14:["Сияющая слава: вокруг вас действует аура, усиливающая союзников и социальные D20 Tests."],18:["Легендарная репутация: сильнейшие эффекты очарования/телепортации получают сниженную цену и расширенный контроль."]});
burden("Бремя лёгкости","Инструмент богов-трикстеров, созданный для хаоса и веселья.",{
3:["Disguise Self","Hideous Laughter","Minor Illusion"],5:["Calm Emotions","Misty Step"],9:["Major Image","Stinking Cloud"],13:["Confusion","Dimension Door"],17:["Modify Memory","Seeming"]
},{3:["Левитация: владение Performance и бонус Wisdom; Charm/иллюзии становятся частью вашей божественной роли."],6:["Звёздный розыгрыш: Charm Person без цены; очарованный воспринимает вас как знаменитость."],14:["Заносчивая мисдирекция: Reprisal может перенаправить атаку на другую подходящую цель."],18:["Безумное перенаправление: иллюзорные/телепортационные эффекты становятся быстрыми и получают сниженные затраты."]});
burden("Бремя милосердия","Целитель и носитель надежды.",{
3:["Cure Wounds","Protection from Evil and Good"],5:["Lesser Restoration","Prayer of Healing"],9:["Remove Curse","Revivify"],13:["Aura of Life","Death Ward"],17:["Mass Cure Wounds","Raise Dead"]
},{3:["Милосердное исцеление: заклинания из списка Бремени не требуют радиантной цены."],6:["Добродетельные благословения: после долгого отдыха благословляет до Wisdom существ бонусом к скорости, социальным/мудрым проверкам или инициативе."],14:["Осуждающий свет: 30-футовая аура наносит радиантный урон выбранному типу сверхъестественных существ и защищает союзников от их магии."],18:["Святое исцеление: исцеление добавляет уровень Мученика; каждое существо ограничено дополнительным исцелением раз за долгий отдых."]});
burden("Бремя одиссеи","Нескончаемое путешествие исследования и открытий.",{
3:["Expeditious Retreat","Feather Fall"],5:["Gust of Wind","Misty Step"],9:["Fly","Water Walk"],13:["Dimension Door","Freedom of Movement"],17:["Passwall","Teleportation Circle"]
},{3:["Ловкость путешественника: улучшенная скорость и движение по сложной местности."],6:["Естественный спутник: Find Familiar и Speak with Animals без радиантной цены и расхода использования."],14:["Шаг зефира: после достаточного перемещения атаки против вас получают помеху, а Sacrificial Strike временно не требует цены."],18:["Нескончаемый путь: экстремальная мобильность, защита и усиленные перемещения между точками мира."]});
burden("Бремя возрождения","Восстановление разрушенной природы.",{
3:["Entangle","Find Familiar","Goodberry","Shillelagh","Speak with Animals"],5:["Pass without Trace","Spike Growth"],9:["Plant Growth","Speak with Plants"],13:["Giant Insect","Hallucinatory Terrain"],17:["Awaken","Reincarnate"]
},{3:["Природный спутник: Find Familiar и Speak with Animals без цены."],6:["Надёжная поступь: сложная местность не замедляет вас и союзников рядом; защита от Entangle/Spike Growth/Plant Growth."],14:["Зелёная стойкость: бонусным действием на минуту получаете регенерацию и сопротивление дробящему/колющему/рубящему."],18:["Колесо жизни: Reincarnate без материальных компонентов и радиантной цены; при смерти возможно возвращение через 24 часа, с ограниченным повтором."]});
burden("Бремя революции","Освобождение угнетённых и свержение тиранов.",{
3:["Command","Heroism"],5:["Hold Person","Magic Weapon"],9:["Divine Wrath","Protection from Energy"],13:["Stoneskin","Wall of Fire"],17:["Hold Monster","Telepathic Bond"]
},{3:["Боевые владения и знамя восстания: дополнительная защита/временные HP после короткой активации."],6:["Аура стойкости: союзники в 30 футах добавляют Wisdom к инициативе; эффект не работает при Incapacitated."],14:["Неукротимое знамя: вы и союзники получают защиту от Charmed/Frightened и усиление воли."],18:["Удар сплочения: после Sacrificial Strike союзник в 30 футах может реакцией сделать оружейную атаку; также доступны эффекты против поверженных врагов."]});
burden("Бремя истины","Пророк, несущий миру опасное знание.",{
3:["Identify","Word of Force"],5:["Word of Terror","Zone of Truth"],9:["Sending","Word of Transience"],13:["Divination","Freedom of Movement"],17:["Legend Lore","True Seeing"]
},{3:["Пророческая речь: бонус к расследованию/проверкам знания и способности раскрывать ложь."],6:["Пророческое восстановление: после короткого отдыха можно вернуть часть использований заклинаний."],14:["Истинное слово: жертвенный эффект усиливает контроль, раскрытие скрытого и защиту от обмана."],18:["Последнее откровение: сильнейшая пророческая магия и возможность раскрыть скрытые свойства существа/явления."]});
burden("Бремя тирании","Тёмный мученик, предназначенный для покорения.",{
3:["Command","Dissonant Whispers"],5:["Hold Person","Spiritual Weapon"],9:["Fear","Slow"],13:["Dominate Beast","Stoneskin"],17:["Dominate Person","Hold Monster"]
},{3:["Властное присутствие: бонус к Запугиванию; атаки/заклинания получают преимущества против запуганных целей."],6:["Аура подчинения: враги в области получают штраф к инициативе и спасброскам против ваших эффектов страха/контроля."],14:["Раздавить волю: реакцией/жертвой HP можно усилить контроль и навязать состояние Frightened/Charmed."],18:["Верховный тиран: после Sacrificial Strike союзник не требуется — вы можете продолжить цепочку атак/контроля против подавленных врагов."]});
const levels={};for(let l=1;l<=20;l++)levels[l]={proficiencyBonus:PB[l],preparedSpells:PREP[l],maxSpellLevel:MAX[l],spellUses:USES[l],features:{
1:["Доспех веры","Использование заклинаний","Мастерство оружия"],2:["Чудесное исцеление","Воздаяние"],3:["Подкласс Мученика","Жертва"],4:["Увеличение характеристик / Черта"],5:["Дополнительная атака"],6:["Способность подкласса"],7:["Жертва врага"],8:["Увеличение характеристик / Черта"],9:["Божественная передышка"],10:["Неумирающий"],11:["Улучшенный жертвенный удар"],12:["Увеличение характеристик / Черта"],13:["Божественная передышка — улучшение"],14:["Способность подкласса"],15:["Шествие к судьбе"],16:["Увеличение характеристик / Черта"],17:["Божественная передышка и улучшенный жертвенный удар"],18:["Способность подкласса"],19:["Эпический дар"],20:["Последнее мученичество"]}[l]||[]};
const progression={className:"Мученик",englishName:"Martyr",edition:"5.5E",source:"Mage Hand Press — Martyr 2024 / Complete Martyr 2024",status:"implemented_2024_runtime",hitDie:12,primaryStat:"wisdom",secondaryStatChoice:["strength","dexterity"],savingThrows:["strength","wisdom"],armor:["light","shields"],weapons:["simple","martial"],skills:{choose:2,from:["athletics","history","insight","intimidation","medicine","persuasion","religion"]},multiclassRequirement:{wisdom:13,strengthOrDexterity:13},levels,spellcasting:{ability:"wisdom",preparedByLevel:PREP,maxSpellLevelByLevel:MAX,spellUsesByLevel:USES,hpDamageBySlot:HIT_COST,spellList:spells,focus:"holy_symbol",cantrips:[]},burdens};
const runtime={progression,burdens,spellList:spells,mechanics:{armorOfFaith:["medium+Wis AC","unarmored 10+Dex+Wis"],spellcasting:{damageType:"radiant",ignoresResistance:true,ignoresImmunity:true,bypassesTempHP:true,noConcentrationCheck:true,noHealingFromOwnSpells:true},miraculousHealing:"bonus_action: spend up to floor(level/2) Hit Dice, each + Con",reprisal:"reaction: halve visible melee damage; attacker takes radiant/necrotic d6 (2d6 lv5,3d6 lv11,4d6 lv17)",sacrifice:{bonusAction:true,selfDamage:5,targetExtraRadiant:10,improvedAt11:{selfDamage:10,targetExtraRadiant:20},freeAt17:true},sacrificeFoe:"kill with Sacrifice removes self-damage",divineRespite:{levels:{9:3,13:6,17:10},oncePerLongRest:true},undying:"0 HP -> 1 HP + Miraculous Healing, 1/long rest",marchUntoDestiny:["no food/drink","immune paralyzed/petrified/stunned"],finalMartyrdom:"10 minutes: advantage all D20, immune all damage/conditions except grappled/invisible/prone/unconscious, free Wish, then irreversible death"},sync(c){const l=Math.max(1,Math.min(20,Number(c?.level)||1)),w=Number(c?.wisdom??c?.abilities?.wisdom??10),m=Math.floor((w-10)/2);return Object.assign({},levels[l],{spellSaveDC:8+PB[l]+m,spellAttackBonus:PB[l]+m,hpCostBySlot:HIT_COST})}};

function martyrState(c){c.classFeaturesState=c.classFeaturesState||{};return c.classFeaturesState.martyr=c.classFeaturesState.martyr||{};}
function martyrLevel(c){return Math.max(1,Math.min(20,Number(c&&c.level)||1));}
function martyrSync(c){var l=martyrLevel(c),s=martyrState(c),w=Number(c&&((c.wisdom??c.stats?.wisdom??c.abilities?.wisdom)))||10,m=Math.floor((w-10)/2);s.level=l;s.proficiencyBonus=PB[l];s.preparedMax=PREP[l];s.maxSpellLevel=MAX[l];s.spellUsesMax=USES[l];s.spellUses=s.spellUses==null?USES[l]:Math.min(Math.max(0,Number(s.spellUses)||0),USES[l]);s.spellSaveDC=8+PB[l]+m;s.spellAttackBonus=PB[l]+m;s.divineRespiteMax=l>=17?10:l>=13?6:l>=9?3:0;s.divineRespiteUses=s.divineRespiteUses==null?(s.divineRespiteMax?1:0):s.divineRespiteUses;s.undyingAvailable=l>=10;s.sacrificialStrikeImproved=l>=11;s.finalMartyrdom=l>=20;return s;}
function martyrPrepareBurden(c,name){if(!burdens[name])return {ok:false,reason:"Неизвестное Бремя."};martyrState(c).burden=name;return {ok:true,burden:name,data:burdens[name]};}
function martyrCast(c,spellLevel,spellName){var l=martyrLevel(c),s=martyrSync(c),sl=Number(spellLevel)||0;if(sl<1||sl>5||sl>MAX[l])return {ok:false,reason:"Этот уровень заклинания недоступен Мученику."};if(s.spellUses<=0)return {ok:false,reason:"Использования заклинаний Мученика закончились."};var list=spells[sl]||[];if(spellName&&list.indexOf(spellName)<0){var b=s.burden&&burdens[s.burden];var extra=b&&b.alwaysPrepared&&b.alwaysPrepared[sl]||[];if(extra.indexOf(spellName)<0)return {ok:false,reason:"Заклинание отсутствует в списке Мученика/его Бремени."};}s.spellUses--;return {ok:true,spell:spellName||null,spellLevel:sl,hpCost:HIT_COST[sl]||0,remaining:s.spellUses,maxUses:s.spellUsesMax,damageType:"radiant",ignoreResistance:true,ignoreImmunity:true};}
function martyrRest(c,type){var s=martyrSync(c);if(type==="long"){s.spellUses=s.spellUsesMax;s.divineRespiteUses=s.divineRespiteMax?1:0;s.undyingUsed=false;}return s;}
function martyrHeal(c,dice){var l=martyrLevel(c),s=martyrSync(c),max=Math.floor(l/2),n=Math.max(0,Math.min(Number(dice)||0,max));return {ok:n>0,hitDiceSpent:n,healingFormula:n+"d12 + "+(Number(c&&c.constitutionModifier)||0)*n,remainingBudget:max-n};}
function martyrUseDivineRespite(c,amount){var s=martyrSync(c);if(!s.divineRespiteMax)return {ok:false,reason:"Божественная передышка доступна с 9 уровня."};if(!s.divineRespiteUses)return {ok:false,reason:"Божественная передышка уже использована после последнего долгого отдыха."};var n=Math.max(0,Math.min(Number(amount)||s.divineRespiteMax,s.divineRespiteMax));s.divineRespiteUses=0;return {ok:true,hitDiceRestored:n,max:s.divineRespiteMax};}
function martyrUndying(c){var s=martyrSync(c);if(!s.undyingAvailable)return {ok:false,reason:"Неумирающий доступен с 10 уровня."};if(s.undyingUsed)return {ok:false,reason:"Неумирающий уже использован после долгого отдыха."};s.undyingUsed=true;return {ok:true,hitPointsAfter:1,triggerHealing:true};}
function martyrSacrifice(c,target,improved){var l=martyrLevel(c),amount=improved&&l>=11?10:5,extra=improved&&l>=11?20:10;return {ok:true,selfDamage:amount,targetExtraRadiant:extra,freeAt17:l>=17,sacrificeFoe:l>=7};}
function martyrFinalMartyrdom(c){if(martyrLevel(c)<20)return {ok:false,reason:"Последнее мученичество доступно только на 20 уровне."};return {ok:true,durationMinutes:10,freeWish:true,advantageAllD20:true,immuneToDamage:true,irreversibleDeath:true};}
window.martyrRuntime=runtime;window.MARTYR_2024=runtime;window.martyrRuntime.state=martyrState;window.martyrRuntime.sync=martyrSync;window.martyrRuntime.prepareBurden=martyrPrepareBurden;window.martyrRuntime.cast=martyrCast;window.martyrRuntime.rest=martyrRest;window.martyrRuntime.miraculousHealing=martyrHeal;window.martyrRuntime.useDivineRespite=martyrUseDivineRespite;window.martyrRuntime.undying=martyrUndying;window.martyrRuntime.sacrifice=martyrSacrifice;window.martyrRuntime.finalMartyrdom=martyrFinalMartyrdom;window.martyrProgression=progression;window.MARTYR_BURDENS=burdens;
})();
/* V70.26.92 closure pass: executable spell-use, burden, rest and martyr-resource APIs. */
