/**
 * summoning_engine.js
 * ------------------------------------------------------------------
 * ЧТО ЭТО ЗА ФАЙЛ:
 * Полноценный runtime для призванных существ и компаньонов VTT.
 *
 * КАК РАБОТАЕТ:
 * - превращает вторичную сущность в полноценного участника инициативы;
 * - синхронизирует HP, AC, состояния и позицию между entity/combatant/token;
 * - поддерживает ход/команду, атаки, получение урона и смерть сущности;
 * - учитывает duration и удаляет временный summon после окончания срока;
 * - предоставляет Battle Board панель действий без prompt.
 *
 * ОСНОВНЫЕ ПЕРЕМЕННЫЕ:
 * entity, combatant, entityId, initiativeTracker, actions, duration,
 * controlMode, ownerId, tokenId.
 *
 * НЕ ИЗМЕНЯЕТ Wallpapers.js/Ambiences.js.
 * ------------------------------------------------------------------
 */
(function(global){
  'use strict';
  var VERSION='1.0.0';
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return null;}}
  function hero(){return global.currentChar||global.currentCharacter||null;}
  function tracker(){var h=hero();return h&&h.initiativeTracker||null;}
  function save(){if(typeof global.autoSaveCurrentCharacter==='function')global.autoSaveCurrentCharacter();else if(typeof global._dndSave==='function')global._dndSave();}
  function notify(){save();if(typeof global.renderInitiativeTracker==='function')global.renderInitiativeTracker();if(global.DNDBattleBoard&&typeof global.DNDBattleBoard.render==='function')global.DNDBattleBoard.render();}
  function findCombatant(id){var t=tracker();if(!t||!Array.isArray(t.combatants))return null;return t.combatants.find(function(c){return String(c.id)===String(id);})||null;}
  function entity(id){return global.DNDSecondaryEntities&&global.DNDSecondaryEntities.get?global.DNDSecondaryEntities.get(id):null;}
  function ensureCombatant(e){var t=tracker();if(!t||!e)return null;var c=t.combatants.find(function(x){return String(x.entityId)===String(e.id);});if(c)return c;var owner=t.combatants.find(function(x){return String(x.id)===String(e.ownerId)||String(x.ownerId)===String(e.ownerId);});var initiative=owner?Number(owner.initiative)||0:Number(e.initiative)||0;c={id:'summon_'+e.id,entityId:e.id,name:e.name,type:'summon',team:e.team||'party',ownerId:e.ownerId||'',ownerTokenId:e.ownerTokenId||'',initiative:initiative,hp:Number(e.hp)||0,maxHp:Number(e.maxHp)||Number(e.hp)||1,tempHp:Number(e.tempHp)||0,ac:Number(e.ac)||10,speed:Number(e.speed)||30,size:Number(e.size)||1,conditions:clone(e.conditions||{}),actions:clone(e.actions||[]),resources:clone(e.resources||{}),turnResources:{action:true,bonusAction:true,reaction:true,movement:Number(e.speed)||30,movementUsed:0}};t.combatants.push(c);if(typeof global.sortInitiativeTracker==='function')global.sortInitiativeTracker();return c;}
  function syncEntity(e){if(!e)return null;var c=ensureCombatant(e);if(!c)return null;c.name=e.name;c.hp=e.hp;c.maxHp=e.maxHp;c.tempHp=e.tempHp;c.ac=e.ac;c.speed=e.speed;c.size=e.size;c.conditions=clone(e.conditions||{});c.actions=clone(e.actions||[]);c.resources=clone(e.resources||{});c.team=e.team||c.team;c.ownerId=e.ownerId||c.ownerId;c.ownerTokenId=e.ownerTokenId||c.ownerTokenId;c.defeated=Number(e.hp)<=0;var token=global.DNDSecondaryEntities.getToken&&global.DNDSecondaryEntities.getToken(e.id);if(token){token.hp=e.hp;token.maxHp=e.maxHp;token.ac=e.ac;token.speed=e.speed;token.name=e.name;token.size=e.size;}return c;}
  function syncAll(){if(!global.DNDSecondaryEntities)return [];var t=tracker();if(!t)return [];var list=global.DNDSecondaryEntities.list();var ids={};list.forEach(function(e){ids[e.id]=1;syncEntity(e);});t.combatants=t.combatants.filter(function(c){return !c.entityId||ids[c.entityId];});return list;}
  function create(spec){var e=global.DNDSecondaryEntities.create(spec);syncEntity(e);notify();return e;}
  function setHp(id,hp){var e=entity(id);if(!e)return null;var n=Math.max(0,Number(hp)||0);global.DNDSecondaryEntities.update(id,{hp:n});var c=syncEntity(entity(id));if(n<=0)defeat(id);notify();return c;}
  function damage(id,amount,type){var e=entity(id);if(!e)return {ok:false,reason:'not_found'};var c=syncEntity(e);var n=Math.max(0,Number(amount)||0),temp=Math.max(0,Number(e.tempHp)||0),absorbed=Math.min(temp,n);n-=absorbed;temp-=absorbed;var hp=Math.max(0,(Number(e.hp)||0)-n);global.DNDSecondaryEntities.update(id,{hp:hp,tempHp:temp});syncEntity(entity(id));if(hp<=0)defeat(id);notify();return {ok:true,amount:Number(amount)||0,absorbedTempHp:absorbed,hp:hp,tempHp:temp,type:type||'',defeated:hp<=0};}
  function heal(id,amount){var e=entity(id);if(!e)return {ok:false,reason:'not_found'};var hp=Math.min(Number(e.maxHp)||1,(Number(e.hp)||0)+(Number(amount)||0));global.DNDSecondaryEntities.update(id,{hp:hp});syncEntity(entity(id));notify();return {ok:true,amount:Number(amount)||0,hp:hp};}
  function defeat(id){var e=entity(id);if(!e)return false;global.DNDSecondaryEntities.update(id,{defeated:true,hp:0});var c=syncEntity(entity(id));if(c)c.defeated=true;return true;}
  function startTurn(c){if(!c||!c.entityId)return null;var e=entity(c.entityId);if(!e)return null;if(e.defeated||Number(e.hp)<=0)return {ok:false,defeated:true};c.turnResources={action:true,bonusAction:true,reaction:true,movement:Number(e.speed)||30,movementUsed:0};if(e.lastCommand){c.pendingCommand=e.lastCommand;delete e.lastCommand;}return {ok:true,entity:clone(e),command:c.pendingCommand||null};}
  function endTurn(c){if(!c||!c.entityId)return;var e=entity(c.entityId);if(!e)return; if(e.duration!=null){e.duration=Number(e.duration)-1;if(e.duration<=0){global.DNDSecondaryEntities.remove(e.id);return;}} global.DNDSecondaryEntities.update(e.id,{duration:e.duration});}
  function command(id,type){var r=global.DNDSecondaryEntities.command(id,type);syncEntity(entity(id));notify();return r;}
  function attack(id,targetId,actionIndex){var e=entity(id),t=tracker();if(!e||!t)return {ok:false,reason:'not_found'};var c=syncEntity(e),target=t.combatants.find(function(x){return String(x.id)===String(targetId);});if(!target)return {ok:false,reason:'target_not_found'};var action=(e.actions||[])[Number(actionIndex)||0];if(!action)return {ok:false,reason:'action_not_found'};if(c.turnResources&&!c.turnResources.action)return {ok:false,reason:'action_used'};var attacker=c;var opts={bonus:Number(action.attackBonus)||0,damage:action.damage||'1d4',damageType:action.damageType||'',target:target,usesStrength:true,meleeOrThrown:true};var seq=global.DNDCombat&&global.DNDCombat.attackSequence?global.DNDCombat.attackSequence(attacker,target,[opts],{stopOnDefeat:true}):null;var r=seq&&seq.attacks?seq.attacks[0]:(global.DNDCombat&&global.DNDCombat.attack?global.DNDCombat.attack(attacker,target,opts):null);if(!r)return {ok:false,reason:'combat_unavailable'};if(c.turnResources)c.turnResources.action=false;if(r.damageResult)syncTarget(target);syncEntity(e);notify();return {ok:true,result:r,action:clone(action)};}
  function syncTarget(c){if(!c)return;if(c.entityId&&global.DNDSecondaryEntities){global.DNDSecondaryEntities.update(c.entityId,{hp:c.hp,tempHp:c.tempHp,conditions:c.conditions});syncEntity(entity(c.entityId));}}
  function onTurnStart(c){syncAll();return startTurn(c);}
  function onTurnEnd(c){endTurn(c);syncAll();notify();}
  function renderPanel(){var box=document.getElementById('battleBoardSummonPanel');if(!box)return;var list=global.DNDSecondaryEntities?global.DNDSecondaryEntities.list():[];if(!list.length){box.innerHTML='<div style="color:#777">Нет активных спутников или призванных существ.</div>';if(global.DNDCompanionPacks&&typeof global.DNDCompanionPacks.render==='function')global.DNDCompanionPacks.render();return;}var t=tracker();var active=t&&t.combatants[t.activeIndex];box.innerHTML=list.map(function(e){var c=t&&t.combatants.find(function(x){return String(x.entityId)===String(e.id);});var owner=e.ownerId&&t&&t.combatants.find(function(x){return String(x.id)===String(e.ownerId);});var buttons='';if(active&&String(active.entityId)===String(e.id)){buttons=(e.actions||[]).map(function(a,i){return '<button class="btn-action" style="padding:5px" onclick="dndSummonAttack(\''+e.id+'\',\''+(a.targetId||'')+'\','+i+')">⚔️ '+String(a.name||'Атака')+'</button>';}).join('');}return '<div style="padding:7px;border:1px solid #333;border-radius:7px;margin:4px 0"><strong>✨ '+String(e.name||'Существо')+'</strong> • HP '+e.hp+'/'+e.maxHp+' • КД '+e.ac+' • '+String(e.controlMode||'command')+'<br><small style="color:#999">Владелец: '+String(owner&&owner.name||'—')+' • '+String(e.duration==null?'постоянно':e.duration+' '+(e.durationUnit||'раундов'))+'</small><div style="display:flex;gap:4px;flex-wrap:wrap;margin-top:5px">'+buttons+'<select data-command-select="'+e.id+'" style="padding:4px;background:#222;color:#ccc;border:1px solid #444;border-radius:5px"><option>Атакуй</option><option>Защищай хозяина</option><option>Переместись к хозяину</option><option>Ожидай</option></select><button class="btn-action" style="padding:5px" onclick="dndSummonCommand(\''+e.id+'\')">📣 Команда</button><button class="btn-action" style="padding:5px" onclick="dndSummonHeal(\''+e.id+'\')">💚 Быстрое лечение</button></div></div>';}).join('');if(global.DNDCompanionPacks&&typeof global.DNDCompanionPacks.render==='function')global.DNDCompanionPacks.render();}
  function init(){if(!document.getElementById('battleBoardSummonPanel')){var b=document.createElement('div');b.id='battleBoardSummonPanel';b.style.cssText='padding:7px 9px;background:#111;border-top:1px solid #222;color:#ccc;font-size:.82em;max-height:170px;overflow:auto;';var tok=document.getElementById('battleBoardTokens');if(tok&&tok.parentNode)tok.parentNode.insertBefore(b,tok.nextSibling);}renderPanel();}
  global.DNDSummoning={VERSION:VERSION,create:create,sync:syncAll,startTurn:onTurnStart,endTurn:onTurnEnd,damage:damage,heal:heal,attack:attack,command:command,defeat:defeat,render:renderPanel};
  global.dndSummonAttack=function(id,targetId,index){var t=tracker();if(!t)return;var target=targetId?findCombatant(targetId):null;if(!target&&global.DNDBattleBoard){var tok=global.DNDBattleBoard.getSelectedToken&&global.DNDBattleBoard.getSelectedToken();if(tok)target=findCombatant(tok.sourceId||tok.entityId);}if(!target){var candidates=t.combatants.filter(function(c){return c.type!=='summon'&&!c.defeated;});if(candidates[0])target=candidates[0];}if(!target)return;var r=attack(id,target.id,index);if(typeof global.dndCombatLog==='function')global.dndCombatLog('✨ '+(entity(id)||{}).name+' → '+target.name);return r;};
  global.dndSummonCommand=function(id){var types=['Атакуй','Защищай хозяина','Переместись к хозяину','Ожидай'];var box=document.getElementById('battleBoardSummonPanel');var type=types[0];if(box&&box.querySelector('[data-command-select="'+id+'"]'))type=box.querySelector('[data-command-select="'+id+'"]').value;return command(id,type);};
  global.dndSummonHeal=function(id){var e=entity(id);if(!e)return null;var amount=Math.max(1,Math.floor((Number(e.maxHp)||1)*0.25));return heal(id,amount);};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(window);
