/**
 * vtt_encounter_map_v59.js
 * ------------------------------------------------------------------
 * V59 Encounter/Map UX: связывает Bestiary -> Encounter -> Initiative ->
 * Battle Board и сохраняет состав/идентификатор боя в Campaign.
 * Не создаёт новый combat, initiative или battle-board engine.
 *
 * Public API: DNDEncounterMapV59
 * Important state: DNDV59EncounterState, activeEncounterId, draft.
 * ------------------------------------------------------------------
 */
(function(global){
  'use strict';
  var VERSION='59.0.0', KEY='dnd_encounter_map_v59';
  var state={draft:null,activeEncounterId:null};
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return null;}}
  function n(v,d){var x=Number(v);return Number.isFinite(x)?x:(d||0);}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&typeof x==='object')state=Object.assign(state,x);}catch(e){}return state;}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}if(global.DNDCampaign&&global.DNDCampaign.save)try{global.DNDCampaign.save();}catch(e){}}
  function hero(){return global.currentChar||global.currentCharacter||null;}
  function campaign(){return global.DNDCampaign&&global.DNDCampaign.getCurrent?global.DNDCampaign.getCurrent():null;}
  function ensureDraft(name){if(!state.draft)state.draft={id:'encdraft_'+Date.now(),name:name||'Новый encounter',combatants:[],map:{cols:24,rows:18,cellFt:5}};return state.draft;}
  function catalogs(){var out=[];if(global.DNDMonsters&&global.DNDMonsters.catalog)Object.keys(global.DNDMonsters.catalog).forEach(function(k){out.push({name:k,source:'monster',data:clone(global.DNDMonsters.catalog[k])});});if(global.DND_BESTIARY_V56_13&&global.DND_BESTIARY_V56_13.catalog)Object.keys(global.DND_BESTIARY_V56_13.catalog).forEach(function(k){if(!out.some(function(x){return x.name===k;}))out.push({name:k,source:'planescape',data:clone(global.DND_BESTIARY_V56_13.catalog[k])});});return out;}
  function findCreature(name){var c=null;if(global.DND_BESTIARY_V56_13&&typeof global.DND_BESTIARY_V56_13.getCreature==='function')c=global.DND_BESTIARY_V56_13.getCreature(name);if(!c&&global.DNDMonsters&&global.DNDMonsters.catalog)c=clone(global.DNDMonsters.catalog[name]);return c;}
  function addCreature(name,count){var d=ensureDraft(),t=findCreature(name);count=Math.max(1,Math.floor(n(count,1)));if(!t)return {ok:false,error:'Существо не найдено: '+name};for(var i=0;i<count;i++){var c=clone(t);c.id='v59_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);c.name=(t.name||name)+(count>1?' #'+(i+1):'');c.tempHp=0;c.defeated=false;c.conditions=c.conditions||{};c.v59Source=name;d.combatants.push(c);}save();render();return {ok:true,count:count,creature:name};}
  function removeCreature(i){var d=ensureDraft();if(i<0||i>=d.combatants.length)return {ok:false,error:'Неверный индекс.'};d.combatants.splice(i,1);save();render();return {ok:true};}
  function clearDraft(){state.draft=null;save();render();return {ok:true};}
  function ensureTrackerFromDraft(){var h=hero(),d=state.draft;if(!h||!d)return {ok:false,error:'Персонаж или encounter отсутствует.'};if(!Array.isArray(h.initiativeTracker)){}h.initiativeTracker={round:1,activeIndex:0,combatants:[]};if(typeof global.addInitiativeCombatant==='function')global.addInitiativeCombatant(h.name||'Герой',true);h.initiativeTracker.combatants=h.initiativeTracker.combatants.concat(d.combatants.map(function(c){return clone(c);}));if(typeof global.sortInitiativeTracker==='function')global.sortInitiativeTracker();if(global.DNDBattleBoard&&typeof global.DNDBattleBoard.syncFromInitiative==='function')global.DNDBattleBoard.syncFromInitiative();return {ok:true,tracker:h.initiativeTracker};}
  function launch(name){var d=state.draft;if(!d||!d.combatants.length)return {ok:false,error:'Добавьте хотя бы одного участника.'};d.name=name||d.name||'Новый encounter';var r=ensureTrackerFromDraft();if(!r.ok)return r;var id='enc_'+Date.now()+'_'+Math.random().toString(36).slice(2,7);state.activeEncounterId=id;var c=campaign();if(c){c.encounterIds=Array.isArray(c.encounterIds)?c.encounterIds:[];c.encounterIds.push(id);c.gameplayEvents=Array.isArray(c.gameplayEvents)?c.gameplayEvents:[];c.gameplayEvents.push({type:'ENCOUNTER_CREATED_V59',encounterId:id,name:d.name,at:new Date().toISOString(),combatantCount:d.combatants.length});}if(global.DNDGameplayV58&&typeof global.DNDGameplayV58.startEncounter==='function')global.DNDGameplayV58.startEncounter(d.name,{sessionId:global.DNDGameplayV58.snapshot().sessionId||null});save();if(typeof global.renderInitiativeTracker==='function')global.renderInitiativeTracker();if(typeof global.dndGameplayCoreV57Render==='function')global.dndGameplayCoreV57Render();openBoard();render();return {ok:true,id:id,name:d.name,combatantCount:d.combatants.length};}
  function openBoard(){if(global.DNDBattleBoard&&typeof global.DNDBattleBoard.open==='function')global.DNDBattleBoard.open();else if(typeof global.dndBattleOpen==='function')global.dndBattleOpen();}
  function tokens(){var h=hero(),b=h&&h.initiativeTracker&&h.initiativeTracker.battlefield;return b&&b.tokens?b.tokens:{};}
  function placeToken(tokenId,x,y){var h=hero(),b=h&&h.initiativeTracker&&h.initiativeTracker.battlefield;if(!b||!b.tokens||!b.tokens[tokenId])return {ok:false,error:'Токен не найден.'};x=Math.floor(n(x,-1));y=Math.floor(n(y,-1));if(x<0||y<0||x>=b.cols||y>=b.rows)return {ok:false,error:'Клетка вне поля.'};b.tokens[tokenId].x=x;b.tokens[tokenId].y=y;if(typeof global.autoSaveCurrentCharacter==='function')global.autoSaveCurrentCharacter();if(global.DNDBattleBoard&&typeof global.DNDBattleBoard.render==='function')global.DNDBattleBoard.render();return {ok:true,token:b.tokens[tokenId]};}
  function snapshot(){var d=state.draft;return {version:VERSION,draft:d?clone(d):null,activeEncounterId:state.activeEncounterId,tokenCount:Object.keys(tokens()).length,combatantCount:d?d.combatants.length:0};}
  function inject(){if(document.getElementById('dndEncounterMapV59'))return;var tab=document.getElementById('tabDice')||document.querySelector('.tab-page');if(!tab)return;var box=document.createElement('div');box.className='card';box.id='dndEncounterMapV59';box.style.marginTop='12px';tab.appendChild(box);render();}
  function render(){var root=document.getElementById('dndEncounterMapV59');if(!root)return;var d=state.draft,cats=catalogs();root.innerHTML='<h3>🗺️ V59 Encounter / Map</h3>'+(d?'<div style="display:flex;gap:6px;flex-wrap:wrap"><input id="v59Name" value="'+esc(d.name)+'" placeholder="Название боя" style="flex:1;min-width:180px"><select id="v59Creature" style="flex:1;min-width:180px"><option value="">— добавить существо —</option>'+cats.map(function(x){return '<option value="'+esc(x.name)+'">'+esc(x.name)+(x.data.cr!=null?' · CR '+esc(x.data.cr):'')+'</option>';}).join('')+'</select><input id="v59Count" type="number" min="1" value="1" style="width:65px"><button class="btn-action" onclick="DNDEncounterMapV59.addSelected()">＋ Добавить</button></div><div style="margin-top:7px">'+(d.combatants.length?d.combatants.map(function(c,i){return '<div style="display:flex;gap:6px;align-items:center;padding:5px;border-bottom:1px solid #333"><span style="flex:1">'+esc(c.name)+' · CR '+esc(c.cr==null?'?':c.cr)+' · '+esc(c.hp||0)+' HP</span><button class="btn-del" onclick="DNDEncounterMapV59.remove('+i+')">✕</button></div>';}).join(''):'<span style="color:#777">Encounter пуст.</span>')+'</div><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:8px"><button class="btn-action" onclick="DNDEncounterMapV59.launch(document.getElementById(\'v59Name\').value)">⚔️ Запустить бой</button><button class="btn-action" onclick="DNDEncounterMapV59.openBoard()">🧭 Battle Board</button><button class="btn-action" onclick="DNDEncounterMapV59.clear()">🗑 Очистить</button></div>':'<button class="btn-action" onclick="DNDEncounterMapV59.newDraft()">＋ Создать Encounter</button>');}
  function addSelected(){var s=document.getElementById('v59Creature'),q=document.getElementById('v59Count');if(s&&s.value)addCreature(s.value,q&&q.value);}
  function restoreSnapshot(s){if(!s||typeof s!=='object')return {ok:false,error:'Нет snapshot V59.'};state.draft=s.draft?clone(s.draft):null;state.activeEncounterId=s.activeEncounterId||null;save();render();return {ok:true,activeEncounterId:state.activeEncounterId};}
  global.DNDEncounterMapV59={VERSION:VERSION,load:load,save:save,newDraft:function(name){state.draft={id:'encdraft_'+Date.now(),name:name||'Новый encounter',combatants:[],map:{cols:24,rows:18,cellFt:5}};save();render();return state.draft;},addCreature:addCreature,remove:removeCreature,clear:clearDraft,launch:launch,openBoard:openBoard,placeToken:placeToken,tokens:tokens,snapshot:snapshot,restoreSnapshot:restoreSnapshot,render:render,addSelected:addSelected};
  global.dndV59CreateEncounter=function(){return global.DNDEncounterMapV59.newDraft();};
  global.addEventListener('DOMContentLoaded',function(){load();setTimeout(inject,450);});
})(window);
