/** V70.5 Debug Scenario Editor + Chains — developer/QA only. */
(function(global){'use strict';
var VERSION='70.5.0', KEY='dndVttQaScenarioEditorV705', ROOT='dndDebugScenarioEditorV705';
var state={open:false,selected:'',message:'',scenarios:[],run:null};
function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
function hero(){return global.currentCharacter||global.currentChar||null;}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function getPath(o,path){var p=String(path||'').split('.').filter(Boolean);for(var i=0;i<p.length;i++){if(o==null)return undefined;o=o[p[i]];}return o;}
function setPath(o,path,val){var p=String(path||'').split('.').filter(Boolean),x=o;if(!p.length)return;if(p.length===1){x[p[0]]=clone(val);return;}for(var i=0;i<p.length-1;i++){if(!x[p[i]]||typeof x[p[i]]!=='object')x[p[i]]={};x=x[p[i]];}x[p[p.length-1]]=clone(val);}
function resolve(v,h){if(v&&typeof v==='object'&&v.path)return clone(getPath(h,v.path));return clone(v);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state.scenarios));}catch(e){}}
function defaults(){return [
{id:'chain-smoke',name:'🔗 Full VTT Smoke Chain',description:'Character → combat → diagnostics → rollback.',steps:[
 {action:'set',path:'level',value:10},{action:'set',path:'hpCurrent',value:{path:'hpMax'}},{action:'set',path:'classes',value:[{name:'Воин',level:5},{name:'Волшебник',level:5}]},{action:'set',path:'inventory',value:[{name:'QA Sword',quantity:1},{name:'QA Potion',quantity:5}]},{action:'event',event:{type:'DEBUG_SCENARIO_STEP',source:'V70.5',label:'smoke-combat'}},{action:'assert',path:'level',equals:10},{action:'assert',path:'classes.1.name',equals:'Волшебник'}]},
{id:'boss-pipeline',name:'👹 Boss Pipeline',description:'Boss state + diagnostic event + assertions.',steps:[{action:'set',path:'hpMax',value:500},{action:'set',path:'hpCurrent',value:500},{action:'set',path:'ac',value:25},{action:'set',path:'initiative',value:20},{action:'event',event:{type:'DEBUG_BOSS_READY',source:'V70.5'}},{action:'assert',path:'ac',equals:25}]},
{id:'broken-recovery',name:'💥 Broken → Diagnose',description:'Creates an invalid state and verifies it can be inspected.',steps:[{action:'set',path:'hpCurrent',value:-50},{action:'set',path:'hpMax',value:1},{action:'set',path:'speed',value:0},{action:'event',event:{type:'DEBUG_BROKEN_STATE',source:'V70.5'}},{action:'assert',path:'hpCurrent',equals:-50}]}
];}
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||'null');if(Array.isArray(x)&&x.length)state.scenarios=x;else state.scenarios=defaults();}catch(e){state.scenarios=defaults();}persist();}
function save(s){var found=false;state.scenarios=state.scenarios.map(function(x){if(x.id===s.id){found=true;return s;}return x;});if(!found)state.scenarios.push(s);persist();state.selected=s.id;}
function refresh(){['updateCharacterUI','renderCharacterSheet','renderConditions','renderSpellSlots','renderCombatAbilities'].forEach(function(n){try{if(typeof global[n]==='function')global[n]();}catch(e){}});try{if(typeof global.autoSaveCurrentCharacter==='function')global.autoSaveCurrentCharacter();}catch(e){}}
function snapshot(){return clone(hero());}
function restore(s){var h=hero();if(!h||!s)return false;Object.keys(h).forEach(function(k){delete h[k];});Object.keys(s).forEach(function(k){h[k]=clone(s[k]);});return true;}
function emit(e){try{if(global.DNDCombatEventBusV69&&global.DNDCombatEventBusV69.record)global.DNDCombatEventBusV69.record(e);}catch(x){}}
function step(step,h){var a=step&&step.action;if(a==='set'){setPath(h,step.path,resolve(step.value,h));return {ok:true,detail:'set '+step.path};}
if(a==='damage'){h.hpCurrent=Math.max(0,(Number(h.hpCurrent)||0)-Number(step.amount||0));return {ok:true,detail:'damage '+step.amount};}
if(a==='heal'){h.hpCurrent=Math.min(Number(h.hpMax)||999999,(Number(h.hpCurrent)||0)+Number(step.amount||0));return {ok:true,detail:'heal '+step.amount};}
if(a==='event'){emit(Object.assign({source:'V70.5',type:'DEBUG_SCENARIO_STEP'},clone(step.event||{})));return {ok:true,detail:'event'};}
if(a==='assert'){var actual=getPath(h,step.path),expected=resolve(step.equals,h),ok=JSON.stringify(actual)===JSON.stringify(expected);return {ok:ok,detail:'assert '+step.path+' expected '+JSON.stringify(expected)+' got '+JSON.stringify(actual)};}
if(a==='diagnose'){var checks=[];['hpCurrent','hpMax','ac','speed','level'].forEach(function(p){var v=getPath(h,p);checks.push({path:p,value:v,ok:typeof v!=='undefined'});});return {ok:checks.every(function(c){return c.ok;}),detail:'diagnose '+checks.length+' fields'};}
return {ok:false,detail:'unknown action '+a};}
function run(id){var s=state.scenarios.filter(function(x){return x.id===id;})[0];if(!s)return null;var h=hero();if(!h){state.message='✕ Нет активного персонажа';render();return null;}var before=snapshot(),results=[],ok=true;(s.steps||[]).forEach(function(x){try{var r=step(x,h);results.push(r);if(!r.ok)ok=false;}catch(e){ok=false;results.push({ok:false,detail:String(e.message||e)});}});refresh();state.run={scenarioId:s.id,scenarioName:s.name,startedAt:new Date().toISOString(),before:before,results:results,ok:ok};emit({type:'DEBUG_SCENARIO_CHAIN_RUN',source:'V70.5',scenarioId:s.id,ok:ok,steps:results.length});state.message=(ok?'✓ ':'⚠ ')+s.name+' — '+results.filter(function(x){return x.ok;}).length+'/'+results.length+' шагов';render();return clone(state.run);}
function rollback(){if(!state.run||!state.run.before){state.message='✕ Нет запуска для rollback';render();return false;}var ok=restore(state.run.before);refresh();state.message=ok?'↩ Rollback выполнен':'✕ Rollback не выполнен';state.run=null;render();return ok;}
function importJSON(raw){var x=typeof raw==='string'?JSON.parse(raw):raw;var arr=Array.isArray(x)?x:(x&&Array.isArray(x.scenarios)?x.scenarios:[x]);arr.forEach(function(s){if(!s||!s.id||!Array.isArray(s.steps))throw new Error('Invalid scenario');save({id:String(s.id),name:s.name||s.id,description:s.description||'Imported QA scenario',steps:clone(s.steps)});});state.message='✓ Импортировано: '+arr.length;render();return arr.length;}
function exportJSON(id){var x=id?state.scenarios.filter(function(s){return s.id===id;})[0]:state.scenarios;return JSON.stringify(x||[],null,2);}
function createFromUI(){var n=document.getElementById('v705Name'),j=document.getElementById('v705JSON');if(!n||!j)return;try{var steps=JSON.parse(j.value);if(!Array.isArray(steps))throw new Error('Steps must be an array');save({id:'custom-'+Date.now(),name:n.value||'Custom Scenario',description:'Custom V70.5 chain',steps:steps});state.message='✓ Сценарий сохранён';render();}catch(e){state.message='✕ JSON: '+e.message;render();}}
function select(id){state.selected=id;render();}
function open(){state.open=true;load();render();}function close(){state.open=false;render();}
function button(t,f){return '<button class="btn-action" style="padding:7px;margin:3px" onclick="'+f+'">'+t+'</button>';}
function render(){var r=document.getElementById(ROOT);if(!r||!r.style)return;r.style.display=state.open?'block':'none';if(!state.open)return;var list=state.scenarios.map(function(s){return '<button class="btn-action" style="display:block;width:100%;text-align:left;margin:4px 0;padding:8px" onclick="dndV705Select(\''+esc(s.id).replace(/&#39;/g,"\\'")+'\')">'+esc(s.name)+'</button>';}).join('');var s=state.scenarios.filter(function(x){return x.id===state.selected;})[0];var detail=s?'<h3>'+esc(s.name)+'</h3><p>'+esc(s.description)+'</p><pre style="max-height:28vh;overflow:auto;background:#171717;padding:8px">'+esc(JSON.stringify(s.steps,null,2))+'</pre>'+button('▶ RUN CHAIN','dndV705Run(\''+esc(s.id).replace(/&#39;/g,"\\'")+'\')')+' '+button('↩ ROLLBACK','dndV705Rollback()')+' '+button('⬇ EXPORT','dndV705Export(\''+esc(s.id).replace(/&#39;/g,"\\'")+'\')'):'<p style="color:#aaa">Выберите сценарий.</p>';r.innerHTML='<div style="padding:10px;max-width:1100px;margin:auto;font-family:system-ui"><div style="display:flex;justify-content:space-between"><b>🔗 Scenario Editor — V70.5</b>'+button('✕','dndV705Close()')+'</div><div style="display:grid;grid-template-columns:minmax(190px,.7fr) 1.3fr;gap:10px;margin-top:10px"><div>'+list+'</div><div>'+detail+'<hr><h3>➕ Create / Import</h3><input id="v705Name" placeholder="Название" style="width:100%;box-sizing:border-box;padding:8px;background:#111;color:#fff"><textarea id="v705JSON" style="width:100%;height:150px;margin-top:6px;background:#111;color:#fff" placeholder="[{\"action\":\"set\",\"path\":\"hpCurrent\",\"value\":1}]\"></textarea>'+button('💾 SAVE SCENARIO','dndV705Create()')+' '+button('⬆ IMPORT FILE','dndV705ImportPrompt()')+'</div></div><div style="margin-top:8px;background:#171717;padding:8px;font-size:.75em;white-space:pre-wrap">'+esc(state.message||'')+'</div></div>';}
function exportToFile(id){var text=exportJSON(id),blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dnd_vtt_scenario_'+(id||'all')+'_v705.json';a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
function importPrompt(){var input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=function(){var f=input.files&&input.files[0];if(!f)return;var reader=new FileReader();reader.onload=function(){try{importJSON(reader.result);}catch(e){state.message='✕ Import: '+e.message;render();}};reader.readAsText(f);};input.click();}
global.DNDDebugScenarioEditorV705={version:VERSION,open:open,close:close,run:run,rollback:rollback,importJSON:importJSON,exportJSON:exportJSON,list:function(){return clone(state.scenarios);},state:function(){return clone(state);}};
global.dndV705Open=open;global.dndV705Close=close;global.dndV705Run=run;global.dndV705Rollback=rollback;global.dndV705Select=select;global.dndV705Create=createFromUI;global.dndV705Export=exportToFile;global.dndV705ImportPrompt=importPrompt;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){load();});else load();
})(window);
