/**
 * vtt_mobile_session_v67.js
 * ------------------------------------------------------------------
 * WHAT: touch-first mobile VTT session save/restore layer.
 * HOW: serializes the current character, Gameplay Core snapshot, selected
 * combat metadata and V66 combat-log history into versioned localStorage
 * slots. It can export/import a JSON session without becoming a second
 * campaign/combat/save engine.
 * DOES NOT: replace campaign_manager, character persistence, combat_engine
 * or network authority. It only orchestrates snapshots and recovery.
 * PUBLIC API: DNDMobileSessionV67, dndV67Open, dndV67Close,
 * dndV67Save, dndV67Restore, dndV67Export, dndV67ImportText.
 * ------------------------------------------------------------------
 */
(function(global){'use strict';
  var VERSION='67.3.0', SCHEMA_VERSION=4, KEY='dnd_vtt_mobile_session_v67', state={open:false,slot:'quick',lastRestoredKey:''};
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return null;}}
  function now(){return new Date().toISOString();}
  function hero(){return global.currentCharacter||global.currentChar||null;}
  function charSnapshot(){var h=hero();if(!h)return null;var x=clone(h)||{};delete x.__proto__;return x;}
  function gameplaySnapshot(){try{return global.DNDGameplayV57&&typeof global.DNDGameplayV57.snapshot==='function'?clone(global.DNDGameplayV57.snapshot()):null;}catch(e){return null;}}
  function combatLog(){try{return global.DNDCombatLogV66&&typeof global.DNDCombatLogV66.events==='function'?clone(global.DNDCombatLogV66.events()):[];}catch(e){return [];}}
  function board(){try{return global.DNDBattleBoard&&typeof global.DNDBattleBoard.getView==='function'?clone(global.DNDBattleBoard.getView()):null;}catch(e){return null;}}
  function networkMeta(){var n=global.dndNetwork&&global.dndNetwork.state||null;return n?{roomId:String(n.roomId||''),stateRevision:Number(n.stateRevision)||0,eventSeq:Number(n.eventSeq)||0,authorityEpoch:Number(n.authorityEpoch)||0,authorityId:String(n.authorityId||n.clientId||''),clientId:String(n.clientId||'')}:{roomId:'',stateRevision:0,eventSeq:0,authorityEpoch:0,authorityId:'',clientId:''};}
  function build(){var nm=networkMeta();return {version:VERSION,schemaVersion:SCHEMA_VERSION,saveId:'save_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8),createdAt:now(),app:'DND VTT',character:charSnapshot(),gameplay:gameplaySnapshot(),combatLog:combatLog().slice(-300),battleBoard:board(),network:global.dndNetwork&&global.dndNetwork.state?clone(global.dndNetwork.state):null,authoritySnapshot:nm};}
  function slots(){try{return JSON.parse(global.localStorage.getItem(KEY)||'{}')||{};}catch(e){return {};}}
  function writeSlot(slot,payload){var s=slots();s[slot]={savedAt:now(),payload:payload};try{global.localStorage.setItem(KEY,JSON.stringify(s));return true;}catch(e){return false;}}
  function readSlot(slot){var s=slots();return s[slot]&&s[slot].payload?migrate(s[slot].payload):null;}
  function migrate(p){if(!p||typeof p!=='object')return null;var x=clone(p);if(!x)return null;x.schemaVersion=SCHEMA_VERSION;x.version=VERSION;x.saveId=x.saveId||('save_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8));x.combatLog=Array.isArray(x.combatLog)?x.combatLog.slice(-300):[];x.authoritySnapshot=x.authoritySnapshot||{roomId:x.network&&x.network.roomId||'',stateRevision:Number(x.network&&x.network.stateRevision)||0,eventSeq:Number(x.network&&x.network.eventSeq)||0,authorityEpoch:Number(x.network&&x.network.authorityEpoch)||0,authorityId:String(x.network&&x.network.authorityId||'')};return x;}
  function listSlots(){var s=slots();return Object.keys(s).map(function(k){return {slot:k,savedAt:s[k].savedAt||null,hasCharacter:!!(s[k].payload&&s[k].payload.character),round:s[k].payload&&s[k].payload.gameplay&&s[k].payload.gameplay.round||0};});}
  function applyCharacter(payload){if(!payload)return false;var h=clone(payload);try{if('currentCharacter' in global)global.currentCharacter=h;if('currentChar' in global)global.currentChar=h;return true;}catch(e){return false;}}
  function restore(slot){var p=readSlot(slot||state.slot);if(!p)return {ok:false,error:'Сохранение не найдено.'};var live=global.dndNetwork&&global.dndNetwork.state||null, saved=p.authoritySnapshot||null;if(live&&saved&&saved.roomId&&String(live.roomId||'')===String(saved.roomId||'')){var le=Number(live.authorityEpoch)||0,lr=Number(live.stateRevision)||0,se=Number(saved.authorityEpoch)||0,sr=Number(saved.stateRevision)||0;if(le>se||(le===se&&lr>sr))return {ok:false,stale:true,error:'Локальное сохранение устарело относительно авторитетного состояния комнаты.',liveRevision:lr,saveRevision:sr,liveEpoch:le,saveEpoch:se};}if(p.saveId&&state.lastRestoredKey===String(slot||state.slot)+':'+p.saveId)return {ok:true,slot:slot||state.slot,idempotent:true,restoredAt:now(),round:p.gameplay&&p.gameplay.round||0};var before=charSnapshot();var ok=applyCharacter(p.character);if(!ok)return {ok:false,error:'Не удалось восстановить персонажа.'};try{if(global.DNDGameplayV57&&typeof global.DNDGameplayV57.restoreSnapshot==='function'&&p.gameplay)global.DNDGameplayV57.restoreSnapshot(p.gameplay);if(global.DNDBattleBoard&&p.battleBoard&&typeof global.DNDBattleBoard.setView==='function')global.DNDBattleBoard.setView(p.battleBoard);if(typeof global.dndSyncCurrentCharacterFromCombat==='function')global.dndSyncCurrentCharacterFromCombat();}catch(e){applyCharacter(before);return {ok:false,error:'Не удалось восстановить состояние боя: '+e.message};}if(global.DNDCombatLogV66&&typeof global.DNDCombatLogV66.clear==='function'&&p.combatLog&&p.combatLog.length){global.DNDCombatLogV66.clear();p.combatLog.forEach(function(e){if(global.DNDCombatLogV66.record)global.DNDCombatLogV66.record(e);});}if(typeof global.autoSaveCurrentCharacter==='function')try{global.autoSaveCurrentCharacter();}catch(e){};state.lastRestoredKey=String(slot||state.slot)+':'+String(p.saveId||'');render();return {ok:true,slot:slot||state.slot,restoredAt:now(),round:p.gameplay&&p.gameplay.round||0,idempotent:false};}
  function save(slot){slot=slot||state.slot;var p=build(),ok=writeSlot(slot,p);if(ok){state.slot=slot;render();return {ok:true,slot:slot,savedAt:p.createdAt};}return {ok:false,error:'Не удалось записать localStorage.'};}
  function remove(slot){var s=slots();delete s[slot||state.slot];try{global.localStorage.setItem(KEY,JSON.stringify(s));render();return true;}catch(e){return false;}}
  function exportSession(slot){var p=readSlot(slot||state.slot)||build(),blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dnd_vtt_session_v67_'+String(slot||state.slot)+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);return p;}
  function importText(text,slot){var p;try{p=JSON.parse(String(text||''));}catch(e){return {ok:false,error:'JSON повреждён или имеет неверный формат.'};}p=migrate(p);if(!p||typeof p!=='object'||(!p.character&&!p.gameplay))return {ok:false,error:'Это не похоже на сохранение D&D VTT.'};var ok=writeSlot(slot||state.slot,p);render();return {ok:ok,slot:slot||state.slot};}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function msg(text){var el=document.getElementById('dndV67Result');if(el)el.textContent=text;}
  function render(){var root=document.getElementById('dndMobileSessionV67');if(!root)return;root.style.display=state.open?'block':'none';var ss=listSlots();var rows=ss.length?ss.map(function(x){return '<div style="display:grid;grid-template-columns:1fr auto;gap:6px;align-items:center;border:1px solid #444;border-radius:9px;padding:8px;margin:6px 0"><div><b>'+esc(x.slot)+'</b><div style="font-size:.7em;color:#aaa">'+esc(x.savedAt||'')+' • раунд '+Number(x.round||0)+(x.hasCharacter?' • персонаж ✓':'')+'</div></div><button class="btn-action" onclick="dndV67Restore(\''+esc(x.slot).replace(/'/g,'\\\'')+'\')">Восстановить</button></div>';}).join(''):'<div style="color:#888;padding:8px">Сохранений пока нет.</div>';
    root.innerHTML='<div style="padding:11px;max-width:720px;margin:auto"><div style="display:flex;justify-content:space-between;align-items:center"><b>💾 Mobile Session V67</b><button class="btn-action" onclick="dndV67Close()">✕</button></div><p style="color:#aaa;font-size:.78em">Сохраняет снимок текущего персонажа, Gameplay Core и журнала боя. Авторитетные движки не заменяются.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px"><button class="btn-action" onclick="dndV67Save()">💾 Быстро сохранить</button><button class="btn-action" onclick="dndV67Export()">⇩ Экспорт JSON</button></div><div style="margin-top:8px"><input id="dndV67ImportFile" type="file" accept="application/json,.json" style="width:100%;box-sizing:border-box;padding:8px;background:#222;color:#ddd;border:1px solid #444;border-radius:7px" onchange="dndV67FileImport(this)"></div><div id="dndV67Result" style="color:#aaa;font-size:.78em;margin:8px 0"></div><h4>Сохранения</h4>'+rows+'</div>';
  }
  function open(){state.open=true;render();}function close(){state.open=false;render();}
  function init(){if(document.getElementById('dndMobileSessionV67'))return;var e=document.createElement('div');e.id='dndMobileSessionV67';e.style.cssText='display:none;position:fixed;inset:0;z-index:29920;background:rgba(10,10,10,.99);color:#fff;overflow:auto;padding:calc(10px + env(safe-area-inset-top)) 8px calc(10px + env(safe-area-inset-bottom));box-sizing:border-box;touch-action:manipulation;';document.body.appendChild(e);}
  function fileImport(input){var f=input&&input.files&&input.files[0];if(!f)return;var r=new FileReader();r.onload=function(){var x=importText(r.result,state.slot);msg(x.ok?'Импорт сохранён.':'Ошибка импорта: '+x.error);render();};r.readAsText(f);}
  global.dndV67Open=open;global.dndV67Close=close;global.dndV67Save=function(s){var r=save(s);msg(r.ok?'Сохранено: '+r.slot:'Ошибка: '+r.error);return r;};global.dndV67Restore=function(s){var r=restore(s);msg(r.ok?'Восстановлено: '+r.slot:'Ошибка: '+r.error);return r;};global.dndV67Export=function(s){var r=exportSession(s);msg('JSON экспортирован.');return r;};global.dndV67FileImport=fileImport;global.dndV67Delete=function(s){return remove(s);};
  global.DNDMobileSessionV67={VERSION:VERSION,SCHEMA_VERSION:SCHEMA_VERSION,build:build,save:save,restore:restore,remove:remove,slots:listSlots,exportSession:exportSession,importText:importText,open:open,close:close};
  if(global.addEventListener)global.addEventListener('DOMContentLoaded',function(){init();});
})(window);
