/**
 * vtt_combat_event_bus_v69.js
 * V69 normalized combat event bus and read-only replay layer.
 * It mirrors V66 combat-log records into a versioned timeline, deduplicates by event id,
 * and provides mobile replay controls without mutating authoritative combat/gameplay state.
 * Public API: DNDCombatEventBusV69, dndV69OpenReplay, dndV69CloseReplay, dndV69Record,
 * dndV69Step, dndV69Seek, dndV69Play, dndV69Stop, dndV69ExportReplay.
 */
(function(global){'use strict';
  var VERSION='69.0.0',KEY='dnd_vtt_event_bus_v69',MAX=500,events=[],state={open:false,index:-1,playing:false,timer:null,filter:'all'};
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function now(){return new Date().toISOString();}
  function load(){try{var x=JSON.parse(global.localStorage.getItem(KEY)||'[]');if(Array.isArray(x))events=x.slice(-MAX);}catch(e){events=[];}}
  function save(){try{global.localStorage.setItem(KEY,JSON.stringify(events.slice(-MAX)));}catch(e){}}
  function normalize(ev){var x=clone(ev||{}),r=x.resolution||x.payload||x;x.id=x.id||'evt69_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);x.at=x.at||x.timestamp||now();x.type=String(x.type||x.kind||'EVENT');x.version=VERSION;x.replay={readOnly:true};x.summary=x.summary||buildSummary(x,r);return x;}
  function buildSummary(e,r){var bits=[String(e.type||'EVENT').replace(/_/g,' ')];if(r&&r.kind)bits.push(String(r.kind));if(r&&r.sourceId)bits.push('actor:'+r.sourceId);if(r&&r.targetId)bits.push('target:'+r.targetId);if(r&&r.total!=null)bits.push('total:'+r.total);if(r&&r.damage&&r.damage.total!=null)bits.push('damage:'+r.damage.total);if(r&&r.critical)bits.push('CRIT');if(r&&r.fumble)bits.push('FUMBLE');return bits.join(' • ');}
  function record(ev,opts){var x=normalize(ev);if(events.some(function(e){return e.id===x.id;}))return events.filter(function(e){return e.id===x.id;})[0];x.seq=events.length?Number(events[events.length-1].seq||0)+1:1;events.push(x);if(events.length>MAX)events=events.slice(-MAX);save();render();return x;}
  function all(){return clone(events);}
  function filtered(){return events.filter(function(e){return state.filter==='all'||String(e.type||'').toLowerCase().indexOf(state.filter)>=0;});}
  function current(){var a=filtered();return state.index>=0&&state.index<a.length?a[state.index]:null;}
  function setIndex(i){var a=filtered();if(!a.length){state.index=-1;render();return null;}state.index=Math.max(0,Math.min(a.length-1,Number(i)||0));render();return clone(a[state.index]);}
  function step(delta){var a=filtered();if(!a.length)return null;var base=state.index<0?(delta>0?-1:a.length):state.index;return setIndex(base+delta);}
  function seek(i){return setIndex(i);}
  function play(){stop();var a=filtered();if(!a.length)return null;if(state.index<0||state.index>=a.length-1)state.index=0;state.playing=true;render();state.timer=setInterval(function(){var next=state.index+1;if(next>=filtered().length){stop();return;}state.index=next;render();},700);return clone(current());}
  function stop(){if(state.timer){clearInterval(state.timer);state.timer=null;}state.playing=false;render();}
  function clear(){stop();events=[];state.index=-1;save();render();}
  function snapshot(){return {version:VERSION,eventCount:events.length,filter:state.filter,index:state.index,currentId:current()&&current().id||null,readOnly:true};}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function detail(e){if(!e)return 'Событие не выбрано.';var r=e.resolution||e.payload||e;return JSON.stringify({id:e.id,seq:e.seq,at:e.at,type:e.type,summary:e.summary,resolution:r,replay:{readOnly:true}},null,2);}
  function render(){var root=document.getElementById('dndCombatReplayV69');if(!root)return;root.style.display=state.open?'block':'none';var a=filtered(),cur=current();var timeline=a.map(function(e,i){var active=i===state.index?'border-color:#fff;background:#303030;':'';return '<button class="btn-action" style="display:block;width:100%;text-align:left;margin:4px 0;padding:8px;'+active+'" onclick="dndV69Seek('+i+')"><b>#'+esc(e.seq)+'</b> '+esc(e.summary||e.type)+'<span style="display:block;color:#888;font-size:.68em">'+esc(e.at)+'</span></button>';}).join('')||'<div style="color:#888;padding:12px">Событий для replay нет.</div>';root.innerHTML='<div style="padding:11px;max-width:800px;margin:auto"><div style="display:flex;justify-content:space-between;align-items:center"><b>⏪ Combat Replay V69</b><button class="btn-action" onclick="dndV69CloseReplay()">✕</button></div><div style="font-size:.75em;color:#aaa;margin:6px 0">Read-only: replay меняет только позицию просмотра и не изменяет authoritative combat state.</div><div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:5px"><button class="btn-action" onclick="dndV69Step(-1)">◀ Назад</button><button class="btn-action" onclick="dndV69Play()">▶ '+(state.playing?'Идёт':'Play')+'</button><button class="btn-action" onclick="dndV69Step(1)">Вперёд ▶</button><button class="btn-action" onclick="dndV69Stop()">■ Стоп</button></div><div style="display:flex;gap:5px;overflow:auto;margin:8px 0"><button class="btn-action" onclick="dndV69Filter(\'all\')">Все</button><button class="btn-action" onclick="dndV69Filter(\'roll\')">🎲 Roll</button><button class="btn-action" onclick="dndV69Filter(\'damage\')">⚔️ Damage</button><button class="btn-action" onclick="dndV69Filter(\'turn\')">⏭ Turn</button><button class="btn-action" onclick="dndV69ExportReplay()">⇩ JSON</button><button class="btn-action" onclick="dndV69Clear()">Очистить</button></div><div style="display:grid;grid-template-columns:1fr;gap:8px"><div style="border:1px solid #444;border-radius:9px;padding:8px;max-height:45vh;overflow:auto">'+timeline+'</div><pre style="white-space:pre-wrap;word-break:break-word;background:#171717;border:1px solid #444;border-radius:9px;padding:9px;font-size:.68em;min-height:100px;overflow:auto">'+esc(detail(cur))+'</pre></div></div>';}
  function filter(x){state.filter=x;state.index=-1;render();}
  function exportReplay(){var payload={version:VERSION,exportedAt:now(),readOnly:true,events:all()};var blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dnd_vtt_combat_replay_v69.json';a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);return payload;}
  function open(){state.open=true;state.index=filtered().length?Math.max(0,filtered().length-1):-1;render();}
  function close(){stop();state.open=false;render();}
  function init(){load();if(global.DNDCombatLogV66&&typeof global.DNDCombatLogV66.events==='function'){global.DNDCombatLogV66.events().forEach(function(e){record(e);});var original=global.DNDCombatLogV66.record;if(typeof original==='function'&&!original.__v69Wrapped){var wrapped=function(ev){var r=original.call(global.DNDCombatLogV66,ev);record(r||ev);return r;};wrapped.__v69Wrapped=true;global.DNDCombatLogV66.record=wrapped;global.dndV66Record=wrapped;}}
    if(!document.getElementById('dndCombatReplayV69')){var e=document.createElement('div');e.id='dndCombatReplayV69';e.style.cssText='display:none;position:fixed;inset:0;z-index:29950;background:rgba(8,8,8,.99);color:#fff;overflow:auto;padding:calc(10px + env(safe-area-inset-top)) 8px calc(10px + env(safe-area-inset-bottom));box-sizing:border-box;touch-action:manipulation;';document.body.appendChild(e);} }
  global.dndV69OpenReplay=open;global.dndV69CloseReplay=close;global.dndV69Record=record;global.dndV69Step=step;global.dndV69Seek=seek;global.dndV69Play=play;global.dndV69Stop=stop;global.dndV69Filter=filter;global.dndV69ExportReplay=exportReplay;global.dndV69Clear=clear;global.DNDCombatEventBusV69={VERSION:VERSION,record:record,events:all,filtered:function(){return clone(filtered())},current:function(){return clone(current())},step:step,seek:seek,play:play,stop:stop,clear:clear,snapshot:snapshot,exportReplay:exportReplay,openReplay:open,closeReplay:close};
  if(global.addEventListener)global.addEventListener('DOMContentLoaded',init);
})(window);
