/** V70.4 Debug Scenario Manager — developer/QA only. */
(function(global){'use strict';
var VERSION='70.4.0', KEY='dndVttQaScenariosV704', ROOT='dndDebugScenariosV704';
var state={open:false,selected:'',message:'',scenarios:[],run:null};
function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function hero(){return global.currentCharacter||global.currentChar||null;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state.scenarios));}catch(e){}}
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||'[]');if(Array.isArray(x))state.scenarios=x;}catch(e){}if(!state.scenarios.length)defaults();}
function defaults(){state.scenarios=[
{id:'near-death',name:'☠ Nearly Dead',description:'Персонаж на грани смерти.',actions:[['set','hpCurrent',1],['set','hpTemp',0],['set','deathSaves',{successes:0,failures:2}]]},
{id:'full-power',name:'✨ Full Power',description:'Максимальные базовые ресурсы для smoke test.',actions:[['set','hpCurrent',{path:'hpMax'}],['set','hpTemp',50],['set','inspiration',true]]},
{id:'multiclass',name:'🧙 Multiclass 10/10',description:'Два класса с общей суммой 20.',actions:[['set','classes',[{name:'Воин',level:10,subclass:''},{name:'Волшебник',level:10,subclass:''}]],['set','level',20]]},
{id:'boss',name:'👹 Boss Encounter',description:'Тяжёлое боевое состояние.',actions:[['set','hpMax',500],['set','hpCurrent',500],['set','ac',25],['set','speed','40'],['set','initiative',20]]},
{id:'spellcaster',name:'🔮 Spellcaster Test',description:'Полные spell slots для проверки магии.',actions:[['set','spellSlots',{1:{current:4,max:4},2:{current:3,max:3},3:{current:3,max:3},4:{current:3,max:3},5:{current:2,max:2},6:{current:1,max:1},7:{current:1,max:1},8:{current:1,max:1},9:{current:1,max:1}}]]},
{id:'broken-state',name:'💥 Broken State',description:'Намеренно противоречивое состояние для диагностики.',actions:[['set','hpCurrent',-50],['set','hpMax',1],['set','ac',-10],['set','speed',0],['set','level',99],['set','initiative',-20]]}
];persist();}
function msg(s){state.message=s;render();}
function getPath(o,path){var p=String(path||'').split('.').filter(Boolean);for(var i=0;i<p.length;i++){if(o==null)return undefined;o=o[p[i]];}return o;}
function setPath(o,path,val){var p=String(path||'').split('.').filter(Boolean),x=o;if(!p.length)return;if(p.length===1){x[p[0]]=val;return;}for(var i=0;i<p.length-1;i++){if(!x[p[i]]||typeof x[p[i]]!=='object')x[p[i]]={};x=x[p[i]];}x[p[p.length-1]]=val;}
function resolve(val,h){if(val&&typeof val==='object'&&val.path)return clone(getPath(h,val.path));return clone(val);}
function snapshot(){var h=hero();return h?clone(h):null;}
function restore(s){var h=hero();if(!h||!s)return false;Object.keys(h).forEach(function(k){delete h[k];});Object.keys(s).forEach(function(k){h[k]=clone(s[k]);});return true;}
function refresh(){['updateCharacterUI','renderCharacterSheet','renderConditions','renderSpellSlots','renderCombatAbilities'].forEach(function(n){try{if(typeof global[n]==='function')global[n]();}catch(e){}});try{if(typeof global.autoSaveCurrentCharacter==='function')global.autoSaveCurrentCharacter();}catch(e){}}
function run(id,opts){var s=state.scenarios.filter(function(x){return x.id===id;})[0];if(!s)return msg('✕ Сценарий не найден');var h=hero();if(!h)return msg('✕ Нет активного персонажа');var before=snapshot(),applied=0,errors=[];s.actions.forEach(function(a){try{if(a[0]==='set'){setPath(h,a[1],resolve(a[2],h));applied++;}else if(a[0]==='damage'){h.hpCurrent=Math.max(0,(Number(h.hpCurrent)||0)-Number(a[1]));applied++;}else if(a[0]==='heal'){h.hpCurrent=Math.min(Number(h.hpMax)||999999,(Number(h.hpCurrent)||0)+Number(a[1]));applied++;}}catch(e){errors.push(String(e.message||e));}});refresh();state.run={scenarioId:s.id,scenarioName:s.name,startedAt:new Date().toISOString(),before:before,applied:applied,errors:errors};try{if(global.DNDCombatEventBusV69&&global.DNDCombatEventBusV69.record)global.DNDCombatEventBusV69.record({type:'DEBUG_SCENARIO_RUN',source:'V70.4',scenarioId:s.id,applied:applied});}catch(e){}msg('✓ '+s.name+' запущен: '+applied+' действий'+(errors.length?' / ошибок '+errors.length:''));return clone(state.run);}
function rollback(){if(!state.run||!state.run.before)return msg('✕ Нет запуска для rollback');if(!restore(state.run.before))return msg('✕ Нет активного персонажа');refresh();msg('↩ Сценарий откатан: '+state.run.scenarioName);state.run=null;}
function saveCustom(){var name=document.getElementById('v704Name'),json=document.getElementById('v704JSON');if(!name||!json)return;var actions;try{actions=JSON.parse(json.value);if(!Array.isArray(actions))throw new Error('Actions must be an array');}catch(e){return msg('✕ JSON: '+e.message);}var id='custom-'+Date.now();state.scenarios.push({id:id,name:name.value||id,description:'Custom QA scenario',actions:actions});persist();state.selected=id;msg('✓ Сценарий сохранён');}
function removeSelected(){var id=state.selected;if(!id)return msg('✕ Сценарий не выбран');state.scenarios=state.scenarios.filter(function(x){return x.id!==id;});persist();state.selected='';msg('✓ Сценарий удалён');}
function select(id){state.selected=id;render();}
function open(){state.open=true;load();render();}
function close(){state.open=false;render();}
function render(){var r=document.getElementById(ROOT);if(!r||!r.style)return;r.style.display=state.open?'block':'none';if(!state.open)return;var list=state.scenarios.map(function(s){return '<button class="btn-action" style="display:block;width:100%;text-align:left;margin:4px 0;padding:8px;'+(state.selected===s.id?'border:2px solid #fff;':'')+'" onclick="dndV704Select(\''+esc(s.id).replace(/&#39;/g,"\\'")+ '\')">'+esc(s.name)+'</button>';}).join('');var s=state.scenarios.filter(function(x){return x.id===state.selected;})[0];var detail=s?'<h3>'+esc(s.name)+'</h3><p style="color:#aaa;font-size:.8em">'+esc(s.description)+'</p><pre style="background:#171717;padding:8px;max-height:25vh;overflow:auto">'+esc(JSON.stringify(s.actions,null,2))+'</pre>'+button('▶ RUN','dndV704Run(\''+esc(s.id).replace(/&#39;/g,"\\'")+'\')')+' '+button('↩ ROLLBACK','dndV704Rollback()'):'<p style="color:#aaa">Выберите сценарий.</p>';r.innerHTML='<div style="padding:10px;max-width:1000px;margin:auto;font-family:system-ui,sans-serif"><div style="display:flex;justify-content:space-between"><b>🧩 Scenario Manager — V70.4</b>'+button('✕','dndV704Close()')+'</div><div style="display:grid;grid-template-columns:minmax(180px,.7fr) 1.3fr;gap:10px;margin-top:10px"><div>'+list+'</div><div>'+detail+'<hr><h3>➕ Custom Scenario</h3><input id="v704Name" placeholder="Название" style="width:100%;box-sizing:border-box;padding:8px;background:#111;color:#fff;border:1px solid #555"><textarea id="v704JSON" style="width:100%;height:130px;box-sizing:border-box;margin-top:6px;background:#111;color:#fff" placeholder="[[\"set\",\"hpCurrent\",1]]"></textarea>'+button('💾 SAVE CUSTOM','dndV704SaveCustom()')+' '+button('🗑 DELETE','dndV704Remove()')+'</div></div><div style="margin-top:10px;background:#171717;padding:8px;white-space:pre-wrap;font-size:.75em">'+esc(state.message||'')+'</div></div>';}
function button(t,f){return '<button class="btn-action" style="padding:8px;margin:4px 2px" onclick="'+f+'">'+t+'</button>';}
global.DNDDebugScenarioManagerV704={version:VERSION,open:open,close:close,run:run,rollback:rollback,saveCustom:saveCustom,remove:removeSelected,select:select,list:function(){return clone(state.scenarios);},state:function(){return clone(state);}};
global.dndV704Open=open;global.dndV704Close=close;global.dndV704Run=run;global.dndV704Rollback=rollback;global.dndV704SaveCustom=saveCustom;global.dndV704Remove=removeSelected;global.dndV704Select=select;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){load();});else load();
})(window);
