/* V70.36.79 — touch paint brush for mobile finishing
 * V70.36.78 — editor stabilization: fill, openings, asset drag/drop
 * V70.36.77 — Sims-like UX + texture asset library
 * V70.36.75 — true WebGL 3D map editor
 * Three.js renderer + GLB/GLTF loading. Reads the existing V15 map format from localStorage.
 * The legacy canvas editor remains available as fallback.
 */
(function(global){
'use strict';
var THREE=null,GLTFLoader=null,renderer=null,scene=null,camera=null,root=null,gizmo=null,gizmoAxis=null,gizmoDragging=false,gizmoStartX=0,gizmoStartY=0,gizmoStartPos=null,gizmoStartRot=0,gizmoStartScale=null,raf=0,map=null,selected=null,mode='orbit',editorMode='objects',transformMode='translate',raycaster=null,mouse=null,assetDB=null,assetCache={},controls={yaw:.8,pitch:.8,distance:24,target:{x:0,y:0,z:0}},touches={},touchGesture=null,snapGrid=true,snapSize=0.25;
var VERSION='V70.36.79';
var undoStack=[],redoStack=[],historyBusy=false;
var openingDrag=null,paintMode=false,painting=false,paintHistoryStarted=false,paintMaterial='stone',paintSide='front',paintedDuringStroke={};
function openingForSelected(){var w=selectedWall();return w&&w.opening?w.opening:null;}
function moveOpeningAlongWall(delta){var w=selectedWall(),op=openingForSelected();if(!w||!op)return;pushHistory();op.offset=Math.max(0,Math.min(Math.max(.01,Number(w.length)||1)-Number(op.width||.9),Number(op.offset||0)+delta));saveMap();build();updateInfo();}
function addOpeningVisuals(w){var op=w.opening;if(!op)return;var h=Math.max(.5,Number(w.height)||2.5),len=Math.max(.1,Number(w.length)||1),t=Math.max(.03,Number(w.thickness)||.09),off=Math.max(0,Math.min(len-Number(op.width||.9),Number(op.offset||0))),ow=Math.min(len,Math.max(.1,Number(op.width)||.9)),oh=Math.min(h,Math.max(.1,Number(op.height)||2.1)),sill=Math.max(0,Math.min(h-oh,Number(op.sill)||0)),z=(Number(w.level)||0)*3,x=Number(w.x)||0,y=Number(w.y)||0;var mat=material(op.type==='door'?'#6b4528':'#7fa8c7',op.type==='door'?.7:.25),frame=material('#3b3027',.55);if(w.dir==='n'){if(op.type==='door'){var leaf=addBox('door:'+w.level+':'+x+':'+y,x+off,y-t*.65,z+sill,ow,.055,oh,[mat]);leaf.userData.editorKind='object';leaf.userData.mapOpening=true;}else{var glass=addBox('window:'+w.level+':'+x+':'+y,x+off,y-t*.65,z+sill,ow,.05,oh,[mat]);glass.userData.editorKind='object';glass.userData.mapOpening=true;var f1=addBox('windowFrame:'+x+':'+y,x+off,y-t*.7,z+sill,.06,.08,oh,[frame]);f1.userData.editorKind='object';var f2=addBox('windowFrame:'+x+':'+y,x+off+ow-.06,y-t*.7,z+sill,.06,.08,oh,[frame]);f2.userData.editorKind='object';}}else{if(op.type==='door'){var leaf2=addBox('door:'+w.level+':'+x+':'+y,x+1-t*.65,y+off,z+sill,.055,ow,oh,[mat]);leaf2.userData.editorKind='object';leaf2.userData.mapOpening=true;}else{var glass2=addBox('window:'+w.level+':'+x+':'+y,x+1-t*.65,y+off,z+sill,.05,ow,oh,[mat]);glass2.userData.editorKind='object';glass2.userData.mapOpening=true;}}}
function editOpeningPosition(){var op=openingForSelected();if(!op){alert('Выберите стену с дверью или окном.');return;}var v=prompt('Смещение проёма вдоль стены',String(Number(op.offset||0)));if(v===null)return;v=Number(v);if(!Number.isFinite(v))return;var w=selectedWall();pushHistory();op.offset=Math.max(0,Math.min(Math.max(0,Number(w.length)||1)-Number(op.width||.9),v));saveMap();build();updateInfo();}
function duplicateSelected(){if(!selected||!selected.userData||!selected.userData.mapObjectId){alert('Выберите объект.');return;}var o=(map.objects||[]).find(function(x){return String(x.id)===String(selected.userData.mapObjectId);});if(!o)return;pushHistory();var n=JSON.parse(JSON.stringify(o));n.id='obj_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6);n.x=Number(n.x||0)+.5;n.y=Number(n.y||0)+.5;map.objects.push(n);saveMap();build();updateInfo();}
function applySurfaceFill(key){if(!map||!map.surfaces||!MATERIAL_CATALOG[key])return;var level=Number(map.levels&&map.levels.current)||0,targets=Object.keys(map.surfaces).filter(function(k){return Number(k.split(':')[0])===level&&map.surfaces[k];});if(!targets.length)return;pushHistory();targets.forEach(function(k){var ss=map.surfaces[k];ss.material=key;ss.color=MATERIAL_CATALOG[key].color;});saveMap();build();updateInfo();}

function snapshotMap(){try{return JSON.stringify(map);}catch(e){return null;}}
function pushHistory(){if(!map||historyBusy)return;var snap=snapshotMap();if(snap){undoStack.push(snap);if(undoStack.length>60)undoStack.shift();redoStack=[];}}
function restoreSnapshot(snap){if(!snap)return;historyBusy=true;try{map=JSON.parse(snap);saveMap();build();selected=null;updateGizmo();updateInfo();}finally{historyBusy=false;}}
function undo(){if(!undoStack.length){alert('Отменять больше нечего.');return;}var cur=snapshotMap(),prev=undoStack.pop();if(cur)redoStack.push(cur);restoreSnapshot(prev);}
function redo(){if(!redoStack.length){alert('Повторять больше нечего.');return;}var cur=snapshotMap(),next=redoStack.pop();if(cur)undoStack.push(cur);restoreSnapshot(next);}
function selectedWall(){if(!selected||!selected.name||selected.name.indexOf('wall:')!==0)return null;var k=selected.name.slice(5);return map&&map.walls?map.walls[k]:null;}
function editSelectedWall(){var w=selectedWall();if(!w){alert('Выберите стену в режиме строительства.');return;}var old=JSON.stringify(w);var len=prompt('Длина стены в клетках',String(Number(w.length)||1));if(len===null)return;var thick=prompt('Толщина стены',String(Number(w.thickness)||.09));if(thick===null)return;var height=prompt('Высота стены',String(Number(w.height)||2.5));if(height===null)return;len=Number(len);thick=Number(thick);height=Number(height);if(!Number.isFinite(len)||!Number.isFinite(thick)||!Number.isFinite(height)){alert('Неверные значения.');return;}pushHistory();w.length=Math.max(.1,len);w.thickness=Math.max(.03,thick);w.height=Math.max(.5,height);saveMap();build();updateInfo();}
function editOpening(type){var w=selectedWall();if(!w){alert('Выберите стену.');return;}var old=w.opening||{};if(!confirm(type==='door'?'Добавить/изменить дверь?':'Добавить/изменить окно?'))return;var width=Number(prompt('Ширина проёма в клетках',String(old.width||.9))),height=Number(prompt('Высота проёма',String(old.height||(type==='door'?2.1:1.2)))),sill=Number(prompt('Высота нижнего края',String(old.sill||(type==='door'?0:.9))));if(!Number.isFinite(width)||!Number.isFinite(height)||!Number.isFinite(sill)){alert('Неверные размеры.');return;}pushHistory();w.opening={type:type,width:Math.max(.1,width),height:Math.max(.1,height),sill:Math.max(0,sill),offset:Math.max(0,Number(old.offset)||0)};saveMap();build();updateInfo();}
function clearOpening(){var w=selectedWall();if(!w)return;pushHistory();w.opening=null;saveMap();build();updateInfo();}
var MATERIAL_CATALOG={stone:{name:'Камень',color:'#777d82'},wood:{name:'Дерево',color:'#8b5a2b'},brick:{name:'Кирпич',color:'#9a5140'},plaster:{name:'Штукатурка',color:'#d0c6b2'},metal:{name:'Металл',color:'#59636d'},dark:{name:'Тёмный',color:'#30343a'}};
function paintRay(ev){
 if(!paintMode||editorMode!=='finish'||!raycaster||!renderer||!map)return false;
 var r=renderer.domElement.getBoundingClientRect();
 if(!r.width||!r.height)return false;
 mouse.x=((ev.clientX-r.left)/r.width)*2-1;mouse.y=-((ev.clientY-r.top)/r.height)*2+1;
 raycaster.setFromCamera(mouse,camera);
 var hits=raycaster.intersectObjects(root.children,true).filter(function(h){var k=h.object.userData&&h.object.userData.editorKind;return k==='surface'||k==='wall';});
 if(!hits.length)return false;
 var o=hits[0].object,e=MATERIAL_CATALOG[paintMaterial];if(!e)return false;
 var changed=false,key='';
 if(o.userData.editorKind==='surface'){
   key=o.name.indexOf('surface:')===0?o.name.slice(8):'';
   var ss=map.surfaces&&map.surfaces[key];
   if(!ss)return false;
   if(ss.material!==paintMaterial||ss.color!==e.color){changed=true;}
 }else{
   key=o.userData.wallKey||'';var w=map.walls&&map.walls[key];if(!w)return false;
   var s=side(w,paintSide);
   if(s.color!==e.color){changed=true;}
 }
 if(!changed)return false;
 if(!paintHistoryStarted){pushHistory();paintHistoryStarted=true;}
 if(o.userData.editorKind==='surface'){var s2=map.surfaces&&map.surfaces[key];if(s2){s2.material=paintMaterial;s2.color=e.color;}}else{var w2=map.walls&&map.walls[key];if(w2){var side2=side(w2,paintSide);side2.color=e.color;w2.material=paintMaterial;w2.color=e.color;}}
 paintedDuringStroke[key]=1;saveMap();build();updateInfo();return true;
}
function togglePaintMode(force){
 paintMode=force==null?!paintMode:!!force;painting=false;paintHistoryStarted=false;paintedDuringStroke={};
 var b=document.getElementById('r3dPaint');if(b)b.textContent=paintMode?'🖌️ Кисть: ВКЛ':'🖌️ Кисть: ВЫКЛ';
 var h=document.getElementById('r3dQuickHint');if(h)h.textContent=paintMode?'Кисть: ведите пальцем по полу или стене. Материал: '+(MATERIAL_CATALOG[paintMaterial]||{}).name+' • сторона стены: '+(paintSide==='front'?'внутри':'снаружи'):'Выберите режим — инструменты появятся в «Ещё».';
 updateInfo();
}
function setPaintMaterial(key){if(!MATERIAL_CATALOG[key])return;paintMaterial=key;paintMode=true;var h=document.getElementById('r3dQuickHint');if(h)h.textContent='Кисть ВКЛ • материал: '+MATERIAL_CATALOG[key].name+' • сторона стены: '+(paintSide==='front'?'внутри':'снаружи');var b=document.getElementById('r3dPaint');if(b)b.textContent='🖌️ Кисть: ВКЛ';}
function setPaintSide(which){paintSide=which==='back'?'back':'front';var h=document.getElementById('r3dQuickHint');if(h&&paintMode)h.textContent='Кисть ВКЛ • материал: '+MATERIAL_CATALOG[paintMaterial].name+' • сторона стены: '+(paintSide==='front'?'внутри':'снаружи');}
function applyMaterialToSelected(key){if(!selected){alert('Сначала выберите элемент.');return;}var e=MATERIAL_CATALOG[key];if(!e)return;pushHistory();var w=selectedWall();if(w){w.material=key;w.color=e.color;side(w,'front').color=e.color;side(w,'back').color=e.color;}else if(selected.userData&&selected.userData.mapObjectId){var o=(map.objects||[]).find(function(x){return String(x.id)===String(selected.userData.mapObjectId);});if(o){o.material=key;o.color=e.color;}}else if((selected.name||'').indexOf('surface:')===0){var k=selected.name.slice(8),ss=map.surfaces&&map.surfaces[k];if(ss){ss.material=key;ss.color=e.color;}}saveMap();build();updateInfo();}
function openMaterialCatalog(){var old=document.getElementById('map3dMaterials');if(old){old.remove();return;}var box=document.createElement('div');box.id='map3dMaterials';box.style.cssText='position:absolute;left:10px;top:58px;width:min(320px,86vw);background:#171c24;border:1px solid #555;border-radius:10px;padding:10px;z-index:6;box-shadow:0 8px 30px #000';box.innerHTML='<b>🎨 Материалы</b><button id="matClose" style="float:right">✕</button><div style="clear:both;color:#aaa;margin:8px 0">Выберите материал для выделенного элемента.</div>';Object.keys(MATERIAL_CATALOG).forEach(function(k){var e=MATERIAL_CATALOG[k],b=document.createElement('button');b.style.cssText='width:100%;margin:4px 0;padding:9px;text-align:left';b.innerHTML='<span style="display:inline-block;width:18px;height:18px;border-radius:4px;background:'+e.color+';vertical-align:middle;margin-right:8px"></span>'+e.name;b.onclick=function(){if(editorMode==='finish'){setPaintMaterial(k);}else{applyMaterialToSelected(k);}};box.appendChild(b);});box.querySelector('#matClose').onclick=function(){box.remove();};modal.appendChild(box);}
function openWallTools(){var old=document.getElementById('map3dWallTools');if(old){old.remove();return;}var box=document.createElement('div');box.id='map3dWallTools';box.style.cssText='position:absolute;left:10px;top:58px;width:min(330px,88vw);background:#171c24;border:1px solid #555;border-radius:10px;padding:10px;z-index:6;box-shadow:0 8px 30px #000';box.innerHTML='<b>🏗️ Стена</b><button id="wallClose" style="float:right">✕</button><div style="clear:both;margin:8px 0;color:#aaa">Сначала выберите стену.</div><button id="wallEdit" style="width:100%;margin:4px 0">📐 Длина / толщина / высота</button><button id="wallDoor" style="width:100%;margin:4px 0">🚪 Дверь</button><button id="wallWindow" style="width:100%;margin:4px 0">🪟 Окно</button><button id="wallMoveL" style="width:49%;margin:4px 0">◀ Проём</button><button id="wallMoveR" style="width:49%;margin:4px 0">Проём ▶</button><button id="wallPos" style="width:100%;margin:4px 0">↔ Позиция проёма</button><button id="wallClear" style="width:100%;margin:4px 0">▢ Убрать проём</button>';box.querySelector('#wallClose').onclick=function(){box.remove();};box.querySelector('#wallEdit').onclick=editSelectedWall;box.querySelector('#wallDoor').onclick=function(){editOpening('door');};box.querySelector('#wallWindow').onclick=function(){editOpening('window');};box.querySelector('#wallMoveL').onclick=function(){moveOpeningAlongWall(-.25);};box.querySelector('#wallMoveR').onclick=function(){moveOpeningAlongWall(.25);};box.querySelector('#wallPos').onclick=editOpeningPosition;box.querySelector('#wallClear').onclick=clearOpening;modal.appendChild(box);}

function esc(s){return String(s==null?'':s).replace(/[&<>"]/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'})[c];});}
function hex(v,f){return /^#[0-9a-f]{6}$/i.test(String(v||''))?String(v):f;}
function loadMap(){try{return JSON.parse(localStorage.getItem('dnd_vtt_3d_map')||'null');}catch(e){return null;}}
function saveMap(){if(!map)return;localStorage.setItem('dnd_vtt_3d_map',JSON.stringify(map));}
function setEditorMode(m){editorMode=m;selected=null;updateGizmo();build();updateInfo();var b=document.querySelectorAll('[data-r3d-mode]');for(var i=0;i<b.length;i++){b[i].style.fontWeight=b[i].getAttribute('data-r3d-mode')===m?'800':'400';b[i].style.outline=b[i].getAttribute('data-r3d-mode')===m?'2px solid #ffd54a':'none';}}
function editorAllows(kind){if(editorMode==='build')return kind==='wall';if(editorMode==='finish')return kind==='surface';if(editorMode==='levels')return false;return kind==='object'||kind==='token';}
function changeLevel(delta){if(!map)return;pushHistory();map.levels=map.levels||{};var max=Math.max(0,Number(map.levels.count||map.levels.max||10)-1),cur=Number(map.levels.current||0);map.levels.current=Math.max(0,Math.min(max,cur+delta));saveMap();build();updateInfo();}
function levelInfo(){return map&&map.levels?'Этаж '+(Number(map.levels.current||0)+1):'Этаж 1';}
function ensureMapCollections(){if(!map)return;map.assets=Array.isArray(map.assets)?map.assets:[];map.objects=Array.isArray(map.objects)?map.objects:[];}
function openAssetDB(){return new Promise(function(resolve,reject){if(assetDB){resolve(assetDB);return;}try{var r=indexedDB.open('dnd_vtt_3d_assets',1);r.onupgradeneeded=function(){var db=r.result;if(!db.objectStoreNames.contains('assets'))db.createObjectStore('assets',{keyPath:'id'});};r.onsuccess=function(){assetDB=r.result;resolve(assetDB);};r.onerror=function(){reject(r.error||new Error('IndexedDB error'));};}catch(e){reject(e);}});}
function putAsset(id,record){return openAssetDB().then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction('assets','readwrite');tx.objectStore('assets').put(Object.assign({id:id},record));tx.oncomplete=function(){assetCache[id]=record;resolve(record);};tx.onerror=function(){reject(tx.error||new Error('Asset save error'));};});});}
function getAsset(id){if(assetCache[id])return Promise.resolve(assetCache[id]);return openAssetDB().then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction('assets','readonly'),q=tx.objectStore('assets').get(id);q.onsuccess=function(){if(q.result)assetCache[id]=q.result;resolve(q.result||null);};q.onerror=function(){reject(q.error||new Error('Asset read error'));};});});}
function newAssetId(){return 'asset_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);}
function syncSelectedTransform(){if(!selected||!selected.userData||!selected.userData.mapObjectId||!map)return;var id=selected.userData.mapObjectId,o=(map.objects||[]).find(function(x){return String(x.id)===String(id);});if(!o)return;o.x=Number(selected.position.x)-.5;o.y=Number(selected.position.z)-.5;o.z=Number(selected.position.y)||0;o.rotation=Number(selected.rotation.y)*180/Math.PI;o.scaleX=Number(selected.scale.x)||1;o.scaleY=Number(selected.scale.z)||1;o.scaleZ=Number(selected.scale.y)||1;saveMap();}
function nudgeSelected(dx,dz){
 pushHistory();if(!selected||!selected.userData||!selected.userData.mapObjectId){alert('Выберите объект.');return;}selected.position.x+=dx;selected.position.z+=dz;syncSelectedTransform();updateInfo();}
function rotateSelected(deg){
 pushHistory();if(!selected||!selected.userData||!selected.userData.mapObjectId){alert('Выберите объект.');return;}selected.rotation.y+=deg*Math.PI/180;syncSelectedTransform();updateInfo();}
function scaleSelected(mult){
 pushHistory();if(!selected||!selected.userData||!selected.userData.mapObjectId){alert('Выберите объект.');return;}selected.scale.multiplyScalar(mult);syncSelectedTransform();updateInfo();}
function side(w,n){w[n]=w[n]||{texture:'none',color:null};return w[n];}
function material(color,rough){return new THREE.MeshStandardMaterial({color:hex(color,'#777777'),roughness:rough==null?.82:rough,metalness:0});}
function tex(url){if(!url||url==='none')return null;try{if(String(url).indexOf('asset:')===0){var id=String(url).slice(6),cached=assetCache[id];if(cached&&cached.url)url=cached.url;else{loadAssetTexture(id).then(function(){if(typeof build==='function')build();});return null;}}var l=new THREE.TextureLoader(),t=l.load(url);t.wrapS=t.wrapT=THREE.RepeatWrapping;return t;}catch(e){return null;}}
function matFromSide(s,base){var m=material((s&&s.color)||base);var t=tex(s&&s.texture);if(t)m.map=t;return m;}
function addBox(name,x,y,z,w,h,d,mats,rot){
 var g=new THREE.BoxGeometry(w,h,d);var ms=Array.isArray(mats)?mats:[mats||material('#777')];var o=new THREE.Mesh(g,ms);o.name=name;o.position.set(x+w*.5,y+d*.5,z+h*.5);if(rot)o.rotation.y=Number(rot)*Math.PI/180;root.add(o);return o;
}
function wallMesh(w){
 var h=Math.max(.5,Number(w.height)||2.5),t=Math.max(.03,Number(w.thickness)||.09),len=Math.max(.1,Number(w.length)||1),z=(Number(w.level)||0)*3;
 var front=side(w,'front'),back=side(w,'back'),base=w.color||'#777777',end=material(base),top=material(base),bottom=material(base),fm=matFromSide(front,base),bm=matFromSide(back,base),mats=w.dir==='n'?[end,end,top,bottom,fm,bm]:[fm,bm,top,bottom,end,end],x=Number(w.x)||0,y=Number(w.y)||0,op=w.opening;
 function part(name,px,py,pz,pw,ph,pd){var q=addBox(name,px,py,pz,pw,ph,pd,mats);q.userData.editorKind='wall';q.userData.wallKey=(Number(w.level)||0)+':'+x+':'+y;return q;}
 if(w.dir==='n'){
   if(!op)return part('wall:'+w.level+':'+x+':'+y,x,y-t/2,z,len,t,h);
   var ow=Math.min(len,Math.max(.1,Number(op.width)||.9)),oh=Math.min(h,Math.max(.1,Number(op.height)||2.1)),os=Math.max(0,Math.min(h-oh,Number(op.sill)||0)),c=(len-ow)/2;
   if(c>0)part('wall:'+w.level+':'+x+':'+y,x,y-t/2,z,c,t,h);
   if(os>0)part('wall:'+w.level+':'+x+':'+y,x+c,y-t/2,z+os,ow,t,os);
   if(c>0)part('wall:'+w.level+':'+x+':'+y,x+c+ow,y-t/2,z,len-c-ow,t,h);
   if(h-os-oh>0)part('wall:'+w.level+':'+x+':'+y,x+c,y-t/2,z+os+oh,ow,t,h-os-oh);
   return;
 }
 if(!op)return part('wall:'+w.level+':'+x+':'+y,x+1-t/2,y,z,t,h,len);
 var ow2=Math.min(len,Math.max(.1,Number(op.width)||.9)),oh2=Math.min(h,Math.max(.1,Number(op.height)||2.1)),os2=Math.max(0,Math.min(h-oh2,Number(op.sill)||0)),c2=(len-ow2)/2;
 if(c2>0)part('wall:'+w.level+':'+x+':'+y,x+1-t/2,y,z,t,h,c2);
 if(os2>0)part('wall:'+w.level+':'+x+':'+y,x+1-t/2,y+c2,z+os2,t,os2,ow2);
 if(c2>0)part('wall:'+w.level+':'+x+':'+y,x+1-t/2,y+c2+ow2,z,t,h,len-c2-ow2);
 if(h-os2-oh2>0)part('wall:'+w.level+':'+x+':'+y,x+1-t/2,y+c2,z+os2+oh2,t,h-os2-oh2,ow2);
}
function build(){
 if(!THREE||!map)return;
 while(root.children.length)root.remove(root.children[0]);
 var cols=Number(map.grid&&map.grid.cols)||20,rows=Number(map.grid&&map.grid.rows)||20,level=Number(map.levels&&map.levels.current)||0;
 var ground=new THREE.Mesh(new THREE.PlaneGeometry(cols,rows),material('#30352f',1));ground.rotation.x=-Math.PI/2;ground.position.set(cols/2,0,rows/2);ground.name='ground';ground.userData.editorKind='ground';root.add(ground);
 var surfaces=map.surfaces||{};Object.keys(surfaces).forEach(function(k){var p=k.split(':'),l=Number(p[0]),x=Number(p[1]),y=Number(p[2]);if(l!==level)return;var s=surfaces[k],m=material(s.color||'#30352f');var t=tex(s.texture);if(t){t.repeat.set(Number(s.repeatX)||1,Number(s.repeatY)||1);m.map=t;}var q=new THREE.Mesh(new THREE.BoxGeometry(1,.08,1),m);q.position.set(x+.5,Number((map.cells&&map.cells[k])||0)*.12+.04,y+.5);q.name='surface:'+k;q.userData.editorKind='surface';root.add(q);});
 Object.keys(map.walls||{}).forEach(function(k){var w=map.walls[k];if(Number(w.level)===level)wallMesh(w);});
 (map.objects||[]).forEach(function(o){if(Number(o.level||0)!==level)return;if(o.assetId){loadAssetObject(o);}else{var m=material(o.color||'#8b5a2b');var t=tex(o.texture);if(t)m.map=t;var q=addBox('object:'+o.id,Number(o.x)+.5,Number(o.y)+.5,Number(o.z)||0,(Number(o.size)||.8)*Number(o.scaleX||1),Math.max(.1,Number(o.size)||.8)*Number(o.scaleZ||1),(Number(o.size)||.8)*Number(o.scaleY||1),m,Number(o.rotation)||0);q.userData.mapObjectId=o.id;q.userData.editorKind='object';}});
 (map.tokens||[]).forEach(function(o){if(Number(o.level||0)!==level)return;var q=addBox('token:'+o.id,Number(o.x)+.35,Number(o.y)+.35,.12,.3,.3,.3,material(o.kind==='monster'?'#b33':'#39c'));q.userData.tokenId=o.id;q.userData.editorKind='token';});
}
function loadAssetObject(o){getAsset(o.assetId).then(function(rec){if(!rec||!rec.buffer)return;var loader=new GLTFLoader();loader.parse(rec.buffer,'',function(g){var q=g.scene;q.name='object:'+o.id;q.userData.mapObjectId=o.id;q.userData.editorKind='object';q.userData.assetId=o.assetId;q.position.set(Number(o.x||0)+.5,Number(o.z||0),Number(o.y||0)+.5);q.rotation.y=Number(o.rotation||0)*Math.PI/180;q.scale.set(Number(o.scaleX||1),Number(o.scaleZ||1),Number(o.scaleY||1));root.add(q);},function(e){console.warn('GLB parse failed',o.assetId,e);});}).catch(function(e){console.warn('Asset read failed',o.assetId,e);});}
function resize(){if(!renderer)return;var c=renderer.domElement,w=c.clientWidth,h=c.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();}
function frame(){if(!renderer)return;var c=renderer.domElement,dx=Math.cos(controls.yaw)*Math.cos(controls.pitch)*controls.distance,dy=Math.sin(controls.pitch)*controls.distance,dz=Math.sin(controls.yaw)*Math.cos(controls.pitch)*controls.distance;camera.position.set(controls.target.x+dx,controls.target.y+dy+8,controls.target.z+dz);camera.lookAt(controls.target.x,controls.target.y,controls.target.z);renderer.render(scene,camera);raf=requestAnimationFrame(frame);}
function pick(ev){if(!raycaster||!renderer)return;var r=renderer.domElement.getBoundingClientRect();mouse.x=((ev.clientX-r.left)/r.width)*2-1;mouse.y=-((ev.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);var hits=raycaster.intersectObjects(root.children,true).filter(function(h){return h.object.name!=='ground'&&!h.object.userData.gizmoAxis&&editorAllows(h.object.userData.editorKind||'object');});if(!hits.length){selected=null;updateGizmo();updateInfo();return;}var o=hits[0].object;while(o&&o.parent&&!(o.userData&&o.userData.mapObjectId)&&o.parent!==root)o=o.parent;selected=o;updateGizmo();updateInfo();}
function updateInfo(){var e=document.getElementById('map3dRealInfo');if(!e)return;e.textContent=(selected?'Выбрано: '+selected.name+(selected.userData&&selected.userData.assetId?' • GLB':''):'Ничего не выбрано')+' • '+levelInfo()+' • '+editorMode;}
function makeGizmo(){if(!THREE||gizmo)return;gizmo=new THREE.Group();gizmo.name='transform-gizmo';function axis(name,color,vec){var mat=new THREE.LineBasicMaterial({color:color,depthTest:false,transparent:true,opacity:.95});var geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),vec.clone().multiplyScalar(1.5)]);var line=new THREE.Line(geo,mat);line.userData.gizmoAxis=name;line.renderOrder=999;gizmo.add(line);var cone=new THREE.Mesh(new THREE.ConeGeometry(.12,.35,12),new THREE.MeshBasicMaterial({color:color,depthTest:false}));cone.userData.gizmoAxis=name;cone.position.copy(vec.clone().multiplyScalar(1.65));if(name==='X')cone.rotation.z=-Math.PI/2;if(name==='Z')cone.rotation.x=Math.PI/2;gizmo.add(cone);}axis('X',0xff5555,new THREE.Vector3(1,0,0));axis('Y',0x55ff66,new THREE.Vector3(0,1,0));axis('Z',0x5599ff,new THREE.Vector3(0,0,1));gizmo.visible=false;gizmo.renderOrder=999;scene.add(gizmo);}
function updateGizmo(){if(!gizmo)return;gizmo.visible=!!selected;if(selected){gizmo.position.copy(selected.getWorldPosition(new THREE.Vector3()));gizmo.scale.setScalar(Math.max(.6,controls.distance*.045));}}
function snapValue(v,step){if(!snapGrid||!step)return v;return Math.round(v/step)*step;}
function applySnap(){if(!selected)return;if(transformMode==='translate'){selected.position.x=snapValue(selected.position.x,snapSize);selected.position.y=snapValue(selected.position.y,snapSize);selected.position.z=snapValue(selected.position.z,snapSize);}else if(transformMode==='rotate'){var step=Math.PI/12;selected.rotation.y=Math.round(selected.rotation.y/step)*step;}else if(transformMode==='scale'){var step=.1;selected.scale.x=Math.max(.1,Math.round(selected.scale.x/step)*step);selected.scale.y=Math.max(.1,Math.round(selected.scale.y/step)*step);selected.scale.z=Math.max(.1,Math.round(selected.scale.z/step)*step);}}
function setGizmoHighlight(axis){if(!gizmo)return;gizmo.children.forEach(function(c){var m=c.material;if(!m)return;var active=c.userData&&c.userData.gizmoAxis===axis;m.opacity=active?1:.82;if(m.color){if(active)m.color.set(0xffff66);else if(c.userData.gizmoAxis==='X')m.color.set(0xff5555);else if(c.userData.gizmoAxis==='Y')m.color.set(0x55ff66);else if(c.userData.gizmoAxis==='Z')m.color.set(0x5599ff);}});}
function gizmoHit(ev){if(!gizmo||!gizmo.visible)return null;var r=renderer.domElement.getBoundingClientRect();mouse.x=((ev.clientX-r.left)/r.width)*2-1;mouse.y=-((ev.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);var h=raycaster.intersectObjects(gizmo.children,true);return h.length?h[0].object.userData.gizmoAxis:null;}
function gizmoMove(ev){if(!selected||!gizmoDragging)return;var dx=ev.clientX-gizmoStartX,dy=ev.clientY-gizmoStartY;var step=Math.max(.002,controls.distance*.0018);if(transformMode==='rotate'){selected.rotation.y=gizmoStartRot+(dx-dy)*.01;}else if(transformMode==='scale'){var q=Math.max(.15,1+(dx-dy)*.004);selected.scale.copy(gizmoStartScale).multiplyScalar(q);}else{if(gizmoAxis==='X')selected.position.x=gizmoStartPos.x+dx*step;else if(gizmoAxis==='Z')selected.position.z=gizmoStartPos.z-dy*step;else if(gizmoAxis==='Y')selected.position.y=gizmoStartPos.y-dy*step;}applySnap();syncSelectedTransform();updateGizmo();updateInfo();}
function setGizmoMode(m){transformMode=m;mode='transform';updateInfo();setGizmoHighlight(null);}
function colorSide(which){
 pushHistory();
 if(!selected||selected.name.indexOf('wall:')!==0){alert('Выберите стену в 3D-сцене.');return;}
 var parts=selected.name.split(':');var k=parts.slice(1).join(':');var w=map.walls&&map.walls[k];if(!w){alert('Стена не найдена в карте.');return;}
 var s=side(w,which),v=prompt(which==='front'?'Цвет внутренней стороны':'Цвет внешней стороны',s.color||'#777777');if(v===null)return;if(!/^#[0-9a-f]{6}$/i.test(v)){alert('Нужен цвет #RRGGBB');return;}s.color=v;saveMap();build();updateInfo();
}
function screenDistance(a,b){var dx=a.clientX-b.clientX,dy=a.clientY-b.clientY;return Math.sqrt(dx*dx+dy*dy);}
function screenMid(a,b){return {x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2};}
function beginTouchGesture(){var ids=Object.keys(touches);if(ids.length<2){touchGesture=null;return;}var a=touches[ids[0]],b=touches[ids[1]],m=screenMid(a,b);touchGesture={distance:screenDistance(a,b),midX:m.x,midY:m.y,targetX:controls.target.x,targetZ:controls.target.z,cameraDistance:controls.distance};}
function updateTouchGesture(){if(!touchGesture)return;var ids=Object.keys(touches);if(ids.length<2)return;var a=touches[ids[0]],b=touches[ids[1]],m=screenMid(a,b),d=screenDistance(a,b);var ratio=touchGesture.distance/Math.max(1,d);controls.distance=Math.max(3,Math.min(150,touchGesture.cameraDistance*ratio));var pan=.012*controls.distance;controls.target.x=touchGesture.targetX-(m.x-touchGesture.midX)*pan;controls.target.z=touchGesture.targetZ+(m.y-touchGesture.midY)*pan;}
function openAssetLibrary(){openAssetDB().then(function(db){var tx=db.transaction('assets','readonly'),q=tx.objectStore('assets').getAll();q.onsuccess=function(){var items=q.result||[],box=document.createElement('div');box.style.cssText='position:absolute;right:10px;top:58px;width:min(390px,92vw);max-height:76vh;overflow:auto;background:#171c24;border:1px solid #555;border-radius:14px;padding:12px;z-index:20;box-shadow:0 12px 40px #000';box.innerHTML='<b>📚 Библиотека ассетов</b><button id="libClose" style="float:right">✕</button><div style="clear:both;color:#aaa;margin:8px 0">GLB — модели. PNG/JPG/WebP — текстуры.</div><button id="libAddModel" style="width:49%;margin:4px 0">🧩 Добавить GLB</button><button id="libAddTex" style="width:49%;margin:4px 0">🖼️ Добавить текстуру</button>';var grid=document.createElement('div');grid.style.cssText='display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin-top:8px';items.forEach(function(rec){var b=document.createElement('button');b.style.cssText='display:flex;flex-direction:column;gap:5px;text-align:left;padding:7px;background:#222933;color:#fff;border:1px solid #394454;border-radius:9px';var title=document.createElement('span');title.textContent=(rec.meta&&rec.meta.kind==='texture'?'🖼️ ':'🧩 ')+(rec.meta&&rec.meta.name||rec.id);b.appendChild(title);if(rec.meta&&rec.meta.kind==='texture'&&rec.buffer){try{var u=URL.createObjectURL(new Blob([rec.buffer],{type:rec.meta.type||'image/png'})),im=document.createElement('img');im.src=u;im.style.cssText='width:100%;height:74px;object-fit:cover;border-radius:6px';b.insertBefore(im,title);setTimeout(function(){URL.revokeObjectURL(u);},60000);}catch(e){}}if(rec.meta&&rec.meta.kind==='texture'){var apply=document.createElement('div');apply.style.cssText='display:flex;gap:4px';var fi=document.createElement('button');fi.textContent='Внутри';fi.onclick=function(ev){ev.stopPropagation();applyTextureAsset(rec.id,'front');};var bo=document.createElement('button');bo.textContent='Снаружи';bo.onclick=function(ev){ev.stopPropagation();applyTextureAsset(rec.id,'back');};apply.appendChild(fi);apply.appendChild(bo);b.appendChild(apply);}else{b.draggable=true;b.addEventListener('dragstart',function(ev){if(ev.dataTransfer){ev.dataTransfer.effectAllowed='copy';ev.dataTransfer.setData('text/plain',rec.id);}});b.onclick=function(){placeLibraryAsset(rec.id,rec.meta&&rec.meta.name||'Asset');box.remove();};}grid.appendChild(b);});box.appendChild(grid);box.querySelector('#libClose').onclick=function(){box.remove();};box.querySelector('#libAddModel').onclick=function(){box.remove();addModel();};box.querySelector('#libAddTex').onclick=function(){box.remove();addTexture('front');};modal.appendChild(box);};});}
function placeLibraryAsset(id,name){pushHistory();ensureMapCollections();var oid='obj_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6);map.objects.push({id:oid,name:name,assetId:id,x:1,y:1,z:0,level:Number(map.levels&&map.levels.current)||0,scaleX:1,scaleY:1,scaleZ:1,rotation:0});saveMap();setEditorMode('objects');}
function addModel(){
 ensureMapCollections();
 var input=document.createElement('input');input.type='file';input.accept='.glb,.gltf,model/gltf-binary,model/gltf+json';input.onchange=function(){var f=input.files&&input.files[0];if(!f)return;if(f.name.toLowerCase().endsWith('.gltf')){alert('Для мобильного редактора лучше использовать .GLB: он сохраняет модель и ресурсы в одном файле.');return;}var rd=new FileReader();rd.onload=function(){var id=newAssetId(),buf=rd.result,meta={name:f.name,type:f.type||'model/gltf-binary',size:f.size,createdAt:new Date().toISOString(),license:'user-imported',source:'local'};putAsset(id,{meta:meta,buffer:buf}).then(function(){map.assets.push({id:id,name:f.name,type:meta.type,size:f.size,createdAt:meta.createdAt,license:meta.license,source:meta.source});var oid='obj_'+Date.now().toString(36);map.objects.push({id:oid,name:f.name,assetId:id,x:1,y:1,z:0,level:Number(map.levels&&map.levels.current)||0,scaleX:1,scaleY:1,scaleZ:1,rotation:0});saveMap();build();updateInfo();alert('GLB сохранён в локальную библиотеку и привязан к карте как assetId: '+id);}).catch(function(e){alert('Не удалось сохранить 3D-ассет: '+e.message);});};rd.readAsArrayBuffer(f);};input.click();
}
function applyTextureAsset(id,which){ensureMapCollections();if(!selected){alert('Сначала выберите элемент.');return;}var w=selectedWall(),rec=map.assets.find(function(a){return String(a.id)===String(id);});if(!rec)return;pushHistory();if(w&&(which==='front'||which==='back'))side(w,which).texture='asset:'+id;else if(w)w.texture='asset:'+id;else if(selected.userData&&selected.userData.mapObjectId){var o=(map.objects||[]).find(function(x){return String(x.id)===String(selected.userData.mapObjectId);});if(o)o.texture='asset:'+id;}else if((selected.name||'').indexOf('surface:')===0){var k=selected.name.slice(8),ss=map.surfaces&&map.surfaces[k];if(ss)ss.texture='asset:'+id;}saveMap();loadAssetTexture(id).then(function(){build();updateInfo();});}
function loadAssetTexture(id){return getAsset(id).then(function(rec){if(!rec||!rec.buffer)return null;if(assetCache[id]&&assetCache[id].url)return assetCache[id].url;var url=URL.createObjectURL(new Blob([rec.buffer],{type:(rec.meta&&rec.meta.type)||'image/png'}));assetCache[id]=Object.assign({},rec,{url:url});return url;});}
function addTexture(which){ensureMapCollections();var input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp,.png,.jpg,.jpeg,.webp';input.onchange=function(){var file=input.files&&input.files[0];if(!file)return;if(file.size>12*1024*1024){alert('Текстура слишком большая. Максимум 12 MB.');return;}var rd=new FileReader();rd.onload=function(){var id=newAssetId(),buf=rd.result,meta={name:file.name,type:file.type||'image/png',size:file.size,createdAt:new Date().toISOString(),license:'user-imported',source:'local',kind:'texture'};putAsset(id,{meta:meta,buffer:buf}).then(function(){map.assets.push({id:id,name:file.name,type:meta.type,size:file.size,createdAt:meta.createdAt,license:meta.license,source:meta.source,kind:'texture'});saveMap();return loadAssetTexture(id);}).then(function(){applyTextureAsset(id,which||'front');}).catch(function(e){alert('Не удалось сохранить текстуру: '+e.message);});};rd.readAsArrayBuffer(file);};input.click();}
function textureSide(which){addTexture(which);}
function open(){
 if(document.getElementById('map3dRealModal'))return;
 map=loadMap();if(!map){alert('Сначала создайте или сохраните 3D-карту в редакторе.');return;}
 var modal=document.createElement('div');modal.id='map3dRealModal';modal.style.cssText='position:fixed;inset:0;z-index:32000;background:#080b10;color:#fff;display:flex;flex-direction:column;';
 modal.innerHTML='<div style="min-height:50px;display:flex;align-items:center;gap:6px;padding:7px 9px;box-sizing:border-box;background:#151a20;border-bottom:1px solid #444;overflow:auto;white-space:nowrap"><b>🏗️ 3D Карты</b><span style="color:#888">'+VERSION+'</span><button data-r3d-mode="build">🏗️ Строить</button><button data-r3d-mode="objects">🪑 Объекты</button><button data-r3d-mode="finish">🎨 Отделка</button><button data-r3d-mode="levels">🏢 Этажи</button><span id="map3dRealInfo" style="flex:1;color:#aaa;min-width:150px">Загрузка…</span><button id="r3dLibrary">📚</button><button id="r3dMaterials">🎨</button><button id="r3dMore">☰ Ещё</button><button id="r3dSave">💾</button><button id="r3dClose">✕</button></div><div id="r3dMorePanel" style="display:none;max-height:30vh;overflow:auto;padding:7px;background:#11161c;border-bottom:1px solid #333"><div style="display:flex;flex-wrap:wrap;gap:5px"><button id="r3dLevelDown">− Этаж</button><button id="r3dLevelUp">+ Этаж</button><button id="r3dFill">🪣 Заливка</button><button id="r3dPaint">🖌️ Кисть: ВЫКЛ</button><button id="r3dPaintFront">🎨 Кисть: внутри</button><button id="r3dPaintBack">🎨 Кисть: снаружи</button><button id="r3dWallTools">🏗️ Стена</button><button id="r3dUndo">↶ Отмена</button><button id="r3dRedo">↷ Повтор</button><button id="r3dDup">⧉ Дубликат</button><button id="r3dFront">🎨 Внутри</button><button id="r3dBack">🎨 Снаружи</button><button id="r3dFrontTex">🖼️ Текстура внутри</button><button id="r3dBackTex">🖼️ Текстура снаружи</button><button id="r3dTexture">🖼️ Текстура</button><button id="r3dModel">🧩 GLB</button><button id="r3dMove">↔ Перемещение</button><button id="r3dRotate">⟳ Вращение</button><button id="r3dScale">⤢ Масштаб</button><button id="r3dSnap">🧲 Сетка: ВКЛ</button><button id="r3dLeft">←</button><button id="r3dRight">→</button><button id="r3dForward">↑</button><button id="r3dBackMove">↓</button><button id="r3dRotL">↶</button><button id="r3dRotR">↷</button><button id="r3dScaleDown">−</button><button id="r3dScaleUp">＋</button></div></div><div id="r3dQuickHint" style="padding:6px 9px;background:#1b2028;color:#b8c1cc;font-size:12px">Выберите режим — инструменты появятся в «Ещё».</div><div id="map3dRealCanvas" style="position:relative;flex:1;min-height:0;overflow:hidden"></div>';
 document.body.appendChild(modal);
 modal.querySelectorAll('[data-r3d-mode]').forEach(function(b){b.onclick=function(){setEditorMode(b.getAttribute('data-r3d-mode'));};});modal.querySelector('#r3dMore').onclick=function(){var p=modal.querySelector('#r3dMorePanel');p.style.display=p.style.display==='none'?'block':'none';};modal.querySelector('#r3dLevelDown').onclick=function(){changeLevel(-1);};modal.querySelector('#r3dLevelUp').onclick=function(){changeLevel(1);};modal.querySelector('#r3dLibrary').onclick=function(){openAssetLibrary();};modal.querySelector('#r3dMaterials').onclick=openMaterialCatalog;modal.querySelector('#r3dFill').onclick=function(){var k=prompt('Заливка текущего этажа. Материал: stone, wood, brick, plaster, metal, dark','stone');if(k&&MATERIAL_CATALOG[k])applySurfaceFill(k);};modal.querySelector('#r3dPaint').onclick=function(){togglePaintMode();};modal.querySelector('#r3dPaintFront').onclick=function(){setPaintSide('front');togglePaintMode(true);};modal.querySelector('#r3dPaintBack').onclick=function(){setPaintSide('back');togglePaintMode(true);};modal.querySelector('#r3dWallTools').onclick=openWallTools;modal.querySelector('#r3dUndo').onclick=undo;modal.querySelector('#r3dRedo').onclick=redo;modal.querySelector('#r3dDup').onclick=duplicateSelected;modal.querySelector('#r3dClose').onclick=function(){cancelAnimationFrame(raf);if(gizmo&&gizmo.parent)gizmo.parent.remove(gizmo);modal.remove();};
 modal.querySelector('#r3dMove').onclick=function(){setGizmoMode('translate');};modal.querySelector('#r3dRotate').onclick=function(){setGizmoMode('rotate');};modal.querySelector('#r3dScale').onclick=function(){setGizmoMode('scale');};modal.querySelector('#r3dSnap').onclick=function(){snapGrid=!snapGrid;this.textContent='🧲 Сетка: '+(snapGrid?'ВКЛ':'ВЫКЛ');if(snapGrid){applySnap();syncSelectedTransform();updateGizmo();}};
 modal.querySelector('#r3dFront').onclick=function(){colorSide('front');};modal.querySelector('#r3dBack').onclick=function(){colorSide('back');};modal.querySelector('#r3dModel').onclick=addModel;modal.querySelector('#r3dTexture').onclick=function(){addTexture('front');};modal.querySelector('#r3dFrontTex').onclick=function(){textureSide('front');};modal.querySelector('#r3dBackTex').onclick=function(){textureSide('back');};modal.querySelector('#r3dLeft').onclick=function(){nudgeSelected(-.25,0);};modal.querySelector('#r3dRight').onclick=function(){nudgeSelected(.25,0);};modal.querySelector('#r3dForward').onclick=function(){nudgeSelected(0,-.25);};modal.querySelector('#r3dBackMove').onclick=function(){nudgeSelected(0,.25);};modal.querySelector('#r3dRotL').onclick=function(){rotateSelected(-15);};modal.querySelector('#r3dRotR').onclick=function(){rotateSelected(15);};modal.querySelector('#r3dScaleDown').onclick=function(){scaleSelected(.9);};modal.querySelector('#r3dScaleUp').onclick=function(){scaleSelected(1.1);};modal.querySelector('#r3dSave').onclick=function(){saveMap();alert('Карта и assetRef сохранены.');};setEditorMode('objects');
 (async function(){
  try{
   var T=await import('./vendor/three.module.min.js');
   var L=await import('./vendor/GLTFLoader.js');
   THREE=T;GLTFLoader=L.GLTFLoader;
   var host=modal.querySelector('#map3dRealCanvas');renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(global.devicePixelRatio||1,1.6));renderer.setSize(host.clientWidth,host.clientHeight,false);renderer.domElement.style.touchAction='none';renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);
   scene=new THREE.Scene();scene.background=new THREE.Color('#10151c');root=new THREE.Group();scene.add(root);camera=new THREE.PerspectiveCamera(55,1,.05,1000);raycaster=new THREE.Raycaster();mouse=new THREE.Vector2();
   scene.add(new THREE.HemisphereLight(0xffffff,0x223344,2));var dl=new THREE.DirectionalLight(0xffffff,2);dl.position.set(10,20,5);scene.add(dl);makeGizmo();
   var dragging=false,lastX=0,lastY=0,button=0;
   renderer.domElement.addEventListener('pointerdown',function(ev){touches[ev.pointerId]={clientX:ev.clientX,clientY:ev.clientY};if(ev.pointerType==='touch'&&Object.keys(touches).length>=2){beginTouchGesture();dragging=false;return;}var gh=ev.button===0?gizmoHit(ev):null;if(gh&&selected&&editorMode==='objects'){gizmoAxis=gh;gizmoDragging=true;gizmoStartX=ev.clientX;gizmoStartY=ev.clientY;gizmoStartPos=selected.position.clone();gizmoStartRot=selected.rotation.y;gizmoStartScale=selected.scale.clone();renderer.domElement.setPointerCapture&&renderer.domElement.setPointerCapture(ev.pointerId);return;}dragging=true;lastX=ev.clientX;lastY=ev.clientY;button=ev.button;renderer.domElement.setPointerCapture&&renderer.domElement.setPointerCapture(ev.pointerId);if(button===0){if(paintMode&&editorMode==='finish'){painting=true;paintHistoryStarted=false;paintedDuringStroke={};paintRay(ev);}else pick(ev);}});
   renderer.domElement.addEventListener('dblclick',function(){if(selected&&selected.userData&&selected.userData.mapObjectId){var o=(map.objects||[]).find(function(x){return String(x.id)===String(selected.userData.mapObjectId);});if(o){var v=prompt('Точный X Y Z, например 2 3 0',Number(o.x||0)+' '+Number(o.y||0)+' '+Number(o.z||0));if(v){var p=v.trim().split(/\\s+/).map(Number);if(p.length===3&&p.every(function(n){return Number.isFinite(n)})){selected.position.set(p[0]+.5,p[2],p[1]+.5);syncSelectedTransform();updateInfo();}}}}});
   renderer.domElement.addEventListener('pointermove',function(ev){if(touches[ev.pointerId]){touches[ev.pointerId].clientX=ev.clientX;touches[ev.pointerId].clientY=ev.clientY;}if(Object.keys(touches).length>=2){updateTouchGesture();return;}if(gizmoDragging){gizmoMove(ev);return;}if(painting&&paintMode&&editorMode==='finish'){paintRay(ev);return;}if(!dragging)return;var dx=ev.clientX-lastX,dy=ev.clientY;lastX=ev.clientX;lastY=ev.clientY;if(button===0){controls.yaw-=dx*.008;controls.pitch=Math.max(.15,Math.min(1.45,controls.pitch-dy*.006));}else if(button===1||ev.shiftKey){var pan=.015*controls.distance;controls.target.x-=dx*pan;controls.target.z+=dy*pan;}});
   renderer.domElement.addEventListener('pointerup',function(ev){delete touches[ev.pointerId];painting=false;paintHistoryStarted=false;paintedDuringStroke={};dragging=false;gizmoDragging=false;gizmoAxis=null;setGizmoHighlight(null);if(Object.keys(touches).length<2)touchGesture=null;});renderer.domElement.addEventListener('pointercancel',function(ev){delete touches[ev.pointerId];painting=false;paintHistoryStarted=false;paintedDuringStroke={};dragging=false;gizmoDragging=false;gizmoAxis=null;touchGesture=null;setGizmoHighlight(null);});
   renderer.domElement.addEventListener('pointermove',function(ev){if(!gizmoDragging){var gh=gizmoHit(ev);setGizmoHighlight(gh);}});renderer.domElement.addEventListener('wheel',function(ev){ev.preventDefault();controls.distance=Math.max(3,Math.min(150,controls.distance*Math.exp(ev.deltaY*.001)));},{passive:false});
   renderer.domElement.addEventListener('dragover',function(ev){ev.preventDefault();});renderer.domElement.addEventListener('drop',function(ev){ev.preventDefault();var id=ev.dataTransfer&&ev.dataTransfer.getData('text/plain');if(!id)return;var rr=renderer.domElement.getBoundingClientRect();mouse.x=((ev.clientX-rr.left)/rr.width)*2-1;mouse.y=-((ev.clientY-rr.top)/rr.height)*2+1;raycaster.setFromCamera(mouse,camera);var g=root.children.find(function(x){return x.userData&&x.userData.editorKind==='ground';});var hit=g?raycaster.intersectObject(g,true)[0]:null;getAsset(id).then(function(rec){ensureMapCollections();pushHistory();map.objects.push({id:'obj_'+Date.now().toString(36),name:rec&&rec.meta&&rec.meta.name||'Asset',assetId:id,x:hit?hit.point.x-.5:1,y:hit?hit.point.z-.5:1,z:0,level:Number(map.levels&&map.levels.current)||0,scaleX:1,scaleY:1,scaleZ:1,rotation:0});saveMap();build();});});renderer.domElement.addEventListener('contextmenu',function(ev){ev.preventDefault();});
   window.addEventListener('resize',resize);resize();ensureMapCollections();updateGizmo();openAssetDB().catch(function(e){console.warn('IndexedDB unavailable; asset persistence disabled',e);});build();frame();
   modal.querySelector('#map3dRealInfo').textContent='WebGL готов • '+(map.name||'Новая карта');
  }catch(e){modal.querySelector('#map3dRealInfo').textContent='WebGL/Three.js не загрузился';alert('Не удалось запустить настоящий 3D: '+e.message+'\nСтарый редактор не удалён.');}
 })();
}
global.dndMap3DOpenReal=open;
global.dndMap3DOpen=open;
})(window);
