/**
 * vtt_debug_panel_v70.js
 * V70 Advanced Debug Panel 2.0 — central developer console for the mobile VTT.
 * It discovers every script linked by index.html, inspects exposed DND/dnd APIs,
 * reads localStorage, captures runtime errors, exposes engine snapshots and can
 * invoke an explicitly requested global API with JSON arguments. Source viewing
 * is read-only; this module never writes project files.
 * Public API: DNDAdvancedDebugV70, dndV70OpenDebug, dndV70CloseDebug,
 * dndV70RefreshDebug, dndV70Export, dndV70InspectSource, dndV70CallAPI,
 * dndV70ClearErrors, dndV70RunHealthCheck.
 */
(function(global){'use strict';
  var VERSION='70.0.0', MAX_ERRORS=100, state={open:false,tab:'overview',selectedFile:'',source:'',apiFilter:'',apiPath:'',apiArgs:'{}',result:'',loading:false};
  var errors=[], sourceCache={}, projectManifest=global.__DND_V70_MANIFEST__||null;
  var rootId='dndAdvancedDebugV70';
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return String(v);}}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function now(){return new Date().toISOString();}
  function safe(fn,fallback){try{return fn();}catch(e){return fallback;}}
  function scripts(){
    return Array.prototype.map.call(document.querySelectorAll('script[src]'),function(s){return s.getAttribute('src');}).filter(Boolean);
  }
  function category(path){var p=String(path).toLowerCase();if(p.indexOf('test_')>=0)return 'TEST';if(p.indexOf('vtt_')>=0)return 'VTT';if(p.indexOf('combat')>=0||p.indexOf('battle')>=0)return 'COMBAT';if(p.indexOf('network')>=0)return 'NETWORK';if(p.indexOf('bestiary')>=0||p.indexOf('monster')>=0)return 'BESTIARY';if(p.indexOf('craft')>=0||p.indexOf('alchemy')>=0||p.indexOf('gather')>=0)return 'CRAFT';if(p.indexOf('class')>=0||p.indexOf('feat')>=0||p.indexOf('spell')>=0)return 'CHARACTER';if(p.indexOf('debug')>=0||p.indexOf('setting')>=0)return 'DEBUG';return 'CORE';}
  function moduleRegistry(){if(projectManifest&&Array.isArray(projectManifest.files))return projectManifest.files.map(function(x,i){return {index:i,path:x.path,category:x.category||category(x.path),kind:x.kind||'binary',bytes:x.bytes||0,loaded:x.kind==='binary'?null:true};});return scripts().map(function(path,i){return {index:i,path:path,category:category(path),kind:'text',bytes:0,loaded:true};});}
  function apiRegistry(){
    var keys=safe(function(){return Object.getOwnPropertyNames(global);},[]),out=[];
    keys.forEach(function(k){if(!/^DND|^dnd/.test(k))return;var v=safe(function(){return global[k];},null),type=typeof v;var methods=[];if(v&&type==='object'){methods=safe(function(){return Object.keys(v).filter(function(x){return typeof v[x]==='function';}).slice(0,80);},[]);}out.push({path:k,type:type,callable:type==='function'||methods.length>0,methods:methods});});
    return out.sort(function(a,b){return a.path.localeCompare(b.path);});
  }
  function storage(){return safe(function(){var o={};for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i),v=localStorage.getItem(k);o[k]={length:v?v.length:0,preview:v&&v.length>600?v.slice(0,600)+'…':v};}return o;},{});}
  function engineSnapshot(){
    var candidates=['DNDGameplayV57','DNDEncounterMapV59','DNDTokenInteractionV60','DNDCombatLogV66','DNDMobileSessionV67','DNDEncounterCheckpointV68','DNDCombatEventBusV69','DNDCombat','DNDRules','DNDNetworkEngine','DNDNetwork','dndNetwork','DNDCampaign','DNDBattleBoard'];
    var o={};candidates.forEach(function(k){var v=safe(function(){return global[k];},null);o[k]={present:!!v,type:typeof v,keys:v&&typeof v==='object'?safe(function(){return Object.keys(v).slice(0,80);},[]):[]};if(v&&typeof v==='object'&&typeof v.snapshot==='function')o[k].snapshot=safe(function(){return clone(v.snapshot());},null);});return o;
  }
  function runtimeSnapshot(){return {url:safe(function(){return location.href;},''),readyState:document.readyState,userAgent:safe(function(){return navigator.userAgent;},''),viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},online:safe(function(){return navigator.onLine;},null),memory:safe(function(){return performance&&performance.memory?{used:performance.memory.usedJSHeapSize,total:performance.memory.totalJSHeapSize,limit:performance.memory.jsHeapSizeLimit}:null;},null),errors:errors.slice()};}
  function fullSnapshot(){return {version:VERSION,at:now(),modules:moduleRegistry(),apis:apiRegistry(),engines:engineSnapshot(),storage:storage(),runtime:runtimeSnapshot(),eventBus:safe(function(){return global.DNDCombatEventBusV69&&global.DNDCombatEventBusV69.snapshot?global.DNDCombatEventBusV69.snapshot():null;},null)};}
  function addError(type,message,stack,extra){errors.push({at:now(),type:type,message:String(message||''),stack:String(stack||''),extra:clone(extra||null)});if(errors.length>MAX_ERRORS)errors=errors.slice(-MAX_ERRORS);if(state.open)render();}
  function installErrorHooks(){if(global.__dndV70ErrorHooks)return;global.__dndV70ErrorHooks=true;global.addEventListener('error',function(e){addError('error',e.message||'Runtime error',e.error&&e.error.stack,{file:e.filename,line:e.lineno,col:e.colno});});global.addEventListener('unhandledrejection',function(e){var r=e.reason||{};addError('unhandledrejection',r.message||String(r),r.stack);});}
  function resolve(path){var parts=String(path||'').trim().split('.').filter(Boolean),obj=global;for(var i=0;i<parts.length;i++){if(obj==null)throw new Error('Path not found at '+parts.slice(0,i+1).join('.'));obj=obj[parts[i]];}return obj;}
  function callAPI(path,argsText){
    var args=[];try{args=argsText==null?[]:JSON.parse(argsText);if(!Array.isArray(args))args=[args];}catch(e){state.result='ARGUMENT ERROR: '+e.message;render();return null;}
    try{var fn=resolve(path);if(typeof fn!=='function')throw new Error(path+' is not a function');var result=fn.apply(null,args);state.result=JSON.stringify({ok:true,path:path,returned:clone(result)},null,2);addError('api-call','Called '+path,'',{args:args});return result;}catch(e){state.result=JSON.stringify({ok:false,path:path,error:e.message,stack:e.stack},null,2);addError('api-error',e.message,e.stack,{path:path,args:args});return null;}
  }
  function inspectFile(path){var m=moduleRegistry().filter(function(x){return x.path===path;})[0];if(m&&m.kind==='binary'){state.selectedFile=path;state.source='Binary asset — '+m.bytes+' bytes. Source preview is intentionally disabled for binary files.';state.loading=false;render();return;}state.selectedFile=path;state.loading=true;state.source='Loading '+path+'…';render();if(sourceCache[path]){state.source=sourceCache[path];state.loading=false;render();return;}fetch(path,{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.text();}).then(function(t){sourceCache[path]=t;state.source=t;state.loading=false;render();}).catch(function(e){state.source='SOURCE ERROR: '+e.message;state.loading=false;addError('source',e.message,e.stack,{path:path});render();});}
  function download(name,text){var blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
  function healthCheck(){var m=moduleRegistry(),a=apiRegistry(),checks={scripts:m.length,missingScripts:m.filter(function(x){return !x.path;}).length,apiCount:a.length,combat:!!global.DNDCombat,gameplay:!!global.DNDGameplayV57,rules:!!global.DNDRules,eventBus:!!global.DNDCombatEventBusV69,checkpoint:!!global.DNDEncounterCheckpointV68,session:!!global.DNDMobileSessionV67,debug:!!global.DNDAdvancedDebugV70};state.result=JSON.stringify({ok:checks.combat&&checks.gameplay&&checks.rules&&checks.eventBus&&checks.debug,checks:checks},null,2);render();return checks;}
  function tabs(){return ['overview','files','apis','storage','events','runtime'];}
  function render(){var root=document.getElementById(rootId);if(!root)return;root.style.display=state.open?'block':'none';if(!state.open)return;var tabButtons=tabs().map(function(t){return '<button class="btn-action" style="padding:7px;'+(state.tab===t?'border:2px solid #fff;':'')+'" onclick="dndV70Tab(\''+t+'\')">'+t.toUpperCase()+'</button>';}).join('');var body='';
    if(state.tab==='overview')body=renderOverview();
    if(state.tab==='files')body=renderModules();
    if(state.tab==='apis')body=renderApis();
    if(state.tab==='storage')body=renderStorage();
    if(state.tab==='events')body=renderEvents();
    if(state.tab==='runtime')body=renderRuntime();
    root.innerHTML='<div style="padding:10px;max-width:1100px;margin:auto;font-family:system-ui,sans-serif"><div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><div><b>🛠 Advanced Debug Panel 2.0 — V70</b><div style="font-size:.68em;color:#999">Central read-only inspector + controlled API console</div></div><button class="btn-action" onclick="dndV70CloseDebug()">✕</button></div><div style="display:flex;gap:5px;overflow:auto;margin:9px 0">'+tabButtons+'</div>'+body+'</div>';
  }
  function renderOverview(){var e=engineSnapshot(),r=runtimeSnapshot();return '<div style="display:grid;grid-template-columns:1fr 1fr;gap:6px"><button class="btn-action" onclick="dndV70RefreshDebug()">↻ Refresh</button><button class="btn-action" onclick="dndV70RunHealthCheck()">✓ Health check</button><button class="btn-action" onclick="dndV70Export()">⇩ Full diagnostic JSON</button><button class="btn-action" onclick="dndV70ClearErrors()">🧹 Clear errors</button><button class="btn-action" onclick="dndV701Open()">🧪 QA Sandbox 70.1</button><button class="btn-action" onclick="dndV702Open()">🧬 Character Lab 70.2</button><button class="btn-action" onclick="dndV705Open()">🔗 Scenario Editor 70.5</button></div><h3>Engines / modules</h3><pre style="white-space:pre-wrap;word-break:break-word;background:#171717;border:1px solid #444;border-radius:9px;padding:9px;font-size:.68em;max-height:42vh;overflow:auto">'+esc(JSON.stringify(e,null,2))+'</pre><h3>Last result</h3><pre style="white-space:pre-wrap;word-break:break-word;background:#171717;border:1px solid #444;border-radius:9px;padding:9px;font-size:.68em;max-height:25vh;overflow:auto">'+esc(state.result||'—')+'</pre><div style="color:#777;font-size:.7em">Runtime errors captured: '+r.errors.length+'</div>';}
  function renderModules(){var list=moduleRegistry(),q=state.apiFilter.toLowerCase();var rows=list.filter(function(x){return !q||x.path.toLowerCase().indexOf(q)>=0||x.category.toLowerCase().indexOf(q)>=0;}).map(function(x){return '<div style="border:1px solid #444;border-radius:8px;padding:7px;margin:5px 0"><b>'+esc(x.path)+'</b><span style="color:#888;font-size:.7em"> • '+x.category+'</span><button class="btn-action" style="float:right;padding:5px" onclick="dndV70InspectSource('+JSON.stringify(x.path).replace(/</g,'\\u003c')+')">'+(x.kind==='text'?'Source':'Info')+'</button></div>';}).join('');return '<input class="form-input" style="width:100%;box-sizing:border-box;margin-bottom:7px" placeholder="Filter files…" value="'+esc(state.apiFilter)+'" oninput="dndV70ModuleFilter(this.value)"><div style="font-size:.72em;color:#888">'+list.length+' project files from VTT_PROJECT_MANIFEST_V70.json</div>'+listWrap(rows)+(state.selectedFile?'<h3>'+esc(state.selectedFile)+'</h3><pre style="white-space:pre-wrap;word-break:break-word;background:#111;border:1px solid #444;border-radius:9px;padding:9px;font-size:.65em;max-height:55vh;overflow:auto">'+esc(state.source)+'</pre>':'');}
  function listWrap(x){return '<div style="max-height:42vh;overflow:auto">'+(x||'<div style="color:#888;padding:10px">Nothing found.</div>')+'</div>';}
  function renderApis(){var list=apiRegistry(),q=state.apiFilter.toLowerCase();var rows=list.filter(function(x){return !q||x.path.toLowerCase().indexOf(q)>=0;}).map(function(x){return '<details style="border:1px solid #444;border-radius:8px;margin:5px 0;padding:6px"><summary><b>'+esc(x.path)+'</b> <span style="color:#888">'+esc(x.type)+(x.callable?' • callable':'')+'</span></summary><div style="font-size:.72em;color:#aaa;margin:5px 0">'+esc(x.methods.join(', ')||'no object methods')+'</div><button class="btn-action" style="padding:5px" onclick="dndV70UseAPI('+JSON.stringify(x.path)+')">Use in console</button></details>';}).join('');return '<input class="form-input" style="width:100%;box-sizing:border-box;margin-bottom:7px" placeholder="Filter DND/dnd APIs…" value="'+esc(state.apiFilter)+'" oninput="dndV70ApiFilter(this.value)"><div style="font-size:.72em;color:#888">'+list.length+' exposed API roots</div>'+listWrap(rows)+'<h3>API Console</h3><input class="form-input" style="width:100%;box-sizing:border-box" placeholder="Global path, e.g. DNDCombatEventBusV69.snapshot" value="'+esc(state.apiPath)+'" oninput="dndV70SetAPIPath(this.value)"><textarea class="form-input" style="width:100%;min-height:75px;box-sizing:border-box;margin-top:6px" placeholder="JSON array of arguments, e.g. []" oninput="dndV70SetAPIArgs(this.value)">'+esc(state.apiArgs)+'</textarea><button class="btn-action" style="margin-top:6px" onclick="dndV70CallAPI()">▶ Call API</button><pre style="white-space:pre-wrap;word-break:break-word;background:#111;border:1px solid #444;border-radius:9px;padding:9px;font-size:.68em;max-height:28vh;overflow:auto">'+esc(state.result||'—')+'</pre>'}
  function renderStorage(){var o=storage(),rows=Object.keys(o).sort().map(function(k){return '<details style="border:1px solid #444;border-radius:8px;margin:4px 0;padding:5px"><summary><b>'+esc(k)+'</b> <span style="color:#888">'+o[k].length+' chars</span></summary><pre style="white-space:pre-wrap;word-break:break-word;font-size:.68em;color:#ccc">'+esc(o[k].preview)+'</pre></details>';}).join('');return '<div style="font-size:.72em;color:#888">localStorage keys: '+Object.keys(o).length+'</div>'+listWrap(rows);}
  function renderEvents(){var bus=safe(function(){return global.DNDCombatEventBusV69&&global.DNDCombatEventBusV69.events?global.DNDCombatEventBusV69.events():[];},[]);return '<div style="display:flex;gap:5px"><button class="btn-action" onclick="dndV69OpenReplay()">Open Replay</button><button class="btn-action" onclick="dndV70RefreshDebug()">Refresh</button></div><pre style="white-space:pre-wrap;word-break:break-word;background:#111;border:1px solid #444;border-radius:9px;padding:9px;font-size:.65em;max-height:65vh;overflow:auto">'+esc(JSON.stringify(bus.slice(-100),null,2))+'</pre>';}
  function renderRuntime(){var r=runtimeSnapshot();return '<div style="display:grid;grid-template-columns:1fr 1fr;gap:6px"><button class="btn-action" onclick="dndV70ClearErrors()">Clear captured errors</button><button class="btn-action" onclick="dndV70RunHealthCheck()">Health check</button></div><pre style="white-space:pre-wrap;word-break:break-word;background:#111;border:1px solid #444;border-radius:9px;padding:9px;font-size:.65em;max-height:70vh;overflow:auto">'+esc(JSON.stringify(r,null,2))+'</pre>';}
  function open(){state.open=true;state.tab='overview';render();}
  function close(){state.open=false;render();}
  function init(){installErrorHooks();if(!projectManifest&&global.fetch){fetch('./VTT_PROJECT_MANIFEST_V70.json',{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(function(m){projectManifest=m;if(state.open)render();}).catch(function(e){addError('manifest',e.message,e.stack);});}if(!document.getElementById(rootId)){var d=document.createElement('div');d.id=rootId;d.style.cssText='display:none;position:fixed;inset:0;z-index:30100;background:rgba(5,5,5,.99);color:#fff;overflow:auto;padding:calc(10px + env(safe-area-inset-top)) 8px calc(10px + env(safe-area-inset-bottom));box-sizing:border-box;touch-action:manipulation;';document.body.appendChild(d);} }
  global.dndV70OpenDebug=open;global.dndV70CloseDebug=close;global.dndV70RefreshDebug=render;global.dndV70InspectSource=inspectFile;global.dndV70CallAPI=function(){return callAPI(state.apiPath,state.apiArgs);};global.dndV70ClearErrors=function(){errors=[];render();};global.dndV70RunHealthCheck=healthCheck;global.dndV70Tab=function(t){state.tab=t;render();};global.dndV70ModuleFilter=function(q){state.apiFilter=q;state.tab='modules';render();};global.dndV70ApiFilter=function(q){state.apiFilter=q;state.tab='apis';render();};global.dndV70SetAPIPath=function(q){state.apiPath=q;};global.dndV70SetAPIArgs=function(q){state.apiArgs=q;};global.dndV70UseAPI=function(path){state.apiPath=path;state.apiArgs='[]';state.tab='apis';render();};global.dndV70Export=function(){download('dnd_vtt_v70_full_diagnostic.json',JSON.stringify(fullSnapshot(),null,2));return fullSnapshot();};global.DNDAdvancedDebugV70={VERSION:VERSION,open:open,close:close,modules:moduleRegistry,apis:apiRegistry,storage:storage,engines:engineSnapshot,runtime:runtimeSnapshot,snapshot:fullSnapshot,inspectSource:inspectFile,callAPI:callAPI,errors:function(){return clone(errors)},healthCheck:healthCheck};
  if(global.addEventListener)global.addEventListener('DOMContentLoaded',init);
})(window);
