/**
 * V70.2 Debug Character / Progression Lab.
 * Developer-only QA layer for force-changing race, class levels, multiclass,
 * background/profession, feats, inventory and spells. It mutates the active
 * character through the existing state object, journals via V70.1 when possible,
 * and reuses existing registries/progression APIs instead of creating gameplay engines.
 * Public API: DNDCharacterLabV702, dndV702Open/Close/Tab and mutation helpers.
 */
(function(global){'use strict';
  var VERSION='70.2.0', ROOT='dndDebugCharacterLabV702', state={open:false,tab:'progression',msg:''};
  function hero(){return global.currentCharacter||global.currentChar||null;}
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function backup(){try{if(global.DNDDebugSandboxV701&&global.DNDDebugSandboxV701.backup)global.DNDDebugSandboxV701.backup();}catch(e){}}
  function save(){try{if(typeof global.autoSaveCurrentCharacter==='function')global.autoSaveCurrentCharacter();}catch(e){}}
  function refresh(){['updateCharacterUI','renderCharacterSheet','renderConditions','renderSpellSlots','renderCombatAbilities','calculateMods'].forEach(function(n){try{if(typeof global[n]==='function')global[n]();}catch(e){}});}
  function record(label,before,after){try{if(global.DNDDebugSandboxV701&&global.DNDDebugSandboxV701.set){/* complex actions are already snapshotted */}}catch(e){};state.msg='✓ '+label;save();refresh();render();}
  function classNames(){var r=global.CLASSES_REFERENCE||{};return Object.keys(r);}
  function races(){try{return typeof global.getAllRaces==='function'?global.getAllRaces():[];}catch(e){return[];}}
  function backgrounds(){try{return typeof global.getAllBackgrounds==='function'?global.getAllBackgrounds():[];}catch(e){return[];}}
  function featNames(){var out=[],seen={};function add(x){if(!x)return;var n=x.nameRu||x.name||x.title||x.id;if(n&&!seen[n]){seen[n]=1;out.push(n);}};['feats_phb','feats_tcoe','feats_xgte','feats_settings','feats_ua_homebrew','Feats','FEATS'].forEach(function(k){var v=global[k];if(Array.isArray(v))v.forEach(add);else if(v&&typeof v==='object')Object.keys(v).forEach(function(q){var a=v[q];if(Array.isArray(a))a.forEach(add);else add(a);});});return out.sort();}
  function selected(id){var e=document.getElementById(id);return e?e.value:'';}
  function input(id){var e=document.getElementById(id);return e?e.value:'';}
  function setField(path,val){var h=hero();if(!h)throw new Error('Нет активного персонажа');if(global.DNDDebugSandboxV701&&global.DNDDebugSandboxV701.set)global.DNDDebugSandboxV701.set(path,val);else{var p=path.split('.'),o=h;for(var i=0;i<p.length-1;i++){if(o[p[i]]==null)o[p[i]]={};o=o[p[i]];}o[p[p.length-1]]=val;save();refresh();}}
  function setRace(){var h=hero(),r=selected('v702Race');if(!h||!r)return;backup();var before=h.race||h.raceName;h.race=r;h.raceName=r;var data=races().find(function(x){return x.name===r||x.id===r;});if(data&&data.speed)h.speed=data.speed;record('Race: '+before+' → '+r,before,r);}
  function classArray(h){if(!Array.isArray(h.classes))h.classes=[];return h.classes;}
  function totalLevel(h){return classArray(h).reduce(function(s,c){return s+(Number(c.level)||0);},0);}
  function applyClass(name,level){var h=hero();if(!h)throw new Error('Нет активного персонажа');if(typeof global.applyClassProgression==='function'){try{global.applyClassProgression(h,name,level);}catch(e){/* developer force mode should still persist the class state */}}}
  function setClassLevel(){var h=hero(),name=selected('v702Class'),level=Math.max(0,Math.min(20,Number(input('v702ClassLevel'))||1));if(!h||!name)return;backup();var arr=classArray(h),c=arr.find(function(x){return x&&x.name===name;});if(!c){c={name:name,level:0};arr.push(c);}var before=c.level;c.level=level;applyClass(name,level);h.level=totalLevel(h);h.class=h.className=name;record('Class level: '+name+' '+before+' → '+level,before,level);}
  function addClass(){var h=hero(),name=selected('v702Class'),level=Math.max(1,Math.min(20,Number(input('v702ClassLevel'))||1));if(!h||!name)return;backup();var arr=classArray(h);if(arr.some(function(c){return c.name===name;})){state.msg='✕ Класс уже есть — используй Set Level';render();return;}arr.push({name:name,level:level,subclass:''});applyClass(name,level);h.level=totalLevel(h);h.class=h.className=arr[0].name;record('Added class: '+name+' '+level,null,level);}
  function removeClass(){var h=hero(),name=selected('v702Class');if(!h||!name)return;backup();var arr=classArray(h),before=arr.length;h.classes=arr.filter(function(c){return c.name!==name;});h.level=totalLevel(h);if(h.classes[0])h.class=h.className=h.classes[0].name;record('Removed class: '+name,before,h.classes.length);}
  function setTotalLevel(){var h=hero(),level=Math.max(1,Math.min(20,Number(input('v702TotalLevel'))||1));if(!h)return;backup();var arr=classArray(h);if(!arr.length){arr.push({name:h.class||h.className||classNames()[0]||'Воин',level:level});}else{var remaining=Math.max(0,level-1);for(var i=1;i<arr.length;i++){var want=Math.max(0,Math.min(20,Number(arr[i].level)||0));var take=Math.min(want,remaining);arr[i].level=take;remaining-=take;}arr[0].level=remaining+1;}arr.forEach(function(c){applyClass(c.name,Number(c.level)||0);});h.level=totalLevel(h);record('Forced total level',null,h.level);}
  function setBackground(){var h=hero(),name=selected('v702Background');if(!h||!name)return;backup();var before=h.background||h.backgroundName;h.background=name;h.backgroundName=name;h.origin=name;record('Background: '+before+' → '+name,before,name);}
  function setProfession(){var h=hero(),name=input('v702Profession');if(!h||!name)return;backup();var before=h.profession;h.profession=name;h.professionName=name;h.career=name;record('Profession: '+before+' → '+name,before,name);}
  function addFeat(){var h=hero(),name=selected('v702Feat')||input('v702FeatCustom');if(!h||!name)return;backup();h.feats=Array.isArray(h.feats)?h.feats:[];h.features=Array.isArray(h.features)?h.features:[];if(h.feats.indexOf(name)<0)h.feats.push(name);if(h.features.indexOf(name)<0)h.features.push(name);record('Added feat: '+name,null,name);}
  function removeFeat(){var h=hero(),name=selected('v702Feat')||input('v702FeatCustom');if(!h||!name)return;backup();h.feats=Array.isArray(h.feats)?h.feats:[];h.features=Array.isArray(h.features)?h.features:[];h.feats=h.feats.filter(function(x){return x!==name;});h.features=h.features.filter(function(x){return x!==name;});try{if(typeof global.revertFeatStatBonus==='function')global.revertFeatStatBonus(h,name);}catch(e){}record('Removed feat: '+name,null,null);}
  function ensureInventory(h){if(!h)return null;if(Array.isArray(h.inventory)){var legacy=h.inventory;h.inventory={weapons:legacy,armor:[],consumables:[],materials:[],junk:[]};}if(!h.inventory||typeof h.inventory!=='object')h.inventory={weapons:[],armor:[],consumables:[],materials:[],junk:[]};['weapons','armor','consumables','materials','junk'].forEach(function(k){if(!Array.isArray(h.inventory[k]))h.inventory[k]=[];});return h.inventory;}
  function addInventory(){var h=hero(),name=input('v702Item'),qty=Math.max(1,Number(input('v702Qty'))||1);if(!h||!name)return;backup();var inv=ensureInventory(h);inv.junk.push({id:'dbg702_'+Date.now(),name:name,count:qty,source:'debug',equipped:false});record('Added item: '+name+' ×'+qty,null,null);}
  function removeInventory(){var h=hero(),i=Number(input('v702ItemIndex'));if(!h)return;backup();var inv=ensureInventory(h),all=[];['weapons','armor','consumables','materials','junk'].forEach(function(k){inv[k].forEach(function(item){all.push({category:k,item:item});});});var entry=all[i];if(!entry)return;var idx=inv[entry.category].indexOf(entry.item);if(idx>=0){var old=inv[entry.category][idx];inv[entry.category].splice(idx,1);record('Removed item #'+i,old,null);}}
  function addSpell(){var h=hero(),name=input('v702Spell'),level=Math.max(0,Math.min(9,Number(input('v702SpellLevel'))||0));if(!h||!name)return;backup();h.spellsData=Array.isArray(h.spellsData)?h.spellsData:[];h.spellsData.push({id:'dbg702_'+Date.now(),name:name,level:level,desc:'',prepared:true,source:'debug'});record('Added spell: '+name+' L'+level,null,null);}
  function removeSpell(){var h=hero(),i=Number(input('v702SpellIndex'));if(!h||!Array.isArray(h.spellsData)||!h.spellsData[i])return;backup();var old=h.spellsData[i];h.spellsData.splice(i,1);record('Removed spell #'+i,old,null);}
  function recalc(){var h=hero();if(!h)return;backup();(classArray(h)).forEach(function(c){if(c&&c.name)applyClass(c.name,Number(c.level)||0);});h.level=totalLevel(h);if(typeof global.calculateMods==='function')try{global.calculateMods();}catch(e){};record('Character recalculated',null,{level:h.level,classes:clone(h.classes)});}
  function render(){var root=document.getElementById(ROOT);if(!root||!root.style)return;root.style.display=state.open?'block':'none';if(!state.open)return;var h=hero();var nav=['progression','identity','feats','items','spells'];var tabs=nav.map(function(t){return '<button class="btn-action" style="padding:7px;'+(state.tab===t?'border:2px solid #fff;':'')+'" onclick="dndV702Tab(\''+t+'\')">'+t.toUpperCase()+'</button>';}).join(' ');var body=state.tab==='progression'?progression(h):state.tab==='identity'?identity(h):state.tab==='feats'?feats(h):state.tab==='items'?items(h):spells(h);root.innerHTML='<div style="padding:10px;max-width:1100px;margin:auto;font-family:system-ui,sans-serif"><div style="display:flex;justify-content:space-between;align-items:center"><div><b>🧬 Character / Progression Lab — V70.2</b><div style="font-size:.68em;color:#999">Force state • multiclass • feats • inventory • spells • recalculate</div></div><button class="btn-action" onclick="dndV702Close()">✕</button></div><div style="display:flex;gap:5px;overflow:auto;margin:9px 0">'+tabs+'</div>'+body+'<div style="margin-top:8px;padding:8px;background:#171717;border:1px solid #444;border-radius:8px;font-size:.75em;white-space:pre-wrap">'+esc(state.msg||'')+'</div></div>';}
  function selectHtml(id,opts){return '<select id="'+id+'" style="width:100%;box-sizing:border-box;padding:7px">'+opts.map(function(o){var val=typeof o==='string'?o:(o.name||o.nameRu||o.id||'');return '<option value="'+esc(val)+'">'+esc(val)+'</option>';}).join('')+'</select>';}
  function progression(h){var cn=classNames(),rs=races(),cls=Array.isArray(h&&h.classes)?h.classes:[];return '<h3>Класс / Multiclass</h3>'+selectHtml('v702Class',cn)+'<input id="v702ClassLevel" type="number" min="0" max="20" value="1" style="width:100%;box-sizing:border-box;margin:5px 0;padding:7px"><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:5px"><button class="btn-action" onclick="dndV702AddClass()">➕ Add Class</button><button class="btn-action" onclick="dndV702SetClassLevel()">⚙ Set Class Level</button><button class="btn-action" onclick="dndV702RemoveClass()">➖ Remove Class</button><button class="btn-action" onclick="dndV702Recalc()">♻ Recalculate</button></div><h3>Total Player Level</h3><input id="v702TotalLevel" type="number" min="1" max="20" value="'+esc(h&&h.level||1)+'" style="width:100%;box-sizing:border-box;padding:7px"><button class="btn-action" onclick="dndV702SetTotalLevel()" style="margin-top:5px">⚡ Force Total Level</button><pre style="background:#171717;padding:8px;max-height:25vh;overflow:auto">'+esc(JSON.stringify({level:h&&h.level,classes:cls},null,2))+'</pre>' ;}
  function identity(h){return '<h3>Race</h3>'+selectHtml('v702Race',races())+'<button class="btn-action" onclick="dndV702SetRace()" style="margin-top:5px">🧬 Force Race</button><h3>Background / Profession</h3>'+selectHtml('v702Background',backgrounds())+'<button class="btn-action" onclick="dndV702SetBackground()" style="margin-top:5px">📜 Force Background</button><input id="v702Profession" value="" placeholder="Профессия / Career" style="width:100%;box-sizing:border-box;margin-top:6px;padding:7px"><button class="btn-action" onclick="dndV702SetProfession()" style="margin-top:5px">🔨 Force Profession</button><pre style="background:#171717;padding:8px;max-height:25vh;overflow:auto">'+esc(JSON.stringify({race:h&&h.race||h&&h.raceName,background:h&&h.background||h&&h.backgroundName,profession:h&&h.profession},null,2))+'</pre>' ;}
  function feats(h){var names=featNames();return '<h3>Feats / Features</h3>'+selectHtml('v702Feat',names)+'<input id="v702FeatCustom" placeholder="или своё имя черты" style="width:100%;box-sizing:border-box;margin:5px 0;padding:7px"><div style="display:grid;grid-template-columns:1fr 1fr;gap:5px"><button class="btn-action" onclick="dndV702AddFeat()">⭐ Add Feat</button><button class="btn-action" onclick="dndV702RemoveFeat()">🗑 Remove Feat</button></div><pre style="background:#171717;padding:8px;max-height:35vh;overflow:auto">'+esc(JSON.stringify({feats:h&&h.feats||[],features:h&&h.features||[]},null,2))+'</pre>' ;}
  function items(h){var inv=ensureInventory(h)||{weapons:[],armor:[],consumables:[],materials:[],junk:[]};return '<h3>Inventory Sandbox</h3><input id="v702Item" placeholder="Название предмета" style="width:100%;box-sizing:border-box;padding:7px"><input id="v702Qty" type="number" min="1" value="1" style="width:100%;box-sizing:border-box;margin:5px 0;padding:7px"><button class="btn-action" onclick="dndV702AddItem()">🎒 Add Item</button><input id="v702ItemIndex" type="number" min="0" placeholder="index" style="width:100%;box-sizing:border-box;margin:5px 0;padding:7px"><button class="btn-action" onclick="dndV702RemoveItem()">🗑 Remove Item</button><pre style="background:#171717;padding:8px;max-height:40vh;overflow:auto">'+esc(JSON.stringify(inv,null,2))+'</pre>' ;}
  function spells(h){var sp=Array.isArray(h&&h.spellsData)?h.spellsData:[];return '<h3>Spell Sandbox</h3><input id="v702Spell" placeholder="Название заклинания" style="width:100%;box-sizing:border-box;padding:7px"><input id="v702SpellLevel" type="number" min="0" max="9" value="1" style="width:100%;box-sizing:border-box;margin:5px 0;padding:7px"><button class="btn-action" onclick="dndV702AddSpell()">✨ Add Spell</button><input id="v702SpellIndex" type="number" min="0" placeholder="index" style="width:100%;box-sizing:border-box;margin:5px 0;padding:7px"><button class="btn-action" onclick="dndV702RemoveSpell()">🗑 Remove Spell</button><pre style="background:#171717;padding:8px;max-height:40vh;overflow:auto">'+esc(JSON.stringify(sp,null,2))+'</pre>' ;}
  function open(){state.open=true;render();}function close(){state.open=false;render();}function tab(t){state.tab=t;render();}
  global.dndV702Open=open;global.dndV702Close=close;global.dndV702Tab=tab;global.dndV702SetRace=setRace;global.dndV702SetClassLevel=setClassLevel;global.dndV702AddClass=addClass;global.dndV702RemoveClass=removeClass;global.dndV702SetTotalLevel=setTotalLevel;global.dndV702SetBackground=setBackground;global.dndV702SetProfession=setProfession;global.dndV702AddFeat=addFeat;global.dndV702RemoveFeat=removeFeat;global.dndV702AddItem=addInventory;global.dndV702RemoveItem=removeInventory;global.dndV702AddSpell=addSpell;global.dndV702RemoveSpell=removeSpell;global.dndV702Recalc=recalc;
  global.DNDCharacterLabV702={version:VERSION,open:open,close:close,setRace:setRace,setClassLevel:setClassLevel,addClass:addClass,removeClass:removeClass,setTotalLevel:setTotalLevel,setBackground:setBackground,setProfession:setProfession,addFeat:addFeat,removeFeat:removeFeat,addInventory:addInventory,removeInventory:removeInventory,addSpell:addSpell,removeSpell:removeSpell,recalculate:recalc,snapshot:function(){var h=hero();return {version:VERSION,character:clone(h),classes:clone(h&&h.classes),feats:clone(h&&h.feats),inventory:clone(h&&h.inventory),spells:clone(h&&h.spellsData)};}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){var r=document.createElement('div');r.id=ROOT;r.style.cssText='display:none;position:fixed;inset:0;z-index:100001;background:rgba(8,8,8,.98);color:#fff;overflow:auto';document.body.appendChild(r);});
  else {var r=document.createElement('div');r.id=ROOT;r.style.cssText='display:none;position:fixed;inset:0;z-index:100001;background:rgba(8,8,8,.98);color:#fff;overflow:auto';document.body.appendChild(r);}
})(window);
