/**
 * vtt_combat_log_v66.js
 * Mobile-first combat history and developer diagnostics over the existing gameplay stack.
 * Stores normalized events, roll formulas, damage/healing/save/status feedback and links.
 * Public API: DNDCombatLogV66, dndV66OpenLog, dndV66OpenDebug, dndV66Record.
 */
(function(global){'use strict';
  var VERSION='66.0.0', KEY='dnd_vtt_combat_log_v66', events=[], state={log:false,debug:false,filter:'all'};
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function now(){return new Date().toISOString();}
  function load(){try{var x=JSON.parse(global.localStorage.getItem(KEY)||'[]');if(Array.isArray(x))events=x.slice(-300);}catch(e){events=[];}}
  function save(){try{global.localStorage.setItem(KEY,JSON.stringify(events.slice(-300)));}catch(e){}}
  function record(ev){var x=clone(ev||{});x.id=x.id||'evt66_'+Date.now()+'_'+Math.random().toString(36).slice(2,7);x.at=x.at||now();x.type=x.type||'EVENT';events.push(x);if(events.length>300)events.shift();save();render();return x;}
  function clear(){events=[];save();render();}
  function filtered(){return events.filter(function(e){return state.filter==='all'||String(e.type||'').toLowerCase().indexOf(state.filter)>=0;}).slice().reverse();}
  function label(e){var r=e.resolution||e.payload||e;return String(e.type||'EVENT').replace(/_/g,' ')+' • '+(r.name||r.actorName||r.sourceId||'system');}
  function detail(e){var r=e.resolution||e.payload||e,parts=[];if(r.formula)parts.push('Формула: '+r.formula);if(r.rolls)parts.push('Кости: ['+r.rolls.join(', ')+']');if(r.total!=null)parts.push('Итог: '+r.total);if(r.d20!=null)parts.push('d20: '+r.d20);if(r.bonus!=null)parts.push('Бонус: '+r.bonus);if(r.damage&&r.damage.total!=null)parts.push('Урон: '+r.damage.total);if(r.damageResult&&r.damageResult.hp!=null)parts.push('HP цели: '+r.damageResult.hp);if(r.healing!=null)parts.push('Лечение: '+r.healing);if(r.success!=null)parts.push(r.success?'УСПЕХ':'ПРОВАЛ');if(r.critical)parts.push('КРИТИЧЕСКИЙ УСПЕХ');if(r.fumble)parts.push('КРИТИЧЕСКИЙ ПРОМАХ');return parts.join(' • ');}
  function renderLog(){var root=document.getElementById('dndCombatLogV66');if(!root)return;root.style.display=state.log?'block':'none';var list=filtered().map(function(e){var r=e.resolution||e.payload||e,critical=r.critical?' • 💥 КРИТ':r.fumble?' • 💀 1':'',links=(r.sourceId?' • actor:'+r.sourceId:'')+(r.targetId?' • target:'+r.targetId:'');return '<details style="border:1px solid #444;border-radius:9px;margin:6px 0;padding:7px;background:#202020"><summary style="font-weight:700">'+label(e)+critical+links+'</summary><div style="font-size:.78em;color:#ccc;margin-top:6px">'+detail(e)+'</div><div style="font-size:.68em;color:#777;margin-top:5px">'+String(e.at||'')+' • '+String(e.id||'')+'</div></details>';}).join('')||'<div style="color:#888;padding:12px">История пуста.</div>';root.innerHTML='<div style="padding:11px;max-width:760px;margin:auto"><div style="display:flex;justify-content:space-between;align-items:center"><b>📜 Combat Log V66</b><button class="btn-action" onclick="dndV66CloseLog()">✕</button></div><div style="display:flex;gap:5px;overflow:auto;margin:8px 0"><button class="btn-action" onclick="dndV66Filter(\'all\')">Все</button><button class="btn-action" onclick="dndV66Filter(\'roll\')">🎲 Броски</button><button class="btn-action" onclick="dndV66Filter(\'damage\')">⚔️ Урон</button><button class="btn-action" onclick="dndV66Filter(\'save\')">🛡 Сейвы</button><button class="btn-action" onclick="dndV66Filter(\'status\')">✨ Статусы</button><button class="btn-action" onclick="dndV66Clear()">Очистить</button></div>'+list+'</div>';}
  function debugSnapshot(){var h=global.currentCharacter||global.currentChar||null,t=global.DNDGameplayV57&&global.DNDGameplayV57.snapshot?global.DNDGameplayV57.snapshot():null;return {build:VERSION,character:h?{id:h.id,name:h.name,level:h.level,hp:h.hpCurrent,maxHp:h.hpMax}:null,gameplay:t,engines:{rules:!!global.DNDRules,combat:!!global.DNDCombat,gameplay:!!global.DNDGameplayV57,network:!!global.dndNetwork,campaign:!!global.DNDCampaign,battleBoard:!!global.DNDBattleBoard},storage:{events:events.length,key:KEY},runtime:{url:global.location&&global.location.href,userAgent:global.navigator&&global.navigator.userAgent}};}
  function renderDebug(){var root=document.getElementById('dndAdvancedDebugV66');if(!root)return;root.style.display=state.debug?'block':'none';var s=debugSnapshot();root.innerHTML='<div style="padding:11px;max-width:760px;margin:auto"><div style="display:flex;justify-content:space-between"><b>🛠 Advanced Debug V66</b><button class="btn-action" onclick="dndV66CloseDebug()">✕</button></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin:9px 0"><button class="btn-action" onclick="dndV66RefreshDebug()">↻ Обновить</button><button class="btn-action" onclick="dndV66Export()">⇩ Экспорт state</button><button class="btn-action" onclick="dndV66SelfTest()">✓ Self-test</button><button class="btn-action" onclick="dndV66Clear()">🧹 Очистить log</button></div><pre style="white-space:pre-wrap;word-break:break-word;background:#171717;border:1px solid #444;border-radius:9px;padding:9px;font-size:.7em;overflow:auto">'+esc(JSON.stringify(s,null,2))+'</pre><div id="dndV66DebugResult" style="color:#aaa;font-size:.78em"></div></div>';}
  function esc(v){return String(v==null?'':v).replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c];});}
  function openLog(){state.log=true;state.debug=false;renderLog();renderDebug();}
  function closeLog(){state.log=false;renderLog();}
  function openDebug(){state.debug=true;state.log=false;renderLog();renderDebug();}
  function closeDebug(){state.debug=false;renderDebug();}
  function render(){renderLog();renderDebug();}
  function filter(x){state.filter=x;renderLog();}
  function exportState(){var blob=new Blob([JSON.stringify(debugSnapshot(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dnd_vtt_debug_v66.json';a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
  function selfTest(){var ok=!!global.DNDGameplayV57&&!!global.DNDCombat&&!!global.DNDRules;var el=document.getElementById('dndV66DebugResult');if(el)el.textContent=ok?'Self-test: базовые движки доступны.':'Self-test: отсутствует один или несколько базовых движков.';record({type:'DEBUG_SELF_TEST',payload:{ok:ok}});renderDebug();}
  function init(){load();if(!document.getElementById('dndCombatLogV66')){var a=document.createElement('div');a.id='dndCombatLogV66';a.style.cssText='display:none;position:fixed;inset:0;z-index:29900;background:rgba(12,12,12,.98);color:#fff;overflow:auto;padding:calc(10px + env(safe-area-inset-top)) 8px calc(10px + env(safe-area-inset-bottom));box-sizing:border-box;touch-action:manipulation;';document.body.appendChild(a);}if(!document.getElementById('dndAdvancedDebugV66')){var b=document.createElement('div');b.id='dndAdvancedDebugV66';b.style.cssText='display:none;position:fixed;inset:0;z-index:29910;background:rgba(8,8,8,.99);color:#fff;overflow:auto;padding:calc(10px + env(safe-area-inset-top)) 8px calc(10px + env(safe-area-inset-bottom));box-sizing:border-box;touch-action:manipulation;';document.body.appendChild(b);}}
  global.dndV66OpenLog=openLog;global.dndV66CloseLog=closeLog;global.dndV66OpenDebug=openDebug;global.dndV66CloseDebug=closeDebug;global.dndV66Filter=filter;global.dndV66Clear=clear;global.dndV66RefreshDebug=renderDebug;global.dndV66Export=exportState;global.dndV66SelfTest=selfTest;global.dndV66Record=record;global.DNDCombatLogV66={VERSION:VERSION,record:record,clear:clear,events:function(){return clone(events)},openLog:openLog,openDebug:openDebug,snapshot:debugSnapshot};
  if(global.addEventListener)global.addEventListener('DOMContentLoaded',init);
})(window);
