/*
 * vtt_gameplay_ux_v58.js — Battle UX + Campaign Gameplay orchestration layer.
 *
 * Не создаёт новый combat/battle/campaign engine. Связывает V57 Gameplay Core,
 * существующий DNDBattleBoard и DNDCampaign в единый пользовательский цикл.
 * Основные переменные: DNDV58GameplayState, activeEncounter, eventLog.
 * Public API: DNDGameplayV58.
 */
(function(global){
  'use strict';
  var VERSION='58.0.0', KEY='dnd_gameplay_v58';
  var state={activeEncounter:null,eventLog:[],sessionId:null};
  function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&typeof x==='object'){state=Object.assign(state,x);if(!Array.isArray(state.eventLog))state.eventLog=[];}}catch(e){}return state;}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}}
  function campaign(){return global.DNDCampaign&&global.DNDCampaign.getCurrent?global.DNDCampaign.getCurrent():null;}
  function persistCampaign(){if(global.DNDCampaign&&global.DNDCampaign.save)try{global.DNDCampaign.save();}catch(e){}}
  function ensureCampaignGameplay(){var c=campaign();if(!c)return null;if(!c.gameplay)c.gameplay={schemaVersion:58,activeEncounter:null,eventLog:[],sessionId:null};if(!Array.isArray(c.gameplay.eventLog))c.gameplay.eventLog=[];return c.gameplay;}
  function tracker(){return global.DNDGameplayV57&&global.DNDGameplayV57.ensureTracker?global.DNDGameplayV57.ensureTracker():null;}
  function boardSync(){if(global.DNDBattleBoard&&global.DNDBattleBoard.syncFromInitiative)try{global.DNDBattleBoard.syncFromInitiative();}catch(e){}}
  function log(type,message,data){var item={id:'gev_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),at:new Date().toISOString(),type:type,message:message,data:data||null};state.eventLog.push(item);if(state.eventLog.length>100)state.eventLog=state.eventLog.slice(-100);var cg=ensureCampaignGameplay();if(cg){cg.eventLog.push(item);if(cg.eventLog.length>200)cg.eventLog=cg.eventLog.slice(-200);}save();persistCampaign();return item;}
  function snapshot(){var t=tracker(),a=global.DNDGameplayV57&&global.DNDGameplayV57.active?global.DNDGameplayV57.active():null;return {version:VERSION,encounter:state.activeEncounter,round:t&&t.round||0,active:a?a.name:null,activeId:a?a.id:null,resources:a&&a.turnResources||null,eventCount:state.eventLog.length};}
  function startEncounter(name,opts){opts=opts||{};var t=tracker();if(!t||!Array.isArray(t.combatants)||!t.combatants.length)return {ok:false,error:'Нет участников инициативы.'};state.activeEncounter={id:'enc_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),name:name||'Новый бой',startedAt:new Date().toISOString(),status:'active',round:t.round||1};state.sessionId=opts.sessionId||state.sessionId||null;var cg=ensureCampaignGameplay();if(cg){cg.activeEncounter=state.activeEncounter;cg.sessionId=state.sessionId;}boardSync();log('encounter_start','Начат бой: '+state.activeEncounter.name,{encounterId:state.activeEncounter.id});render();return {ok:true,encounter:state.activeEncounter};}
  function endTurn(){if(!global.DNDGameplayV57||!global.DNDGameplayV57.endTurn)return {ok:false,error:'V57 Gameplay Core недоступен.'};var before=global.DNDGameplayV57.active&&global.DNDGameplayV57.active();var r=global.DNDGameplayV57.endTurn();if(!r.ok)return r;var after=global.DNDGameplayV57.active&&global.DNDGameplayV57.active();if(state.activeEncounter)state.activeEncounter.round=tracker().round;log('turn_end',(before?before.name:'Участник')+' завершил ход',{next:after?after.name:null,round:tracker().round});boardSync();render();return {ok:true,next:after};}
  function finishEncounter(result){if(!state.activeEncounter)return {ok:false,error:'Активного боя нет.'};state.activeEncounter.status='finished';state.activeEncounter.finishedAt=new Date().toISOString();state.activeEncounter.result=result||'completed';var cg=ensureCampaignGameplay();if(cg)cg.activeEncounter=state.activeEncounter;log('encounter_end','Бой завершён: '+state.activeEncounter.name,{result:state.activeEncounter.result});var done=state.activeEncounter;state.activeEncounter=null;if(cg)cg.activeEncounter=null;save();persistCampaign();render();return {ok:true,encounter:done};}
  function newSession(){var c=campaign();if(!c)return {ok:false,error:'Нет активной кампании.'};var s={id:'ses_'+Date.now(),title:'Игровая сессия '+((c.sessions||[]).length+1),date:new Date().toLocaleDateString(),notes:'',gameplayEvents:[]};if(!Array.isArray(c.sessions))c.sessions=[];c.sessions.push(s);state.sessionId=s.id;var cg=ensureCampaignGameplay();cg.sessionId=s.id;save();persistCampaign();log('session_start','Начата игровая сессия '+s.title,{sessionId:s.id});return {ok:true,session:s};}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
  function render(){var root=document.getElementById('dndGameplayV58');if(!root)return;var s=snapshot(),r=s.resources||{};root.innerHTML='<div style="display:flex;justify-content:space-between;gap:8px;align-items:center;flex-wrap:wrap"><div><strong>⚔️ V58 Battle UX</strong><div style="font-size:.78em;color:#999">'+(s.encounter?esc(s.encounter.name):'Бой не запущен')+' • Раунд '+s.round+'</div></div><div style="display:flex;gap:5px;flex-wrap:wrap">'+(s.encounter?'<button class="btn-action" onclick="dndV58EndTurn()">⏭️ Конец хода</button><button class="btn-action" onclick="dndV58Finish()">🏁 Завершить</button>':'<button class="btn-action" onclick="dndV58Start()">⚔️ Начать бой</button>')+'<button class="btn-action" onclick="dndV58OpenBoard()">🗺️ Поле</button></div></div><div style="margin-top:8px;background:#151515;padding:8px;border-radius:6px">Активный: <strong>'+esc(s.active||'—')+'</strong> · Action '+(r.action?'✓':'—')+' · Bonus '+(r.bonusAction?'✓':'—')+' · Reaction '+(r.reaction?'✓':'—')+' · Movement '+(r.movement||0)+'</div><details style="margin-top:8px"><summary>📜 Журнал ('+s.eventCount+')</summary><div style="max-height:180px;overflow:auto">'+state.eventLog.slice(-12).reverse().map(function(e){return '<div style="font-size:.78em;padding:4px 0;border-bottom:1px solid #333"><span style="color:#888">'+esc(new Date(e.at).toLocaleTimeString())+'</span> '+esc(e.message)+'</div>';}).join('')+'</div></details>';}
  function inject(){if(document.getElementById('dndGameplayV58'))return;var tab=document.getElementById('tabDice')||document.querySelector('.tab-page');if(!tab)return;var box=document.createElement('div');box.className='card';box.id='dndGameplayV58';box.style.marginTop='12px';tab.appendChild(box);render();}
  global.dndV58Start=function(){var t=tracker();if(!t||!t.combatants||!t.combatants.length){alert('Сначала сформируйте инициативу.');return;}var name=prompt('Название боя:','Новый бой');if(!name)return;startEncounter(name);};
  global.dndV58EndTurn=function(){var r=endTurn();if(!r.ok)alert(r.error||'Не удалось завершить ход.');};
  global.dndV58Finish=function(){if(!confirm('Завершить текущий бой?'))return;finishEncounter('completed');};
  global.dndV58OpenBoard=function(){if(global.dndBattleOpen)global.dndBattleOpen();else if(global.DNDBattleBoard&&global.DNDBattleBoard.open)global.DNDBattleBoard.open();};
  function restoreSnapshot(s){if(!s||typeof s!=='object')return {ok:false,error:'Нет snapshot V58.'};if(s.encounter===null){state.activeEncounter=null;}else if(s.encounter)state.activeEncounter=JSON.parse(JSON.stringify(s.encounter));if(s.sessionId!=null)state.sessionId=s.sessionId;save();var cg=ensureCampaignGameplay();if(cg){cg.activeEncounter=state.activeEncounter;cg.sessionId=state.sessionId;}persistCampaign();render();return {ok:true,encounter:state.activeEncounter};}
  global.DNDGameplayV58={VERSION:VERSION,load:load,save:save,snapshot:snapshot,restoreSnapshot:restoreSnapshot,startEncounter:startEncounter,endTurn:endTurn,finishEncounter:finishEncounter,newSession:newSession,log:log,render:render};
  document.addEventListener('DOMContentLoaded',function(){load();setTimeout(inject,450);});
})(window);
