/* V70.37.17 — standalone 3D editor controls */
(function(global){
'use strict';
var ID='r3dNewUi',tab='build',open=false;
var tabs=[['build','🧱','Стройка'],['furniture','🛋','Мебель'],['texture','🎨','Текстура'],['view','👁','Вид'],['add','➕','Добавить']];
var items={build:[['wall','Стена'],['room','Комната'],['floor','Пол'],['stairs','Лестница'],['ramp','Рампа'],['window','Окно']],furniture:[['exterior','Экстерьер'],['interior','Интерьер'],['walls','Стены'],['ceiling','Потолок'],['floor','Пол']],view:[['editor','Редактор'],['first','1 лицо'],['third','3 лицо']]};
function modal(){return document.getElementById('map3dRealModal')||document.getElementById('map3dModal');}
function css(){if(document.getElementById(ID+'Style'))return;var s=document.createElement('style');s.id=ID+'Style';s.textContent='#'+ID+'{position:absolute;inset:0;z-index:35000;pointer-events:none;font-family:system-ui,sans-serif}#'+ID+' .tabs{position:absolute;left:0;right:0;bottom:0;display:flex;justify-content:center;gap:6px;padding:7px 7px calc(7px + env(safe-area-inset-bottom));pointer-events:auto}#'+ID+' .tab{min-width:68px;height:48px;border:1px solid #59636b;border-radius:11px;background:rgba(18,22,26,.95);color:#eee;font-size:11px;font-weight:700;display:flex;flex-direction:column;align-items:center;justify-content:center}#'+ID+' .tab b{font-size:18px;line-height:18px}#'+ID+' .tab.active{background:#34404a;border-color:#c0c8ce}#'+ID+' .drawer{position:absolute;right:0;top:0;bottom:0;width:min(340px,82vw);background:rgba(16,20,24,.98);border-left:1px solid #66717f;box-shadow:-8px 0 28px #000b;transform:translateX(102%);transition:.18s;pointer-events:auto;overflow:auto;padding:12px 10px 80px;box-sizing:border-box}.drawer.open{transform:none}#'+ID+' h3{margin:3px 45px 12px 4px;color:#fff}#'+ID+' .close{position:absolute;right:10px;top:9px;width:38px;height:38px;border-radius:9px;border:1px solid #59636b;background:#252b30;color:#fff;font-size:20px}#'+ID+' .list{display:grid;gap:7px}#'+ID+' .action{min-height:46px;border:1px solid #4d565d;border-radius:10px;background:#20272c;color:#eee;text-align:left;padding:10px 12px;font-size:14px;font-weight:650}#'+ID+' .hint{color:#9da7ad;font-size:12px;line-height:1.4;padding:5px 4px 10px}';document.head.appendChild(s);}
function action(a){try{var api=global.R3DEditorAPI;if(api){if(a==='build:room')api.buildRoom();else if(a==='build:wall')api.buildWall();else if(a==='build:floor')api.buildFloor();else if(a==='build:window')api.selectWindow();else if(a==='texture:wall')api.openTexture('wall');else if(a==='texture:floor')api.openTexture('floor');else if(a==='texture:furniture')api.paint();else if(a==='view:editor')api.view('editor');else if(a==='view:first')api.view('first');else if(a==='view:third')api.view('third');}}catch(e){console.warn('[R3D UI]',e)}}
function draw(){var m=modal();if(!m)return;css();var r=document.getElementById(ID);if(!r){r=document.createElement('div');r.id=ID;m.appendChild(r);r.addEventListener('click',function(e){var t=e.target.closest('[data-tab]');if(t){tab=t.dataset.tab;open=true;draw();return}if(e.target.closest('[data-close]')){open=false;draw();return}var a=e.target.closest('[data-action]');if(a)action(a.dataset.action);});}
var h='<div class="tabs">';tabs.forEach(function(t){h+='<button class="tab '+(tab===t[0]?'active':'')+'" data-tab="'+t[0]+'"><b>'+t[1]+'</b><span>'+t[2]+'</span></button>'});h+='</div>';
var title={build:'Стройка',furniture:'Мебель',texture:'Текстура',view:'Вид',add:'Добавить'}[tab],body='';
if(tab==='add')body='<div class="hint">Раздел зарезервирован под NPC, предметы, токены и прочие элементы сцены.</div>';
else if(tab==='texture')body='<div class="hint">Выберите объект в сцене. Здесь будут каталог и параметры текстуры.</div><div class="list"><button class="action" data-action="texture:wall">🧱 Текстура стены</button><button class="action" data-action="texture:floor">🟫 Текстура пола</button><button class="action" data-action="texture:furniture">🛋 Текстура мебели</button></div>';
else if(tab==='build')body='<div class="hint">Инструменты строительства.</div><div class="list">'+items.build.map(function(x){return '<button class="action" data-action="build:'+x[0]+'">'+x[1]+'</button>'}).join('')+'</div>';
else if(tab==='furniture')body='<div class="hint">Пока заглушки. Каталоги выбора будут здесь.</div><div class="list">'+items.furniture.map(function(x){return '<button class="action" data-action="furniture:'+x[0]+'">'+x[1]+'</button>'}).join('')+'</div>';
else body='<div class="hint">Режим камеры.</div><div class="list">'+items.view.map(function(x){return '<button class="action" data-action="view:'+x[0]+'">'+x[1]+'</button>'}).join('')+'</div>';
r.innerHTML=h+'<div class="drawer '+(open?'open':'')+'"><button class="close" data-close>×</button><h3>'+title+'</h3>'+body+'</div>';
}
function wait(){if(modal())draw();else setTimeout(wait,250);}
global.R3DNewUI={open:function(t){tab=t||'build';open=true;draw()},close:function(){open=false;draw()},render:draw};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wait);else wait();
})(window);