/**
 * V70.3 Debug QA Laboratories
 * Combat / Dice / Network / Chaos testing layer. Developer-only; non-authoritative.
 */
(function(global){'use strict';
  var VERSION='70.3.0', ROOT='dndDebugLabV703';
  var state={open:false,tab:'combat',message:'',backup:null,forcedDice:null,network:{latency:0,loss:0,offline:false,duplicate:false,outOfOrder:false},journal:[]};
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function hero(){return global.currentCharacter||global.currentChar||null;}
  function save(){try{if(typeof global.autoSaveCurrentCharacter==='function')global.autoSaveCurrentCharacter();}catch(e){}}
  function refresh(){['updateCharacterUI','renderCharacterSheet','renderConditions','renderSpellSlots','renderCombatAbilities'].forEach(function(n){try{if(typeof global[n]==='function')global[n]();}catch(e){}});}
  function journal(action,before,after,meta){state.journal.push({at:new Date().toISOString(),action:action,before:clone(before),after:clone(after),meta:clone(meta||{})});state.journal=state.journal.slice(-100);}
  function msg(s){state.message=s;render();}
  function backup(){var h=hero();if(!h)return msg('✕ Нет активного персонажа');state.backup=clone(h);journal('snapshot',null,h,{scope:'character'});msg('✓ Snapshot создан');}
  function rollback(){var h=hero();if(!h||!state.backup)return msg('✕ Нет snapshot');Object.keys(h).forEach(function(k){delete h[k];});Object.keys(state.backup).forEach(function(k){h[k]=clone(state.backup[k]);});save();refresh();journal('rollback',null,h,{});msg('↩ Snapshot восстановлен');}
  function mutate(path,val){var h=hero();if(!h)return msg('✕ Нет активного персонажа');var parts=String(path).split('.').filter(Boolean),o=h;for(var i=0;i<parts.length-1;i++){if(!o[parts[i]]||typeof o[parts[i]]!=='object')o[parts[i]]={};o=o[parts[i]];}var key=parts[parts.length-1],before=clone(o[key]);o[key]=val;journal('set '+path,before,val,{path:path});save();refresh();msg('✓ '+path+' = '+JSON.stringify(val));}
  function dice(){var raw=document.getElementById('v703DiceValue');var mode=document.getElementById('v703DiceMode');var n=raw?Number(raw.value):20;var result=mode&&mode.value==='nat1'?1:mode&&mode.value==='nat20'?20:Math.max(1,Math.min(n||20,20));state.forcedDice={mode:mode?mode.value:'fixed',value:result};journal('force dice',null,state.forcedDice,{});msg('🎲 Следующий тестовый d20 = '+result);}
  function clearDice(){state.forcedDice=null;msg('✓ Forced dice cleared');}
  function combatAction(kind){var h=hero();if(!h)return msg('✕ Нет активного персонажа');var old=clone(h);if(kind==='damage'){h.hpCurrent=Math.max(0,(Number(h.hpCurrent)||0)-Number(document.getElementById('v703CombatAmount').value||10));}
    if(kind==='heal'){h.hpCurrent=Math.min(Number(h.hpMax)||999999,(Number(h.hpCurrent)||0)+Number(document.getElementById('v703CombatAmount').value||10));}
    if(kind==='down'){h.hpCurrent=0;h.deathSaves={successes:0,failures:0};}
    if(kind==='initiative'){h.initiative=Number(document.getElementById('v703CombatAmount').value||20);}
    if(kind==='resource'){h.combatResources=h.combatResources||{};h.combatResources.debug={current:0,max:999};}
    journal('combat:'+kind,old,h,{amount:document.getElementById('v703CombatAmount')&&document.getElementById('v703CombatAmount').value});save();refresh();
    if(global.DNDCombatEventBusV69&&typeof global.DNDCombatEventBusV69.record==='function')try{global.DNDCombatEventBusV69.record({type:'DEBUG_COMBAT_'+kind,source:'V70.3',characterId:h.id||null,amount:document.getElementById('v703CombatAmount')&&document.getElementById('v703CombatAmount').value});}catch(e){}
    msg('✓ Combat '+kind+' applied');
  }
  function networkApply(){var ids=['v703Latency','v703Loss'];state.network.latency=Math.max(0,Number(document.getElementById(ids[0]).value)||0);state.network.loss=Math.max(0,Math.min(100,Number(document.getElementById(ids[1]).value)||0));state.network.offline=document.getElementById('v703Offline').checked;state.network.duplicate=document.getElementById('v703Duplicate').checked;state.network.outOfOrder=document.getElementById('v703OutOfOrder').checked;journal('network profile',null,state.network,{});msg('🌐 Симуляция сети применена (только QA layer)');}
  function networkReset(){state.network={latency:0,loss:0,offline:false,duplicate:false,outOfOrder:false};msg('✓ Network simulation reset');}
  function chaos(){var h=hero();if(!h)return msg('✕ Нет активного персонажа');backup();h.hpCurrent=0;h.hpTemp=999;h.ac=1;h.speed='0';h.inspiration=true;h.activeConditions=Object.assign({},h.activeConditions||{},{Poisoned:true,Stunned:true,Prone:true,Blinded:true,Restrained:true});h.deathSaves={successes:0,failures:3};h.inventory=(h.inventory||[]).concat([{name:'QA Flood Item',quantity:9999,weight:9999}]);state.network={latency:1000,loss:25,offline:false,duplicate:true,outOfOrder:true};state.forcedDice={mode:'nat20',value:20};journal('CHAOS MODE',null,h,{network:state.network,forcedDice:state.forcedDice});save();refresh();if(global.DNDCombatEventBusV69&&typeof global.DNDCombatEventBusV69.record==='function')try{global.DNDCombatEventBusV69.record({type:'DEBUG_CHAOS_MODE',source:'V70.3',characterId:h.id||null});}catch(e){}msg('☢ Chaos Mode включён. Rollback вернёт состояние.');}
  function tabs(){return ['combat','dice','network','chaos','journal'];}
  function btn(t,fn,style){return '<button class="btn-action" style="padding:7px;'+(style||'')+'" onclick="'+fn+'">'+t+'</button>';}
  function render(){var r=document.getElementById(ROOT);if(!r||!r.style)return;r.style.display=state.open?'block':'none';if(!state.open)return;var h=hero(),th=tabs().map(function(t){return btn(t.toUpperCase(),"dndV703Tab('"+t+"')",state.tab===t?'border:2px solid #fff;':'');}).join(' '),body='';if(state.tab==='combat')body=renderCombat(h);if(state.tab==='dice')body=renderDice();if(state.tab==='network')body=renderNetwork();if(state.tab==='chaos')body=renderChaos();if(state.tab==='journal')body=renderJournal();r.innerHTML='<div style="padding:10px;max-width:1100px;margin:auto;font-family:system-ui,sans-serif"><div style="display:flex;justify-content:space-between;align-items:center"><div><b>🧪 QA Laboratories — V70.3</b><div style="font-size:.68em;color:#999">Combat • Dice • Network • Chaos • rollback</div></div>'+btn('✕','dndV703Close()')+'</div><div style="display:flex;gap:5px;overflow:auto;margin:9px 0">'+th+'</div>'+body+'<div style="margin-top:9px;padding:8px;background:#171717;border:1px solid #444;border-radius:8px;font-size:.75em;white-space:pre-wrap">'+esc(state.message||'')+'</div></div>';}
  function renderCombat(h){return '<h3>⚔️ Combat Laboratory</h3><p style="font-size:.78em;color:#aaa">Принудительные состояния проходят через QA layer и журналируются.</p><input id="v703CombatAmount" type="number" value="10" style="width:100%;box-sizing:border-box;padding:8px;background:#111;color:#fff;border:1px solid #555"> <div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:6px">'+btn('💥 Damage','dndV703Combat(\'damage\')')+btn('💚 Heal','dndV703Combat(\'heal\')')+btn('☠️ HP 0','dndV703Combat(\'down\')')+btn('🎯 Set Initiative','dndV703Combat(\'initiative\')')+btn('♾ Resource Stress','dndV703Combat(\'resource\')')+btn('📸 Snapshot','dndV703Backup()')+btn('↩ Rollback','dndV703Rollback()')+'</div><pre style="max-height:25vh;overflow:auto;background:#171717;padding:8px">'+esc(JSON.stringify(h?{name:h.name,hpCurrent:h.hpCurrent,hpMax:h.hpMax,ac:h.ac,initiative:h.initiative}:null,null,2))+'</pre>';}
  function renderDice(){return '<h3>🎲 Dice Laboratory</h3><select id="v703DiceMode" style="width:100%;padding:8px;background:#111;color:#fff"><option value="fixed">Fixed value</option><option value="nat1">Natural 1</option><option value="nat20">Natural 20</option></select><input id="v703DiceValue" type="number" min="1" max="20" value="20" style="width:100%;margin-top:6px;padding:8px;box-sizing:border-box;background:#111;color:#fff;border:1px solid #555">'+btn('🎲 Force next d20','dndV703ForceDice()','margin-top:6px')+' '+btn('✕ Clear','dndV703ClearDice()','margin-top:6px')+'<pre style="background:#171717;padding:8px">'+esc(JSON.stringify(state.forcedDice,null,2))+'</pre><p style="font-size:.75em;color:#aaa">V70.3 хранит override отдельно от production RNG; существующий dice engine остаётся авторитетным.</p>' ;}
  function renderNetwork(){return '<h3>🌐 Network Laboratory</h3><label>Latency (ms)</label><input id="v703Latency" type="number" value="'+state.network.latency+'" style="width:100%;padding:7px;box-sizing:border-box;background:#111;color:#fff"><label>Packet loss (%)</label><input id="v703Loss" type="number" value="'+state.network.loss+'" min="0" max="100" style="width:100%;padding:7px;box-sizing:border-box;background:#111;color:#fff"><label><input id="v703Offline" type="checkbox" '+(state.network.offline?'checked':'')+'> Offline</label><br><label><input id="v703Duplicate" type="checkbox" '+(state.network.duplicate?'checked':'')+'> Duplicate events</label><br><label><input id="v703OutOfOrder" type="checkbox" '+(state.network.outOfOrder?'checked':'')+'> Out-of-order events</label><div style="margin-top:7px">'+btn('🌐 Apply simulation','dndV703NetworkApply()')+' '+btn('↺ Reset','dndV703NetworkReset()')+'</div><pre style="background:#171717;padding:8px">'+esc(JSON.stringify(state.network,null,2))+'</pre><p style="font-size:.75em;color:#aaa">Это профиль симуляции для будущего transport adapter; он не меняет реальный WebRTC transport.</p>';}
  function renderChaos(){return '<h3>☢ Chaos Mode</h3><p style="font-size:.8em;color:#aaa">Сохраняет snapshot, затем создаёт намеренно экстремальное состояние персонажа и сети.</p>'+btn('☢ RUN CHAOS TEST','dndV703Chaos()','background:#8b0000;color:#fff;width:100%;padding:12px')+' '+btn('↩ ROLLBACK','dndV703Rollback()','width:100%;margin-top:6px')+'<ul style="font-size:.78em;color:#bbb"><li>HP 0 / temp HP 999</li><li>AC 1 / Speed 0</li><li>5 conditions + 3 failed death saves</li><li>inventory flood</li><li>1000ms latency + 25% packet loss</li><li>duplicate/out-of-order simulation</li><li>forced Natural 20</li></ul>' ;}
  function renderJournal(){return '<h3>📜 QA Journal</h3><pre style="max-height:55vh;overflow:auto;background:#171717;padding:8px;white-space:pre-wrap">'+esc(JSON.stringify(state.journal.slice().reverse(),null,2))+'</pre>' ;}
  function open(tab){state.open=true;state.tab=tab||'combat';render();}
  global.DNDDebugLabV703={version:VERSION,open:open,close:function(){state.open=false;render();},backup:backup,rollback:rollback,forceDice:dice,clearDice:clearDice,combat:combatAction,network:networkApply,resetNetwork:networkReset,chaos:chaos,getState:function(){return clone(state);}};
  global.dndV703Open=function(tab){open(tab);};global.dndV703Close=function(){state.open=false;render();};global.dndV703Tab=function(t){state.tab=t;render();};global.dndV703Backup=backup;global.dndV703Rollback=rollback;global.dndV703ForceDice=dice;global.dndV703ClearDice=clearDice;global.dndV703Combat=combatAction;global.dndV703NetworkApply=networkApply;global.dndV703NetworkReset=networkReset;global.dndV703Chaos=chaos;
  function mount(){if(document.getElementById(ROOT))return;var d=document.createElement('div');d.id=ROOT;d.style.cssText='display:none;position:fixed;inset:0;background:rgba(0,0,0,.94);color:#fff;z-index:60000;overflow:auto;box-sizing:border-box;';document.body.appendChild(d);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})(window);
