/**
 * vtt_character_actions_v64.js
 * Touch-first action/spell/resource sheet for the existing character and combat APIs.
 * It does not resolve combat itself; attacks are delegated to DNDGameplayV57.
 * Public API: DNDCharacterActionsV64, dndV64Open, dndV64Close, dndV64Use.
 */
(function(global){'use strict';
  var VERSION='64.0.0',state={open:false};
  function hero(){return global.currentCharacter||global.currentChar||null;}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function list(h){var a=[];(h&&h.actions||[]).forEach(function(x){if(x&&x.name)a.push({name:x.name,type:'action',resource:'action',damage:x.damage||x.damageDice||null,description:x.description||''});});(h&&h.bonusActions||[]).forEach(function(x){if(x&&x.name)a.push({name:x.name,type:'bonus',resource:'bonusAction',description:x.description||''});});(h&&h.combatAbilities||[]).forEach(function(x){if(x&&x.name)a.push({name:x.name,type:'ability',resource:x.resource||'action',description:x.description||''});});return a;}
  function spells(h){var s=[];if(Array.isArray(h&&h.spellsData))s=h.spellsData;else if(Array.isArray(h&&h.spells))s=h.spells;return s.filter(Boolean).slice(0,30);}
  function use(i){var h=hero(),a=list(h)[i];if(!a)return {ok:false,error:'Действие не найдено.'};if(a.resource==='action'||a.resource==='bonusAction'||a.resource==='reaction'){if(global.DNDGameplayV57&&typeof global.DNDGameplayV57.spendAction==='function')return global.DNDGameplayV57.spendAction(a.resource);}return {ok:true,action:a};}
  function render(){var root=document.getElementById('dndCharacterActionsV64');if(!root)return;root.style.display=state.open?'block':'none';var h=hero();if(!h){root.innerHTML='<div style="padding:16px">Персонаж не выбран.</div>';return;}var aa=list(h),ss=spells(h);var ah=aa.length?aa.map(function(a,i){return '<button class="btn-action" onclick="dndV64Use('+i+')" style="text-align:left;padding:10px">⚔️ '+esc(a.name)+'<span style="display:block;font-size:.72em;color:#aaa">'+esc(a.type)+' • '+esc(a.resource)+(a.damage?' • '+esc(a.damage):'')+'</span></button>';}).join(''):'<div style="color:#888">Действия персонажа не зарегистрированы.</div>';var sh=ss.length?ss.map(function(s){return '<div style="padding:9px;border:1px solid #444;border-radius:9px"><b>'+esc(s.name||s.title||'Заклинание')+'</b><div style="font-size:.72em;color:#aaa">Уровень '+esc(s.level||0)+'</div></div>';}).join(''):'<div style="color:#888">Заклинания не зарегистрированы.</div>';root.innerHTML='<div style="padding:11px;max-width:720px;margin:auto"><div style="display:flex;justify-content:space-between"><b>⚔️ Действия и заклинания</b><button class="btn-action" onclick="dndV64Close()">✕</button></div><h4>Действия</h4><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px">'+ah+'</div><h4>Заклинания</h4><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px">'+sh+'</div></div>';}
  function open(){state.open=true;render();} function close(){state.open=false;render();}
  function init(){if(document.getElementById('dndCharacterActionsV64'))return;var e=document.createElement('div');e.id='dndCharacterActionsV64';e.style.cssText='display:none;position:fixed;inset:0;z-index:29810;background:rgba(12,12,12,.98);color:#fff;overflow:auto;padding:calc(10px + env(safe-area-inset-top)) 8px calc(10px + env(safe-area-inset-bottom));box-sizing:border-box;touch-action:manipulation;';document.body.appendChild(e);}
  global.dndV64Open=open;global.dndV64Close=close;global.dndV64Use=function(i){var r=use(i);if(!r.ok&&global.alert)global.alert(r.error);render();return r;};global.DNDCharacterActionsV64={VERSION:VERSION,open:open,close:close,use:use,actions:function(){return list(hero())}};if(global.addEventListener)global.addEventListener('DOMContentLoaded',init);
})(window);
