/**
 * vtt_dice_resolution_v65.js
 * Structured mobile dice resolution layer for checks, attacks, saves and damage.
 * It uses DNDCombat/rulesEngine where available and emits normalized resolution records.
 * Public API: DNDDiceResolutionV65, dndV65Open, dndV65Resolve.
 */
(function(global){'use strict';
  var VERSION='65.0.0',state={open:false},history=[];
  function n(v,d){var x=Number(v);return isFinite(x)?x:(d||0);}
  function die(s){return Math.floor(Math.random()*Math.max(1,n(s,20)))+1;}
  function parse(expr){var m=String(expr||'1d20').replace(/\s+/g,'').match(/^(\d*)d(\d+)([+-]\d+)?$/i);return m?{count:Math.max(1,n(m[1],1)),sides:n(m[2],20),mod:n(m[3],0)}:null;}
  function roll(expr,opts){opts=opts||{};var p=parse(expr)||{count:1,sides:20,mod:0},a=[],total=p.mod;for(var i=0;i<p.count;i++)a.push(die(p.sides));a.forEach(function(x){total+=x;});return {expression:expr,rolls:a,modifier:p.mod,total:total,critical:opts.d20&&a[0]===20,fumble:opts.d20&&a[0]===1};}
  function resolve(kind,opts){opts=opts||{};var r;if(kind==='attack'&&global.DNDCombat&&global.DNDCombat.attack&&opts.attacker&&opts.target){r=global.DNDCombat.attack(opts.attacker,opts.target,opts);r.kind='attack';}else if(kind==='save'&&global.DNDCombat&&global.DNDCombat.savingThrow){r=global.DNDCombat.savingThrow(opts.target||opts.actor,opts.stat||'dex',opts.dc||10);r.kind='save';}else{r=roll(opts.expression||'1d20',opts);r.kind=kind;r.success=opts.dc!=null?r.total>=n(opts.dc):undefined;}r.timestamp=new Date().toISOString();r.id='res65_'+Date.now()+'_'+Math.random().toString(36).slice(2,7);r.formula=opts.expression||opts.damage||null;r.sourceId=opts.attacker&&opts.attacker.id||opts.actor&&opts.actor.id||null;r.targetId=opts.target&&opts.target.id||null;history.unshift(r);if(history.length>100)history.length=100;return r;}
  function render(){var root=document.getElementById('dndDiceResolutionV65');if(!root)return;root.style.display=state.open?'block':'none';root.innerHTML='<div style="padding:11px;max-width:720px;margin:auto"><div style="display:flex;justify-content:space-between"><b>🎲 Броски и разрешение</b><button class="btn-action" onclick="dndV65Close()">✕</button></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:9px"><button class="btn-action" onclick="dndV65Resolve(\"check\",{expression:\"1d20\",d20:true})">d20 Проверка</button><button class="btn-action" onclick="dndV65Resolve(\"damage\",{expression:\"1d6\"})">1d6 Урон</button></div><div style="margin-top:10px">'+history.map(function(x){return '<div style="padding:8px;border:1px solid #444;border-radius:9px;margin-bottom:6px"><b>'+String(x.kind||'roll').toUpperCase()+'</b> — '+(x.total!=null?x.total:(x.d20!=null?x.d20:'—'))+(x.critical?' • КРИТ':'')+(x.fumble?' • ПРОМАХ':'')+'<div style="font-size:.72em;color:#aaa">'+String(x.formula||'')+' • '+String(x.timestamp||'')+'</div></div>';}).join('')+'</div></div>';}
  function open(){state.open=true;render();}function close(){state.open=false;render();}
  function init(){if(document.getElementById('dndDiceResolutionV65'))return;var e=document.createElement('div');e.id='dndDiceResolutionV65';e.style.cssText='display:none;position:fixed;inset:0;z-index:29820;background:rgba(12,12,12,.98);color:#fff;overflow:auto;padding:calc(10px + env(safe-area-inset-top)) 8px calc(10px + env(safe-area-inset-bottom));box-sizing:border-box;touch-action:manipulation;';document.body.appendChild(e);}
  global.dndV65Open=open;global.dndV65Close=close;global.dndV65Resolve=function(k,o){var r=resolve(k,o);render();if(global.DNDCombatLogV66&&global.DNDCombatLogV66.record)global.DNDCombatLogV66.record({type:'ROLL_RESOLVED',resolution:r});return r;};global.DNDDiceResolutionV65={VERSION:VERSION,resolve:resolve,history:function(){return history.slice()},roll:roll};if(global.addEventListener)global.addEventListener('DOMContentLoaded',init);
})(window);
