/**
 * V70.1 Debug / QA Sandbox
 * Controlled developer-only mutation layer over the existing VTT state.
 * It intentionally mutates currentCharacter/currentChar for testing, but never
 * becomes authoritative for gameplay. Every mutation is journaled and can be rolled back.
 */
(function(global){'use strict';
  var VERSION='70.1.0', KEY='dnd_v701_debug_journal', MAX=100;
  var state={open:false, tab:'quick', path:'', value:'', message:'', backup:null};
  var journal=[];
  var rootId='dndDebugSandboxV701';
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function hero(){return global.currentCharacter||global.currentChar||null;}
  function save(){try{if(typeof global.autoSaveCurrentCharacter==='function')global.autoSaveCurrentCharacter();}catch(e){}}
  function refresh(){try{if(typeof global.updateCharacterUI==='function')global.updateCharacterUI();}catch(e){} try{if(typeof global.renderCharacterSheet==='function')global.renderCharacterSheet();}catch(e){} try{if(typeof global.renderConditions==='function')global.renderConditions();}catch(e){} try{if(typeof global.renderSpellSlots==='function')global.renderSpellSlots();}catch(e){} try{if(typeof global.renderCombatAbilities==='function')global.renderCombatAbilities();}catch(e){}}
  function journalLoad(){try{journal=JSON.parse(localStorage.getItem(KEY)||'[]');if(!Array.isArray(journal))journal=[];}catch(e){journal=[];}}
  function journalSave(){try{localStorage.setItem(KEY,JSON.stringify(journal.slice(-MAX)));}catch(e){}}
  function log(action,before,after,meta){journal.push({id:'dbg701_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),at:new Date().toISOString(),action:action,before:clone(before),after:clone(after),meta:clone(meta||{})});if(journal.length>MAX)journal=journal.slice(-MAX);journalSave();}
  function setPath(obj,path,val){var parts=String(path||'').split('.').filter(Boolean);if(!parts.length)throw new Error('Empty path');var cur=obj;for(var i=0;i<parts.length-1;i++){if(cur[parts[i]]==null||typeof cur[parts[i]]!=='object')cur[parts[i]]={};cur=cur[parts[i]];}cur[parts[parts.length-1]]=val;}
  function getPath(obj,path){var parts=String(path||'').split('.').filter(Boolean),cur=obj;for(var i=0;i<parts.length;i++){if(cur==null)return undefined;cur=cur[parts[i]];}return cur;}
  function parseValue(text){var s=String(text==null?'':text).trim();if(s==='true')return true;if(s==='false')return false;if(s==='null')return null;if(s!==''&&isFinite(Number(s)))return Number(s);try{return JSON.parse(s);}catch(e){return s;}}
  function mutate(path,value,action){var h=hero();if(!h)throw new Error('Нет активного персонажа');var before=getPath(h,path);setPath(h,path,value);var after=getPath(h,path);log(action||('set '+path),before,after,{path:path,characterId:h.id||null,characterName:h.name||null});save();refresh();state.message='✓ '+path+' = '+JSON.stringify(after);render();return after;}
  function backup(){var h=hero();if(!h)throw new Error('Нет активного персонажа');state.backup=clone(h);state.message='✓ Snapshot персонажа создан';render();}
  function rollback(){var h=hero();if(!h||!state.backup)throw new Error('Нет snapshot для отката');var id=h.id;Object.keys(h).forEach(function(k){delete h[k];});Object.keys(state.backup).forEach(function(k){h[k]=clone(state.backup[k]);});if(id!=null)h.id=id;log('rollback character',null,h,{characterId:h.id||null});save();refresh();state.message='↩ Персонаж восстановлен из snapshot';render();}
  function quick(path,val,label){try{mutate(path,val,'quick: '+label);}catch(e){state.message='✕ '+e.message;render();}}
  function damage(n){var h=hero();if(!h)return state.message='✕ Нет активного персонажа';var old=Number(h.hpCurrent)||0,amt=Math.max(0,Number(n)||0);quick('hpCurrent',Math.max(0,old-amt),'damage '+amt);}
  function heal(n){var h=hero();if(!h)return state.message='✕ Нет активного персонажа';var old=Number(h.hpCurrent)||0,max=Number(h.hpMax)||999999,amt=Math.max(0,Number(n)||0);quick('hpCurrent',Math.min(max,old+amt),'heal '+amt);}
  function addCondition(name){var h=hero();if(!h)return;h.activeConditions=h.activeConditions||{};var before=clone(h.activeConditions);h.activeConditions[name]=true;log('add condition',before,h.activeConditions,{condition:name});save();refresh();state.message='✓ Condition: '+name;render();}
  function clearConditions(){var h=hero();if(!h)return;var before=clone(h.activeConditions||{});h.activeConditions={};log('clear conditions',before,h.activeConditions,{});save();refresh();state.message='✓ Conditions cleared';render();}
  function setSpell(level,used,total){var h=hero();if(!h)return;h.spellSlotsData=h.spellSlotsData||{};var key=String(level),before=clone(h.spellSlotsData[key]);h.spellSlotsData[key]={used:Number(used)||0,total:Number(total)||0};log('set spell slots',before,h.spellSlotsData[key],{level:key});save();refresh();state.message='✓ Spell slots L'+key;render();}
  function setResource(index,current,max){var h=hero();if(!h)return;h.combatAbilities=h.combatAbilities||[];var a=h.combatAbilities[index];if(!a)throw new Error('Нет способности #'+index);var before={usedCount:a.usedCount,maxUses:a.maxUses};a.usedCount=Number(current)||0;if(max!==''&&max!=null)a.maxUses=Number(max)||0;log('set resource',before,{usedCount:a.usedCount,maxUses:a.maxUses},{index:index,name:a.name||''});save();refresh();state.message='✓ Resource: '+(a.name||('#'+index));render();}
  function injectEvent(){var text=document.getElementById('dbg701EventPayload');if(!text)return;try{var ev=JSON.parse(text.value);if(global.DNDCombatEventBusV69&&typeof global.DNDCombatEventBusV69.record==='function'){global.DNDCombatEventBusV69.record(ev);state.message='✓ Event injected';render();}else throw new Error('Event Bus V69 недоступен');}catch(e){state.message='✕ '+e.message;render();}}
  function createStress(){var h=hero();if(!h)throw new Error('Нет активного персонажа');var before=clone(h);h.hpCurrent=0;h.hpTemp=50;h.activeConditions=Object.assign({},h.activeConditions||{},{Poisoned:true,Prone:true,Stunned:true});h.ac=1;h.speed='0';h.inspiration=true;h.deathSaves={successes:0,failures:3};h.spellSlotsData=h.spellSlotsData||{};h.spellSlotsData['1']={used:99,total:2};log('stress state',before,h,{preset:'near-death'});save();refresh();state.message='⚠ Stress state applied';render();}
  function resetLocalJournal(){journal=[];journalSave();state.message='✓ Debug journal cleared';render();}
  function tabs(){return ['quick','character','combat','events','journal'];}
  function btn(label,fn,extra){return '<button class="btn-action" style="padding:7px;'+(extra||'')+'" onclick="'+fn+'">'+label+'</button>';}
  function render(){var root=document.getElementById(rootId);if(!root)return;root.style.display=state.open?'block':'none';if(!state.open)return;var h=hero(),tabsHtml=tabs().map(function(t){return btn(t.toUpperCase(),"dndV701Tab('"+t+"')",state.tab===t?'border:2px solid #fff;':'');}).join(' '),body='';
    if(state.tab==='quick')body=renderQuick(h);if(state.tab==='character')body=renderCharacter(h);if(state.tab==='combat')body=renderCombat(h);if(state.tab==='events')body=renderEvents();if(state.tab==='journal')body=renderJournal();
    root.innerHTML='<div style="padding:10px;max-width:1100px;margin:auto;font-family:system-ui,sans-serif"><div style="display:flex;justify-content:space-between;align-items:center;gap:8px"><div><b>🧪 QA / Debug Sandbox — V70.1</b><div style="font-size:.68em;color:#999">Controlled state mutation • snapshots • rollback • stress testing</div></div>'+btn('✕','dndV701Close()')+'</div><div style="display:flex;gap:5px;overflow:auto;margin:9px 0">'+tabsHtml+'</div>'+body+'<div style="margin-top:9px;padding:8px;background:#171717;border:1px solid #444;border-radius:8px;font-size:.75em;white-space:pre-wrap">'+esc(state.message||'')+'</div></div>';
  }
  function renderQuick(h){if(!h)return '<p>Нет активного персонажа.</p>';return '<div style="display:grid;grid-template-columns:1fr 1fr;gap:6px">'+btn('❤️ HP 1',"dndV701Set('hpCurrent',1)")+btn('💚 Full HP',"dndV701Set('hpCurrent',Number(dndV701Hero().hpMax)||1)")+btn('🛡 AC 30',"dndV701Set('ac',30)")+btn('🐌 Speed 0',"dndV701Set('speed','0')")+btn('⚡ Speed 120',"dndV701Set('speed','120')")+btn('⭐ Level 20',"dndV701Set('level',20)")+btn('📈 XP 1000000',"dndV701Set('experience',1000000)")+btn('✨ Inspiration ON',"dndV701Set('inspiration',true)")+btn('☠️ Stress state',"dndV701Stress()")+btn('🧹 Clear conditions',"dndV701ClearConditions()")+btn('📸 Snapshot',"dndV701Backup()")+btn('↩ Rollback',"dndV701Rollback()")+'</div><h3>Active character</h3><pre style="max-height:32vh;overflow:auto;background:#171717;padding:8px">'+esc(JSON.stringify({id:h.id,name:h.name,level:h.level,hpCurrent:h.hpCurrent,hpMax:h.hpMax,ac:h.ac,speed:h.speed},null,2))+'</pre>';
  }
  function renderCharacter(h){if(!h)return '<p>Нет активного персонажа.</p>';return '<h3>Any-field editor</h3><p style="font-size:.75em">Можно менять любое поле объекта персонажа. Пример: <code>abilities.str</code>, <code>skills.stealth</code>, <code>saves.dex</code>, <code>hpCurrent</code>, <code>inventory.0.quantity</code>.</p><input id="dbg701Path" value="'+esc(state.path)+'" placeholder="object.path" style="width:100%;box-sizing:border-box;margin:3px 0"><textarea id="dbg701Value" rows="3" style="width:100%;box-sizing:border-box" placeholder="JSON / число / строка / true / false">'+esc(state.value)+'</textarea>'+btn('⚙ SET FIELD',"dndV701SetPath()",'margin-top:5px')+' '+btn('📖 Read',"dndV701ReadPath()",'margin-top:5px')+'<h3>Common fields</h3><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:5px">'+['name','level','experience','hpCurrent','hpMax','hpTemp','ac','speed','proficiencyBonus','inspiration'].map(function(p){return btn(p,"dndV701UsePath('"+p+"')");}).join('')+'</div><pre id="dbg701PathResult" style="white-space:pre-wrap;background:#171717;padding:8px;max-height:25vh;overflow:auto"></pre>';
  }
  function renderCombat(h){var abilities=h&&Array.isArray(h.combatAbilities)?h.combatAbilities:[];return '<h3>Combat state</h3><div style="display:grid;grid-template-columns:1fr 1fr;gap:5px">'+btn('💥 Damage 5',"dndV701Damage(5)")+btn('💥 Damage 20',"dndV701Damage(20)")+btn('💚 Heal 5',"dndV701Heal(5)")+btn('💚 Full heal',"dndV701Set('hpCurrent',Number(dndV701Hero().hpMax)||1)")+btn('🎯 Initiative 20',"dndV701Set('initiativeTracker.combatants.0.initiative',20)")+btn('📍 X=0 Y=0',"dndV701Set('battlePosition',{x:0,y:0})")+'</div><h3>Conditions</h3><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:5px">'+['Blinded','Charmed','Frightened','Poisoned','Prone','Stunned','Unconscious','Restrained','Invisible'].map(function(c){return btn(c,"dndV701Condition('"+c+"')");}).join('')+'</div><h3>Resources</h3><div>'+abilities.map(function(a,i){return '<div style="display:flex;gap:5px;align-items:center;margin:4px 0"><span style="flex:1">'+esc(a.name||('#'+i))+'</span><button class="btn-action" onclick="dndV701Resource('+i+',0)">RESET</button><button class="btn-action" onclick="dndV701Resource('+i+',99)">99</button></div>';}).join('')+'</div><h3>Spell slots</h3><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:5px">'+[1,2,3,4,5,6,7,8,9].map(function(l){return btn('L'+l+' FULL',"dndV701Spell("+l+",0,9)");}).join('')+'</div>';
  }
  function renderEvents(){return '<h3>Inject synthetic Event Bus event</h3><textarea id="dbg701EventPayload" rows="7" style="width:100%;box-sizing:border-box">'+esc(JSON.stringify({type:'debug.synthetic',source:'V70.1',timestamp:new Date().toISOString(),payload:{message:'QA test event'}},null,2))+'</textarea>'+btn('⚡ Inject event',"dndV701InjectEvent()")+'<p style="font-size:.72em">Используется только для тестирования Event Bus/Replay/Combat Log.</p>' ;}
  function renderJournal(){return '<div style="display:flex;gap:5px">'+btn('↩ Rollback current snapshot',"dndV701Rollback()")+btn('🧹 Clear journal',"dndV701ClearJournal()")+'</div><pre style="white-space:pre-wrap;background:#171717;padding:8px;max-height:60vh;overflow:auto;font-size:.7em">'+esc(JSON.stringify(journal.slice().reverse(),null,2))+'</pre>';}
  function open(){journalLoad();state.open=true;render();}
  function close(){state.open=false;render();}
  function setTab(t){state.tab=t;render();}
  function apiSet(path,value){try{mutate(path,value,'manual set');}catch(e){state.message='✕ '+e.message;render();}}
  global.dndV701Hero=hero;global.dndV701Open=open;global.dndV701Close=close;global.dndV701Tab=setTab;global.dndV701Set=function(path,val){apiSet(path,val);};global.dndV701SetPath=function(){var p=document.getElementById('dbg701Path'),v=document.getElementById('dbg701Value');if(p&&v){state.path=p.value;state.value=v.value;apiSet(state.path,parseValue(state.value));}};global.dndV701ReadPath=function(){var h=hero(),p=document.getElementById('dbg701Path'),r=document.getElementById('dbg701PathResult');if(h&&p&&r)r.textContent=JSON.stringify(getPath(h,p.value),null,2);};global.dndV701UsePath=function(p){state.path=p;state.value='';state.tab='character';render();};global.dndV701Backup=backup;global.dndV701Rollback=rollback;global.dndV701Damage=damage;global.dndV701Heal=heal;global.dndV701Condition=addCondition;global.dndV701ClearConditions=clearConditions;global.dndV701Spell=setSpell;global.dndV701Resource=setResource;global.dndV701InjectEvent=injectEvent;global.dndV701Stress=createStress;global.dndV701ClearJournal=resetLocalJournal;
  global.DNDDebugSandboxV701={version:VERSION,open:open,close:close,hero:hero,set:function(p,v){return mutate(p,v,'api set');},get:function(p){return getPath(hero(),p);},backup:backup,rollback:rollback,damage:damage,heal:heal,addCondition:addCondition,clearConditions:clearConditions,setSpell:setSpell,setResource:setResource,injectEvent:injectEvent,journal:function(){return clone(journal);},snapshot:function(){return {version:VERSION,hero:clone(hero()),journal:clone(journal),hasBackup:!!state.backup};}};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){journalLoad();});else journalLoad();
})(window);
