/* V70.36.73 — true WebGL 3D map editor
 * Three.js renderer + GLB/GLTF loading. Reads the existing V15 map format from localStorage.
 * The legacy canvas editor remains available as fallback.
 */
(function(global){
'use strict';
var THREE=null,GLTFLoader=null,renderer=null,scene=null,camera=null,root=null,gizmo=null,gizmoAxis=null,gizmoDragging=false,gizmoStartX=0,gizmoStartY=0,gizmoStartPos=null,gizmoStartRot=0,gizmoStartScale=null,raf=0,map=null,selected=null,mode='orbit',transformMode='translate',raycaster=null,mouse=null,assetDB=null,assetCache={},controls={yaw:.8,pitch:.8,distance:24,target:{x:0,y:0,z:0}},touches={},touchGesture=null,snapGrid=true,snapSize=0.25;
var VERSION='V70.36.73';
function esc(s){return String(s==null?'':s).replace(/[&<>"]/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'})[c];});}
function hex(v,f){return /^#[0-9a-f]{6}$/i.test(String(v||''))?String(v):f;}
function loadMap(){try{return JSON.parse(localStorage.getItem('dnd_vtt_3d_map')||'null');}catch(e){return null;}}
function saveMap(){if(!map)return;localStorage.setItem('dnd_vtt_3d_map',JSON.stringify(map));}
function ensureMapCollections(){if(!map)return;map.assets=Array.isArray(map.assets)?map.assets:[];map.objects=Array.isArray(map.objects)?map.objects:[];}
function openAssetDB(){return new Promise(function(resolve,reject){if(assetDB){resolve(assetDB);return;}try{var r=indexedDB.open('dnd_vtt_3d_assets',1);r.onupgradeneeded=function(){var db=r.result;if(!db.objectStoreNames.contains('assets'))db.createObjectStore('assets',{keyPath:'id'});};r.onsuccess=function(){assetDB=r.result;resolve(assetDB);};r.onerror=function(){reject(r.error||new Error('IndexedDB error'));};}catch(e){reject(e);}});}
function putAsset(id,record){return openAssetDB().then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction('assets','readwrite');tx.objectStore('assets').put(Object.assign({id:id},record));tx.oncomplete=function(){assetCache[id]=record;resolve(record);};tx.onerror=function(){reject(tx.error||new Error('Asset save error'));};});});}
function getAsset(id){if(assetCache[id])return Promise.resolve(assetCache[id]);return openAssetDB().then(function(db){return new Promise(function(resolve,reject){var tx=db.transaction('assets','readonly'),q=tx.objectStore('assets').get(id);q.onsuccess=function(){if(q.result)assetCache[id]=q.result;resolve(q.result||null);};q.onerror=function(){reject(q.error||new Error('Asset read error'));};});});}
function newAssetId(){return 'asset_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);}
function syncSelectedTransform(){if(!selected||!selected.userData||!selected.userData.mapObjectId||!map)return;var id=selected.userData.mapObjectId,o=(map.objects||[]).find(function(x){return String(x.id)===String(id);});if(!o)return;o.x=Number(selected.position.x)-.5;o.y=Number(selected.position.z)-.5;o.z=Number(selected.position.y)||0;o.rotation=Number(selected.rotation.y)*180/Math.PI;o.scaleX=Number(selected.scale.x)||1;o.scaleY=Number(selected.scale.z)||1;o.scaleZ=Number(selected.scale.y)||1;saveMap();}
function nudgeSelected(dx,dz){if(!selected||!selected.userData||!selected.userData.mapObjectId){alert('Выберите объект.');return;}selected.position.x+=dx;selected.position.z+=dz;syncSelectedTransform();updateInfo();}
function rotateSelected(deg){if(!selected||!selected.userData||!selected.userData.mapObjectId){alert('Выберите объект.');return;}selected.rotation.y+=deg*Math.PI/180;syncSelectedTransform();updateInfo();}
function scaleSelected(mult){if(!selected||!selected.userData||!selected.userData.mapObjectId){alert('Выберите объект.');return;}selected.scale.multiplyScalar(mult);syncSelectedTransform();updateInfo();}
function side(w,n){w[n]=w[n]||{texture:'none',color:null};return w[n];}
function material(color,rough){return new THREE.MeshStandardMaterial({color:hex(color,'#777777'),roughness:rough==null?.82:rough,metalness:0});}
function tex(url){if(!url||url==='none')return null;try{var l=new THREE.TextureLoader();var t=l.load(url);t.wrapS=t.wrapT=THREE.RepeatWrapping;return t;}catch(e){return null;}}
function matFromSide(s,base){var m=material((s&&s.color)||base);var t=tex(s&&s.texture);if(t)m.map=t;return m;}
function addBox(name,x,y,z,w,h,d,mats,rot){
 var g=new THREE.BoxGeometry(w,h,d);var ms=Array.isArray(mats)?mats:[mats||material('#777')];var o=new THREE.Mesh(g,ms);o.name=name;o.position.set(x+w*.5,y+d*.5,z+h*.5);if(rot)o.rotation.y=Number(rot)*Math.PI/180;root.add(o);return o;
}
function wallMesh(w){
 var h=Math.max(.5,Number(w.height)||2.5),t=Math.max(.03,Number(w.thickness)||.09),z=(Number(w.level)||0)*3+(Number(map.cells&&map.cells[(w.level||0)+':'+w.x+':'+w.y])||0);
 var front=side(w,'front'),back=side(w,'back'),base=w.color||'#777777';
 var mats=[material(base),matFromSide(front,base),matFromSide(back,base),material(base),material(base),material(base)];
 var x=Number(w.x)||0,y=Number(w.y)||0;
 if(w.dir==='n')return addBox('wall:'+w.level+':'+x+':'+y,x,y-t/2,z,1,t,h,mats);
 return addBox('wall:'+w.level+':'+x+':'+y,x+1-t/2,y,z,t,1,h,mats);
}
function build(){
 if(!THREE||!map)return;
 while(root.children.length)root.remove(root.children[0]);
 var cols=Number(map.grid&&map.grid.cols)||20,rows=Number(map.grid&&map.grid.rows)||20,level=Number(map.levels&&map.levels.current)||0;
 var ground=new THREE.Mesh(new THREE.PlaneGeometry(cols,rows),material('#30352f',1));ground.rotation.x=-Math.PI/2;ground.position.set(cols/2,0,rows/2);ground.name='ground';root.add(ground);
 var surfaces=map.surfaces||{};Object.keys(surfaces).forEach(function(k){var p=k.split(':'),l=Number(p[0]),x=Number(p[1]),y=Number(p[2]);if(l!==level)return;var s=surfaces[k],m=material(s.color||'#30352f');var t=tex(s.texture);if(t){t.repeat.set(Number(s.repeatX)||1,Number(s.repeatY)||1);m.map=t;}var q=new THREE.Mesh(new THREE.BoxGeometry(1,.08,1),m);q.position.set(x+.5,Number((map.cells&&map.cells[k])||0)*.12+.04,y+.5);q.name='surface:'+k;root.add(q);});
 Object.keys(map.walls||{}).forEach(function(k){var w=map.walls[k];if(Number(w.level)===level)wallMesh(w);});
 (map.objects||[]).forEach(function(o){if(Number(o.level||0)!==level)return;if(o.assetId){loadAssetObject(o);}else{var m=material(o.color||'#8b5a2b');var t=tex(o.texture);if(t)m.map=t;var q=addBox('object:'+o.id,Number(o.x)+.5,Number(o.y)+.5,Number(o.z)||0,(Number(o.size)||.8)*Number(o.scaleX||1),Math.max(.1,Number(o.size)||.8)*Number(o.scaleZ||1),(Number(o.size)||.8)*Number(o.scaleY||1),m,Number(o.rotation)||0);q.userData.mapObjectId=o.id;}});
 (map.tokens||[]).forEach(function(o){if(Number(o.level||0)!==level)return;var q=addBox('token:'+o.id,Number(o.x)+.35,Number(o.y)+.35,.12,.3,.3,.3,material(o.kind==='monster'?'#b33':'#39c'));q.userData.tokenId=o.id;});
}
function loadAssetObject(o){getAsset(o.assetId).then(function(rec){if(!rec||!rec.buffer)return;var loader=new GLTFLoader();loader.parse(rec.buffer,'',function(g){var q=g.scene;q.name='object:'+o.id;q.userData.mapObjectId=o.id;q.userData.assetId=o.assetId;q.position.set(Number(o.x||0)+.5,Number(o.z||0),Number(o.y||0)+.5);q.rotation.y=Number(o.rotation||0)*Math.PI/180;q.scale.set(Number(o.scaleX||1),Number(o.scaleZ||1),Number(o.scaleY||1));root.add(q);},function(e){console.warn('GLB parse failed',o.assetId,e);});}).catch(function(e){console.warn('Asset read failed',o.assetId,e);});}
function resize(){if(!renderer)return;var c=renderer.domElement,w=c.clientWidth,h=c.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(1,h);camera.updateProjectionMatrix();}
function frame(){if(!renderer)return;var c=renderer.domElement,dx=Math.cos(controls.yaw)*Math.cos(controls.pitch)*controls.distance,dy=Math.sin(controls.pitch)*controls.distance,dz=Math.sin(controls.yaw)*Math.cos(controls.pitch)*controls.distance;camera.position.set(controls.target.x+dx,controls.target.y+dy+8,controls.target.z+dz);camera.lookAt(controls.target.x,controls.target.y,controls.target.z);renderer.render(scene,camera);raf=requestAnimationFrame(frame);}
function pick(ev){if(!raycaster||!renderer)return;var r=renderer.domElement.getBoundingClientRect();mouse.x=((ev.clientX-r.left)/r.width)*2-1;mouse.y=-((ev.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);var hits=raycaster.intersectObjects(root.children,true).filter(function(h){return h.object.name!=='ground'&&!h.object.userData.gizmoAxis;});if(!hits.length){selected=null;updateGizmo();updateInfo();return;}var o=hits[0].object;while(o&&o.parent&&!(o.userData&&o.userData.mapObjectId)&&o.parent!==root)o=o.parent;selected=o;updateGizmo();updateInfo();}
function updateInfo(){var e=document.getElementById('map3dRealInfo');if(!e)return;e.textContent=selected?'Выбрано: '+selected.name+(selected.userData&&selected.userData.assetId?' • GLB':''):'Ничего не выбрано';}
function makeGizmo(){if(!THREE||gizmo)return;gizmo=new THREE.Group();gizmo.name='transform-gizmo';function axis(name,color,vec){var mat=new THREE.LineBasicMaterial({color:color,depthTest:false,transparent:true,opacity:.95});var geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),vec.clone().multiplyScalar(1.5)]);var line=new THREE.Line(geo,mat);line.userData.gizmoAxis=name;line.renderOrder=999;gizmo.add(line);var cone=new THREE.Mesh(new THREE.ConeGeometry(.12,.35,12),new THREE.MeshBasicMaterial({color:color,depthTest:false}));cone.userData.gizmoAxis=name;cone.position.copy(vec.clone().multiplyScalar(1.65));if(name==='X')cone.rotation.z=-Math.PI/2;if(name==='Z')cone.rotation.x=Math.PI/2;gizmo.add(cone);}axis('X',0xff5555,new THREE.Vector3(1,0,0));axis('Y',0x55ff66,new THREE.Vector3(0,1,0));axis('Z',0x5599ff,new THREE.Vector3(0,0,1));gizmo.visible=false;gizmo.renderOrder=999;scene.add(gizmo);}
function updateGizmo(){if(!gizmo)return;gizmo.visible=!!selected;if(selected){gizmo.position.copy(selected.getWorldPosition(new THREE.Vector3()));gizmo.scale.setScalar(Math.max(.6,controls.distance*.045));}}
function snapValue(v,step){if(!snapGrid||!step)return v;return Math.round(v/step)*step;}
function applySnap(){if(!selected)return;if(transformMode==='translate'){selected.position.x=snapValue(selected.position.x,snapSize);selected.position.y=snapValue(selected.position.y,snapSize);selected.position.z=snapValue(selected.position.z,snapSize);}else if(transformMode==='rotate'){var step=Math.PI/12;selected.rotation.y=Math.round(selected.rotation.y/step)*step;}else if(transformMode==='scale'){var step=.1;selected.scale.x=Math.max(.1,Math.round(selected.scale.x/step)*step);selected.scale.y=Math.max(.1,Math.round(selected.scale.y/step)*step);selected.scale.z=Math.max(.1,Math.round(selected.scale.z/step)*step);}}
function setGizmoHighlight(axis){if(!gizmo)return;gizmo.children.forEach(function(c){var m=c.material;if(!m)return;var active=c.userData&&c.userData.gizmoAxis===axis;m.opacity=active?1:.82;if(m.color){if(active)m.color.set(0xffff66);else if(c.userData.gizmoAxis==='X')m.color.set(0xff5555);else if(c.userData.gizmoAxis==='Y')m.color.set(0x55ff66);else if(c.userData.gizmoAxis==='Z')m.color.set(0x5599ff);}});}
function gizmoHit(ev){if(!gizmo||!gizmo.visible)return null;var r=renderer.domElement.getBoundingClientRect();mouse.x=((ev.clientX-r.left)/r.width)*2-1;mouse.y=-((ev.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(mouse,camera);var h=raycaster.intersectObjects(gizmo.children,true);return h.length?h[0].object.userData.gizmoAxis:null;}
function gizmoMove(ev){if(!selected||!gizmoDragging)return;var dx=ev.clientX-gizmoStartX,dy=ev.clientY-gizmoStartY;var step=Math.max(.002,controls.distance*.0018);if(transformMode==='rotate'){selected.rotation.y=gizmoStartRot+(dx-dy)*.01;}else if(transformMode==='scale'){var q=Math.max(.15,1+(dx-dy)*.004);selected.scale.copy(gizmoStartScale).multiplyScalar(q);}else{if(gizmoAxis==='X')selected.position.x=gizmoStartPos.x+dx*step;else if(gizmoAxis==='Z')selected.position.z=gizmoStartPos.z-dy*step;else if(gizmoAxis==='Y')selected.position.y=gizmoStartPos.y-dy*step;}applySnap();syncSelectedTransform();updateGizmo();updateInfo();}
function setGizmoMode(m){transformMode=m;mode='transform';updateInfo();setGizmoHighlight(null);}
function colorSide(which){
 if(!selected||selected.name.indexOf('wall:')!==0){alert('Выберите стену в 3D-сцене.');return;}
 var parts=selected.name.split(':');var k=parts.slice(1).join(':');var w=map.walls&&map.walls[k];if(!w){alert('Стена не найдена в карте.');return;}
 var s=side(w,which),v=prompt(which==='front'?'Цвет внутренней стороны':'Цвет внешней стороны',s.color||'#777777');if(v===null)return;if(!/^#[0-9a-f]{6}$/i.test(v)){alert('Нужен цвет #RRGGBB');return;}s.color=v;saveMap();build();updateInfo();
}
function screenDistance(a,b){var dx=a.clientX-b.clientX,dy=a.clientY-b.clientY;return Math.sqrt(dx*dx+dy*dy);}
function screenMid(a,b){return {x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2};}
function beginTouchGesture(){var ids=Object.keys(touches);if(ids.length<2){touchGesture=null;return;}var a=touches[ids[0]],b=touches[ids[1]],m=screenMid(a,b);touchGesture={distance:screenDistance(a,b),midX:m.x,midY:m.y,targetX:controls.target.x,targetZ:controls.target.z};}
function updateTouchGesture(){if(!touchGesture)return;var ids=Object.keys(touches);if(ids.length<2)return;var a=touches[ids[0]],b=touches[ids[1]],m=screenMid(a,b),d=screenDistance(a,b);var ratio=touchGesture.distance/Math.max(1,d);controls.distance=Math.max(3,Math.min(150,controls.distance*ratio));var pan=.012*controls.distance;controls.target.x=touchGesture.targetX-(m.x-touchGesture.midX)*pan;controls.target.z=touchGesture.targetZ+(m.y-touchGesture.midY)*pan;}
function addModel(){
 ensureMapCollections();
 var input=document.createElement('input');input.type='file';input.accept='.glb,.gltf,model/gltf-binary,model/gltf+json';input.onchange=function(){var f=input.files&&input.files[0];if(!f)return;if(f.name.toLowerCase().endsWith('.gltf')){alert('Для мобильного редактора лучше использовать .GLB: он сохраняет модель и ресурсы в одном файле.');return;}var rd=new FileReader();rd.onload=function(){var id=newAssetId(),buf=rd.result,meta={name:f.name,type:f.type||'model/gltf-binary',size:f.size,createdAt:new Date().toISOString(),license:'user-imported',source:'local'};putAsset(id,{meta:meta,buffer:buf}).then(function(){map.assets.push({id:id,name:f.name,type:meta.type,size:f.size,createdAt:meta.createdAt,license:meta.license,source:meta.source});var oid='obj_'+Date.now().toString(36);map.objects.push({id:oid,name:f.name,assetId:id,x:1,y:1,z:0,scaleX:1,scaleY:1,scaleZ:1,rotation:0});saveMap();build();updateInfo();alert('GLB сохранён в локальную библиотеку и привязан к карте как assetId: '+id);}).catch(function(e){alert('Не удалось сохранить 3D-ассет: '+e.message);});};rd.readAsArrayBuffer(f);};input.click();
}
function open(){
 if(document.getElementById('map3dRealModal'))return;
 map=loadMap();if(!map){alert('Сначала создайте или сохраните 3D-карту в редакторе.');return;}
 var modal=document.createElement('div');modal.id='map3dRealModal';modal.style.cssText='position:fixed;inset:0;z-index:32000;background:#080b10;color:#fff;display:flex;flex-direction:column;';
 modal.innerHTML='<div style="height:48px;display:flex;align-items:center;gap:8px;padding:6px 10px;box-sizing:border-box;background:#151a20;border-bottom:1px solid #444"><b>🏗️ Настоящий 3D-редактор</b><span style="color:#888">'+VERSION+'</span><span id="map3dRealInfo" style="flex:1;color:#aaa">Загрузка WebGL…</span><button id="r3dFront">🎨 Внутри</button><button id="r3dBack">🎨 Снаружи</button><button id="r3dModel">🧩 GLB</button><button id="r3dMove">↔ Перемещение</button><button id="r3dRotate">⟳ Вращение</button><button id="r3dScale">⤢ Масштаб</button><button id="r3dSnap">🧲 Сетка: ВКЛ</button><button id="r3dLeft">←</button><button id="r3dRight">→</button><button id="r3dForward">↑</button><button id="r3dBackMove">↓</button><button id="r3dRotL">↶</button><button id="r3dRotR">↷</button><button id="r3dScaleDown">−</button><button id="r3dScaleUp">＋</button><button id="r3dSave">💾 Сохранить</button><button id="r3dClose">✕</button></div><div id="map3dRealCanvas" style="position:relative;flex:1;min-height:0;overflow:hidden"></div>';
 document.body.appendChild(modal);
 modal.querySelector('#r3dClose').onclick=function(){cancelAnimationFrame(raf);if(gizmo&&gizmo.parent)gizmo.parent.remove(gizmo);modal.remove();};
 modal.querySelector('#r3dMove').onclick=function(){setGizmoMode('translate');};modal.querySelector('#r3dRotate').onclick=function(){setGizmoMode('rotate');};modal.querySelector('#r3dScale').onclick=function(){setGizmoMode('scale');};modal.querySelector('#r3dSnap').onclick=function(){snapGrid=!snapGrid;this.textContent='🧲 Сетка: '+(snapGrid?'ВКЛ':'ВЫКЛ');if(snapGrid){applySnap();syncSelectedTransform();updateGizmo();}};
 modal.querySelector('#r3dFront').onclick=function(){colorSide('front');};modal.querySelector('#r3dBack').onclick=function(){colorSide('back');};modal.querySelector('#r3dModel').onclick=addModel;modal.querySelector('#r3dLeft').onclick=function(){nudgeSelected(-.25,0);};modal.querySelector('#r3dRight').onclick=function(){nudgeSelected(.25,0);};modal.querySelector('#r3dForward').onclick=function(){nudgeSelected(0,-.25);};modal.querySelector('#r3dBackMove').onclick=function(){nudgeSelected(0,.25);};modal.querySelector('#r3dRotL').onclick=function(){rotateSelected(-15);};modal.querySelector('#r3dRotR').onclick=function(){rotateSelected(15);};modal.querySelector('#r3dScaleDown').onclick=function(){scaleSelected(.9);};modal.querySelector('#r3dScaleUp').onclick=function(){scaleSelected(1.1);};modal.querySelector('#r3dSave').onclick=function(){saveMap();alert('Карта и assetRef сохранены.');};
 (async function(){
  try{
   var T=await import('./vendor/three.module.min.js');
   var L=await import('./vendor/GLTFLoader.js');
   THREE=T;GLTFLoader=L.GLTFLoader;
   var host=modal.querySelector('#map3dRealCanvas');renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(global.devicePixelRatio||1,1.6));renderer.setSize(host.clientWidth,host.clientHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);
   scene=new THREE.Scene();scene.background=new THREE.Color('#10151c');root=new THREE.Group();scene.add(root);camera=new THREE.PerspectiveCamera(55,1,.05,1000);raycaster=new THREE.Raycaster();mouse=new THREE.Vector2();
   scene.add(new THREE.HemisphereLight(0xffffff,0x223344,2));var dl=new THREE.DirectionalLight(0xffffff,2);dl.position.set(10,20,5);scene.add(dl);makeGizmo();
   var dragging=false,lastX=0,lastY=0,button=0;
   renderer.domElement.addEventListener('pointerdown',function(ev){touches[ev.pointerId]={clientX:ev.clientX,clientY:ev.clientY};if(ev.pointerType==='touch'&&Object.keys(touches).length>=2){beginTouchGesture();dragging=false;return;}var gh=ev.button===0?gizmoHit(ev):null;if(gh&&selected){gizmoAxis=gh;gizmoDragging=true;gizmoStartX=ev.clientX;gizmoStartY=ev.clientY;gizmoStartPos=selected.position.clone();gizmoStartRot=selected.rotation.y;gizmoStartScale=selected.scale.clone();renderer.domElement.setPointerCapture&&renderer.domElement.setPointerCapture(ev.pointerId);return;}dragging=true;lastX=ev.clientX;lastY=ev.clientY;button=ev.button;renderer.domElement.setPointerCapture&&renderer.domElement.setPointerCapture(ev.pointerId);if(button===0)pick(ev);});
   renderer.domElement.addEventListener('dblclick',function(){if(selected&&selected.userData&&selected.userData.mapObjectId){var o=(map.objects||[]).find(function(x){return String(x.id)===String(selected.userData.mapObjectId);});if(o){var v=prompt('Точный X Y Z, например 2 3 0',Number(o.x||0)+' '+Number(o.y||0)+' '+Number(o.z||0));if(v){var p=v.trim().split(/\\s+/).map(Number);if(p.length===3&&p.every(function(n){return Number.isFinite(n)})){selected.position.set(p[0]+.5,p[2],p[1]+.5);syncSelectedTransform();updateInfo();}}}}});
   renderer.domElement.addEventListener('pointermove',function(ev){if(touches[ev.pointerId]){touches[ev.pointerId].clientX=ev.clientX;touches[ev.pointerId].clientY=ev.clientY;}if(Object.keys(touches).length>=2){updateTouchGesture();return;}if(gizmoDragging){gizmoMove(ev);return;}if(!dragging)return;var dx=ev.clientX-lastX,dy=ev.clientY;lastX=ev.clientX;lastY=ev.clientY;if(button===0){controls.yaw-=dx*.008;controls.pitch=Math.max(.15,Math.min(1.45,controls.pitch-dy*.006));}else if(button===1||ev.shiftKey){var pan=.015*controls.distance;controls.target.x-=dx*pan;controls.target.z+=dy*pan;}});
   renderer.domElement.addEventListener('pointerup',function(ev){delete touches[ev.pointerId];dragging=false;gizmoDragging=false;gizmoAxis=null;setGizmoHighlight(null);if(Object.keys(touches).length<2)touchGesture=null;});renderer.domElement.addEventListener('pointercancel',function(ev){delete touches[ev.pointerId];dragging=false;gizmoDragging=false;gizmoAxis=null;touchGesture=null;setGizmoHighlight(null);});
   renderer.domElement.addEventListener('pointermove',function(ev){if(!gizmoDragging){var gh=gizmoHit(ev);setGizmoHighlight(gh);}});renderer.domElement.addEventListener('wheel',function(ev){ev.preventDefault();controls.distance=Math.max(3,Math.min(150,controls.distance*Math.exp(ev.deltaY*.001)));},{passive:false});
   renderer.domElement.addEventListener('contextmenu',function(ev){ev.preventDefault();});
   window.addEventListener('resize',resize);resize();ensureMapCollections();updateGizmo();openAssetDB().catch(function(e){console.warn('IndexedDB unavailable; asset persistence disabled',e);});build();frame();
   modal.querySelector('#map3dRealInfo').textContent='WebGL готов • '+(map.name||'Новая карта');
  }catch(e){modal.querySelector('#map3dRealInfo').textContent='WebGL/Three.js не загрузился';alert('Не удалось запустить настоящий 3D: '+e.message+'\nСтарый редактор не удалён.');}
 })();
}
global.dndMap3DOpenReal=open;
global.dndMap3DOpen=open;
})(window);
