/** V70.6 Deterministic Dice / Attack / Save Laboratory. */
(function(global){'use strict';
var VERSION='70.6.0', KEY='dndVttDiceLabV706', ROOT='dndDiceLabV706';
var state={open:false,forcedD20:null,forcedDamage:null,forcedAttack:null,forcedSave:null,history:[],config:{resistance:{},immunity:[],vulnerability:[]}};
function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
function num(v,d){var n=Number(v);return isFinite(n)?n:d;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({forcedD20:state.forcedD20,forcedDamage:state.forcedDamage,forcedAttack:state.forcedAttack,forcedSave:state.forcedSave,config:state.config}));}catch(e){}}
function load(){try{var x=JSON.parse(localStorage.getItem(KEY)||'null');if(x)Object.assign(state,x);}catch(e){}}
function log(action,detail){state.history.unshift({id:'qa706_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),time:new Date().toISOString(),action:action,detail:detail});if(state.history.length>100)state.history.length=100;}
function emit(type,payload){try{if(global.DNDCombatEventBusV69&&global.DNDCombatEventBusV69.record)global.DNDCombatEventBusV69.record(Object.assign({type:type,source:'V70.6'},payload||{}));}catch(e){}}
function setD20(v){v=v==null||v===''?null:Math.max(1,Math.min(20,Math.floor(num(v,20))));state.forcedD20=v;persist();log('FORCE_D20',v);emit('DEBUG_DICE_FORCE',{kind:'d20',value:v});render();return v;}
function setDamage(v){v=v==null||v===''?null:num(v,0);state.forcedDamage=v;persist();log('FORCE_DAMAGE',v);render();return v;}
function setAttack(v){state.forcedAttack=v==null||v===''?null:(String(v).toLowerCase()==='hit'?'hit':String(v).toLowerCase()==='miss'?'miss':null);persist();log('FORCE_ATTACK',state.forcedAttack);render();return state.forcedAttack;}
function setSave(v){state.forcedSave=v==null||v===''?null:(String(v).toLowerCase()==='success'?'success':String(v).toLowerCase()==='fail'?'fail':null);persist();log('FORCE_SAVE',state.forcedSave);render();return state.forcedSave;}
function rollD20(){var r=state.forcedD20==null?Math.floor(Math.random()*20)+1:state.forcedD20;var out={roll:r,critical:r===20,fumble:r===1,forced:state.forcedD20!=null};log('ROLL_D20',out);emit('DEBUG_DICE_ROLL',out);return out;}
function resolveAttack(opts){opts=opts||{};var d=rollD20(), result=state.forcedAttack||((opts.ac!=null?d.roll+num(opts.modifier,0)>=num(opts.ac,10):d.roll>=10)?'hit':'miss');if(!state.forcedAttack&&d.critical)result='hit';var out={kind:'attack',result:result,d20:d.roll,critical:d.critical,fumble:d.fumble,forced:!!state.forcedAttack,modifier:num(opts.modifier,0),ac:opts.ac==null?null:num(opts.ac,10)};if(result==='hit'&&state.forcedDamage!=null)out.damage=state.forcedDamage;log('ATTACK',out);emit('DEBUG_ATTACK_RESOLVED',out);return out;}
function resolveSave(opts){opts=opts||{};var d=rollD20(), result=state.forcedSave||((opts.dc!=null?d.roll+num(opts.modifier,0)>=num(opts.dc,10):d.roll>=10)?'success':'fail');var out={kind:'save',result:result,d20:d.roll,forced:!!state.forcedSave,modifier:num(opts.modifier,0),dc:opts.dc==null?null:num(opts.dc,10)};log('SAVE',out);emit('DEBUG_SAVE_RESOLVED',out);return out;}
function damage(type,amount){type=String(type||'untyped').toLowerCase();var raw=state.forcedDamage!=null?state.forcedDamage:num(amount,0);var immune=state.config.immunity.indexOf(type)>=0;var vuln=state.config.vulnerability.indexOf(type)>=0;var resist=num(state.config.resistance[type],0)>0;var final=immune?0:resist?Math.floor(raw/2):vuln?raw*2:raw;var out={type:type,raw:raw,final:final,immune:immune,resisted:resist,vulnerable:vuln};log('DAMAGE_MATRIX',out);emit('DEBUG_DAMAGE_RESOLVED',out);return out;}
function setResistance(type,mode){type=String(type||'').toLowerCase();if(!type)return;state.config.resistance=state.config.resistance||{};if(mode==='resist')state.config.resistance[type]=1;else delete state.config.resistance[type];if(mode==='immune'){if(state.config.immunity.indexOf(type)<0)state.config.immunity.push(type);}else state.config.immunity=state.config.immunity.filter(function(x){return x!==type;});if(mode==='vulnerable'){if(state.config.vulnerability.indexOf(type)<0)state.config.vulnerability.push(type);}else state.config.vulnerability=state.config.vulnerability.filter(function(x){return x!==type;});persist();log('DAMAGE_TYPE', {type:type,mode:mode});render();}
function reset(){state.forcedD20=null;state.forcedDamage=null;state.forcedAttack=null;state.forcedSave=null;state.config={resistance:{},immunity:[],vulnerability:[]};persist();log('RESET','all overrides cleared');render();}
function snapshot(){return clone({forcedD20:state.forcedD20,forcedDamage:state.forcedDamage,forcedAttack:state.forcedAttack,forcedSave:state.forcedSave,config:state.config});}
function restore(s){if(!s)return false;Object.assign(state,clone(s));persist();log('RESTORE','dice lab snapshot');render();return true;}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function btn(t,fn){return '<button class="btn-action" onclick="'+fn+'" style="padding:7px 9px;margin:2px">'+t+'</button>';}
function render(){var r=document.getElementById(ROOT);if(!r)return;r.style.display=state.open?'block':'none';if(!state.open)return;var h=state.history.slice(0,12).map(function(x){return '<div style="padding:5px;border-bottom:1px solid #333"><b>'+esc(x.action)+'</b> <span style="color:#aaa">'+esc(JSON.stringify(x.detail))+'</span></div>';}).join('');r.innerHTML='<div style="padding:12px;max-width:850px;margin:auto;font-family:system-ui"><div style="display:flex;justify-content:space-between"><b>🎲 Dice / Combat Laboratory — V70.6</b>'+btn('✕','dndV706Close()')+'</div><div style="background:#171717;padding:9px;margin-top:8px;border-radius:8px"><b>Deterministic d20</b><div style="margin-top:6px">'+btn('Natural 1','dndV706SetD20(1)')+btn('Natural 20','dndV706SetD20(20)')+btn('Random','dndV706SetD20(null)')+btn('Roll','dndV706Roll()')+'</div></div><div style="background:#171717;padding:9px;margin-top:8px;border-radius:8px"><b>Attack</b><div>'+btn('Force HIT','dndV706SetAttack(\'hit\')')+btn('Force MISS','dndV706SetAttack(\'miss\')')+btn('Normal','dndV706SetAttack(null)')+btn('Test Attack','dndV706Attack()')+'</div></div><div style="background:#171717;padding:9px;margin-top:8px;border-radius:8px"><b>Saving Throw</b><div>'+btn('Force SUCCESS','dndV706SetSave(\'success\')')+btn('Force FAIL','dndV706SetSave(\'fail\')')+btn('Normal','dndV706SetSave(null)')+btn('Test Save','dndV706Save()')+'</div></div><div style="background:#171717;padding:9px;margin-top:8px;border-radius:8px"><b>Damage Type Matrix</b><div style="margin-top:6px"><input id="v706Type" value="fire" style="padding:7px;background:#111;color:#fff;border:1px solid #444;width:120px"><input id="v706Amt" value="20" type="number" style="padding:7px;background:#111;color:#fff;border:1px solid #444;width:90px">'+btn('Resist','dndV706Type(\'resist\')')+btn('Immune','dndV706Type(\'immune\')')+btn('Vulnerable','dndV706Type(\'vulnerable\')')+btn('Clear','dndV706Type(\'clear\')')+btn('Resolve','dndV706Damage()')+'</div></div><div style="margin-top:8px">'+btn('↩ Reset Overrides','dndV706Reset()')+'</div><details style="margin-top:8px"><summary>QA History</summary><div style="margin-top:5px">'+(h||'<span style="color:#888">Пусто</span>')+'</div></details></div>';}
function open(){state.open=true;render();}function close(){state.open=false;render();}
function init(){if(document.getElementById(ROOT))return;var e=document.createElement('div');e.id=ROOT;e.style.cssText='display:none;position:fixed;inset:0;z-index:29950;background:rgba(10,10,10,.98);color:#fff;overflow:auto;padding:calc(10px + env(safe-area-inset-top)) 8px 20px;box-sizing:border-box;touch-action:manipulation';document.body.appendChild(e);render();}
load();
global.DNDDiceLabV706={VERSION:VERSION,open:open,close:close,rollD20:rollD20,resolveAttack:resolveAttack,resolveSave:resolveSave,resolveDamage:damage,setD20:setD20,setDamage:setDamage,setAttack:setAttack,setSave:setSave,setDamageType:setResistance,reset:reset,snapshot:snapshot,restore:restore,history:function(){return clone(state.history)},state:function(){return clone(state)}};
global.dndV706Open=open;global.dndV706Close=close;global.dndV706Roll=function(){var r=rollD20();render();return r;};global.dndV706Attack=function(){var r=resolveAttack({ac:15,modifier:5});render();return r;};global.dndV706Save=function(){var r=resolveSave({dc:15,modifier:5});render();return r;};global.dndV706SetD20=setD20;global.dndV706SetDamage=setDamage;global.dndV706SetAttack=setAttack;global.dndV706SetSave=setSave;global.dndV706Type=function(mode){var t=document.getElementById('v706Type');setResistance(t?t.value:'fire',mode);};global.dndV706Damage=function(){var t=document.getElementById('v706Type'),a=document.getElementById('v706Amt');var r=damage(t?t.value:'fire',a?a.value:20);render();return r;};global.dndV706Reset=reset;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})(window);
