/**
 * vtt_mobile_combat_hud_v62.js
 * ------------------------------------------------------------------
 * ЧТО ЭТО: компактный touch-first combat HUD для мобильного VTT.
 * КАК РАБОТАЕТ: показывает HP/AC/скорость, текущий ход и Action/Bonus/
 * Reaction/Movement, а также быстрые атаки выбранного участника через
 * существующие DNDGameplayV57 и DNDTokenInteractionV60.
 * НЕ ДЕЛАЕТ: не создаёт второй character/combat/initiative engine.
 * ПУБЛИЧНЫЕ API: DNDMobileCombatHUDV62, dndV62Open, dndV62Close,
 * dndV62QuickAttack, dndV62EndTurn.
 * ------------------------------------------------------------------
 */
(function(global){
  'use strict';
  var VERSION='62.0.0';
  var state={open:true,expanded:false};
  function hero(){return global.currentChar||global.currentCharacter||null;}
  function tracker(){var h=hero();return h&&h.initiativeTracker||null;}
  function active(){return global.DNDGameplayV57&&typeof global.DNDGameplayV57.active==='function'?global.DNDGameplayV57.active():(function(){var t=tracker();return t&&t.combatants&&t.combatants[t.activeIndex];})();}
  function esc(v){return typeof global.escapeDndHtml==='function'?global.escapeDndHtml(v):String(v==null?'':v).replace(/[&<>\"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c];});}
  function attacks(c){if(!c)return [];var a=Array.isArray(c.attacks)?c.attacks:[];if(!a.length&&Array.isArray(c.actions))a=c.actions.filter(function(x){return x&&(x.damage||x.damageDice||x.attackBonus!=null||x.bonus!=null);}).map(function(x){return {name:x.name||'Атака',bonus:x.bonus!=null?x.bonus:x.attackBonus,damage:x.damage||x.damageDice||'1d6'};});return a.slice(0,4);}
  function resources(c){var r=c&&c.turnResources||{};return {action:r.action!==false,bonusAction:r.bonusAction!==false,reaction:r.reaction!==false,movement:Math.max(0,Number(r.movement||c&&c.speed||30)-Number(r.movementUsed||0)),movementMax:Number(r.movement||c&&c.speed||30)};}
  function save(){if(typeof global.autoSaveCurrentCharacter==='function')global.autoSaveCurrentCharacter();}
  function event(type,payload){var h=hero();if(!h)return;h.gameplayEvents=Array.isArray(h.gameplayEvents)?h.gameplayEvents:[];h.gameplayEvents.push({id:'evt62_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),type:type,at:new Date().toISOString(),payload:payload||{}});if(h.gameplayEvents.length>100)h.gameplayEvents=h.gameplayEvents.slice(-100);save();}
  function quickAttack(i){var c=active(),list=attacks(c);if(!c)return {ok:false,error:'Нет активного участника.'};if(!list[i])return {ok:false,error:'Атака не найдена.'};if(global.DNDTokenInteractionV60&&typeof global.DNDTokenInteractionV60.selectActor==='function'){global.DNDTokenInteractionV60.selectActor(c.id);return global.dndV60QuickAttack(i);}return {ok:false,error:'V60 Token Interaction недоступен.'};}
  function endTurn(){if(!global.DNDGameplayV57||typeof global.DNDGameplayV57.endTurn!=='function')return {ok:false,error:'Gameplay Core V57 недоступен.'};var r=global.DNDGameplayV57.endTurn();if(r&&r.ok)event('MOBILE_HUD_END_TURN_V62',{previousId:r.previous&&r.previous.id,activeId:r.active&&r.active.id,round:r.round});render();return r;}
  function spend(resource){if(!global.DNDGameplayV57)return {ok:false,error:'Gameplay Core V57 недоступен.'};var r=global.DNDGameplayV57.spendAction(resource);render();return r;}
  function open(){state.open=true;render();}
  function close(){state.open=false;var el=document.getElementById('dndMobileCombatHUDV62');if(el)el.style.display='none';}
  function toggle(){state.expanded=!state.expanded;render();}
  function render(){var debugTools=global.dndDebugEnabled?'<button class="btn-action" onclick="dndV70OpenDebug()" style="padding:7px">🛠 Debug</button><button class="btn-action" onclick="dndV701Open()" style="padding:7px">🧪 QA</button><button class="btn-action" onclick="dndV702Open()" style="padding:7px">🧬 Lab</button><button class="btn-action" onclick="dndV705Open()" style="padding:7px">🔗 Scen</button>':'';var el=document.getElementById('dndMobileCombatHUDV62');if(!el){init();el=document.getElementById('dndMobileCombatHUDV62');}if(!el)return;el.style.display=state.open?'block':'none';var c=active(),h=hero(),box=document.getElementById('dndV62HudBody');if(!box)return;if(!c){box.innerHTML='<div style="color:#aaa;text-align:center;padding:8px">Бой не запущен</div>';return;}var r=resources(c),hp=Number(c.hp!=null?c.hp:(h&&h===c?h.hpCurrent:0)),maxHp=Number(c.maxHp!=null?c.maxHp:(h&&h===c?h.hpMax||h.maxHp:0));var html='<div style="display:flex;align-items:center;gap:8px"><div style="flex:1;min-width:0"><div style="font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">'+esc(c.name||'Участник')+'</div><div style="font-size:.72em;color:#aaa">Раунд '+Number(tracker()&&tracker().round||1)+' • КД '+Number(c.ac||10)+' • '+Number(c.speed||30)+' фт.</div></div><div style="font-weight:800">❤ '+hp+'/'+maxHp+'</div><button class="btn-action" onclick="dndV62Toggle()" style="padding:5px 8px;background:#424242">'+(state.expanded?'⌄':'⌃')+'</button></div>';
    html+='<div style="display:grid;grid-template-columns:1fr 1fr 1fr 1.35fr;gap:5px;margin-top:7px;font-size:.72em"><div style="padding:5px;border-radius:7px;background:'+(r.action?'#315d37':'#333')+'">⚔️ Action '+(r.action?'✓':'—')+'</div><div style="padding:5px;border-radius:7px;background:'+(r.bonusAction?'#4d3d68':'#333')+'">✨ Bonus '+(r.bonusAction?'✓':'—')+'</div><div style="padding:5px;border-radius:7px;background:'+(r.reaction?'#31556a':'#333')+'">↩ Reaction '+(r.reaction?'✓':'—')+'</div><div style="padding:5px;border-radius:7px;background:#333">🏃 '+r.movement+'/'+r.movementMax+' фт.</div></div>';
    if(state.expanded){var list=attacks(c);html+='<div style="display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:7px">';if(list.length)list.forEach(function(a,i){html+='<button class="btn-action" onclick="dndV62QuickAttack('+i+')" style="padding:8px;background:#7b3f16;text-align:left">⚔️ '+esc(a.name||'Атака')+'<span style="float:right">+'+Number(a.bonus||0)+' • '+esc(a.damage||'1d6')+'</span></button>';});else html+='<div style="grid-column:1/-1;color:#888;font-size:.78em;padding:5px">Быстрые атаки не зарегистрированы.</div>';html+='</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:6px"><button class="btn-action" onclick="dndV62Spend(\'action\')" style="padding:7px;background:#455a64">⚔️ Потратить Action</button><button class="btn-action" onclick="dndV62Spend(\'bonusAction\')" style="padding:7px;background:#455a64">✨ Потратить Bonus</button></div>';}html+='<div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr 1fr;gap:5px;margin-top:6px"><button class="btn-action" onclick="dndV63Open()" style="padding:7px">👤 Лист</button><button class="btn-action" onclick="dndV64Open()" style="padding:7px">⚔️ Действия</button><button class="btn-action" onclick="dndV66OpenLog()" style="padding:7px">📜 Log</button>'+debugTools+'<button class="btn-action" onclick="dndV67Open()" style="padding:7px">💾 Save</button><button class="btn-action" onclick="dndV68Open()" style="padding:7px">🧭 Check</button><button class="btn-action" onclick="dndV69OpenReplay()" style="padding:7px">⏪ Replay</button></div>'+
      '<button class="btn-action" onclick="dndV62EndTurn()" style="width:100%;margin-top:7px;padding:9px;background:#6d2630;font-weight:700">⏭ Закончить ход</button>';box.innerHTML=html;}
  function init(){var el=document.createElement('div');el.id='dndMobileCombatHUDV62';el.style.cssText='display:none;position:fixed;left:7px;right:7px;bottom:calc(7px + env(safe-area-inset-bottom));z-index:29600;background:rgba(24,24,24,.97);color:#fff;border:1px solid #555;border-radius:14px;padding:9px;box-shadow:0 8px 28px rgba(0,0,0,.55);box-sizing:border-box;touch-action:manipulation;max-width:720px;margin:auto;';el.innerHTML='<div id="dndV62HudBody"></div>';document.body.appendChild(el);}
  global.dndV62Open=open;global.dndV62Close=close;global.dndV62Toggle=toggle;global.dndV62QuickAttack=function(i){var r=quickAttack(i);if(!r.ok&&global.alert)global.alert(r.error);return r;};global.dndV62EndTurn=function(){var r=endTurn();if(!r.ok&&global.alert)global.alert(r.error);return r;};global.dndV62Spend=function(x){var r=spend(x);if(!r.ok&&global.alert)global.alert(r.error);return r;};global.DNDMobileCombatHUDV62={VERSION:VERSION,state:state,open:open,close:close,toggle:toggle,quickAttack:quickAttack,endTurn:endTurn,spend:spend,snapshot:function(){var c=active(),r=resources(c);return {version:VERSION,activeId:c&&c.id||null,hp:c&&c.hp,maxHp:c&&c.maxHp,resources:r,expanded:state.expanded};}};
  if(global.addEventListener)global.addEventListener('DOMContentLoaded',function(){init();setTimeout(render,300);});
})(window);
