window.meleeWeapons = [
  // --- ПРОСТОЕ РУКОПАШНОЕ ---
  {
    id: 'w_dagger',
    name: 'Кинжал',
    category: 'Простое рукопашное',
    groupKey: 'simple',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'колющий',
    weight: '1 фунт',
    cost: '2 зм',
    properties: ['Фехтовальное', 'легкое', 'метательное (дистанция 20/60)'],
    proficiencies: ['p_weapon_simple', 'p_weap_dagger'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Легкий, обоюдоострый клинок, который легко спрятать в складках одежды. Идеален для внезапных атак из тени, ближнего боя в тесноте и метания на коротке.'
  },
  {
    id: 'w_club',
    name: 'Дубина',
    category: 'Простое рукопашное',
    groupKey: 'simple',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'дробящий',
    weight: '2 фунта',
    cost: '1 см',
    properties: ['Легкое'],
    proficiencies: ['p_weapon_simple', 'p_weap_club'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Грубый кусок дерева, подобранный под руку и обтесанный с одного конца. Простейшее оружие нищих, крестьян и гоблинов.'
  },
  {
    id: 'w_handaxe',
    name: 'Ручной топорик',
    category: 'Простое рукопашное',
    groupKey: 'simple',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d6',
    damageType: 'рубящий',
    weight: '2 фунта',
    cost: '5 зм',
    properties: ['Легкое', 'метательное (дистанция 20/60)'],
    proficiencies: ['p_weapon_simple', 'p_weap_handaxe'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Универсальный инструмент лесоруба и путешественника. Сбалансирован для рубки дров и стремительного метания во врага.'
  },
  {
    id: 'w_javelin',
    name: 'Сулицах (дротик)',
    category: 'Простое рукопашное',
    groupKey: 'simple',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d6',
    damageType: 'колющий',
    weight: '2 фунта',
    cost: '5 см',
    properties: ['Метательное (дистанция 30/120)'],
    proficiencies: ['p_weapon_simple', 'p_weap_javelin'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Легкое метательное копье с узким наконечником. Позволяет охотникам и воинам поражать дичь или врагов на подступах к ближнему бою.'
  },
  {
    id: 'w_spear',
    name: 'Копье',
    category: 'Простое рукопашное',
    groupKey: 'simple',
    typeKey: 'melee',
    hands: '🖐️ 1 или 2 руки (универсальное)',
    damage: '1d6',
    damageType: 'колющий',
    weight: '3 фунта',
    cost: '1 зм',
    properties: ['Метательное (дистанция 20/60)', 'универсальное (1d8)'],
    proficiencies: ['p_weapon_simple', 'p_weap_spear'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Древнейшее и надежнейшее оружие человечества. Может применяться как с одной рукой вместе со щитом, так и с двумя для нанесения более сильных колющих ударов.'
  },
  {
    id: 'w_mace',
    name: 'Булава',
    category: 'Простое рукопашное',
    groupKey: 'simple',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d6',
    damageType: 'дробящий',
    weight: '4 фунта',
    cost: '5 зм',
    properties: [],
    proficiencies: ['p_weapon_simple', 'p_weap_mace'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Оружие с массивным металлическим набалдашником в виде фланцев или шипов. Любимый выбор жрецов и паладинов, отлично пробивающий тяжелые латы и панцири.'
  },
  {
    id: 'w_quarterstaff',
    name: 'Боевой посох',
    category: 'Простое рукопашное',
    groupKey: 'simple',
    typeKey: 'melee',
    hands: '🖐️ 1 или 2 руки (универсальное)',
    damage: '1d6',
    damageType: 'дробящий',
    weight: '4 фунта',
    cost: '2 зм',
    properties: ['Универсальное (1d8)'],
    proficiencies: ['p_weapon_simple', 'p_weap_quarterstaff'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Прочный деревянный посох странников, магов и монахов. Позволяет проводить быстрые серии ударов обоими концами при двуручном хвате.'
  },
  {
    id: 'w_sickle',
    name: 'Серп',
    category: 'Простое рукопашное',
    groupKey: 'simple',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'рубящий',
    weight: '2 фунта',
    cost: '1 зм',
    properties: ['Легкое'],
    proficiencies: ['p_weapon_simple', 'p_weap_sickle'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Сельскохозяйственный серп для жатвы, приспособленный крестьянами для самообороны. Оставляет болезненные режущие раны.'
  },
  {
    id: 'w_light_hammer',
    name: 'Легкий молот',
    category: 'Простое рукопашное',
    groupKey: 'simple',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'дробящий',
    weight: '2 фунта',
    cost: '2 зм',
    properties: ['Легкое', 'метательное (дистанция 20/60)'],
    proficiencies: ['p_weapon_simple', 'p_weap_light_hammer'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Небольшой молоток кузнеца или плотника, удобный как в строительстве, так и в качестве метательного оружия ближнего боя.'
  },
  {
    id: 'w_sap',
    name: 'Блекджек (Кистень-хлопушка)',
    category: 'Простое рукопашное (Хоумбрю)',
    groupKey: 'simple',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'дробящий',
    weight: '1 фунт',
    cost: '1 зм',
    properties: ['Легкое', 'скрытное', 'оглушающее'],
    proficiencies: ['p_weapon_simple', 'p_weap_light_hammer'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Кожаный мешочек, утяжеленный свинцовой дробью. Создан для бесшумного оглушения противников ударом по голове сзади.'
  },
  {
    id: 'w_spiked_gauntlet',
    name: 'Шипастая рукавица',
    category: 'Простое рукопашное (Хоумбрю)',
    groupKey: 'simple',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'колющий',
    weight: '1 фунт',
    cost: '5 зм',
    properties: ['Нельзя выронить'],
    proficiencies: ['p_weapon_simple', 'p_weap_dagger'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Тяжелая кожаная перчатка со стальными шипами на костяшках пальцев, превращающая обычный кулачный удар в опасную колющую атаку.'
  },

  // --- ВОИНСКОЕ РУКОПАШНОЕ ---
  {
    id: 'w_longsword',
    name: 'Длинный меч',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 или 2 руки (универсальное)',
    damage: '1d8',
    damageType: 'рубящий',
    weight: '3 фунта',
    cost: '15 зм',
    properties: ['Универсальное (1d10)'],
    proficiencies: ['p_weapon_martial', 'p_weap_longsword'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Классический прямой меч с обоюдоострым клинком и крестовиной. Символ рыцарской чести, доблести и непревзойденной эффективности в бою.'
  },
  {
    id: 'w_rapier',
    name: 'Рапира',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d8',
    damageType: 'колющий',
    weight: '2 фунта',
    cost: '25 зм',
    properties: ['Фехтовальное'],
    proficiencies: ['p_weapon_martial', 'p_weap_rapier'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Изящный, тонкий и упругий клинок с развитой гардой. Требует не столько грубой силы, сколько безупречной ловкости, скорости и точного расчета.'
  },
  {
    id: 'w_scimitar',
    name: 'Скимитар',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d6',
    damageType: 'рубящий',
    weight: '3 фунта',
    cost: '25 зм',
    properties: ['Фехтовальное', 'легкое'],
    proficiencies: ['p_weapon_martial', 'p_weap_scimitar'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Изогнутый меч пустынных воинов и дерзких пиратов. Изогнутая геометрия лезвия оставляет глубокие и опасные режущие раны.'
  },
  {
    id: 'w_shortsword',
    name: 'Короткий меч',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d6',
    damageType: 'колющий',
    weight: '2 фунта',
    cost: '10 зм',
    properties: ['Фехтовальное', 'легкое'],
    proficiencies: ['p_weapon_martial', 'p_weap_shortsword'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Короткий клинок для стремительных атак и ближнего боя в стесненных условиях вроде окопов или коридоров подземелий.'
  },
  {
    id: 'w_battleaxe',
    name: 'Боевой топор',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 или 2 руки (универсальное)',
    damage: '1d8',
    damageType: 'рубящий',
    weight: '4 фунта',
    cost: '10 зм',
    properties: ['Универсальное (1d10)'],
    proficiencies: ['p_weapon_martial', 'p_weap_battleaxe'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Тяжелый топор с массивным лезвием и балансировкой для бескомпромиссного ближнего боя. Любимое оружие дворфийских воинов.'
  },
  {
    id: 'w_morningstar',
    name: 'Моргенштерн',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d8',
    damageType: 'колющий',
    weight: '4 фунта',
    cost: '15 зм',
    properties: [],
    proficiencies: ['p_weapon_martial', 'p_weap_morningstar'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Ужасающая булава с шипастым стальным шаром на рукояти. Сочетает дробящий и колющий урон, легко сминая любую защиту.'
  },
  {
    id: 'w_flail',
    name: 'Цеп (Кистень)',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d8',
    damageType: 'дробящий',
    weight: '2 фунта',
    cost: '10 зм',
    properties: [],
    proficiencies: ['p_weapon_martial', 'p_weap_flail'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Ударный груз на гибкой цепи. Позволяет обходить вражеские щиты, перелетая через их край и нанося болезненные удары.'
  },
  {
    id: 'w_warhammer',
    name: 'Боевой молот',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 или 2 руки (универсальное)',
    damage: '1d8',
    damageType: 'дробящий',
    weight: '2 фунта',
    cost: '15 зм',
    properties: ['Универсальное (1d10)'],
    proficiencies: ['p_weapon_martial', 'p_weap_warhammer'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Сбалансированный боевой молот с бойком и клевцом. Идеален против латных доспехов и каменных автоматонов.'
  },
  {
    id: 'w_trident',
    name: 'Трезубец',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 или 2 руки (универсальное)',
    damage: '1d6',
    damageType: 'колющий',
    weight: '4 фунта',
    cost: '5 зм',
    properties: ['Метательное (дистанция 20/60)', 'универсальное (1d8)'],
    proficiencies: ['p_weapon_martial', 'p_weap_trident'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Грозное оружие гладиаторов арены и морской стражи с тремя широкими зубцами, наносящими тяжелые рваные раны.'
  },
  {
    id: 'w_whip',
    name: 'Кнут',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'рубящий',
    weight: '3 фунта',
    cost: '2 зм',
    properties: ['Фехтовальное', 'досягаемость'],
    proficiencies: ['p_weapon_martial', 'p_weap_whip'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Длинный плетеный кожаный или металлический хлыст. Позволяет атаковать врагов на дистанции, оставляя болезненные секущие рассечения.'
  },
  {
    id: 'w_falchion',
    name: 'Фальшион',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d8',
    damageType: 'рубящий',
    weight: '4 фунта',
    cost: '25 зм',
    properties: ['Легкое', 'критический урон'],
    proficiencies: ['p_weapon_martial', 'p_weap_scimitar'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Изогнутый однолезвийный меч с утяжеленной передней частью, сочетающий рубящую мощь топора и маневренность меча.'
  },
  {
    id: 'w_katanas_1h',
    name: 'Катана (Одноручный хват)',
    category: 'Воинское рукопашное (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 или 2 руки (универсальное)',
    damage: '1d8',
    damageType: 'рубящий/колющий',
    weight: '3 фунта',
    cost: '50 зм',
    properties: ['Фехтовальное', 'универсальное (1d10)'],
    proficiencies: ['p_weapon_martial', 'p_weap_longsword', 'p_weap_scimitar'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Легендарный изогнутый самурайский меч исключительной остроты ручной работы. Позволяет совершать молниеносные смертельные выпады.'
  },
  {
    id: 'w_kusarigama',
    name: 'Кусаригама (Серп с цепью)',
    category: 'Воинское рукопашное (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d6',
    damageType: 'рубящий/дробящий',
    weight: '3 фунта',
    cost: '20 зм',
    properties: ['Досягаемость', 'особое', 'фехтовальное'],
    proficiencies: ['p_weapon_martial', 'p_weap_sickle', 'p_weap_whip'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Изощренное восточное оружие, объединяющее боевой серп и длинную цепь с грузилом для запутывания противников и дистанционных атак.'
  },
  {
    id: 'w_cestus',
    name: 'Цестус',
    category: 'Воинское рукопашное (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d6',
    damageType: 'дробящий/колющий',
    weight: '2 фунта',
    cost: '10 зм',
    properties: ['Легкое', 'нельзя обезоружить'],
    proficiencies: ['p_weapon_martial', 'p_weap_mace'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Кожаные ремни с тяжелыми металлическими вставками для жестокого кулачного боя на аренах.'
  },
  {
    id: 'w_rapier_main_gauche',
    name: 'Рапира с дагой',
    category: 'Воинское рукопашное (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d8',
    damageType: 'колющий',
    weight: '3 фунта',
    cost: '45 зм',
    properties: ['Фехтовальное', 'защитное (+1 КД)'],
    proficiencies: ['p_weapon_martial', 'p_weap_rapier', 'p_weap_dagger'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Комплект благородного дуэлянта: элегантная рапира для нападения и короткая кинжальная дага с широкой гардой для парирования ударов в левой руке.'
  }
];
