window.heavyWeapons = [
  {
    id: 'w_halberd',
    name: 'Алебарда',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d10',
    damageType: 'рубящий',
    weight: '6 фунтов',
    cost: '20 зм',
    properties: ['Двуручное', 'тяжелое', 'досягаемость'],
    proficiencies: ['p_weapon_martial', 'p_weap_halberd'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Сочетает свойства копья и топора, позволяет атаковать врагов на расстоянии.'
  },
  {
    id: 'w_greatclub',
    name: 'Великая дубина',
    category: 'Простое рукопашное',
    groupKey: 'simple',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d8',
    damageType: 'дробящий',
    weight: '10 фунтов',
    cost: '2 зм',
    properties: ['Двуручное'],
    proficiencies: ['p_weapon_simple', 'p_weap_greatclub'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Тяжелое двуручное бревно, наносящее сокрушительные удары.'
  },
  {
    id: 'w_greatsword',
    name: 'Великий меч (Двуручник)',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '2d6',
    damageType: 'рубящий',
    weight: '6 фунтов',
    cost: '50 зм',
    properties: ['Двуручное', 'тяжелое'],
    proficiencies: ['p_weapon_martial', 'p_weap_greatsword'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Огромный меч, способный перерубить врага вместе с его доспехом.'
  },
  {
    id: 'w_glaive',
    name: 'Глефа',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d10',
    damageType: 'рубящий',
    weight: '6 фунтов',
    cost: '20 зм',
    properties: ['Двуручное', 'тяжелое', 'досягаемость'],
    proficiencies: ['p_weapon_martial', 'p_weap_glaive'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Длинное древковое оружие с изогнутым клинком на конце.'
  },
  {
    id: 'w_double_scimitar',
    name: 'Двойной скимитар (Валарский клинок)',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '2d4',
    damageType: 'рубящий',
    weight: '6 фунтов',
    cost: '100 зм',
    properties: ['Двуручное', 'фехтовальное', 'особое'],
    proficiencies: ['p_weapon_martial', 'p_weap_scimitar'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Обоюдный меч эльфов-наемников, позволяющий проводить молниеносные серии ударов.'
  },
  {
    id: 'w_lucerne_hammer',
    name: 'Люцернский молот',
    category: 'Воинское рукопашное (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d10',
    damageType: 'дробящий/колющий',
    weight: '8 фунтов',
    cost: '25 зм',
    properties: ['Двуручное', 'тяжелое', 'досягаемость', 'бронебойное'],
    proficiencies: ['p_weapon_martial', 'p_weap_warhammer', 'p_weap_pike'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Древковое оружие с бойком-молотком и клевцом на конце для пробивания лат.'
  },
  {
    id: 'w_executioner_sword',
    name: 'Меч палача',
    category: 'Воинское рукопашное (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d12',
    damageType: 'рубящий',
    weight: '8 фунтов',
    cost: '60 зм',
    properties: ['Двуручное', 'тяжелое', 'казнь (крит х3 в хб)'],
    proficiencies: ['p_weapon_martial', 'p_weap_greatsword'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Широкий прямой меч с тупым концом, созданный для точных обезглавливаний.'
  },
  {
    id: 'w_maul',
    name: 'Молот (Тяжелый двуручный)',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '2d6',
    damageType: 'дробящий',
    weight: '10 фунтов',
    cost: '10 зм',
    properties: ['Двуручное', 'тяжелое'],
    proficiencies: ['p_weapon_martial', 'p_weap_maul'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Огромная кувалда, способная сплющить доспех вместе с тем, кто внутри.'
  },
  {
    id: 'w_nodachi',
    name: 'Нодати (Длинный двуручный самурайский меч)',
    category: 'Воинское рукопашное (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '2d6',
    damageType: 'рубящий',
    weight: '7 фунтов',
    cost: '75 зм',
    properties: ['Двуручное', 'тяжелое', 'фехтовальное'],
    proficiencies: ['p_weapon_martial', 'p_weap_greatsword'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Огромный полевой меч японской пехоты.'
  },
  {
    id: 'w_pike',
    name: 'Пика',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d10',
    damageType: 'колющий',
    weight: '18 фунтов',
    cost: '5 зм',
    properties: ['Двуручное', 'тяжелое', 'досягаемость'],
    proficiencies: ['p_weapon_martial', 'p_weap_pike'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Сверхдлинное колющее оружие для строя и сдерживания кавалерии или монстров.'
  },
  {
    id: 'w_greataxe',
    name: 'Секира (Двуручный топор)',
    category: 'Воинское рукопашное',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d12',
    damageType: 'рубящий',
    weight: '7 фунтов',
    cost: '30 зм',
    properties: ['Двуручное', 'тяжелое'],
    proficiencies: ['p_weapon_martial', 'p_weap_greataxe'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Огромное лезвие на длинном древке наносит сокрушительный урон.'
  },
  {
    id: 'w_heavy_flail',
    name: 'Тяжелый двуручный цеп',
    category: 'Воинское рукопашное (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d12',
    damageType: 'дробящий',
    weight: '10 фунтов',
    cost: '30 зм',
    properties: ['Двуручное', 'тяжелое', 'игнорирует щиты'],
    proficiencies: ['p_weapon_martial', 'p_weap_flail'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Длинная цепь с тяжелым шипастым шаром на конце.'
  }
];
