window.rangedWeapons = [
  // --- ПРОСТОЕ ДАЛЬНОБОЙНОЕ ---
  {
    id: 'w_light_crossbow',
    name: 'Легкий арбалет',
    category: 'Простое дальнобойное',
    groupKey: 'simple',
    typeKey: 'ranged',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d8',
    damageType: 'колющий',
    weight: '5 фунтов',
    cost: '25 зм',
    properties: ['Боеприпас (дистанция 80/320)', 'заряжание', 'двуручное'],
    proficiencies: ['p_weapon_simple', 'p_crossbows', 'p_weap_light_crossbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Надежный арбалет с механическим натяжителем тетивы. Хотя перезаряжание требует драгоценных секунд, стальной болт летит значительно дальше и обладает большей пробивной силой, чем стрелы из обычного лука, прошивая даже плотные кожаные доспехи.'
  },
  {
    id: 'w_throwing_dart',
    name: 'Метательный дротик (Сюрикэн / Дарт)',
    category: 'Простое дальнобойное (Хоумбрю)',
    groupKey: 'simple',
    typeKey: 'ranged',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'колющий',
    weight: '0.2 фунта',
    cost: '5 см',
    properties: ['Фехтовальное', 'метательное (дистанция 20/60)'],
    proficiencies: ['p_weapon_simple', 'p_weap_javelin'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Миниатюрный сбалансированный снаряд или остро заточенная метательная звезда. Позволяет совершать быстрые, практически незаметные броски с использованием ловкости кисти, застигая противника врасплох.'
  },
  {
    id: 'w_repeating_crossbow',
    name: 'Многозарядный арбалет (Чо-ко-ну)',
    category: 'Воинское дальнобойное (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'ranged',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d6',
    damageType: 'колющий',
    weight: '6 фунтов',
    cost: '150 зм',
    properties: ['Боеприпас (дистанция 40/160)', 'емкость (6 болтов)', 'двуручное'],
    proficiencies: ['p_weapon_martial', 'p_crossbows', 'p_weap_light_crossbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Инженерное чудо восточных мастеров. Оснащен магазином с рычажным механизмом, позволяющим взводить тетиву и выпускать болты один за другим единым плавным движением, обеспечивая высокую плотность непрерывного огня.'
  },
  {
    id: 'w_shortbow',
    name: 'Короткий лук',
    category: 'Простое дальнобойное',
    groupKey: 'simple',
    typeKey: 'ranged',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d6',
    damageType: 'колющий',
    weight: '2 фунта',
    cost: '25 зм',
    properties: ['Боеприпас (дистанция 80/320)', 'двуручное'],
    proficiencies: ['p_weapon_simple', 'p_bows', 'p_weap_shortbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Компактный и легкий лук, созданный для мобильности. Его удобно носить за спиной и использовать в стесненных условиях — в густом лесу, узких подземельях или прямо на ходу во время конной погони.'
  },
  {
    id: 'w_sling',
    name: 'Праща',
    category: 'Простое дальнобойное',
    groupKey: 'simple',
    typeKey: 'ranged',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'дробящий',
    weight: '0 фунтов',
    cost: '1 см',
    properties: ['Боеприпас (дистанция 30/120)'],
    proficiencies: ['p_weapon_simple', 'p_weap_sling'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Простейшая полоса кожи с петлями, ставшая грозным оружием в умелых руках пастухов и партизан. В качестве снарядов используются круглые камни или свинцовые пули, способные нанести серьезную травму на неожиданном расстоянии.'
  },
  {
    id: 'w_hand_crossbow',
    name: 'Ручной арбалет',
    category: 'Воинское дальнобойное',
    groupKey: 'martial',
    typeKey: 'ranged',
    hands: '🖐️ 1 рука',
    damage: '1d6',
    damageType: 'колющий',
    weight: '3 фунта',
    cost: '75 зм',
    properties: ['Боеприпас (дистанция 30/120)', 'заряжание', 'легкое'],
    proficiencies: ['p_weapon_martial', 'p_crossbows', 'p_weap_hand_crossbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Изысканное оружие наемных убийц, шпионов и дуэлянтов. Компактные размеры позволяют скрытно носить его под плащом и использовать одной рукой, совмещая со стрельбой с руки или клинком во второй руке.'
  },
  {
    id: 'w_composite_bow',
    name: 'Составной длинный лук',
    category: 'Воинское дальнобойное (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'ranged',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d8',
    damageType: 'колющий',
    weight: '3 фунта',
    cost: '100 зм',
    properties: ['Боеприпас (дистанция 150/600)', 'двуручное', 'тяжелое', 'модификатор силы к урону'],
    proficiencies: ['p_weapon_martial', 'p_bows', 'p_weap_longbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Сложное композитное изделие из дерева, рога и сухожилий. Конструкция позволяет стрелку вкладывать всю свою физическую мощь в натяжение тетивы, придавая стреле дополнительное ускорение и разрушительную кинетическую энергию.'
  },
  {
    id: 'w_blowgun',
    name: 'Духовая трубка',
    category: 'Воинское дальнобойное',
    groupKey: 'martial',
    typeKey: 'ranged',
    hands: '🖐️🖐️ 2 руки',
    damage: '1',
    damageType: 'колющий',
    weight: '1 фунт',
    cost: '10 зм',
    properties: ['Боеприпас (дистанция 25/100)', 'заряжание'],
    proficiencies: ['p_weapon_martial', 'p_weap_blowgun'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Длинная полая трубка для бесшумного метания миниатюрных игл силой выдоха. Сама по себе она наносит ничтожный урон, но в руках умелого мастера, использующего паралитические яды или сонный экстракт, становится орудием тихого убийства.'
  },
  {
    id: 'w_longbow',
    name: 'Длинный лук',
    category: 'Воинское дальнобойное',
    groupKey: 'martial',
    typeKey: 'ranged',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d8',
    damageType: 'колющий',
    weight: '2 фунта',
    cost: '50 зм',
    properties: ['Боеприпас (дистанция 150/600)', 'двуручное', 'тяжелое'],
    proficiencies: ['p_weapon_martial', 'p_bows', 'p_weap_longbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Элегантное и смертоносное оружие эльфийских следопытов и мастеров-лучников. Требует выдающейся физической силы и тренировки для натяжения тугой тетивы, взамен одаривая невероятной дальностью стрельбы и убийственной точностью.'
  },
  {
    id: 'w_heavy_crossbow',
    name: 'Тяжелый арбалет',
    category: 'Воинское дальнобойное',
    groupKey: 'martial',
    typeKey: 'ranged',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d10',
    damageType: 'колющий',
    weight: '18 фунтов',
    cost: '50 зм',
    properties: ['Боеприпас (дистанция 100/400)', 'заряжание', 'двуручное', 'тяжелое'],
    proficiencies: ['p_weapon_martial', 'p_crossbows', 'p_weap_heavy_crossbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Настоящая полевая артиллерия в миниатюре. Оснащен воротом для взведения мощного стального плеча. Его тяжелый болт обладает чудовищной убойной силой, способной пробить толстые деревянные щиты и латы рыцарей.'
  },
  {
    id: 'w_drik_rifle',
    name: 'Аркебуза',
    category: 'Огнестрельное (Эпоха Возрождения)',
    groupKey: 'firearm',
    typeKey: 'ranged',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d10',
    damageType: 'колющий/пуля',
    weight: '9 фунтов',
    cost: '300 зм',
    properties: ['Боеприпас (дистанция 50/150)', 'заряжание', 'двуручное', 'сошки'],
    proficiencies: ['p_firearms', 'p_weap_heavy_crossbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Раннее тяжелое фитильное ружье пехоты. Из-за большой массы и отдачи часто требует использования специальных опорных сошек для прицельной стрельбы на средних дистанциях.'
  },
  {
    id: 'w_revolver',
    name: 'Капсюльный револьвер',
    category: 'Огнестрельное (Дикий Запад / Хоумбрю)',
    groupKey: 'firearm',
    typeKey: 'ranged',
    hands: '🖐️ 1 рука',
    damage: '2d6',
    damageType: 'колющий/пуля',
    weight: '3 фунта',
    cost: '700 зм',
    properties: ['Боеприпас (дистанция 50/150)', 'емкость (6 патронов)'],
    proficiencies: ['p_firearms', 'p_weap_hand_crossbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Шестизарядное нарезное чудо оружейного дела нового времени. Барабан с капсюльным воспламенением обеспечивает невероятную скорострельность, точность и надежность, меняя правила выживания на диких рубежах.'
  },
  {
    id: 'w_pistol',
    name: 'Кремневый пистолет',
    category: 'Огнестрельное (Эпоха Возрождения)',
    groupKey: 'firearm',
    typeKey: 'ranged',
    hands: '🖐️ 1 рука',
    damage: '1d10',
    damageType: 'колющий/пуля',
    weight: '3 фунта',
    cost: '250 зм',
    properties: ['Боеприпас (дистанция 30/90)', 'заряжание'],
    proficiencies: ['p_firearms', 'p_weap_blowgun'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Громкое, дымное и смертоносное ручное оружие эпохи перемен. Любимый аргумент пиратов, дуэлянтов и корабельных офицеров. Свинцовая пуля из этого ствола способна остановить атакующего наотмашь, но требует долгой и кропотливой перезарядки с шомполом.'
  },
  {
    id: 'w_musket',
    name: 'Кремневый мушкет',
    category: 'Огнестрельное (Эпоха Возрождения)',
    groupKey: 'firearm',
    typeKey: 'ranged',
    hands: '🖐️🖐️ 2 руки',
    damage: '1d12',
    damageType: 'колющий/пуля',
    weight: '10 фунтов',
    cost: '500 зм',
    properties: ['Боеприпас (дистанция 40/120)', 'заряжание', 'двуручное'],
    proficiencies: ['p_firearms', 'p_weap_heavy_crossbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Длинноствольное гладкоствольное ружье с внушительной дальнобойностью и чудовищной убойной силой. Залпы линий мушкетеров способны обратить в бегство даже самых закаленных в боях монстров, разрушая привычные устои средневековой войны.'
  },
  {
    id: 'w_pepperbox',
    name: 'Многоствольный пистолет (Пеппербокс)',
    category: 'Огнестрельное (Хоумбрю)',
    groupKey: 'firearm',
    typeKey: 'ranged',
    hands: '🖐️ 1 рука',
    damage: '1d8',
    damageType: 'колющий/пуля',
    weight: '4 фунта',
    cost: '400 зм',
    properties: ['Боеприпас (дистанция 30/90)', 'емкость (4 выстрела)', 'осечка'],
    proficiencies: ['p_firearms', 'p_weap_hand_crossbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Конструкция с блоком вращающихся стволов, позволяющая сделать несколько выстрелов подряд без необходимости перезарядки после каждого хлопка. Однако сложный механизм капризен и склонен к осечкам в пылу боя.'
  },
  {
    id: 'w_blunderbuss',
    name: 'Мушкетон (Тромблон)',
    category: 'Огнестрельное (Хоумбрю)',
    groupKey: 'firearm',
    typeKey: 'ranged',
    hands: '🖐️🖐️ 2 руки',
    damage: '2d6',
    damageType: 'колющий/дробь',
    weight: '8 фунтов',
    cost: '350 зм',
    properties: ['Боеприпас (дистанция 15/45)', 'заряжание', 'двуручное', 'широкий урон'],
    proficiencies: ['p_firearms', 'p_weap_heavy_crossbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Короткое ружье с характерным раструбом на конце ствола. Заряжается горстью рубленного свинца, гвоздей или старых монет. На короткой дистанции накрывает смертоносным конусом поражения всё живое.'
  },
  {
    id: 'w_dragon_pistol',
    name: 'Драгунский пистолет (Обрезыч)',
    category: 'Огнестрельное (Хоумбрю)',
    groupKey: 'firearm',
    typeKey: 'ranged',
    hands: '🖐️ 1 рука',
    damage: '2d4',
    damageType: 'колющий/дробь',
    weight: '4 фунта',
    cost: '200 зм',
    properties: ['Боеприпас (дистанция 20/60)', 'заряжание', 'ближний конус'],
    proficiencies: ['p_firearms', 'p_weap_hand_crossbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Укороченный мушкетон с раструбом, созданный специально для конных драгун и абордажных команд. Удобен в тесноте, бьет широко и сокрушительно на коротких дистанциях.'
  },
  {
    id: 'w_hand_mortar',
    name: 'Ручная мортирка',
    category: 'Огнестрельное (Хоумбрю)',
    groupKey: 'firearm',
    typeKey: 'ranged',
    hands: '🖐️🖐️ 2 руки',
    damage: '2d8',
    damageType: 'огонь / взрыв',
    weight: '14 фунтов',
    cost: '900 зм',
    properties: ['Боеприпас (дистанция 30/90)', 'заряжание', 'двуручное', 'взрыв по площади'],
    proficiencies: ['p_firearms', 'p_weap_heavy_crossbow'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Экстремальное оружие подрывников — короткоствольная ручная пушонка, предназначенная для метания небольших зажигательных или разрывных бомб с часовым механизмом прямо в скопления врагов.'
  }
];
