window.specialWeapons = [
  {
    id: 'w_bolas',
    name: 'Болас',
    category: 'Экзотическое (Хоумбрю)',
    groupKey: 'simple',
    typeKey: 'ranged',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'дробящий',
    weight: '2 фунта',
    cost: '1 зм',
    properties: ['Особое', 'метательное (дистанция 20/60)', 'сбивает с ног / опутывает'],
    proficiencies: ['p_weapon_simple', 'p_weap_net'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Охотничье метательное приспособление из прочных кожаных ремней и тяжелых каменных или свинцовых грузиков на концах. При броске обвивается вокруг ног бегущей цели, сбивая её с ног и спутывая движения.'
  },
  {
    id: 'w_fighting_fan',
    name: 'Боевой вее́р (Тессэн)',
    category: 'Экзотическое (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'рубящий/дробящий',
    weight: '1.5 фунта',
    cost: '20 зм',
    properties: ['Фехтовальное', 'легкое', 'скрытное'],
    proficiencies: ['p_weapon_martial', 'p_weap_dagger', 'p_weap_scimitar'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'С виду безобидный складной веер знатного вельможи, чьи спицы выполнены из закаленной стали с бритвенно-острыми краями. Сочетает изящество придворного танца и смертоносную технику самообороны.'
  },
  {
    id: 'w_hook_hand',
    name: 'Крюк вместо руки',
    category: 'Экзотическое (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'рубящий',
    weight: '1 фунт',
    cost: '5 зм',
    properties: ['Особое', 'нельзя обезоружить'],
    proficiencies: ['p_weapon_martial', 'p_weap_dagger'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Классический мрачный атрибут бывалого капитана или пирата, потерявшего конечность. Надежно крепится к культе, заменяя кисть рук, и позволяет не только наносить болезненные рваные раны, но и цепляться за врагов или такелаж.'
  },
  {
    id: 'w_lasso',
    name: 'Лассо',
    category: 'Экзотическое (Хоумбрю)',
    groupKey: 'simple',
    typeKey: 'ranged',
    hands: '🖐️ 1 рука',
    damage: '0',
    damageType: 'нет',
    weight: '3 фунта',
    cost: '5 см',
    properties: ['Особое', 'метательное (дистанция 10/30)', 'захват цели'],
    proficiencies: ['p_weapon_simple', 'p_weap_net'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Прочная пеньковая или кожаная веревка с затягивающейся скользящей петлей на конце. Незаменимый инструмент для охотников за головами, позволяющий на расстоянии поймать беглеца или обездвижить опасного зверя.'
  },
  {
    id: 'w_net',
    name: 'Сетка',
    category: 'Воинское дальнобойное',
    groupKey: 'martial',
    typeKey: 'ranged',
    hands: '🖐️ 1 рука',
    damage: '0',
    damageType: 'нет',
    weight: '3 фунта',
    cost: '1 зм',
    properties: ['Особое', 'метательное (дистанция 5/15)'],
    proficiencies: ['p_weapon_martial', 'p_weap_net'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Тяжелая гладиаторская сеть с утяжеленными краями. При успешном броске накрывает крупную или меньшую цель, намертво опутывая её и лишая возможности двигаться, пока жертва не вырвется или не разрежет путы.'
  },
  {
    id: 'w_blowgun_poison',
    name: 'Скрытый рукавной клинок',
    category: 'Экзотическое (Хоумбрю)',
    groupKey: 'martial',
    typeKey: 'melee',
    hands: '🖐️ 1 рука',
    damage: '1d4',
    damageType: 'колющий',
    weight: '1 фунт',
    cost: '50 зм',
    properties: ['Особое', 'скрытное (преимущество на инициативу скрытой атаки)'],
    proficiencies: ['p_weapon_martial', 'p_weap_dagger'],
    toHit: 0,
    bonuses: { str: 0, dex: 0, con: 0, int: 0, wis: 0, cha: 0 },
    description: 'Изощренное скрытое оружие ассасинов. Пружинный механизм выбрасывает острый клинок из-под запястья по щелчку пальцев, позволяя нанести неожиданный удар изобличающей тени.'
  }
];
