#!/usr/bin/env node
/* Transfer multiple MakeHuman targets through the body's UV surface once.
 * Usage: node tools/build_makehuman_morphs.js <mpfb data dir> <source.glb>
 *   <output.glb> [channels.json]
 * Input OBJ and target files use native MakeHuman X/Y-up/Z coordinates;
 * Blender's X/-Z/Y conversion is NOT appropriate for this glTF Y-up mesh.
 * Deliberately rejects unsupported topology/UV conventions and incomplete maps.
 */
const fs=require('fs'),path=require('path'),zlib=require('zlib'),crypto=require('crypto');
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const {readGlb}=require('../tests/makehuman_morph_bridge');
const align=n=>(n+3)&~3;
function acc(glb,i,n){const a=glb.json.accessors[i],v=glb.json.bufferViews[a.bufferView];if(a.componentType!==5126||v.byteStride||a.sparse)throw Error('Expected packed float accessor');const offset=(v.byteOffset||0)+(a.byteOffset||0);return new Float32Array(glb.bin.buffer,glb.bin.byteOffset+offset,a.count*n);}
function obj(file){const vertices=[],uv=[],triangles=[];let group='';for(const line of fs.readFileSync(file,'utf8').split(/\r?\n/)){const s=line.trim().split(/\s+/);if(s[0]==='v')vertices.push(s.slice(1,4).map(Number));if(s[0]==='vt')uv.push(s.slice(1,3).map(Number));if(s[0]==='g')group=s[1];if(s[0]==='f'&&group==='body'){const f=s.slice(1).map(x=>x.split('/').slice(0,2).map(v=>Number(v)-1));for(let i=1;i<f.length-1;i++)triangles.push([f[0],f[i],f[i+1]]);}}if(!triangles.length)throw Error('Missing body UV surface');return{vertices,uv,triangles};}
function mapSurface(hm,uv){const N=100,grid=new Map(),key=(x,y)=>x+','+y;
 hm.triangles.forEach((t,i)=>{const p=t.map(x=>hm.uv[x[1]]);if(p.some(x=>!x))throw Error('Missing OBJ UV');const lo=[0,1].map(k=>Math.floor(Math.min(...p.map(x=>x[k]))*N)),hi=[0,1].map(k=>Math.floor(Math.max(...p.map(x=>x[k]))*N));for(let x=lo[0];x<=hi[0];x++)for(let y=lo[1];y<=hi[1];y++){const k=key(x,y);if(!grid.has(k))grid.set(k,[]);grid.get(k).push(i);}});
 const result=[];let maxOutside=0,extrapolated=0;
 for(let i=0;i<uv.length;i+=2){const p=[uv[i],1-uv[i+1]],x=Math.floor(p[0]*N),y=Math.floor(p[1]*N);let best=null;
  function search(ids){for(const id of ids||[]){const t=hm.triangles[id],a=hm.uv[t[0][1]],b=hm.uv[t[1][1]],c=hm.uv[t[2][1]],ab=[b[0]-a[0],b[1]-a[1]],ac=[c[0]-a[0],c[1]-a[1]],ap=[p[0]-a[0],p[1]-a[1]],den=ab[0]*ac[1]-ab[1]*ac[0];if(Math.abs(den)<1e-14)continue;const u=(ap[0]*ac[1]-ap[1]*ac[0])/den,v=(ab[0]*ap[1]-ab[1]*ap[0])/den,w=[1-u-v,u,v],outside=Math.max(0,-Math.min(...w),Math.max(...w)-1);if(!best||outside<best.outside)best={ids:t.map(x=>x[0]),w,outside};if(outside<1e-7)return;}}
  search(grid.get(key(x,y)));if(!best||best.outside>1e-4)for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++)search(grid.get(key(x+dx,y+dy)));
  if(!best||best.outside>.001)throw Error('UV map failed at vertex '+i/2+'; barycentric outside='+ (best&&best.outside));
  maxOutside=Math.max(maxOutside,best.outside);if(best.outside>1e-5)extrapolated++;
  const sum=best.w.reduce((s,w)=>s+Math.max(0,w),0);best.w=best.w.map(w=>Math.max(0,w)/sum);result.push(best);
 }return{vertices:result,maxOutside,extrapolated};}
function target(file,count){const raw=fs.readFileSync(file),text=(file.endsWith('.gz')?zlib.gunzipSync(raw):raw).toString('utf8'),d=new Float32Array(count*3);for(const l of text.split(/\r?\n/)){const s=l.trim();if(!s||s[0]==='#'||s[0]==='"')continue;const p=s.split(/\s+/).map(Number),i=p[0];if(p.length!==4||!Number.isInteger(i)||i<0||i>=count||!p.every(Number.isFinite))throw Error('Malformed target '+file);d.set(p.slice(1),i*3);}return d;}
function build(dataDir,input,output,config){if(path.resolve(input)===path.resolve(output))throw Error('Source must not be overwritten');const glb=readGlb(input),json=JSON.parse(JSON.stringify(glb.json)),hm=obj(path.join(dataDir,'3dobjs/base.obj')),rules=JSON.parse(fs.readFileSync(config,'utf8')),channels={},chunks=[Buffer.from(glb.bin)];let offset=align(glb.bin.length);if(offset>glb.bin.length)chunks.push(Buffer.alloc(offset-glb.bin.length));const diagnostics=[],sourceHashes={baseObj:sha(path.join(dataDir,'3dobjs/base.obj'))};
 const meshes=json.meshes||[];if(meshes.length!==1||meshes[0].primitives.length!==1)throw Error('Builder currently requires one body mesh/primitive');const mesh=meshes[0],p=mesh.primitives[0];if(p.targets&&p.targets.length)throw Error('Use an unmodified source GLB');if(p.attributes.TEXCOORD_0==null)throw Error('Body UV required');const count=json.accessors[p.attributes.POSITION].count,uv=acc(glb,p.attributes.TEXCOORD_0,2);if(uv.length!==count*2)throw Error('UV count mismatch');const map=mapSurface(hm,uv);
 p.targets=[];mesh.weights=[];mesh.extras=mesh.extras||{};mesh.extras.targetNames=[];
 for(const [axis,rule] of Object.entries(rules)){channels[axis]={positive:rule.positive,negative:rule.negative,scale:rule.scale==null?1:rule.scale};for(const name of [rule.positive,rule.negative]){if(mesh.extras.targetNames.includes(name))throw Error('Duplicate target '+name);const source=path.join(dataDir,'targets',rule.folder,name+'.target.gz'),d=target(source,hm.vertices.length),out=new Float32Array(count*3),min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];let nonZero=0;
 for(let i=0;i<count;i++){const hit=map.vertices[i];for(let k=0;k<3;k++){let value=0;for(let j=0;j<3;j++)value+=d[hit.ids[j]*3+k]*hit.w[j];value*=.1;out[i*3+k]=value;min[k]=Math.min(min[k],out[i*3+k]);max[k]=Math.max(max[k],out[i*3+k]);}if(Math.hypot(...out.subarray(i*3,i*3+3))>1e-7)nonZero++;}if(!nonZero)throw Error('Empty transferred target '+name);sourceHashes[name]=sha(source);
 const view=json.bufferViews.length;json.bufferViews.push({buffer:0,byteOffset:offset,byteLength:out.byteLength,target:34962});const ai=json.accessors.length;json.accessors.push({bufferView:view,componentType:5126,type:'VEC3',count,min,max});p.targets.push({POSITION:ai});mesh.weights.push(0);mesh.extras.targetNames.push(name);chunks.push(Buffer.from(out.buffer));offset+=out.byteLength;diagnostics.push({name,nonZero,min,max});}}
 json.extras=Object.assign({},json.extras,{dndMorphChannels:channels,dndMorphSource:{project:'makehumancommunity/mpfb2',commit:process.env.MAKEHUMAN_SOURCE_COMMIT||undefined,sourceHashes,license:'CC0',method:'body UV barycentric; V flip; native Y-up deltas at 0.1 units',vertices:count,extrapolated:map.extrapolated,maxOutside:map.maxOutside}});json.buffers[0].byteLength=offset;
 const jb=Buffer.from(JSON.stringify(json)),jpad=Buffer.alloc(align(jb.length)-jb.length,32),bin=Buffer.concat(chunks),header=Buffer.alloc(12),jh=Buffer.alloc(8),bh=Buffer.alloc(8);header.write('glTF');header.writeUInt32LE(2,4);header.writeUInt32LE(28+jb.length+jpad.length+bin.length,8);jh.writeUInt32LE(jb.length+jpad.length);jh.writeUInt32LE(0x4e4f534a,4);bh.writeUInt32LE(bin.length);bh.writeUInt32LE(0x004e4942,4);fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,Buffer.concat([header,jh,jb,jpad,bh,bin]));return{output,bytes:fs.statSync(output).size,mapping:json.extras.dndMorphSource,targets:diagnostics};}
if(require.main===module){const [data,input,output,config=path.join(__dirname,'makehuman_morph_channels.json')]=process.argv.slice(2);if(!data||!input||!output)throw Error('Usage: dataDir source.glb output.glb [channels.json]');console.log(JSON.stringify(build(data,input,output,config),null,2));}
module.exports={build,mapSurface,obj,target};
