/* Optional real Chromium/WebGL integration QA. Set PLAYWRIGHT_MODULE and BROWSER_EXECUTABLE if needed. */
const fs=require('fs'),assert=require('assert');const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const path=require('path'),http=require('http'),root=path.resolve(__dirname,'..'),modules=['gltf_loader','gltf_character_pipeline','character_system','character_morph_assets','character_body_geometry','character_appearance_store','character_editor_3d'];
const html='<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><body>'+modules.map(name=>'<script src="app/3dmap/'+name+'.js"></script>').join('')+'<script>DNDGLTFCharacterPipeline.install();window.allCharacters=[{id:"qa",name:"Тестовый персонаж",hp:17}];window.currentChar=allCharacters[0];window.currentCharacterId="qa";if(!localStorage.getItem("dnd_multi_characters_v2"))localStorage.setItem("dnd_multi_characters_v2",JSON.stringify(allCharacters));dndOpenCharacterEditor3D();</script></body></html>';
const server=http.createServer((req,res)=>{if(req.url.split('?')[0]==='/_character_qa.html'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html);return;}const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404);res.end();return;}if(file.endsWith('.html'))res.setHeader('Content-Type','text/html; charset=utf-8');if(file.endsWith('.js'))res.setHeader('Content-Type','application/javascript');res.end(fs.readFileSync(file));});
process.on('exit',()=>server.close());
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(origin+'/_character_qa.html');await page.waitForFunction(()=>document.getElementById('ceGLStatus').textContent.startsWith('Человек'),{timeout:45000});if(process.env.BROWSER_QA_OUTPUT)await page.screenshot({path:path.join(process.env.BROWSER_QA_OUTPUT,'editor-desktop.png')});
await page.selectOption('#ceGender','female');await page.selectOption('#ceSkin','human_young_female');await page.click('#ceTab_torso');await page.evaluate(()=>DNDCharacterEditor3D.setAxis('breastSize',.7));await page.check('#ceArmorToggle');await page.waitForFunction(()=>DNDCharacterEditor3D.diagnostics().armorTriangles>100);if(process.env.BROWSER_QA_OUTPUT)await page.screenshot({path:path.join(process.env.BROWSER_QA_OUTPUT,'editor-female-armor.png')});
const d=await page.evaluate(()=>DNDCharacterEditor3D.diagnostics());await page.click('#ceSide');await page.click('#cePlus');await page.waitForTimeout(100);assert.deepStrictEqual(await page.evaluate(()=>DNDCharacterEditor3D.diagnostics()),d,'camera does not rebuild or upload');await page.click('#ceSave');assert.strictEqual(await page.locator('#dnd3dCharacterEditor').count(),0);await page.evaluate(()=>dndOpenCharacterEditor3D());await page.waitForFunction(()=>document.getElementById('ceGLStatus').textContent.startsWith('Человек'));assert.strictEqual(await page.evaluate(()=>DNDCharacterEditor3D.getState().body.breastSize),.7);assert.strictEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('dnd_multi_characters_v2'))[0].hp),17);
await page.setViewportSize({width:390,height:844});await page.click('#ceFront');if(process.env.BROWSER_QA_OUTPUT)await page.screenshot({path:path.join(process.env.BROWSER_QA_OUTPUT,'editor-mobile.png')});const layout=await page.evaluate(()=>{let save=document.getElementById('ceSave').getBoundingClientRect(),panel=document.querySelector('.cePanel');return {saveBottom:save.bottom,viewport:innerHeight,panelScroll:panel.scrollHeight>panel.clientHeight,overflow:document.getElementById('dnd3dCharacterEditor').scrollWidth>innerWidth};});assert(layout.saveBottom<=layout.viewport);assert(!layout.overflow);assert(layout.panelScroll);
// Recreate GPU resources after a real context loss.
const result=await page.evaluate(async()=>{const gl=document.getElementById('ceGL').getContext('webgl'),ext=gl.getExtension('WEBGL_lose_context');if(!ext)return false;ext.loseContext();await new Promise(r=>setTimeout(r,100));ext.restoreContext();return true;});if(result){await page.waitForFunction(()=>document.getElementById('ceGLStatus').textContent.startsWith('Человек'));if(process.env.BROWSER_QA_OUTPUT)await page.screenshot({path:path.join(process.env.BROWSER_QA_OUTPUT,'editor-restored.png')});}
assert.deepStrictEqual(errors,[]);await page.goto(origin+'/index.html');await page.waitForFunction(()=>typeof DNDCharacterEditor3D!=='undefined'&&typeof openCharacter==='function');await page.evaluate(()=>{loadAllCharacters();openCharacter('qa');dndOpenCharacterEditor3D();});await page.waitForFunction(()=>document.getElementById('ceGLStatus').textContent.startsWith('Человек'));assert.strictEqual(await page.evaluate(()=>DNDCharacterEditor3D.getState().body.breastSize),.7);await page.evaluate(()=>DNDCharacterEditor3D.setAxis('armLength',.4));await page.click('#ceSave');assert.strictEqual(await page.evaluate(()=>currentChar.appearance3d.body.armLength),.4);await page.reload();await page.waitForFunction(()=>typeof DNDCharacterEditor3D!=='undefined'&&typeof openCharacter==='function');await page.evaluate(()=>{loadAllCharacters();openCharacter('qa');dndOpenCharacterEditor3D();});await page.waitForFunction(()=>document.getElementById('ceGLStatus').textContent.startsWith('Человек'));assert.strictEqual(await page.evaluate(()=>DNDCharacterEditor3D.getState().body.armLength),.4);console.log(JSON.stringify({status:'PASS',webgl:true,contextRestore:result,diagnostics:d,layout}));await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1);});
