plugins {
    id "com.android.application"
}

android {
    namespace "com.dndvtt.app"
    compileSdk 36

    defaultConfig {
        applicationId "com.dndvtt.app"
        minSdk 24
        targetSdk 36
        versionCode 7025061
        versionName "70.25.61"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.webkit:webkit:1.17.1"
}
